### ISSUE TITLE
"E0906 Failed to create cgroup" when creating pod on fedora-29

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#10011]
Somewhere between creating a pod and creating an actual docker container things go wrong.

See https://bugzilla.redhat.com/show_bug.cgi?id=1596874.

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTopology (check_kubernetes.TestKubernetes)
#
bash: /etc/kubernetes/start-kubernetes: No such file or directory
Error response from daemon: no such id: gcr.io/google_containers/pause-amd64:3.0
[0906/171202.399718:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9390/devtools/browser/2e31d5df-82f9-4529-a569-8f01d1f48927
[0906/171202.458295:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 105690: Permission denied (13)
[0906/171202.623955:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 105716: Permission denied (13)
> warning: error: current-context must exist in order to minify

> warning: received invalid kubectl config 
> warning: Failed to query RHEL subscription status: 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestKubernetes-testTopology-fedora-29-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestKubernetes-testTopology-fedora-29-127.0.0.2-2401-FAIL.html
Wrote JS log to TestKubernetes-testTopology-fedora-29-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestKubernetes-testTopology-fedora-29-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/kubelib.py", line 645, in testTopology
    b.wait_text("#service-list tr[data-name='mock'] td.containers", "1")
  File "/build/cockpit/test/common/testlib.py", line 320, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("#service-list tr[data-name='mock'] td.containers","1")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":5,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1536253923042.21, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '105716.8'}
warning: error: current-context must exist in order to minify

warning: received invalid kubectl config 
warning: Failed to query RHEL subscription status: 
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 40 testTopology (check_kubernetes.TestKubernetes) # duration: 172s
```
First occurrence: 2018-09-06T17:14:12.922413 | revision 5e0693adaea8546859794993d9e0860fcf8fc67b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180906-163232-5e0693ad-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-06T17:14:12.922413 | revision 5e0693adaea8546859794993d9e0860fcf8fc67b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180906-163232-5e0693ad-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDashboard (check_kubernetes.TestKubernetes)
#
bash: /etc/kubernetes/start-kubernetes: No such file or directory
Error response from daemon: no such id: gcr.io/google_containers/pause-amd64:3.0
[0906/171217.091107:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10099/devtools/browser/8c2babdd-af8b-4877-ab76-c8c3d713569d
[0906/171217.141260:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 106243: Permission denied (13)
[0906/171217.329965:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 106276: Permission denied (13)
> warning: error: current-context must exist in order to minify

> warning: received invalid kubectl config 
> warning: Failed to query RHEL subscription status: 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestKubernetes-testDashboard-fedora-29-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestKubernetes-testDashboard-fedora-29-127.0.0.2-2801-FAIL.html
Wrote JS log to TestKubernetes-testDashboard-fedora-29-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestKubernetes-testDashboard-fedora-29-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/kubelib.py", line 435, in testDashboard
    b.wait_text("#service-list tr[data-name='mock']:first-of-type td.containers", "1")
  File "/build/cockpit/test/common/testlib.py", line 320, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("#service-list tr[data-name='mock']:first-of-type td.containers","1")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":5,"id":4}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1536253937795.8, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '106276.8'}
warning: error: current-context must exist in order to minify

warning: received invalid kubectl config 
warning: Failed to query RHEL subscription status: 
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 36 testDashboard (check_kubernetes.TestKubernetes) # duration: 176s
```
First occurrence: 2018-09-06T17:14:31.268542 | revision 5e0693adaea8546859794993d9e0860fcf8fc67b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180906-163232-5e0693ad-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-06T17:14:31.268542 | revision 5e0693adaea8546859794993d9e0860fcf8fc67b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180906-163232-5e0693ad-verify-fedora-29/log.html)

**Comment by martinpitt** [comment]
@Gundersanne: Wrong bugzilla -- the one in the description is for Python.

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTopology (check_kubernetes.TestKubernetes)
#
bash: /etc/kubernetes/start-kubernetes: No such file or directory
Error response from daemon: no such id: gcr.io/google_containers/pause-amd64:3.0
[1112/174720.406381:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9663/devtools/browser/28921d47-81f3-4c4d-814b-b2e985334536
[1112/174720.410035:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 58890: Permission denied (13)
[1112/174720.565337:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 58955: Permission denied (13)
> warning: error: current-context must exist in order to minify

> warning: received invalid kubectl config 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestKubernetes-testTopology-fedora-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestKubernetes-testTopology-fedora-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestKubernetes-testTopology-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKubernetes-testTopology-fedora-testing-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/kubelib.py", line 645, in testTopology
    b.wait_text("#service-list tr[data-name='mock'] td.containers", "1")
  File "/build/cockpit/test/common/testlib.py", line 320, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("#service-list tr[data-name='mock'] td.containers","1")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":5,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1542044841029.33, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '1000058955.8'}
warning: error: current-context must exist in order to minify

warning: received invalid kubectl config 
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 9 testTopology (check_kubernetes.TestKubernetes) # duration: 164s
```
First occurrence: 2018-11-12T17:49:32.057422 | revision c872878b9996b1ca1ab0b1ee7375ea370ba9f379, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10557-20181112-171212-c872878b-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-11-12T17:49:32.057422 | revision c872878b9996b1ca1ab0b1ee7375ea370ba9f379, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10557-20181112-171212-c872878b-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDashboard (check_kubernetes.TestKubernetes)
#
bash: /etc/kubernetes/start-kubernetes: No such file or directory
Error response from daemon: no such id: gcr.io/google_containers/pause-amd64:3.0
[1112/174739.448598:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10029/devtools/browser/8d493abc-985e-427d-93c5-e8bdaa1b59f3
[1112/174739.452516:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 59496: Permission denied (13)
[1112/174739.606275:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 59521: Permission denied (13)
> warning: error: current-context must exist in order to minify

> warning: received invalid kubectl config 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestKubernetes-testDashboard-fedora-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestKubernetes-testDashboard-fedora-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestKubernetes-testDashboard-fedora-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKubernetes-testDashboard-fedora-testing-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/kubelib.py", line 435, in testDashboard
    b.wait_text("#service-list tr[data-name='mock']:first-of-type td.containers", "1")
  File "/build/cockpit/test/common/testlib.py", line 320, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("#service-list tr[data-name='mock']:first-of-type td.containers","1")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":5,"id":4}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1542044859959.02, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '1000059521.8'}
warning: error: current-context must exist in order to minify

warning: received invalid kubectl config 
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 5 testDashboard (check_kubernetes.TestKubernetes) # duration: 164s
```
First occurrence: 2018-11-12T17:49:50.417612 | revision c872878b9996b1ca1ab0b1ee7375ea370ba9f379, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10557-20181112-171212-c872878b-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-11-12T17:49:50.417612 | revision c872878b9996b1ca1ab0b1ee7375ea370ba9f379, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10557-20181112-171212-c872878b-verify-fedora-testing/log.html)
