### ISSUE TITLE
packagekitd crash on fedora-29 during check-storage-lvm2 tests

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#10027]
Also see, https://bugzilla.redhat.com/show_bug.cgi?id=1626796

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLvm (check_storage_lvm2.TestStorage)
#
[0909/091402.599314:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10181/devtools/browser/3e4915f0-fbce-4ab6-bb84-a4d32564fafc
[0909/091402.647945:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 37472: Permission denied (13)
[0909/091402.767053:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 37497: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
  WARNING: Sum of all thin volume sizes (100.00 MiB) exceeds the size of thin pool TEST1/pool and the size of whole volume group (48.00 MiB).
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /1_ddaadddd : {"command":"close","channel":"1:1!9"}
> warning: PackageKit went away during transaction /2_bbabeedb : {"command":"close","channel":"1:1!9"}
> warning: Checking for available updates failed: Error: PackageKit crashed
> warning: Checking for available updates failed: Error: PackageKit crashed
Unexpected journal messages:
Process 1663 (packagekitd) of user 0 dumped core.

Stack trace of thread 1762:
#0  0x00007faadbd788c7 __strlen_avx2 (libc.so.6)
#1  0x00007faadbc6a3c7 vfprintf (libc.so.6)
#2  0x00007faadbd257fc __vasprintf_chk (libc.so.6)
#3  0x00007faadbf521cd g_vasprintf (libglib-2.0.so.0)
#4  0x00007faadbf2b681 g_strdup_vprintf (libglib-2.0.so.0)
#5  0x00007faadbef5826 g_error_new_valist (libglib-2.0.so.0)
#6  0x00007faadbef5c1f g_set_error (libglib-2.0.so.0)
#7  0x00007faacc7e05bd dnf_repo_update (libdnf.so.2)
#8  0x00007faacc7d2a8b dnf_sack_add_repo (libdnf.so.2)
#9  0x00007faacc7d2d4a dnf_sack_add_repos (libdnf.so.2)
#10 0x00007faacc96715a n/a (libpk_backend_dnf.so)
#11 0x00007faacc96cb4c n/a (libpk_backend_dnf.so)
#12 0x000055e32a64405e n/a (packagekitd)
#13 0x00007faadbf346ea n/a (libglib-2.0.so.0)
#14 0x00007faadbde558e start_thread (libpthread.so.0)
#15 0x00007faadbd14513 __clone (libc.so.6)

Stack trace of thread 1663:
#0  0x00007faadbd09301 __poll (libc.so.6)
#1  0x00007faadbf0b5e6 n/a (libglib-2.0.so.0)
#2  0x00007faadbf0b9a2 g_main_loop_run (libglib-2.0.so.0)
#3  0x000055e32a62eb86 main (packagekitd)
#4  0x00007faadbc3b413 __libc_start_main (libc.so.6)
#5  0x000055e32a62ee3a _start (packagekitd)

Stack trace of thread 1672:
#0  0x00007faadbd09301 __poll (libc.so.6)
#1  0x00007faadbf0b5e6 n/a (libglib-2.0.so.0)
#2  0x00007faadbf0b710 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007faadbf0b761 n/a (libglib-2.0.so.0)
#4  0x00007faadbf346ea n/a (libglib-2.0.so.0)
#5  0x00007faadbde558e start_thread (libpthread.so.0)
#6  0x00007faadbd14513 __clone (libc.so.6)

Stack trace of thread 1677:
#0  0x00007faadbd09301 __poll (libc.so.6)
#1  0x00007faadbf0b5e6 n/a (libglib-2.0.so.0)
#2  0x00007faadbf0b9a2 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007faadc10d90a n/a (libgio-2.0.so.0)
#4  0x00007faadbf346ea n/a (libglib-2.0.so.0)
#5  0x00007faadbde558e start_thread (libpthread.so.0)
#6  0x00007faadbd14513 __clone (libc.so.6)

Wrote JS log to TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.log
Core dumps downloaded to /build/cockpit/TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.core
Wrote screenshot to TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.html
Wrote JS log to TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.log
Core dumps downloaded to /build/cockpit/TestStorage-testLvm-fedora-29-127.0.0.2-2601-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 692, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 873, in check_journal_messages
    raise Error(first)
testlib.Error: Process 1663 (packagekitd) of user 0 dumped core.

not ok 180 testLvm (check_storage_lvm2.TestStorage) # duration: 51s
```
First occurrence: 2018-09-09T09:14:33.591052 | revision af1c509c590ff95471c21440ec63e13e05fa9446, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180909-085959-af1c509c-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-09T09:14:33.591052 | revision af1c509c590ff95471c21440ec63e13e05fa9446, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180909-085959-af1c509c-verify-fedora-29/log.html)
