### ISSUE TITLE
SELinux map denials for dogtag-ipa-rene on fedora-29

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#10031]
Happens during `check-sosreport` tests.

https://bugzilla.redhat.com/show_bug.cgi?id=1626849

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_sosreport.TestSOS)
#
[0914/045047.365890:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9738/devtools/browser/b90a461e-c945-497a-9b6c-105af7241e8f
[0914/045047.394751:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 32674: Permission denied (13)
[0914/045047.597077:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 32720: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Unexpected journal messages:
audit: type=1400 audit(1536900697.285:630): avc:  denied  { map } for  pid=4371 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F6666696B4D62677975202864656C6574656429 dev="tmpfs" ino=40027 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1536900697.298:631): avc:  denied  { map } for  pid=4371 comm="dogtag-ipa-rene" path=2F746D702F6666695A4A70593876202864656C6574656429 dev="tmpfs" ino=40028 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1536900697.303:632): avc:  denied  { map } for  pid=4371 comm="dogtag-ipa-rene" path=2F7661722F746D702F666669624854494A78202864656C6574656429 dev="dm-0" ino=18047241 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1536900697.303:633): avc:  denied  { write } for  pid=4371 comm="dogtag-ipa-rene" name="/" dev="tmpfs" ino=11587 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
Wrote JS log to TestSOS-testBasic-fedora-29-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestSOS-testBasic-fedora-29-127.0.0.2-2701-FAIL.log
Wrote screenshot to TestSOS-testBasic-fedora-29-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestSOS-testBasic-fedora-29-127.0.0.2-2701-FAIL.html
Wrote JS log to TestSOS-testBasic-fedora-29-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestSOS-testBasic-fedora-29-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 692, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 873, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536900697.285:630): avc:  denied  { map } for  pid=4371 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F6666696B4D62677975202864656C6574656429 dev="tmpfs" ino=40027 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0

not ok 169 testBasic (check_sosreport.TestSOS) # duration: 118s
```
First occurrence: 2018-09-14T04:52:25.616968 | revision d0cdc4cb45cdc85990dd2c17cbef7b6f30a2ade6, [logs](https://209.132.184.41:8493/logs/pull-9916-20180914-043535-d0cdc4cb-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-14T04:52:25.616968 | revision d0cdc4cb45cdc85990dd2c17cbef7b6f30a2ade6, [logs](https://209.132.184.41:8493/logs/pull-9916-20180914-043535-d0cdc4cb-verify-fedora-29/log.html)
