### ISSUE TITLE
Logging in with AD user crashes cockpit-bridge

### ISSUE THREAD

**Issue by christophert** [cockpit-project/cockpit#10077]
Attempting to login to Cockpit with an AD user causes the bridge to crash. The web UI will display an error indicating that I've been disconnected and it will stop responding until I restart the service.

I am able to retrieve AD user attributes to id/getent and am able to SSH/sudo on the machine normally.

This is the relevant syslog entry:
```Sep 16 20:32:24 HOSTNAME cockpit-ws[26297]: cockpit-session: gssapi auth failed: An unsupported mechanism was requested (Unknown error)
Sep 16 20:32:31 HOSTNAME cockpit-session: pam_ssh_add: Failed adding some keys
Sep 16 20:32:31 HOSTNAME cockpit-bridge[31271]: couldn't get polkit authority: Error initializing authority: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)
Sep 16 20:32:31 HOSTNAME cockpit-ws[26297]: logged in user session
Sep 16 20:32:31 HOSTNAME cockpit-ws[26297]: New connection to session from 1.2.3.4
Sep 16 20:32:31 HOSTNAME cockpit-bridge[31271]: Error executing command as another user: No authentication agent found.
Sep 16 20:32:31 HOSTNAME cockpit-bridge[31271]: 1:1!6: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)
Sep 16 20:32:31 HOSTNAME cockpit-bridge[31271]: 1:1!10: (null)
Sep 16 20:32:31 HOSTNAME cockpit-bridge[31271]: 1:1!20: (null)
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: 29#011../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #0  0x00007fa2bd0aeb3a in __waitpid (pid=31292, stat_loc=0x7ffc2c72bba0,
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #1  0x0000557ba0a016f4 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #2  <signal handler called>
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #3  0x00007fa2bdb757d0 in g_slist_find ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #4  0x00007fa2bde345fa in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #5  0x00007fa2bde355b6 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #6  0x00007fa2bde3710e in g_object_new_valist ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #7  0x00007fa2bde373b1 in g_object_new ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #8  0x0000557ba09f60b0 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #9  0x0000557ba09f6438 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #10 0x0000557ba09ec169 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #11 0x00007fa2bc051038 in ffi_call_unix64 ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #12 0x00007fa2bc050a9a in ffi_call ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #13 0x00007fa2bde307ae in g_cclosure_marshal_generic ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #14 0x00007fa2bde2ff75 in g_closure_invoke ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #15 0x00007fa2bde41f82 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #16 0x00007fa2bde4a67f in g_signal_emit_valist ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #17 0x00007fa2bde4afbf in g_signal_emit ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #18 0x0000557ba0a02563 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #19 0x0000557ba0a02803 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #20 0x0000557ba09f69ea in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #21 0x00007fa2bc051038 in ffi_call_unix64 ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #22 0x00007fa2bc050a9a in ffi_call ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #23 0x00007fa2bde307ae in g_cclosure_marshal_generic ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #24 0x00007fa2bde2ff75 in g_closure_invoke ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #25 0x00007fa2bde41f82 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #26 0x00007fa2bde4abdc in g_signal_emit_valist ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #27 0x00007fa2bde4afbf in g_signal_emit ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #28 0x0000557ba09ff925 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #29 0x00007fa2bde329e4 in g_cclosure_marshal_VOID__STRINGv ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #30 0x00007fa2bde301a4 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #31 0x00007fa2bde4a8cd in g_signal_emit_valist ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #32 0x00007fa2bde4afbf in g_signal_emit ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #33 0x00007fa2bdb530a4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #34 0x00007fa2bdb566aa in g_main_context_dispatch ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #35 0x00007fa2bdb56a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #36 0x00007fa2bdb56b0c in g_main_context_iteration ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #37 0x0000557ba09d3074 in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #38 0x00007fa2bcd1f2e1 in __libc_start_main (main=0x557ba09d2bc0, argc=1,
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: #39 0x0000557ba09d3c1a in ?? ()
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: Error: signal Segmentation fault:
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: cockpit-bridge(+0x41709)[0x557ba0a01709]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /lib/x86_64-linux-gnu/libc.so.6(+0x33060)[0x7fa2bcd32060]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_slist_find+0x10)[0x7fa2bdb757d0]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x145fa)[0x7fa2bde345fa]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x155b6)[0x7fa2bde355b6]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_new_valist+0x44e)[0x7fa2bde3710e]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_new+0xf1)[0x7fa2bde373b1]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: cockpit-bridge(+0x360b0)[0x557ba09f60b0]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: cockpit-bridge(+0x36438)[0x557ba09f6438]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: cockpit-bridge(+0x2c169)[0x557ba09ec169]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c)[0x7fa2bc051038]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x32a)[0x7fa2bc050a9a]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_generic+0x20e)[0x7fa2bde307ae]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x145)[0x7fa2bde2ff75]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x21f82)[0x7fa2bde41f82]
Sep 16 20:32:32 HOSTNAME cockpit-bridge[31271]: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x8df)[0x7fa2bde4a67f]
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write control message: Broken pipe
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write control message: Broken pipe
Sep 16 20:32:32 HOSTNAME cockpit-ws[26297]: /dashboard/index.html: external channel failed: internal-error
Sep 16 20:32:32 HOSTNAME cockpit-ws[26297]: /base1/fonts/fontawesome.woff: external channel failed: internal-error
Sep 16 20:32:32 HOSTNAME cockpit-ws[26297]: /base1/fonts/patternfly.woff: external channel failed: internal-error
Sep 16 20:32:32 HOSTNAME cockpit-ws[26297]: WebSocket from 1.2.3.4 for session closed
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write control message: Broken pipe
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write control message: Broken pipe
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write control message: Broken pipe
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write control message: Broken pipe
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write authorize message: Broken pipe
Sep 16 20:32:32 HOSTNAME cockpit-ssh[31290]: couldn't write authorize message: Broken pipe```

**Comment by martinpitt** [comment]
What's your Linux distribution and cockpit version? Are you able to install debug symbols and reproduce the crash, so that the stack trace becomes useful?

**Comment by martinpitt** [comment]
Ping? I'm afraid we need much more information about this, starting with the previous comment. Without being able to reproduce or a detailled stack trace we can't do anything about this.

**Comment by marusak** [comment]
No additional info
