### ISSUE TITLE
SELinux denies certmonger to output certificates to /run/cockpit

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10086]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1629685

**Comment by cockpituous** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
[0917/110759.695521:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9503/devtools/browser/284f6736-77d0-4983-8c67-22c090d12d57
[0917/110759.750441:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 311574: Permission denied (13)
[0917/110759.945296:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 311607: Permission denied (13)
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1001' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 1
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 2
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 3
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 4
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 5
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 6
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 7
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 8
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 9
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 10
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 11
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 12
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 13
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 14
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 15
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 16
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 17
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=0 O = 3f49587e219c4846abc47b14c4fc04a5, CN = x0.cockpit.lan
verify error:num=18:self signed certificate
140413980239680:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1916:
Wrote screenshot to TestRealms-testIpa-rhel-x-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestRealms-testIpa-rhel-x-127.0.0.2-2201-FAIL.html
Wrote JS log to TestRealms-testIpa-rhel-x-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestRealms-testIpa-rhel-x-127.0.0.2-2201-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-realms", line 154, in testIpa
    out = m.execute("openssl s_client -verify 5 -verify_return_error -connect localhost:9090")
  File "/build/cockpit/bots/machine/testvm.py", line 510, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'openssl s_client -verify 5 -verify_return_error -connect localhost:9090' returned non-zero exit status 1.

not ok 140 testIpa (check_realms.TestRealms) # duration: 345s
```
First occurrence: 2018-09-17T11:11:54.808284 | revision d627c7316a3a4d659d7209f4c9fe43eac36cdaab, [logs](https://209.132.184.41:8493/logs/pull-10074-20180917-105353-d627c731-verify-rhel-x/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-17T11:11:54.808284 | revision d627c7316a3a4d659d7209f4c9fe43eac36cdaab, [logs](https://209.132.184.41:8493/logs/pull-10074-20180917-105353-d627c731-verify-rhel-x/log.html)

**Comment by martinpitt** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (__main__.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
[0930/233514.247075:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9479/devtools/browser/65d104f6-6502-4e09-97fc-64b7d059e8b8
> warning: Failed to query RHEL subscription status: 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=0 O = 771f2cccf0c04588ab3339ad34ba8433, CN = x0.cockpit.lan
verify error:num=18:self signed certificate
140051179697984:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1924:
Wrote screenshot to TestRealms-testIpa-fedora-29-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-29-127.0.0.2-2201-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-29-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-29-127.0.0.2-2201-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-realms", line 154, in testIpa
    out = m.execute("openssl s_client -verify 5 -verify_return_error -connect localhost:9090")
  File "/home/martin/upstream/c2/bots/machine/testvm.py", line 510, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'openssl s_client -verify 5 -verify_return_error -connect localhost:9090' returned non-zero exit status 1.

not ok 1 testIpa (__main__.TestRealms) # duration: 126s
```
First occurrence: 2018-09-30T23:36:23.537949
Times recorded: 1
Latest occurrences:

- 2018-09-30T23:36:23.537949

**Comment by cockpituous** [comment]
verify/fedora-28
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
[1015/205719.091541:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10041/devtools/browser/4cee1626-6d5a-468b-98d4-2fda156f41bb
[1015/205719.096892:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 85213: Permission denied (13)
[1015/205719.318597:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 85250: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f28&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache keyring 'persistent:0:0' not found
klist: Credentials cache keyring 'persistent:1000:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=0 O = e74a90b706d14e49b659ebe6bf64434f, CN = x0.cockpit.lan
verify error:num=18:self signed certificate
139752250177344:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1245:
Wrote screenshot to TestRealms-testIpa-fedora-28-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-28-127.0.0.2-2401-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-28-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-28-127.0.0.2-2401-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2402-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-realms", line 154, in testIpa
    out = m.execute("openssl s_client -verify 5 -verify_return_error -connect localhost:9090")
  File "/build/cockpit/bots/machine/testvm.py", line 510, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'openssl s_client -verify 5 -verify_return_error -connect localhost:9090' returned non-zero exit status 1.

not ok 171 testIpa (check_realms.TestRealms) # duration: 133s
```
First occurrence: 2018-10-15T20:58:24.430968 | revision 7dcc5073849332f83f0e3278e79fd7bb790db40d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10296-20181015-204343-7dcc5073-verify-fedora-28/log.html)
Times recorded: 1
Latest occurrences:

- 2018-10-15T20:58:24.430968 | revision 7dcc5073849332f83f0e3278e79fd7bb790db40d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10296-20181015-204343-7dcc5073-verify-fedora-28/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
[1015/213553.419539:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9540/devtools/browser/0d50bb5e-9bf7-4b88-8a5d-096ddcc483c8
[1015/213553.423163:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 116789: Permission denied (13)
[1015/213553.593921:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 116815: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f28&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f28&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f28&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache keyring 'persistent:0:0' not found
klist: Credentials cache keyring 'persistent:1000:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=0 O = e272fe16215d0d9a7c7abda872dbfbae, CN = x0.cockpit.lan
verify error:num=18:self signed certificate
3081090816:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1245:
Wrote screenshot to TestRealms-testIpa-fedora-i386-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-i386-127.0.0.2-2801-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-i386-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-i386-127.0.0.2-2801-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2802-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-realms", line 154, in testIpa
    out = m.execute("openssl s_client -verify 5 -verify_return_error -connect localhost:9090")
  File "/build/cockpit/bots/machine/testvm.py", line 510, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'openssl s_client -verify 5 -verify_return_error -connect localhost:9090' returned non-zero exit status 1.

not ok 171 testIpa (check_realms.TestRealms) # duration: 106s
```
First occurrence: 2018-10-15T21:36:45.968700 | revision 3036a3b2564d0eabd28e6c5f3f51543d9be1a1fe, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10298-20181015-212323-3036a3b2-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2018-10-15T21:36:45.968700 | revision 3036a3b2564d0eabd28e6c5f3f51543d9be1a1fe, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10298-20181015-212323-3036a3b2-verify-fedora-i386/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
[1016/125301.315233:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9609/devtools/browser/04e7fd12-0ce1-46ba-a95c-04baed02b0d2
[1016/125301.318903:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 24822: Permission denied (13)
[1016/125301.480592:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 24862: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f28&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache keyring 'persistent:0:0' not found
klist: Credentials cache keyring 'persistent:1000:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 1
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 2
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 3
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 4
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 5
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 6
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 7
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 8
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 9
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 10
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 11
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 12
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 13
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 14
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 15
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 16
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=0 O = 1228e3899c0c43d6a2fa7098a73a0614, CN = x0.cockpit.lan
verify error:num=18:self signed certificate
139739405186880:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1245:
Wrote screenshot to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2902-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-realms", line 154, in testIpa
    out = m.execute("openssl s_client -verify 5 -verify_return_error -connect localhost:9090")
  File "/build/cockpit/bots/machine/testvm.py", line 510, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'openssl s_client -verify 5 -verify_return_error -connect localhost:9090' returned non-zero exit status 1.

not ok 185 testIpa (check_realms.TestRealms) # duration: 250s
```
First occurrence: 2018-10-16T12:56:20.256673 | revision e55c04ca78840359c8347a0c45c1415010a6a637, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10311-20181016-124141-e55c04ca-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-10-16T12:56:20.256673 | revision e55c04ca78840359c8347a0c45c1415010a6a637, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10311-20181016-124141-e55c04ca-verify-fedora-testing/log.html)
