### ISSUE TITLE
Failed to execute com.redhat.*: Permission denied

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10188]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1634496

**Comment by martinpitt** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNoUpdates (__main__.TestUpdatesSubscriptions)
#
++ seq 1 200
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ break
[1001/084002.761140:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9312/devtools/browser/32987387-a78e-4c0a-b0d8-5426f78dcba0
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
Wrote screenshot to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2301-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2301-FAIL.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-candlepin-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-packagekit", line 720, in testNoUpdates
    b.wait_in_text("#system_information_updates_text", "Not Registered")
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 314, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#system_information_updates_text","Not Registered")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":4,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1538376003414.77, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '1000015602.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold

not ok 1 testNoUpdates (__main__.TestUpdatesSubscriptions) # duration: 120s
```
First occurrence: 2018-10-01T08:41:07.466164
Times recorded: 1
Latest occurrences:

- 2018-10-01T08:41:07.466164
