### ISSUE TITLE
fedora 29: grub2-mkconfig crashes

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10240]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1637055

**Comment by martinpitt** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
#
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.
[1008/161441.595721:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9988/devtools/browser/8eb1cf09-1b90-4d72-8560-9c244042563d
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> error: Warning: Each child in an array or iterator should have a unique "key" prop.%s%s See https://fb.me/react-warning-keys for more information.%s 

Check the render method of `KdumpPage`.  
    in span (created by KdumpPage)
    in KdumpPage
> warning: Failed to query RHEL subscription status: 
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.18.11-301.fc29.x86_64
Found initrd image: /boot/initramfs-4.18.11-301.fc29.x86_64.img
Found linux image: /boot/vmlinuz-4.18.10-300.fc29.x86_64
Found initrd image: /boot/initramfs-4.18.10-300.fc29.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-0a158232059d43f3b98dac3f2e24968b
Found initrd image: /boot/initramfs-0-rescue-0a158232059d43f3b98dac3f2e24968b.img
error: ../grub-core/script/lexer.c:337:$.
error: ../grub-core/script/lexer.c:337:syntax error.
error: ../grub-core/script/lexer.c:337:Incorrect command.
error: ../grub-core/script/lexer.c:337:syntax error.
Syntax error at line 86
Syntax errors are detected in generated GRUB config file.
Ensure that there are no errors in /etc/default/grub
and /etc/grub.d/* files or please file a bug report with
/boot/grub2/grub.cfg.new file attached.
Wrote screenshot to TestKdump-testBasic-fedora-29-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-29-127.0.0.2-2301-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-29-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-29-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 92, in testBasic
    self.enableKdump()
  File "test/verify/check-kdump", line 41, in enableKdump
    self.machine.execute("grub2-mkconfig -o /boot/grub2/grub.cfg")
  File "/home/martin/upstream/c2/bots/machine/testvm.py", line 510, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'grub2-mkconfig -o /boot/grub2/grub.cfg' returned non-zero exit status 1.

not ok 1 testBasic (__main__.TestKdump) # duration: 28s
```
First occurrence: 2018-10-08T16:14:51.152772
Times recorded: 1
Latest occurrences:

- 2018-10-08T16:14:51.152772
