### ISSUE TITLE
 grub2-mkconfig now silently ignores options in GRUB_CMDLINE_LINUX=

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10262]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1637875

**Comment by martinpitt** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
#
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
[1010/111336.466373:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10165/devtools/browser/7bf1390f-1284-4051-9462-740599cd5d82
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
Generating grub configuration file ...
done
> warning: transport closed: disconnected
Connection to 127.0.0.2 closed by remote host.
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1539162824988.24,"url":"http://127.0.0.2:9091/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"1000029341.28"}
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: read: Connection reset by peer
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
Wrote screenshot to TestKdump-testBasic-rhel-x-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestKdump-testBasic-rhel-x-127.0.0.2-2201-FAIL.html
Wrote JS log to TestKdump-testBasic-rhel-x-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-x-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 97, in testBasic
    self.browser.wait_in_text("#app", "256 MiB")
  File "/home/martin/upstream/c2/test/common/testlib.py", line 314, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/c2/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#app","256 MiB")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '49', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '49', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '49', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":9,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1539162817209.75, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000029341.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: transport closed: disconnected
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: net::ERR_EMPTY_RESPONSE', 'timestamp': 1539162824988.24, 'url': 'http://127.0.0.2:9091/cockpit/static/fonts/OpenSans-Light-webfont.woff', 'networkRequestId': '1000029341.28'}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1539162850799.04, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000029341.114'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold

not ok 1 testBasic (__main__.TestKdump) # duration: 199s
```
First occurrence: 2018-10-10T11:16:15.038720
Times recorded: 1
Latest occurrences:

- 2018-10-10T11:16:15.038720
