### ISSUE TITLE
kvdo broken on current rhel-x: kernel version mismatch

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10264]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1637911

**Comment by martinpitt** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorage)
#
[1010/121829.754991:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9688/devtools/browser/5c60c55e-3294-4bd9-bfec-fbc4321b9cd3
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-23.el8.x86_64

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-23.el8.x86_64
Wrote screenshot to TestStorage-testVdo-rhel-x-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testVdo-rhel-x-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testVdo-rhel-x-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testVdo-rhel-x-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-vdo", line 57, in testVdo
    self.dialog_wait_close()
  File "/home/martin/upstream/c2/test/verify/storagelib.py", line 276, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/martin/upstream/c2/test/common/testlib.py", line 290, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/c2/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1539166710281.01, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000001781.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-23.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-23.el8.x86_64

not ok 1 testVdo (__main__.TestStorage) # duration: 87s
```
First occurrence: 2018-10-10T12:19:43.593482
Times recorded: 1
Latest occurrences:

- 2018-10-10T12:19:43.593482
