### ISSUE TITLE
libssh 0.8.1 fails to parse known_hosts, resulting in SSH_SERVER_FOUND_OTHER error for hostkey verification

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10426]
Downstream report: https://launchpad.net/bugs/1799665

**Comment by martinpitt** [comment]
I prepared a stable release update and sent it to Ubuntu. With that package, the tests work fine again.

**Comment by martinpitt** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNegotiate (__main__.TestKerberos)
#
+ seq 1 20
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ break
+ realm join -vU admin cockpit.lan
+ echo foobarfoo
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Unconditionally checking packages
 * Resolving required packages
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2018-10-22 22:54:28
    Valid Until: 2038-10-22 22:54:28

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
SSSD enabled
Configured /etc/openldap/ldap.conf
Unable to find 'admin' user with 'getent passwd admin@cockpit.lan'!
Unable to reliably detect configuration. Check NSS setup manually.
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful
This program will set up FreeIPA client.
Version 4.7.1

WARNING: conflicting time&date synchronization service 'ntp' will be disabled
in favor of chronyd


Using default chrony configuration.
 * /usr/sbin/update-rc.d sssd enable
 * /usr/sbin/service sssd restart
 * Successfully enrolled machine in realm
+ seq 1 20
+ KRB5_TRACE=/dev/stderr kinit -f admin@COCKPIT.LAN
+ echo foobarfoo
[7533] 1540374523.494755: Getting initial credentials for admin@COCKPIT.LAN
[7533] 1540374523.494757: Sending unauthenticated request
[7533] 1540374523.494758: Sending request (171 bytes) to COCKPIT.LAN
[7533] 1540374523.494759: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[7533] 1540374523.494760: No URI records found
[7533] 1540374523.494761: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[7533] 1540374523.494762: SRV answer: 0 100 88 "f0.cockpit.lan."
[7533] 1540374523.494763: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[7533] 1540374523.494764: SRV answer: 0 100 88 "f0.cockpit.lan."
[7533] 1540374523.494765: Resolving hostname f0.cockpit.lan.
[7533] 1540374523.494766: Resolving hostname f0.cockpit.lan.
[7533] 1540374523.494767: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[7533] 1540374523.494768: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[7533] 1540374523.494769: Initiating TCP connection to stream 172.27.0.15:88
[7533] 1540374523.494770: Terminating TCP connection to stream 172.27.0.15:88
[7533] 1540374523.494771: Initiating TCP connection to stream 10.111.112.100:88
[7533] 1540374523.494772: Sending TCP request to stream 10.111.112.100:88
[7533] 1540374523.494773: Received answer (492 bytes) from stream 10.111.112.100:88
[7533] 1540374523.494774: Terminating TCP connection to stream 10.111.112.100:88
[7533] 1540374523.494775: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[7533] 1540374523.494776: No URI records found
[7533] 1540374523.494777: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[7533] 1540374523.494778: SRV answer: 0 100 88 "f0.cockpit.lan."
[7533] 1540374523.494779: Response was from master KDC
[7533] 1540374523.494780: Received error from KDC: -1765328359/Additional pre-authentication required
[7533] 1540374523.494783: Preauthenticating using KDC method data
[7533] 1540374523.494784: Processing preauth types: 16, 15, 14, 136, 19, 147, 151, 2, 133
[7533] 1540374523.494785: Selected etype info: etype aes256-cts, salt "F_M/K}!?(u:O]eI}", params ""
[7533] 1540374523.494786: Received cookie: MIT1\x00\x00\x00\x01\xbf\x95\xd2g\x04f\x1d\x0b\xf4'\x15\xf5\xd8\x93\x99^\xb6{\xf8\xcd\xb6\xc0db\xe6Y\xe1\xeb\xbdfw0Y\x95)\xb0\xb4UA"l\xf7F\x11\xc2\x8fl\xbe\xc6W\xacK\x9b\x120\xc0\xe5\xe7\xc4\xc1\x81[\xd75s\x0a\x8f\xcf2\xe3F\xe5i\x9aJ\xf7\x1a\x1a~\xb3\xc7/\x98\xbf\xc0\xbeS\x86\x93)b\xe4iI\x82l9]\xc1\xf1I]+\xf2\xeeYG\xc5zp\x9f=\x8d\xaf\xd8\x86\x9c"Ou0\xa0?yx(\x7f\xb9\xd0n
[7533] 1540374523.494787: AS key obtained for encrypted timestamp: aes256-cts/B653
[7533] 1540374523.494789: Encrypted timestamp (for 1540374523.603598): plain 301AA011180F32303138313032343039343834335AA10502030935CE, encrypted 750D1F37532736C2181BB436CCC4E0B0A062AE8262BE2B1130256C0D30CDC31C2F0B8EF314D7A68A0835AA66362B48421143F9AB469BC180
[7533] 1540374523.494790: Preauth module encrypted_timestamp (2) (real) returned: 0/Success
[7533] 1540374523.494791: Produced preauth for next request: 133, 2
[7533] 1540374523.494792: Sending request (406 bytes) to COCKPIT.LAN
[7533] 1540374523.494793: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[7533] 1540374523.494794: No URI records found
[7533] 1540374523.494795: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[7533] 1540374523.494796: SRV answer: 0 100 88 "f0.cockpit.lan."
[7533] 1540374523.494797: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[7533] 1540374523.494798: SRV answer: 0 100 88 "f0.cockpit.lan."
[7533] 1540374523.494799: Resolving hostname f0.cockpit.lan.
[7533] 1540374523.494800: Resolving hostname f0.cockpit.lan.
[7533] 1540374523.494801: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[7533] 1540374523.494802: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[7533] 1540374523.494803: Initiating TCP connection to stream 172.27.0.15:88
[7533] 1540374523.494804: Terminating TCP connection to stream 172.27.0.15:88
[7533] 1540374523.494805: Initiating TCP connection to stream 10.111.112.100:88
[7533] 1540374523.494806: Sending TCP request to stream 10.111.112.100:88
[7533] 1540374523.494807: Received answer (724 bytes) from stream 10.111.112.100:88
[7533] 1540374523.494808: Terminating TCP connection to stream 10.111.112.100:88
[7533] 1540374523.494809: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[7533] 1540374523.494810: No URI records found
[7533] 1540374523.494811: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[7533] 1540374523.494812: SRV answer: 0 100 88 "f0.cockpit.lan."
[7533] 1540374523.494813: Response was from master KDC
[7533] 1540374523.494814: Processing preauth types: 19
[7533] 1540374523.494815: Selected etype info: etype aes256-cts, salt "F_M/K}!?(u:O]eI}", params ""
[7533] 1540374523.494816: Produced preauth for next request: (empty)
[7533] 1540374523.494817: AS key determined by preauth: aes256-cts/B653
[7533] 1540374523.494818: Decrypted AS reply; session key is: aes256-cts/B5D4
[7533] 1540374523.494819: FAST negotiation: available
[7533] 1540374523.494820: Initializing KEYRING:persistent:0:0 with default princ admin@COCKPIT.LAN
[7533] 1540374523.494821: Storing admin@COCKPIT.LAN -> krbtgt/COCKPIT.LAN@COCKPIT.LAN in KEYRING:persistent:0:0
[7533] 1540374523.494822: Storing config in KEYRING:persistent:0:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: fast_avail: yes
[7533] 1540374523.494823: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/fast_avail/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KEYRING:persistent:0:0
[7533] 1540374523.494824: Storing config in KEYRING:persistent:0:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: pa_type: 2
[7533] 1540374523.494825: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/pa_type/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KEYRING:persistent:0:0
+ break
+ grep -iq ^C\.utf
+ locale -a
+ loc=C.UTF-8
+ type ipa
+ LC_ALL=C.UTF-8 ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN
+ ipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab
+ seq 1 60
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 1
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 2
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 3
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 4
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 5
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 6
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 7
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 8
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 9
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 10
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 11
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 12
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 13
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 14
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 15
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sleep 16
+ getent passwd admin
+ break
+ getent passwd admin
+ chown -R admin /home/admin
+ seq 1 60
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin x0.cockpit.lan true
+ break
[1024/115106.996685:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9912/devtools/browser/66f1feec-a6d5-440d-839a-8f3eea728ce7
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
Wrote screenshot to TestKerberos-testNegotiate-ubuntu-stable-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestKerberos-testNegotiate-ubuntu-stable-127.0.0.2-2301-FAIL.html
Wrote JS log to TestKerberos-testNegotiate-ubuntu-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKerberos-testNegotiate-ubuntu-stable-127.0.0.2-2301-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-realms", line 506, in testNegotiate
    b.wait_in_text('#troubleshoot-dialog h4', "Log in to")
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 314, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 281, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 278, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#troubleshoot-dialog h4","Log in to")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":2,"id":1}'}}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold

not ok 1 testNegotiate (__main__.TestKerberos) # duration: 327s
```
First occurrence: 2018-10-24T11:52:12.671898
Times recorded: 1
Latest occurrences:

- 2018-10-24T11:52:12.671898

**Comment by Mausy5043** [comment]
I have his problem also/still on Raspberry Pi (Raspbian)
```
cockpit-ssh ***: bridge killed by signal SEGV
```
```
Linux *** 4.19.42+ #1219 Tue May 14 21:16:38 BST 2019 armv6l
```
and
```
Linux *** 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
```

**Comment by lachlan-00** [comment]
@Mausy5043
This is because the pi doesn't have all the CPU instructions that debian uses in arm.

I had to compile it manually to work on a pi. using the compiled deb will not work
