### ISSUE TITLE
 SELinux is preventing systemd-timesyncd from using the 'nnp_transition'

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10586]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1649257

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTimeServers (check_system_info.TestSystemInfo)
#
Removed /etc/systemd/system/dbus-org.freedesktop.timedate1.service.
Removed /etc/systemd/system/systemd-timedated.service.
[1115/141244.670087:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9662/devtools/browser/3c4fa3c2-f32f-4376-aec0-a2bb17846e25
[1115/141244.674626:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 21466: Permission denied (13)
[1115/141244.845703:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 21490: Permission denied (13)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: Failed to query RHEL subscription status: {"problem":null,"name":"org.freedesktop.DBus.Python.AttributeError","message":"Traceback (most recent call last):\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/identity.py\", line 140, in reload\n    self.consumer = self._get_consumer_identity()\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/identity.py\", line 164, in _get_consumer_identity\n    return ConsumerIdentity.read()\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/identity.py\", line 53, in read\n    with open(cls.keypath()) as key_file:\nFileNotFoundError: [Errno 2] No such file or directory: '/etc/pki/consumer/key.pem'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib64/python3.7/site-packages/dbus/service.py\", line 707, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"<decorator-gen-2>\", line 2, in check_status\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/scripts/rhsm_d.py\", line 161, in ensure_exit\n    return func(*args, **kwargs)\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/scripts/rhsm_d.py\", line 216, in check_status\n    status = check_status(self.force_signal)\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/scripts/rhsm_d.py\", line 134, in check_status\n    pre_result = pre_check_status(force_signal)\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/scripts/rhsm_d.py\", line 124, in pre_check_status\n    identity = require(IDENTITY)\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/injection.py\", line 106, in require\n    return FEATURES.require(feature, *args, **kwargs)\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/injection.py\", line 80, in require\n    self.providers[feature] = provider(*args, **kwargs)\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/identity.py\", line 133, in __init__\n    self.reload()\n  File \"/usr/lib64/python3.7/site-packages/subscription_manager/identity.py\", line 147, in reload\n    if isinstance(err, IOError) and err.errno == os.errno.ENOENT:\nAttributeError: module 'os' has no attribute 'errno'\n"}
Unexpected journal messages:
audit: type=1400 audit(1542291172.643:298): avc:  denied  { nnp_transition } for  pid=1759 comm="(imesyncd)" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:systemd_timedated_t:s0 tclass=process2 permissive=0
audit: type=1401 audit(1542291172.643:298): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:init_t:s0 newcontext=system_u:system_r:systemd_timedated_t:s0
Wrote JS log to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.log
Wrote screenshot to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 694, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 875, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1542291172.643:298): avc:  denied  { nnp_transition } for  pid=1759 comm="(imesyncd)" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:systemd_timedated_t:s0 tclass=process2 permissive=0

not ok 209 testTimeServers (check_system_info.TestSystemInfo) # duration: 33s
```
First occurrence: 2018-11-15T14:12:58.105631 | revision 3e5688ff94862a855ca8839ce5288dfb8502409c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10587-20181115-135959-3e5688ff-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-11-15T14:12:58.105631 | revision 3e5688ff94862a855ca8839ce5288dfb8502409c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10587-20181115-135959-3e5688ff-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTimeServers (check_system_info.TestSystemInfo)
#
Removed /etc/systemd/system/dbus-org.freedesktop.timedate1.service.
Removed /etc/systemd/system/systemd-timedated.service.
[1116/110153.737364:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10071/devtools/browser/28fab6d7-97fd-4527-a6a3-4d14137cdf24
[1116/110153.741176:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 113863: Permission denied (13)
[1116/110153.924708:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 113888: Permission denied (13)
Unexpected journal messages:
audit: type=1400 audit(1542366122.596:295): avc:  denied  { nnp_transition } for  pid=1607 comm="(imesyncd)" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:systemd_timedated_t:s0 tclass=process2 permissive=0
audit: type=1401 audit(1542366122.596:295): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:init_t:s0 newcontext=system_u:system_r:systemd_timedated_t:s0
Wrote JS log to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2401-FAIL.log
Wrote screenshot to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 694, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 876, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1542366122.596:295): avc:  denied  { nnp_transition } for  pid=1607 comm="(imesyncd)" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:systemd_timedated_t:s0 tclass=process2 permissive=0

not ok 215 testTimeServers (check_system_info.TestSystemInfo) # duration: 36s
```
First occurrence: 2018-11-16T11:02:07.002459 | revision 90528c7bf95225b1725bff7e2c80676a2837bd57, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10567-20181116-105252-90528c7b-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2018-11-16T11:02:07.002459 | revision 90528c7bf95225b1725bff7e2c80676a2837bd57, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10567-20181116-105252-90528c7b-verify-fedora-i386/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTimeServers (check_system_info.TestSystemInfo)
#
Removed /etc/systemd/system/dbus-org.freedesktop.timedate1.service.
Removed /etc/systemd/system/systemd-timedated.service.
[1127/044613.792900:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10145/devtools/browser/790c78c0-93f5-4802-8d04-610aef00deb7
[1127/044613.796223:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 17943: Permission denied (13)
[1127/044613.964603:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 18007: Permission denied (13)
Unexpected journal messages:
audit: type=1400 audit(1543293981.440:298): avc:  denied  { nnp_transition } for  pid=1743 comm="(imesyncd)" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:systemd_timedated_t:s0 tclass=process2 permissive=0
audit: type=1401 audit(1543293981.440:298): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:init_t:s0 newcontext=system_u:system_r:systemd_timedated_t:s0
Wrote JS log to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.log
Wrote screenshot to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 737, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 919, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1543293981.440:298): avc:  denied  { nnp_transition } for  pid=1743 comm="(imesyncd)" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:systemd_timedated_t:s0 tclass=process2 permissive=0

not ok 251 testTimeServers (check_system_info.TestSystemInfo) # duration: 34s
```
First occurrence: 2018-11-27T04:46:26.257669 | revision 49618737538d490a6f8e33a16329b60f398be2b9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10679-20181127-043737-49618737-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-11-27T04:46:26.257669 | revision 49618737538d490a6f8e33a16329b60f398be2b9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10679-20181127-043737-49618737-verify-fedora-testing/log.html)
