### ISSUE TITLE
test: lib - execute in machine_core/ssh_connection.py causes traceback when run under avocado(unittest)

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#10674]
There is touble with using ``execute`` method of command  inside: ``ssh_connection``
it contains code like: ``os.write(sys.stderr.fileno(), data)``
what causes traceback, because avocado (also some other frameworks) redirects stdout/err to logs

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 925, in _run_avocado
    raise test_exception

  File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 826, in _run_avocado
    testMethod()

  File "/home/jscotka/git/cockpit/test/avocado/selenium-base.py", line 177, in test80TerminalTool
    self.machine.execute("ls {0}abc |wc -l |grep 0".format(prefix))

  File "/home/jscotka/git/cockpit/test/avocado/machine_core/ssh_connection.py", line 334, in execute
    os.write(sys.stderr.fileno(), data)

AttributeError: 'LoggingFile' object has no attribute 'fileno'
```
there helped explicitly put there ``quiet=True`` to avoid this code execution

**Comment by marusak** [comment]
@jscotka can you please write how to reproduce this?
Also, would you be interested in fixing of this?
