### ISSUE TITLE
firewall-cmd --reload fails: RULE_REPLACE failed (No such file or directory): rule in chain {INPUT,OUTPUT}

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10671]
Downstream report: https://bugs.debian.org/914694

**Comment by martinpitt** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInternal (__main__.TestMetrics)
#
[1126/132937.255635:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9659/devtools/browser/289ee13e-f4cb-4024-9ef1-4c9455f55af8
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
Measured CPU 98.44813424520551
Measured Memory 301178880
Error: COMMAND_FAILED: '/sbin/ip6tables-restore -w -n' failed: ip6tables-restore v1.8.2 (nf_tables): 
line 4: RULE_REPLACE failed (No such file or directory): rule in chain INPUT
line 4: RULE_REPLACE failed (No such file or directory): rule in chain OUTPUT

Wrote screenshot to TestMetrics-testInternal-debian-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMetrics-testInternal-debian-testing-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMetrics-testInternal-debian-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMetrics-testInternal-debian-testing-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-metrics", line 195, in testInternal
    self.check_host_metrics()
  File "test/verify/check-metrics", line 150, in check_host_metrics
    m.execute("if firewall-cmd --state >/dev/null 2>&1; then firewall-cmd --permanent --zone=public --add-port=2000/tcp && firewall-cmd --reload; fi")
  File "/home/martin/upstream/c2/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'if firewall-cmd --state >/dev/null 2>&1; then firewall-cmd --permanent --zone=public --add-port=2000/tcp && firewall-cmd --reload; fi' returned non-zero exit status 13.

not ok 1 testInternal (__main__.TestMetrics) # duration: 100s
```
First occurrence: 2018-11-26T13:31:04.699576
Times recorded: 1
Latest occurrences:

- 2018-11-26T13:31:04.699576

**Comment by martinpitt** [comment]
Since this breaks too much, I went a different route and applied a workaround in #10648.
