### ISSUE TITLE
subscription-manager crashes: the 'dbus-python' distribution was not found

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10700]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1651669

**Comment by martinpitt** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNoUpdates (__main__.TestUpdatesSubscriptions)
#
++ seq 1 200
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ break
[1129/132050.658274:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9305/devtools/browser/ccd5efd7-0d50-4e12-a35c-3a1bb17605d5
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
Wrote screenshot to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2201-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-rhel-x-127.0.0.2-2201-FAIL.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-candlepin-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-packagekit", line 741, in testNoUpdates
    b.wait_in_text("#system_information_updates_text", "Not Registered")
  File "/home/martin/upstream/c2/test/common/testlib.py", line 354, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 321, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/c2/test/common/testlib.py", line 318, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#system_information_updates_text","Not Registered")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":4,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1543494051230.45, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000027307.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold

not ok 1 testNoUpdates (__main__.TestUpdatesSubscriptions) # duration: 123s
```
First occurrence: 2018-11-29T13:21:55.435280
Times recorded: 1
Latest occurrences:

- 2018-11-29T13:21:55.435280

**Comment by cockpituous** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNoUpdates (check_packagekit.TestUpdatesSubscriptions)
#
++ seq 1 200
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.113.5:8443/candlepin
+ break
[1203/141536.804077:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9929/devtools/browser/b5db1931-ec98-4014-94c7-2c4e34cfaec6
[1203/141536.807498:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 338240: Permission denied (13)
[1203/141536.919454:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 338264: Permission denied (13)
Wrote screenshot to TestUpdatesSubscriptions-testNoUpdates-rhel-8-0-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testNoUpdates-rhel-8-0-127.0.0.2-2601-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testNoUpdates-rhel-8-0-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-rhel-8-0-127.0.0.2-2601-FAIL.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-candlepin-127.0.0.2-2602-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-packagekit", line 741, in testNoUpdates
    b.wait_in_text("#system_information_updates_text", "Not Registered")
  File "/build/cockpit/test/common/testlib.py", line 354, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 321, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 318, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#system_information_updates_text","Not Registered")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":4,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1543846537348.71, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '1000338264.8'}

not ok 237 testNoUpdates (check_packagekit.TestUpdatesSubscriptions) # duration: 135s
```
First occurrence: 2018-12-03T14:16:41.190065 | revision 32b57a585ceeca590fb72c5e9998eb014cb5a8cf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10740-20181203-140707-32b57a58-verify-rhel-8-0/log.html)
Times recorded: 1
Latest occurrences:

- 2018-12-03T14:16:41.190065 | revision 32b57a585ceeca590fb72c5e9998eb014cb5a8cf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10740-20181203-140707-32b57a58-verify-rhel-8-0/log.html)
