### ISSUE TITLE
Debian: qemu crashes in tcg mode when under heavy load

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#10718]
QEMU routinely crashes when in tcg mode and under heavy load on the debian 9 image.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915116

**Comment by martinpitt** [comment]
Excellent downstream report and reproducer! :heart:

**Comment by cockpituous** [comment]
verify/debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreate (check_machines_virsh.TestMachinesVirsh)
#
dpkg: warning: ignoring request to remove libvirt-dbus which isn't installed
[1203/135735.762958:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9997/devtools/browser/b698002d-ebe9-4f8d-92ae-1fc0d559dad1
[1203/135735.766372:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 105741: Permission denied (13)
[1203/135735.925525:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 105766: Permission denied (13)
> info: index.es6: Setting Libvirt as virt provider.
    *
    * validation errors and ui info/warn messages expected:
    * 
> warning: error: failed to get domain 'subVmTestCreate8'
error: Domain not found: no domain with matching name 'subVmTestCreate8'

> warning: spawn 'virsh' process returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get domain 'subVmTestCreate8'\nerror: Domain not found: no domain with matching name 'subVmTestCreate8'"}", data: """"
> warning: dumpxml() exception: 'error: failed to get domain 'subVmTestCreate8'
error: Domain not found: no domain with matching name 'subVmTestCreate8'', data: '', output: '
'
> warning: ERROR    internal error: process exited while connecting to monitor
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate8
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation."}", data: """"
> warning: ERROR    Error: --disk size=10000,format=qcow2: There is not enough free space on the storage pool to create the volume. (10240000 M requested allocation > 5199 M available)

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    Error: --disk size=10000,format=qcow2: There is not enough free space on the storage pool to create the volume. (10240000 M requested allocation > 5199 M available)"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate11
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate11\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate11
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate11\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate12
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate12\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate12
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate12\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate13
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate13\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate13
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate13\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate14
error: Requested operation is not valid: domain is not running

> warning: error: failed to get domain 'subVmTestCreate14'
error: Domain not found: no domain with matching name 'subVmTestCreate14'

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate14\nerror: Requested operation is not valid: domain is not running"}", data: """"
> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get domain 'subVmTestCreate14'\nerror: Domain not found: no domain with matching name 'subVmTestCreate14'"}", data: """"
> warning: error: failed to get domain 'subVmTestCreate15'
error: Domain not found: no domain with matching name 'subVmTestCreate15'

> warning: spawn 'virsh' process returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get domain 'subVmTestCreate15'\nerror: Domain not found: no domain with matching name 'subVmTestCreate15'"}", data: """"
> warning: dumpxml() exception: 'error: failed to get domain 'subVmTestCreate15'
error: Domain not found: no domain with matching name 'subVmTestCreate15'', data: '', output: '
'
> warning: ERROR    internal error: qemu unexpectedly closed the monitor
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///session start subVmTestCreate15
otherwise, please restart your installation.

Unexpected journal messages:
Process 1673 (qemu-system-x86) of user 64055 dumped core.
Process 2649 (qemu-system-x86) of user 1000 dumped core.
Wrote JS log to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2701-FAIL.log
Wrote screenshot to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 737, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 919, in check_journal_messages
    raise Error(first)
testlib.Error: Process 1673 (qemu-system-x86) of user 64055 dumped core.

not ok 81 testCreate (check_machines_virsh.TestMachinesVirsh) # duration: 370s
```
First occurrence: 2018-12-03T14:03:33.589953 | revision 05dded0f728cdde58ba5db5662b6735aa7428111, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10731-20181203-134646-05dded0f-verify-debian-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2018-12-03T14:03:33.589953 | revision 05dded0f728cdde58ba5db5662b6735aa7428111, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10731-20181203-134646-05dded0f-verify-debian-stable/log.html)
