### ISSUE TITLE
kvdo broken on current rhel-8: kernel version mismatch

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#10898]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1662971

**Comment by cockpituous** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (check_storage_vdo.TestStorage)
#
[0102/153746.093236:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9373/devtools/browser/566db08b-f079-499b-b6e1-05d261c060a2
[0102/153746.096739:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 23625: Permission denied (13)
[0102/153746.112758:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/153746.114625:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0102/153746.256654:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 23654: Permission denied (13)
> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-57.el8.x86_64

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-57.el8.x86_64
Wrote screenshot to TestStorage-testVdo-rhel-8-0-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestStorage-testVdo-rhel-8-0-127.0.0.2-2801-FAIL.html
Wrote JS log to TestStorage-testVdo-rhel-8-0-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestStorage-testVdo-rhel-8-0-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-vdo", line 58, in testVdo
    self.dialog_wait_close()
  File "/build/cockpit/test/verify/storagelib.py", line 282, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/common/testlib.py", line 330, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 321, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 318, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1546443466607.25, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '1000023654.8'}
warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-57.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-57.el8.x86_64

not ok 186 testVdo (check_storage_vdo.TestStorage) # duration: 93s
```
First occurrence: 2019-01-02T15:39:00.020257 | revision 2210e60e0c243351a2ac7455feaf56de1f1beb3c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10861-20190102-152727-2210e60e-verify-rhel-8-0/log.html)
Times recorded: 1
Latest occurrences:

- 2019-01-02T15:39:00.020257 | revision 2210e60e0c243351a2ac7455feaf56de1f1beb3c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10861-20190102-152727-2210e60e-verify-rhel-8-0/log.html)
