### ISSUE TITLE
ipa-getcert crashes in ipa-submit

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10901]
Retrieving an IPA certificate stopped working and now causes a crash in ipa-submit.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1663112

**Comment by martinpitt** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (__main__.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
[0103/092950.060390:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9348/devtools/browser/68bf30bf-4a50-4249-aca5-2809c4b00f2c
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=0 O = ae29ed351e949e39eb7611b383a1137b, CN = x0.cockpit.lan
verify error:num=18:self signed certificate
3080374016:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1924:
Wrote screenshot to TestRealms-testIpa-fedora-i386-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-i386-127.0.0.2-2201-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-i386-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-i386-127.0.0.2-2201-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2202-FAIL.log
Core dumps downloaded to /home/martin/upstream/c2/TestRealms-testIpa-fedora-i386-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-realms", line 150, in testIpa
    out = m.execute("openssl s_client -verify 5 -verify_return_error -connect localhost:9090")
  File "/home/martin/upstream/c2/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'openssl s_client -verify 5 -verify_return_error -connect localhost:9090' returned non-zero exit status 1.

not ok 1 testIpa (__main__.TestRealms) # duration: 157s
```
First occurrence: 2019-01-03T09:31:13.823742
Times recorded: 1
Latest occurrences:

- 2019-01-03T09:31:13.823742

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
[0103/121844.519550:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9276/devtools/browser/a5ba1b68-2893-45d3-b6be-ce3ccb740a4c
[0103/121844.524919:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 76547: Permission denied (13)
[0103/121844.540990:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0103/121844.546627:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0103/121844.744858:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 76577: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=0 O = 4e5a43d1514941c79fc6a970fc7ea543, CN = x0.cockpit.lan
verify error:num=18:self signed certificate
139750497183552:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1924:
Wrote screenshot to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2902-FAIL.log
Core dumps downloaded to /build/cockpit/TestRealms-testIpa-fedora-testing-127.0.0.2-2901-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-realms", line 150, in testIpa
    out = m.execute("openssl s_client -verify 5 -verify_return_error -connect localhost:9090")
  File "/build/cockpit/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'openssl s_client -verify 5 -verify_return_error -connect localhost:9090' returned non-zero exit status 1.

not ok 169 testIpa (check_realms.TestRealms) # duration: 170s
```
First occurrence: 2019-01-03T12:20:08.178296 | revision 354a03ffe04baf26112bed59b9b38958d31a0080, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10879-20190103-115959-354a03ff-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2019-01-03T12:20:08.178296 | revision 354a03ffe04baf26112bed59b9b38958d31a0080, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10879-20190103-115959-354a03ff-verify-fedora-testing/log.html)
