### ISSUE TITLE
avc: denied { signull } for comm="systemd-journal"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11228]
This is a very recent regression on RHEL 8.0.

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1679468

**Comment by cockpituous** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTroubleshootAlerts (check_setroubleshoot.TestSelinux)
#
[0221/143239.777296:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10208/devtools/browser/d75cc470-8881-4caf-ac17-5ba8f88d0e30
[0221/143239.782194:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 31225: Permission denied (13)
[0221/143239.793496:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0221/143239.794957:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0221/143239.922774:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 31258: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestSelinux-testTroubleshootAlerts-rhel-8-0-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestSelinux-testTroubleshootAlerts-rhel-8-0-127.0.0.2-2701-FAIL.html
Wrote JS log to TestSelinux-testTroubleshootAlerts-rhel-8-0-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestSelinux-testTroubleshootAlerts-rhel-8-0-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 68, in testTroubleshootAlerts
    b.wait_in_text("body", "No SELinux alerts.")
  File "/build/cockpit/test/common/testlib.py", line 359, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 326, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 323, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("body","No SELinux alerts.")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 206, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 217, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:218:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1550759560259.51, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '1000031258.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


not ok 140 testTroubleshootAlerts (check_setroubleshoot.TestSelinux) # duration: 83s
```
First occurrence: 2019-02-21T14:33:42.734415 | revision 58892773e015678bf80356512fac7fb2b478d31a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-11219-20190221-141111-58892773-verify-rhel-8-0/log.html)
Times recorded: 1
Latest occurrences:

- 2019-02-21T14:33:42.734415 | revision 58892773e015678bf80356512fac7fb2b478d31a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-11219-20190221-141111-58892773-verify-rhel-8-0/log.html)
