### ISSUE TITLE
Debian stretch: virt-install fails to spawn multiple guests with VNC enabled

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#11265]
virt-install always fails to start two domains sequentially with VNC enabled, with error:
```
Failed to start VNC server: Failed to bind socket: Address already in use
```

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923398

**Comment by cockpituous** [comment]
verify/debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreate (check_machines_virsh.TestMachinesVirsh)
#
dpkg: warning: ignoring request to remove libvirt-dbus which isn't installed
[0227/161200.096379:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9744/devtools/browser/7da04019-d0a4-4923-ace3-c8a258d5f7e7
[0227/161200.100746:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 44573: Permission denied (13)
[0227/161200.116893:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0227/161200.119610:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0227/161200.273307:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 44609: Permission denied (13)
> info: index.js: Setting Libvirt as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

    *
    * validation errors and ui info/warn messages expected:
    * 
> warning: error: failed to get domain 'subVmTestCreate8'
error: Domain not found: no domain with matching name 'subVmTestCreate8'

> warning: spawn 'virsh' process returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get domain 'subVmTestCreate8'\nerror: Domain not found: no domain with matching name 'subVmTestCreate8'"}", data: """"
> warning: dumpxml() exception: 'error: failed to get domain 'subVmTestCreate8'
error: Domain not found: no domain with matching name 'subVmTestCreate8'', data: '', output: '
'
> warning: ERROR    internal error: qemu unexpectedly closed the monitor: 2019-02-27T16:12:16.994584Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate8
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: qemu unexpectedly closed the monitor: 2019-02-27T16:12:16.994584Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation."}", data: """"
> warning: ERROR    Error: --disk size=10000,format=qcow2: There is not enough free space on the storage pool to create the volume. (10240000 M requested allocation > 5323 M available)

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    Error: --disk size=10000,format=qcow2: There is not enough free space on the storage pool to create the volume. (10240000 M requested allocation > 5323 M available)"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate11
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate11\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate11
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate11\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate12
error: Requested operation is not valid: domain is not running

> warning: error: Failed to get memory statistics for domain subVmTestCreate12
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate12\nerror: Requested operation is not valid: domain is not running"}", data: """"
> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate12\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate13
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate13\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate13
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate13\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate14
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate14\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate14
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate14\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: ERROR    unsupported configuration: CPU mode 'custom' for x86_64 kvm domain on x86_64 host is not supported by hypervisor
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///session start subVmTestCreate15
otherwise, please restart your installation.

> warning: error: Failed to get memory statistics for domain subVmTestCreate16
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate16\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: Failed to get memory statistics for domain subVmTestCreate16
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate16\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: error: failed to get domain 'subVmTestCreate17'
error: Domain not found: no domain with matching name 'subVmTestCreate17'

> warning: spawn 'virsh' process returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get domain 'subVmTestCreate17'\nerror: Domain not found: no domain with matching name 'subVmTestCreate17'"}", data: """"
> warning: dumpxml() exception: 'error: failed to get domain 'subVmTestCreate17'
error: Domain not found: no domain with matching name 'subVmTestCreate17'', data: '', output: '
'
> warning: ERROR    internal error: process exited while connecting to monitor: 2019-02-27T16:13:08.049125Z qemu-system-x86_64: -vnc 127.0.0.1:0: Failed to start VNC server: Failed to bind socket: Address already in use
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate17
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2019-02-27T16:13:08.049125Z qemu-system-x86_64: -vnc 127.0.0.1:0: Failed to start VNC server: Failed to bind socket: Address already in use\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate17\notherwise, please restart your installation."}", data: """"
Wrote screenshot to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2401-FAIL.html
Wrote JS log to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachinesVirsh-testCreate-debian-stable-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/machineslib.py", line 1144, in testCreate
    start_vm=True))
  File "/build/cockpit/test/verify/machineslib.py", line 997, in createTest
    runner.tryCreate(dialog) \
  File "/build/cockpit/test/verify/machineslib.py", line 1480, in tryCreate
    dialog.open() \
  File "/build/cockpit/test/verify/machineslib.py", line 1363, in create
    TestMachines.CreateVmRunner.assertVmStates(self, self.name, None, init_state, second_state)
  File "/build/cockpit/test/verify/machineslib.py", line 1474, in assertVmStates
    b.wait(lambda: waitForWanted(wanted, after))
  File "/build/cockpit/test/common/testlib.py", line 311, in wait
    val = predicate()
  File "/build/cockpit/test/verify/machineslib.py", line 1474, in <lambda>
    b.wait(lambda: waitForWanted(wanted, after))
  File "/build/cockpit/test/verify/machineslib.py", line 1457, in waitForWanted
    b.wait_present(selector)
  File "/build/cockpit/test/common/testlib.py", line 332, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 326, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 323, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTestCreate17-state")): {'exceptionId': 11, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:223:24)', 'objectId': '{"injectedScriptId":5,"id":11}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1551283920546.58, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '1000044609.8'}
info: index.js: Setting Libvirt as virt provider.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: error: failed to get domain 'subVmTestCreate8'
error: Domain not found: no domain with matching name 'subVmTestCreate8'

warning: spawn 'virsh' process returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get domain 'subVmTestCreate8'\nerror: Domain not found: no domain with matching name 'subVmTestCreate8'"}", data: """"
warning: dumpxml() exception: 'error: failed to get domain 'subVmTestCreate8'
error: Domain not found: no domain with matching name 'subVmTestCreate8'', data: '', output: '
'
warning: ERROR    internal error: qemu unexpectedly closed the monitor: 2019-02-27T16:12:16.994584Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate8
otherwise, please restart your installation.

info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: qemu unexpectedly closed the monitor: 2019-02-27T16:12:16.994584Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation."}", data: """"
warning: ERROR    Error: --disk size=10000,format=qcow2: There is not enough free space on the storage pool to create the volume. (10240000 M requested allocation > 5323 M available)

info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    Error: --disk size=10000,format=qcow2: There is not enough free space on the storage pool to create the volume. (10240000 M requested allocation > 5323 M available)"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate11
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate11\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate11
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate11\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate12
error: Requested operation is not valid: domain is not running

warning: error: Failed to get memory statistics for domain subVmTestCreate12
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate12\nerror: Requested operation is not valid: domain is not running"}", data: """"
info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate12\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate13
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate13\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate13
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate13\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate14
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate14\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate14
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate14\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: ERROR    unsupported configuration: CPU mode 'custom' for x86_64 kvm domain on x86_64 host is not supported by hypervisor
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///session start subVmTestCreate15
otherwise, please restart your installation.

warning: error: Failed to get memory statistics for domain subVmTestCreate16
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate16\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: Failed to get memory statistics for domain subVmTestCreate16
error: Requested operation is not valid: domain is not running

info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTestCreate16\nerror: Requested operation is not valid: domain is not running"}", data: """"
warning: error: failed to get domain 'subVmTestCreate17'
error: Domain not found: no domain with matching name 'subVmTestCreate17'

warning: spawn 'virsh' process returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get domain 'subVmTestCreate17'\nerror: Domain not found: no domain with matching name 'subVmTestCreate17'"}", data: """"
warning: dumpxml() exception: 'error: failed to get domain 'subVmTestCreate17'
error: Domain not found: no domain with matching name 'subVmTestCreate17'', data: '', output: '
'
warning: ERROR    internal error: process exited while connecting to monitor: 2019-02-27T16:13:08.049125Z qemu-system-x86_64: -vnc 127.0.0.1:0: Failed to start VNC server: Failed to bind socket: Address already in use
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate17
otherwise, please restart your installation.

info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2019-02-27T16:13:08.049125Z qemu-system-x86_64: -vnc 127.0.0.1:0: Failed to start VNC server: Failed to bind socket: Address already in use\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate17\notherwise, please restart your installation."}", data: """"

not ok 28 testCreate (check_machines_virsh.TestMachinesVirsh) # duration: 143s
```
First occurrence: 2019-02-27T16:14:09.744157 | revision d7c13f32a72eda01189cc155d2e46d4510cfc53b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-11206-20190227-154343-d7c13f32-verify-debian-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2019-02-27T16:14:09.744157 | revision d7c13f32a72eda01189cc155d2e46d4510cfc53b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-11206-20190227-154343-d7c13f32-verify-debian-stable/log.html)

**Comment by nikrozman21** [comment]
Any updates on this?
It's still an issue.

**Comment by KKoukiou** [comment]
> Any updates on this?
> It's still an issue.

I had created an issue about that on debian bug tracking as you can see on the description; https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923398
The patch with the fix was never backported so I suggest you to move on to the current stable release which is debian-10 (buster)

**Comment by martinpitt** [comment]
We don't support/test on Debian 9 any more, so closing this obsolete known issue.
