### ISSUE TITLE
PackageKit went away during transaction

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11292]
PackageKit dumps core, very likely issue related to new version of subscription-manager.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1685037

**Comment by marusak** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestUpdates)
#
[0304/101857.791543:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9933/devtools/browser/3d8162f7-6e4c-48dc-b055-5af4e54446f2
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /14_aaddeccc : {"command":"close","channel":"1:2!1"}
> warning: PackageKit went away during transaction /14_aaddeccc : {"command":"close","channel":"1:2!1"}
> log: PackageKit went away from D-Bus
Wrote screenshot to TestUpdates-testBasic-rhel-8-0-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestUpdates-testBasic-rhel-8-0-127.0.0.2-2201-FAIL.html
Wrote JS log to TestUpdates-testBasic-rhel-8-0-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestUpdates-testBasic-rhel-8-0-127.0.0.2-2201-FAIL.log
Core dumps downloaded to /home/mmarusak/cockpit/cockpit/TestUpdates-testBasic-rhel-8-0-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "./test/verify/check-packagekit", line 210, in testBasic
    b.wait_present("#app .container-fluid h1")
  File "/home/mmarusak/cockpit/cockpit/test/common/testlib.py", line 332, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/mmarusak/cockpit/cockpit/test/common/testlib.py", line 326, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mmarusak/cockpit/cockpit/test/common/testlib.py", line 323, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mmarusak/cockpit/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#app .container-fluid h1")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:223:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1551691138272.83, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000032295.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: PackageKit went away from D-Bus
warning: PackageKit went away during transaction /14_aaddeccc : {"command":"close","channel":"1:2!1"}
warning: PackageKit went away during transaction /14_aaddeccc : {"command":"close","channel":"1:2!1"}
log: PackageKit went away from D-Bus

not ok 1 testBasic (__main__.TestUpdates) # duration: 87s
```
First occurrence: 2019-03-04T10:20:12.929466
Times recorded: 1
Latest occurrences:

- 2019-03-04T10:20:12.929466

**Comment by marusak** [comment]
This issue never landed and should not land in our tests. Closing
