### ISSUE TITLE
rhel-8-0: LVM-VDO-LVM sandwich layout broken

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11365]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1684249

**Comment by martinpitt** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorage)
#
[0311/140707.938978:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10180/devtools/browser/9799647e-f73b-49aa-be95-d2fe8c2b0d74
[0311/140708.965373:ERROR:vaapi_wrapper.cc(324)] vaInitialize failed: unknown libva error
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

> warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.
Wrote screenshot to TestStorage-testVdo-rhel-8-0-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testVdo-rhel-8-0-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testVdo-rhel-8-0-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testVdo-rhel-8-0-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-vdo", line 58, in testVdo
    self.dialog_wait_close()
  File "/home/martin/upstream/cockpit/test/verify/storagelib.py", line 283, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 335, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 326, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 323, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:223:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1552309628588.93, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000019274.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

not ok 1 testVdo (__main__.TestStorage) # duration: 94s
```
First occurrence: 2019-03-11T14:08:22.959392
Times recorded: 1
Latest occurrences:

- 2019-03-11T14:08:22.959392

**Comment by cockpituous** [comment]
verify/rhel-8-0-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (check_storage_vdo.TestStorage)
#
[0429/074901.145025:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9633/devtools/browser/b4c41280-21fe-41cc-857d-d1b5a1d63942
[0429/074901.148609:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 19232: Permission denied (13)
[0429/074901.160152:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0429/074901.161696:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0429/074901.291959:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 19265: Permission denied (13)
> warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

> warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.
Wrote screenshot to TestStorage-testVdo-rhel-8-0-distropkg-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorage-testVdo-rhel-8-0-distropkg-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorage-testVdo-rhel-8-0-distropkg-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testVdo-rhel-8-0-distropkg-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-vdo", line 57, in testVdo
    self.dialog_wait_close()
  File "/build/cockpit/test/verify/storagelib.py", line 276, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:223:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1556524141569.22, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '1000019265.8'}
warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

not ok 165 testVdo (check_storage_vdo.TestStorage) # duration: 98s
```
First occurrence: 2019-04-29T07:50:17.160889 | revision e553f6ee3c63e3c45d3070d981e75ee72b38eab3, [logs](https://209.132.184.41:8493/logs/pull-11695-20190429-073737-e553f6ee-verify-rhel-8-0-distropkg/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-29T07:50:17.160889 | revision e553f6ee3c63e3c45d3070d981e75ee72b38eab3, [logs](https://209.132.184.41:8493/logs/pull-11695-20190429-073737-e553f6ee-verify-rhel-8-0-distropkg/log.html)

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (check_storage_vdo.TestStorage)
#
[0501/024943.611379:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9973/devtools/browser/b644422e-7928-4e38-953c-e211cf1252cb
[0501/024943.614921:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 12930: Permission denied (13)
[0501/024943.627400:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0501/024943.628981:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0501/024943.800153:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 12970: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

> warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.
Wrote screenshot to TestStorage-testVdo-rhel-8-1-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestStorage-testVdo-rhel-8-1-127.0.0.2-2601-FAIL.html
Wrote JS log to TestStorage-testVdo-rhel-8-1-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestStorage-testVdo-rhel-8-1-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-vdo", line 57, in testVdo
    self.dialog_wait_close()
  File "/build/cockpit/test/verify/storagelib.py", line 276, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:223:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1556678984096.83, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '1000012970.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

warning: vdo: ERROR - Device /dev/vdo_vgroup/lvol excluded by a filter.

not ok 262 testVdo (check_storage_vdo.TestStorage) # duration: 95s
```
First occurrence: 2019-05-01T02:50:58.374128 | revision 23e9d6dfd74e8687b61fd8578da7d0db8daf06f8, [logs](https://209.132.184.41:8493/logs/pull-11720-20190501-022929-23e9d6df-verify-rhel-8-1/log.html)
Times recorded: 1
Latest occurrences:

- 2019-05-01T02:50:58.374128 | revision 23e9d6dfd74e8687b61fd8578da7d0db8daf06f8, [logs](https://209.132.184.41:8493/logs/pull-11720-20190501-022929-23e9d6df-verify-rhel-8-1/log.html)
