### ISSUE TITLE
debian-testing: can't get PXE boot logs from libvirt guest on a serial console

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#11381]
Downstream report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924423

**Comment by KKoukiou** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreate (__main__.TestMachinesDBus)
#
[0312/215515.046331:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9843/devtools/browser/c041caf7-dec6-4c3b-b75f-fb080e1e41ba
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
    *
    * validation errors and ui info/warn messages expected:
    * 
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_da0138d6_73fe_4e4a_ab4a_40c720e4beec 
> warning: ERROR    internal error: process exited while connecting to monitor: 2019-03-12T20:55:32.400209Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate8
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2019-03-12T20:55:32.400209Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation."}", data: """"
> warning: ERROR    The requested volume capacity will exceed the available pool space when the volume is fully allocated. (10240000 M requested capacity > 4742 M available) (Use --check disk_size=off or --check all=off to override)

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    The requested volume capacity will exceed the available pool space when the volume is fully allocated. (10240000 M requested capacity > 4742 M available) (Use --check disk_size=off or --check all=off to override)"}", data: """"
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_204a47c0_f654_483f_bf3f_5874087fddc3 
> warning: ERROR    internal error: qemu unexpectedly closed the monitor: Could not allocate dynamic translator buffer
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///session start subVmTestCreate15
otherwise, please restart your installation.

> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_337024ab_37d2_43b0_a29e_3d22e21474d8 
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
Wrote screenshot to TestMachinesDBus-testCreate-debian-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesDBus-testCreate-debian-testing-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesDBus-testCreate-debian-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesDBus-testCreate-debian-testing-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/home/kkoukiou/repos/cockpit/test/verify/machineslib.py", line 1248, in testCreate
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/home/kkoukiou/repos/cockpit/test/common/testlib.py", line 1433, in wait
    val = func()
  File "/home/kkoukiou/repos/cockpit/test/verify/machineslib.py", line 1248, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/home/kkoukiou/repos/cockpit/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.

not ok 1 testCreate (__main__.TestMachinesDBus) # duration: 271s
```
First occurrence: 2019-03-12T21:59:34.124215
Times recorded: 1
Latest occurrences:

- 2019-03-12T21:59:34.124215

**Comment by cockpituous** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreate (check_machines_dbus.TestMachinesDBus)
#
[0313/111521.912978:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9436/devtools/browser/59512edc-08aa-41cc-a2f6-aa6beb133b99
[0313/111521.917160:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 36059: Permission denied (13)
[0313/111521.935343:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0313/111521.937443:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0313/111522.040414:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 36089: Permission denied (13)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

    *
    * validation errors and ui info/warn messages expected:
    * 
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_7edbc43a_f013_4377_b11b_7dc011ce6f4c 
> warning: ERROR    internal error: process exited while connecting to monitor: 2019-03-13T11:15:43.376999Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate8
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2019-03-13T11:15:43.376999Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation."}", data: """"
> warning: ERROR    The requested volume capacity will exceed the available pool space when the volume is fully allocated. (10240000 M requested capacity > 4199 M available) (Use --check disk_size=off or --check all=off to override)

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    The requested volume capacity will exceed the available pool space when the volume is fully allocated. (10240000 M requested capacity > 4199 M available) (Use --check disk_size=off or --check all=off to override)"}", data: """"
> warning: ERROR    unsupported configuration: CPU mode 'custom' for x86_64 kvm domain on x86_64 host is not supported by hypervisor
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///session start subVmTestCreate15
otherwise, please restart your installation.

> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_14328010_f0d6_47bc_8776_1114ec39d318 
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
Wrote screenshot to TestMachinesDBus-testCreate-ubuntu-stable-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMachinesDBus-testCreate-ubuntu-stable-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMachinesDBus-testCreate-ubuntu-stable-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachinesDBus-testCreate-ubuntu-stable-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/machineslib.py", line 1248, in testCreate
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/build/cockpit/test/common/testlib.py", line 1433, in wait
    val = func()
  File "/build/cockpit/test/verify/machineslib.py", line 1248, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/build/cockpit/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.

not ok 249 testCreate (check_machines_dbus.TestMachinesDBus) # duration: 293s
```
First occurrence: 2019-03-13T11:19:51.977219 | revision 5dce00a0a1a65ad2215a26f89934667fbf3a9025, [logs](https://209.132.184.41:8493/logs/pull-11179-20190313-110404-5dce00a0-verify-ubuntu-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2019-03-13T11:19:51.977219 | revision 5dce00a0a1a65ad2215a26f89934667fbf3a9025, [logs](https://209.132.184.41:8493/logs/pull-11179-20190313-110404-5dce00a0-verify-ubuntu-stable/log.html)

**Comment by cockpituous** [comment]
verify/debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreate (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9701/devtools/browser/9365355c-3fbc-4b61-9353-5e916a174017
[0707/214310.008442:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0707/214310.010264:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

    *
    * validation errors and ui info/warn messages expected:
    * 
> warning: 
(process:1097): GLib-GIO-WARNING **: 17:43:18.398: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:1097): GLib-GIO-WARNING **: 17:43:18.398: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: 
(process:1119): GLib-GIO-WARNING **: 17:43:19.907: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)

> log: osinfo-detect command failed:  (process:1119): GLib-GIO-WARNING **: 17:43:19.907: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)
> warning: 
(process:1189): GLib-GIO-WARNING **: 17:43:26.194: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)

> log: osinfo-detect command failed:  (process:1189): GLib-GIO-WARNING **: 17:43:26.194: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)
> warning: 
(process:1225): GLib-GIO-WARNING **: 17:43:28.004: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)

> log: osinfo-detect command failed:  (process:1225): GLib-GIO-WARNING **: 17:43:28.004: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)
> warning: 
(process:1252): GLib-GIO-WARNING **: 17:43:29.400: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)

> log: osinfo-detect command failed:  (process:1252): GLib-GIO-WARNING **: 17:43:29.400: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)
> warning: 
(process:1313): GLib-GIO-WARNING **: 17:43:32.526: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)

> log: osinfo-detect command failed:  (process:1313): GLib-GIO-WARNING **: 17:43:32.526: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)
> warning: 
(process:1374): GLib-GIO-WARNING **: 17:43:35.843: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)

> log: osinfo-detect command failed:  (process:1374): GLib-GIO-WARNING **: 17:43:35.843: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to load .treeinfo file: Operation not supported (15)
> warning: 
(process:3108): GLib-GIO-WARNING **: 17:43:40.473: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:3108): GLib-GIO-WARNING **: 17:43:40.473: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
{"exceptionId":8,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate15-state not found"},"executionContextId":7}
> warning: 
(process:6951): GLib-GIO-WARNING **: 17:43:47.286: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:6951): GLib-GIO-WARNING **: 17:43:47.286: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
{"exceptionId":10,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate16-state not found"},"executionContextId":7}
> warning: 
(process:7246): GLib-GIO-WARNING **: 17:43:54.454: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:7246): GLib-GIO-WARNING **: 17:43:54.454: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
{"exceptionId":12,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate17-state not found"},"executionContextId":7}
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_117643c8_4715_41da_8bbe_6352816360e7 
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
> warning: 
(process:7828): GLib-GIO-WARNING **: 17:44:13.040: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:7828): GLib-GIO-WARNING **: 17:44:13.040: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_f5736fcf_b761_4ae9_b3e3_6e55d52ee6ec 
> warning: 
(process:7969): GLib-GIO-WARNING **: 17:44:18.284: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:7969): GLib-GIO-WARNING **: 17:44:18.284: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_cb2f89b6_9f85_4428_9530_87eb3d56d18f 
ls: cannot access '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_DISK1': No such file or directory
Information: You may need to update /etc/fstab.

> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: 
(process:8214): GLib-GIO-WARNING **: 17:44:28.504: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:8214): GLib-GIO-WARNING **: 17:44:28.504: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
{"exceptionId":14,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate22-state not found"},"executionContextId":13}
CDP: {"source":"javascript","level":"warning","text":"WebSocket connection to 'ws://127.0.0.2:9191/cockpit/channel/325d72fe3fd8a6d340a3bd6e44fcabe27da7f0c54a315210660b14ab9b5528ab?eyJwYXlsb2FkIjoic3RyZWFtIiwicHJvdG9jb2wiOiJiaW5hcnkiLCJiaW5hcnkiOiJyYXciLCJhZGRyZXNzIjoiMTI3LjAuMC4xIiwicG9ydCI6NTkwMX0=' failed: WebSocket is closed before the connection is established.","timestamp":1562535877698.15,"url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":55,"stackTrace":{"callFrames":[{"functionName":"close","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":55,"columnNumber":594165},{"functionName":"_disconnect","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":55,"columnNumber":630864},{"functionName":"_updateConnectionState","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":55,"columnNumber":633317},{"functionName":"disconnect","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":55,"columnNumber":628706},{"functionName":"value","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":55,"columnNumber":657311},{"functionName":"value","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":55,"columnNumber":657241},{"functionName":"po","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":75770},{"functionName":"_o","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":77331},{"functionName":"Xo","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":81584},{"functionName":"Ho","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":84901},{"functionName":"","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":98277},{"functionName":"t.unstable_runWithPriority","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":47,"columnNumber":3193},{"functionName":"Ns","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":98212},{"functionName":"Os","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":97988},{"functionName":"ks","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":97333},{"functionName":"Rs","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":98708},{"functionName":"kn","scriptId":"749","url":"http://127.0.0.2:9191/cockpit/$0ecaa3a55762de3a6978187b0c4cdda8adfc95626c527dd6fd60b43278e0b829/machines/machines.js","lineNumber":38,"columnNumber":30566},{"functionName":"ph_mouse","scriptId":"739","url":"","lineNumber":146,"columnNumber":7},{"functionName":"","scriptId":"887","url":"","lineNumber":0,"columnNumber":0}]}}
> warning: WebSocket on-error event
Generating a RSA private key
....................................................++++
..........................................++++
writing new private key to 'key.pem'
-----
> error: Disconnection timed out.
> warning: 
(process:9391): GLib-GIO-WARNING **: 17:44:41.726: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to open fileOperation not supported (15)

> log: osinfo-detect command failed:  (process:9391): GLib-GIO-WARNING **: 17:44:41.726: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to open fileOperation not supported (15)
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_a99f5e8e_a69b_4930_8c8e_3167c59fa4ee 
> warning: 
(process:9532): GLib-GIO-WARNING **: 17:44:47.294: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to open fileOperation not supported (15)

> log: osinfo-detect command failed:  (process:9532): GLib-GIO-WARNING **: 17:44:47.294: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
gi.repository.GLib.Error: g-io-error-quark: Failed to open fileOperation not supported (15)
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_f6f67484_4050_465e_8d39_449b8a4a8798 
> warning: ERROR    internal error: process exited while connecting to monitor: 2019-07-07T21:44:49.343257Z qemu-system-x86_64: -drive file=https://localhost:8000/novell.iso,format=raw,if=none,id=drive-ide0-0-0,readonly=on: Unknown protocol 'https'
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate24
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2019-07-07T21:44:49.343257Z qemu-system-x86_64: -drive file=https://localhost:8000/novell.iso,format=raw,if=none,id=drive-ide0-0-0,readonly=on: Unknown protocol 'https'\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate24\notherwise, please restart your installation."}", data: """"
> warning: GET_NETWORK action failed failed for path /org/libvirt/QEMU/network/_bbc443f7_abc2_4aba_a5b9_49633cfa7bf5 
52:54:01:00:00:02 -> eth2
52:54:01:00:00:02 -> eth2
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestMachinesDBus-testCreate-debian-stable-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesDBus-testCreate-debian-stable-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesDBus-testCreate-debian-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDBus-testCreate-debian-stable-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/machineslib.py", line 1629, in testCreate
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/build/cockpit/test/common/testlib.py", line 1447, in wait
    val = func()
  File "/build/cockpit/test/verify/machineslib.py", line 1629, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/build/cockpit/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.

not ok 49 testCreate (check_machines_dbus.TestMachinesDBus) # duration: 315s
```
First occurrence: 2019-07-07T21:48:12.190804 | revision f4166036d52bbea9f04ac81fa8de8c329d4d6302, [logs](https://209.132.184.41:8493/logs/pull-12248-20190707-213838-f4166036-verify-debian-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2019-07-07T21:48:12.190804 | revision f4166036d52bbea9f04ac81fa8de8c329d4d6302, [logs](https://209.132.184.41:8493/logs/pull-12248-20190707-213838-f4166036-verify-debian-stable/log.html)
