### ISSUE TITLE
Listing timezones fails on Fedora 30

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11441]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1691492

Opening dialog for changing time on Fedora 30 triggers `timedatectl list-timezones` which fails with

    Failed to request list of time zones: No such method “ListTimezones”

**Comment by marusak** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTime (__main__.TestSystemInfo)
#
[0322/083118.898196:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9324/devtools/browser/bbfdce6b-5cab-4dfe-bcd1-0644c593d3af
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

Unexpected journal messages:
Failed to request list of time zones: No such method “ListTimezones”
Failed to request list of time zones: No such method “ListTimezones”
Failed to request list of time zones: No such method “ListTimezones”
Wrote JS log to TestSystemInfo-testTime-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-30-127.0.0.2-2201-FAIL.log
Wrote screenshot to TestSystemInfo-testTime-fedora-30-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSystemInfo-testTime-fedora-30-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSystemInfo-testTime-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-30-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/home/mmarusak/cockpit/cockpit/test/common/testlib.py", line 757, in tearDown
    self.check_journal_messages()
  File "/home/mmarusak/cockpit/cockpit/test/common/testlib.py", line 960, in check_journal_messages
    raise Error(first)
testlib.Error: Failed to request list of time zones: No such method “ListTimezones”

not ok 1 testTime (__main__.TestSystemInfo) # duration: 40s
```
First occurrence: 2019-03-22T08:31:47.034560
Times recorded: 1
Latest occurrences:

- 2019-03-22T08:31:47.034560

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTime (check_system_info.TestSystemInfo)
#

DevTools listening on ws://127.0.0.1:9711/devtools/browser/179a40d9-da6b-4dce-9ea8-40aca62d7947
[0510/152905.127627:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 78666: Permission denied (13)
[0510/152905.144254:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0510/152905.146238:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[0510/152905.329335:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 78722: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

Unexpected journal messages:
Failed to request list of time zones: No such method “ListTimezones”
Failed to request list of time zones: No such method “ListTimezones”
Failed to request list of time zones: No such method “ListTimezones”
Wrote JS log to TestSystemInfo-testTime-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-testing-127.0.0.2-2501-FAIL.log
Wrote screenshot to TestSystemInfo-testTime-fedora-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestSystemInfo-testTime-fedora-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestSystemInfo-testTime-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-testing-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 956, in check_journal_messages
    raise Error(first)
testlib.Error: Failed to request list of time zones: No such method “ListTimezones”

not ok 198 testTime (check_system_info.TestSystemInfo) # duration: 47s
```
First occurrence: 2019-05-10T15:29:33.679525 | revision a5d61f5afc8f77fae5ef136000fea278e29e7338, [logs](https://209.132.184.41:8493/logs/pull-11793-20190510-151818-a5d61f5a-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2019-05-10T15:29:33.679525 | revision a5d61f5afc8f77fae5ef136000fea278e29e7338, [logs](https://209.132.184.41:8493/logs/pull-11793-20190510-151818-a5d61f5a-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTime (check_system_info.TestSystemInfo)
#

DevTools listening on ws://127.0.0.1:9858/devtools/browser/f806ac89-d5e7-490f-b93a-523603b8e92d
[0529/090827.249396:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 100913: Permission denied (13)
[0529/090827.265846:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0529/090827.267355:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[0529/090827.439177:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 100960: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> warning: pcp-archive: couldn't create pcp archive context for /var/log/pcp/pmlogger/localhost.localdomain/20200124.08.03: Empty archive log file
> warning: metrics channel failed: internal-error
> warning: pcp-archive: couldn't create pcp archive context for /var/log/pcp/pmlogger/localhost.localdomain/20200124.08.03: Empty archive log file
> warning: metrics channel failed: internal-error
> warning: pcp-archive: couldn't create pcp archive context for /var/log/pcp/pmlogger/localhost.localdomain/20200124.08.03: Empty archive log file
> warning: metrics channel failed: internal-error
> warning: pcp-archive: couldn't create pcp archive context for /var/log/pcp/pmlogger/localhost.localdomain/20200124.08.03: Empty archive log file
> warning: metrics channel failed: internal-error
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/product_uuid: Permission denied

Unexpected journal messages:
Failed to request list of time zones: No such method “ListTimezones”
Failed to request list of time zones: No such method “ListTimezones”
Failed to request list of time zones: No such method “ListTimezones”
Wrote JS log to TestSystemInfo-testTime-fedora-i386-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-i386-127.0.0.2-2501-FAIL.log
Wrote screenshot to TestSystemInfo-testTime-fedora-i386-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestSystemInfo-testTime-fedora-i386-127.0.0.2-2501-FAIL.html
Wrote JS log to TestSystemInfo-testTime-fedora-i386-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-i386-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 955, in check_journal_messages
    raise Error(first)
testlib.Error: Failed to request list of time zones: No such method “ListTimezones”

not ok 248 testTime (check_system_info.TestSystemInfo) # duration: 52s
```
First occurrence: 2019-05-29T09:09:00.212574 | revision 6976a666733b74af2c9721b6a7bdf468ab15d14a, [logs](https://209.132.184.41:8493/logs/pull-11952-20190529-080606-6976a666-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2019-05-29T09:09:00.212574 | revision 6976a666733b74af2c9721b6a7bdf468ab15d14a, [logs](https://209.132.184.41:8493/logs/pull-11952-20190529-080606-6976a666-verify-fedora-i386/log.html)
