### ISSUE TITLE
joining IPA domain causes SELinux violation: avc: denied { getattr } for comm="ipa-submit"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11477]
Seen on latest RHEL 7.7 nightlies.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1693280

**Comment by cockpituous** [comment]
verify/rhel-7-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
[0327/163617.831320:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10207/devtools/browser/ec994a4d-aa72-4303-9f1c-6337cfc53c13
[0327/163617.834793:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 97291: Permission denied (13)
[0327/163617.845635:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0327/163617.847138:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0327/163617.988210:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 97320: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache keyring 'persistent:0:0' not found
klist: Credentials cache keyring 'persistent:1001:1001' not found
++ seq 1 60
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 1
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 2
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 3
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 4
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 5
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 6
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 7
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 8
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 9
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 10
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 11
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ systemctl --quiet is-failed sssd.service
+ sleep 12
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in '$(seq 1 60)'
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: Warning: cockpit.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Failed to cat /etc/systemd/system/cockpit.service.d/notls.conf: No such file or directory
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Removing principal HTTP/x0.cockpit.lan@COCKPIT.LAN

> log: Failed to join domain: cockpit.lan: Already running another action
Unexpected journal messages:
type=1400 audit(1553704640.962:4): avc:  denied  { getattr } for  pid=8260 comm="ipa-submit" name="/" dev="dm-0" ino=64 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0
type=1400 audit(1553704640.970:5): avc:  denied  { getattr } for  pid=8260 comm="ipa-submit" name="/" dev="dm-0" ino=64 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0
Wrote JS log to TestRealms-testIpa-rhel-7-7-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpa-rhel-7-7-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2902-FAIL.log
Wrote screenshot to TestRealms-testIpa-rhel-7-7-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestRealms-testIpa-rhel-7-7-127.0.0.2-2901-FAIL.html
Wrote JS log to TestRealms-testIpa-rhel-7-7-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpa-rhel-7-7-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2902-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 757, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 960, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1553704640.962:4): avc:  denied  { getattr } for  pid=8260 comm="ipa-submit" name="/" dev="dm-0" ino=64 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0

not ok 189 testIpa (check_realms.TestRealms) # duration: 244s
```
First occurrence: 2019-03-27T16:39:52.902756 | revision d3ebde8b7b6902f467233bd02d252706c3eed2a9, [logs](https://209.132.184.41:8493/logs/pull-11467-20190327-160909-d3ebde8b-verify-rhel-7-7/log.html)
Times recorded: 1
Latest occurrences:

- 2019-03-27T16:39:52.902756 | revision d3ebde8b7b6902f467233bd02d252706c3eed2a9, [logs](https://209.132.184.41:8493/logs/pull-11467-20190327-160909-d3ebde8b-verify-rhel-7-7/log.html)
