### ISSUE TITLE
kvdo broken on current rhel-8-1: kernel version mismatch

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11566]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1698299

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (check_storage_vdo.TestStorage)
#
[0410/045619.052854:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9587/devtools/browser/a40f7d37-419c-4cb0-993c-047ae901a885
[0410/045619.057289:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 109019: Permission denied (13)
[0410/045619.070296:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0410/045619.071856:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0410/045619.220642:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 109088: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-80.10.el8.x86_64

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-80.10.el8.x86_64
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestStorage-testVdo-rhel-8-1-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestStorage-testVdo-rhel-8-1-127.0.0.2-2801-FAIL.html
Wrote JS log to TestStorage-testVdo-rhel-8-1-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestStorage-testVdo-rhel-8-1-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-vdo", line 57, in testVdo
    self.dialog_wait_close()
  File "/build/cockpit/test/verify/storagelib.py", line 276, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/common/testlib.py", line 343, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 334, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 331, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:223:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1554872179498.33, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '1000109088.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-80.10.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-80.10.el8.x86_64
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]

not ok 254 testVdo (check_storage_vdo.TestStorage) # duration: 92s
```
First occurrence: 2019-04-10T04:57:52.766950 | revision 21d374efa8b62a2dc0137ea95703eec190ad62a0, [logs](https://209.132.184.41:8493/logs/pull-11552-20190410-043535-21d374ef-verify-rhel-8-1/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-10T04:57:52.766950 | revision 21d374efa8b62a2dc0137ea95703eec190ad62a0, [logs](https://209.132.184.41:8493/logs/pull-11552-20190410-043535-21d374ef-verify-rhel-8-1/log.html)
