### ISSUE TITLE
machines: Implement iscsi-direct pool

### ISSUE THREAD

**Issue by qiankehan** [cockpit-project/cockpit#11562]
Libvirt add **iscsi-direct** pool type in 4.7. It is a storage pool based on **libiscsi**. Request to support it in cockpit.
libvirt reference: https://libvirt.org//storage.html#StorageBackendISCSIDirect

**Comment by KKoukiou** [comment]
Hey @qiankehan thanks for the interest! We do support iscsi but not yet iscsi-direct. Howerver the patch for the support should be very straightforward. Is there a chance that you would like to implement it?

JFTR here is the commit that introduced iSCSI support for storage pools, support for iSCSI-direct should be similar, https://github.com/cockpit-project/cockpit/commit/9346b8b6b3969c0c146a81ba084bc31961444871

**Comment by qiankehan** [comment]
@KKoukiou  Thank you. I'd like to try to finish this feature with the reference of 9346b8b

**Comment by KKoukiou** [comment]
@qiankehan super! Let me know if you need any guidance :)

**Comment by qiankehan** [comment]
@KKoukiou I finished it and installed it in local machine. However on http://localhost:9090/machines, the left tab is **oVirt Machines** not **Virtual Machines**. And the machines will be managed ovirt not libvirt, thus I couldn't check my newly add feature. 
Is cockpit-machine  integrate ovirt by default now?

**Comment by KKoukiou** [comment]
> @KKoukiou I finished it and installed it in local machine. However on http://localhost:9090/machines, the left tab is **oVirt Machines** not **Virtual Machines**. And the machines will be managed ovirt not libvirt, thus I couldn't check my newly add feature.
> Is cockpit-machine integrate ovirt by default now?

@qiankehan not, just these two packages (cockpit-ovirt-machines vs cockpit-machines) can not be used in parallel and the first one is prioritized. So if you are building from sources the only way to bypass this is to set the Cockpit Machines page priority higher than the oVirt one.

Do it in the bundled code to keep it persistent between rebuilds:
Change in dist/machines/manifest.json the priority to 20 for example.

**Comment by qiankehan** [comment]
I tested it but  one error happended when selected the iscsi direct pool type:
```
react-dom.production.min.js:198 Invariant Violation: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Nm for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:423
    at a (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:526)
    at http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:52042
    at Eo (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:58905)
    at Ao (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:59900)
    at Ro (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:66547)
    at za (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:90673)
    at Wa (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:91057)
    at Ns (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:97944)
    at As (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:97324)
ha @ react-dom.production.min.js:198
react-dom.production.min.js:248 Uncaught Invariant Violation: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Nm for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:423
    at a (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:526)
    at http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:52042
    at Eo (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:58905)
    at Ao (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:59900)
    at Ro (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:66547)
    at za (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:90673)
    at Wa (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:91057)
    at Ns (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:97944)
    at As (http://localhost:9090/cockpit/$4a59a708c73b061dc1d3492c1b617a74409a133232bc062288c96ec174d2c588/machines/machines.js:42:97324)
```
Could you please give some advice for debugging? @KKoukiou

**Comment by martinpitt** [comment]
@qiankehan: Please clean your build tree (`git clean -fdx`, `make clean` is *not* enough) and rebuild with debugging enabled:

    ./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-strict --enable-debug

then you will get proper React errors.
