### ISSUE TITLE
podman PullImage varlink API broken on fedora-29 when the tag specified does not exist

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#11579]
Issue in libpod project:  https://github.com/containers/libpod/issues/2860

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDownloadImage (__main__.TestApplication)
#
Warning: Stopping io.podman.service, but it can still be activated by:
  io.podman.socket
Getting image source signatures
Copying blob sha256:0b97b1c81a3200e9eeb87f17a5d25a50791a16fa08fc41eb94ad15f26516ccea
Copying config sha256:af2f74c517aac1d26793a6ed05ff45b299a037e1a9eefeae5eacda133e70a825
Writing manifest to image destination
Storing signatures
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
[0412/090725.274282:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9470/devtools/browser/ef942a28-23f2-497a-8758-35768974826d
[0412/090725.278739:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 90883: Permission denied (13)
[0412/090725.291911:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0412/090725.293601:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0412/090725.441985:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 90919: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
Process 6990 (podman) of user 0 dumped core.
Stack trace of thread 7082:
#0  0x000056448d3016b4 n/a (podman)
#1  0x000056448d2e7d58 n/a (podman)
#2  0x000056448d2e6fe8 n/a (podman)
#3  0x000056448d3019a3 n/a (podman)
#4  0x00007fed5f744070 __restore_rt (libpthread.so.0)
#5  0x000056448d3016b4 n/a (podman)
#6  0x000056448d2e796a n/a (podman)
#7  0x000056448d2d1ad9 n/a (podman)
#8  0x000056448d2d148f n/a (podman)
#9  0x000056448d2d0490 n/a (podman)
#10 0x000056448d2e75e6 n/a (podman)
#11 0x000056448e17bf17 n/a (podman)
#12 0x000056448d2ffd81 n/a (podman)
Wrote JS log to TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.log
Core dumps downloaded to /build/cockpit/TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.core
Wrote screenshot to TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.html
Wrote JS log to TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.log
Core dumps downloaded to /build/cockpit/TestApplication-testDownloadImage-fedora-29-127.0.0.2-2501-FAIL.core
Traceback (most recent call last):
  File "test/common/testlib.py", line 778, in tearDown
    self.check_journal_messages()
  File "test/common/testlib.py", line 960, in check_journal_messages
    raise Error(first)
testlib.Error: Process 6990 (podman) of user 0 dumped core.

not ok 2 testDownloadImage (__main__.TestApplication) # duration: 43s
```
First occurrence: 2019-04-12T09:07:43.341705 | revision 4c82e3f26cdfd7787126344d6ed583b9dcab0f2a, [logs](https://209.132.184.41:8493/logs/pull-11580-20190412-082323-4c82e3f2-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-12T09:07:43.341705 | revision 4c82e3f26cdfd7787126344d6ed583b9dcab0f2a, [logs](https://209.132.184.41:8493/logs/pull-11580-20190412-082323-4c82e3f2-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDownloadImage (__main__.TestApplication)
#
Warning: Stopping io.podman.service, but it can still be activated by:
  io.podman.socket
Getting image source signatures
Copying blob sha256:0b97b1c81a3200e9eeb87f17a5d25a50791a16fa08fc41eb94ad15f26516ccea
Copying config sha256:af2f74c517aac1d26793a6ed05ff45b299a037e1a9eefeae5eacda133e70a825
Writing manifest to image destination
Storing signatures
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
[0419/221241.896004:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10175/devtools/browser/30b0eb43-6159-4d4c-8b81-441253f51343
[0419/221241.899523:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 54644: Permission denied (13)
[0419/221241.911711:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0419/221241.915439:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0419/221242.059194:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 54672: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
Process 6761 (podman) of user 0 dumped core.
Stack trace of thread 6872:
#0  0x0000561f74c207f1 n/a (podman)
#1  0x0000561f74c074c8 n/a (podman)
#2  0x0000561f74c065e0 n/a (podman)
#3  0x0000561f74c20ae3 n/a (podman)
#4  0x00007f91a6b17e70 __restore_rt (libpthread.so.0)
#5  0x0000561f74c207f1 n/a (podman)
#6  0x0000561f74c070da n/a (podman)
#7  0x0000561f74bf1a36 n/a (podman)
#8  0x0000561f74bf13f9 n/a (podman)
#9  0x0000561f74c06e55 n/a (podman)
#10 0x0000561f75b0e334 n/a (podman)
#11 0x0000561f74c1eeb1 n/a (podman)
Wrote JS log to TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.log
Core dumps downloaded to /build/cockpit/TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.core
Wrote screenshot to TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.html
Wrote JS log to TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.log
Core dumps downloaded to /build/cockpit/TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.core
Traceback (most recent call last):
  File "test/common/testlib.py", line 776, in tearDown
    self.check_journal_messages()
  File "test/common/testlib.py", line 958, in check_journal_messages
    raise Error(first)
testlib.Error: Process 6761 (podman) of user 0 dumped core.

not ok 2 testDownloadImage (__main__.TestApplication) # duration: 50s
```
First occurrence: 2019-04-19T22:13:04.884740 | revision 08739acdbce8d874e564f0e694efc1e90122299c, [logs](https://209.132.184.41:8493/logs/pull-11642-20190419-215252-08739acd-verify-fedora-30/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-19T22:13:04.884740 | revision 08739acdbce8d874e564f0e694efc1e90122299c, [logs](https://209.132.184.41:8493/logs/pull-11642-20190419-215252-08739acd-verify-fedora-30/log.html)
