### ISSUE TITLE
SELinux denies iscsid { read } for modules.dep.bin and modules.softdep

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#11614]
This breaks cockpit-machines tests for iscsi-pools
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1700245

**Comment by KKoukiou** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (__main__.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9836/devtools/browser/814260fd-ba92-438c-b6b6-ceda2b4f64c7
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-machines-dbus", line 809, in testStoragePoolsCreate
    source={"host": "127.0.0.1", "source_path": target_iqn}
  File "test/verify/check-machines-dbus", line 660, in execute
    self.create()
  File "test/verify/check-machines-dbus", line 696, in create
    b.wait_not_present("#create-storage-pool-dialog")
  File "/home/kkoukiou/repos/cockpit/test/common/testlib.py", line 343, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/kkoukiou/repos/cockpit/test/common/testlib.py", line 334, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/kkoukiou/repos/cockpit/test/common/testlib.py", line 331, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/kkoukiou/repos/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#create-storage-pool-dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:223:24', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1555400956654.84, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000011142.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
info: index.js: Setting LibvirtDBus as virt provider.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 1 testStoragePoolsCreate (__main__.TestMachinesDBus) # duration: 92s
```
First occurrence: 2019-04-16T09:50:34.453608
Times recorded: 1
Latest occurrences:

- 2019-04-16T09:50:34.453608

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#
[0424/081705.666621:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9988/devtools/browser/3bf6bdce-81cf-4c14-9149-b5979abc13f8
[0424/081705.670469:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 84784: Permission denied (13)
[0424/081705.682910:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0424/081705.686301:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0424/081705.857781:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 84816: Permission denied (13)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 809, in testStoragePoolsCreate
    source={"host": "127.0.0.1", "source_path": target_iqn}
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 660, in execute
    self.create()
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 696, in create
    b.wait_not_present("#create-storage-pool-dialog")
  File "/build/cockpit/test/common/testlib.py", line 343, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 334, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 331, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#create-storage-pool-dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:223:24)', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1556093826202.31, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '1000084816.8'}
info: index.js: Setting LibvirtDBus as virt provider.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]

not ok 86 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 118s
```
First occurrence: 2019-04-24T08:18:24.546208 | revision f721d3314d149c9fdd35d591c5951f33476e1125, [logs](https://209.132.184.41:8493/logs/pull-11655-20190424-073434-f721d331-verify-rhel-8-1/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-24T08:18:24.546208 | revision f721d3314d149c9fdd35d591c5951f33476e1125, [logs](https://209.132.184.41:8493/logs/pull-11655-20190424-073434-f721d331-verify-rhel-8-1/log.html)

**Comment by cockpituous** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#
[0429/131531.437993:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9924/devtools/browser/a4cb2a34-1e44-434e-a149-f24370720e97
[0429/131531.445184:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 106838: Permission denied (13)
[0429/131531.463499:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0429/131531.471005:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0429/131531.651151:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 106872: Permission denied (13)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

{"exceptionId":1,"text":"Uncaught","lineNumber":58,"columnNumber":707979,"url":"http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/machines/machines.js","stackTrace":{"callFrames":[{"functionName":"lm.then.then.e","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/machines/machines.js","lineNumber":58,"columnNumber":707979},{"functionName":"s","scriptId":"32","url":"http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js","lineNumber":962,"columnNumber":32},{"functionName":"","scriptId":"32","url":"http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js","lineNumber":974,"columnNumber":16},{"functionName":"n","scriptId":"32","url":"http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js","lineNumber":880,"columnNumber":16}]},"exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read property 'v' of undefined\n    at Function.lm.then.then.e (http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/machines/machines.js:59:707980)\n    at s (http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js:963:33)\n    at http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js:975:17\n    at n (http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js:881:17)","objectId":"{\"injectedScriptId\":5,\"id\":1}","preview":{"type":"object","subtype":"error","description":"TypeError: Cannot read property 'v' of undefined\n    at Function.lm.then.then.e (http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/machines/machines.js:59:707980)\n    at s (http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js:963:33)\n    at http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js:975:17\n    at n (http://127.0.0.2:9391/cockpit/$4ee1ad242824a0e6c97beadd9e3a300d00225623f79ef93bd53e9a06fc096546/base1/cockpit.js:881:17)","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Cannot read property 'v' of undefined\n …f79ef93bd53e9a06fc096546/base1/cockpit.js:881:17)"},{"name":"message","type":"string","value":"Cannot read property 'v' of undefined"}]}},"executionContextId":5}
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 830, in testStoragePoolsCreate
    source={"host": "127.0.0.1", "source_path": target_iqn}
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 659, in execute
    self.open()
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 669, in open
    b.click("#create-storage-pool")
  File "/build/cockpit/test/common/testlib.py", line 211, in click
    self.mouse(selector, "click", 0, 0, 0, force)
  File "/build/cockpit/test/common/testlib.py", line 207, in mouse
    self.wait_present(selector)
  File "/build/cockpit/test/common/testlib.py", line 341, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 329, in wait_js_cond
    silent=False, awaitPromise=True, trace="wait: " + cond)
  File "/build/cockpit/test/common/cdp.py", line 87, in invoke
    res = self.command(cmd)
  File "/build/cockpit/test/common/cdp.py", line 114, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: Cannot read property 'v' of undefined

not ok 240 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 65s
```
First occurrence: 2019-04-29T13:15:50.420601 | revision d391715a73783d4fdf8cfc83ce98f06fccb79257, [logs](https://209.132.184.41:8493/logs/pull-11068-20190429-123030-d391715a-verify-rhel-8-0/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-29T13:15:50.420601 | revision d391715a73783d4fdf8cfc83ce98f06fccb79257, [logs](https://209.132.184.41:8493/logs/pull-11068-20190429-123030-d391715a-verify-rhel-8-0/log.html)

**Comment by cockpituous** [comment]
verify/rhel-8-0-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#
[0501/203501.402678:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10006/devtools/browser/31566f16-8a2f-4f38-b49a-1b69727c9d8f
[0501/203501.405980:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 38081: Permission denied (13)
[0501/203501.416942:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0501/203501.419605:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0501/203501.562960:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 38110: Permission denied (13)
> info: index.js: Setting LibvirtDBus as virt provider.
{"exceptionId":1,"text":"Uncaught","lineNumber":58,"columnNumber":707973,"url":"http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/machines/machines.js","stackTrace":{"callFrames":[{"functionName":"lm.then.then.e","scriptId":"39","url":"http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/machines/machines.js","lineNumber":58,"columnNumber":707973},{"functionName":"s","scriptId":"32","url":"http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js","lineNumber":957,"columnNumber":32},{"functionName":"","scriptId":"32","url":"http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js","lineNumber":969,"columnNumber":16},{"functionName":"n","scriptId":"32","url":"http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js","lineNumber":875,"columnNumber":16}]},"exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read property 'v' of undefined\n    at Function.lm.then.then.e (http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/machines/machines.js:59:707974)\n    at s (http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js:958:33)\n    at http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js:970:17\n    at n (http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js:876:17)","objectId":"{\"injectedScriptId\":5,\"id\":1}","preview":{"type":"object","subtype":"error","description":"TypeError: Cannot read property 'v' of undefined\n    at Function.lm.then.then.e (http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/machines/machines.js:59:707974)\n    at s (http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js:958:33)\n    at http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js:970:17\n    at n (http://127.0.0.2:9691/cockpit/$142bca857e1cdf43a796dc38acc60d7a3e40308bf7ca91a24f4a81e000c67257/base1/cockpit.js:876:17)","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Cannot read property 'v' of undefined\n …f7ca91a24f4a81e000c67257/base1/cockpit.js:876:17)"},{"name":"message","type":"string","value":"Cannot read property 'v' of undefined"}]}},"executionContextId":5}
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-distropkg-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-distropkg-127.0.0.2-2801-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-distropkg-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-8-0-distropkg-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 830, in testStoragePoolsCreate
    source={"host": "127.0.0.1", "source_path": target_iqn}
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 659, in execute
    self.open()
  File "/build/cockpit/bots/../test/verify/check-machines-dbus", line 669, in open
    b.click("#create-storage-pool")
  File "/build/cockpit/test/common/testlib.py", line 211, in click
    self.mouse(selector, "click", 0, 0, 0, force)
  File "/build/cockpit/test/common/testlib.py", line 207, in mouse
    self.wait_present(selector)
  File "/build/cockpit/test/common/testlib.py", line 341, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 329, in wait_js_cond
    silent=False, awaitPromise=True, trace="wait: " + cond)
  File "/build/cockpit/test/common/cdp.py", line 87, in invoke
    res = self.command(cmd)
  File "/build/cockpit/test/common/cdp.py", line 114, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: Cannot read property 'v' of undefined

not ok 87 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 45s
```
First occurrence: 2019-05-01T20:35:19.652049 | revision d1c89099698e6fa1dc3da251e090b5455a7d3170, [logs](https://209.132.184.41:8493/logs/pull-11720-20190501-200202-d1c89099-verify-rhel-8-0-distropkg/log.html)
Times recorded: 1
Latest occurrences:

- 2019-05-01T20:35:19.652049 | revision d1c89099698e6fa1dc3da251e090b5455a7d3170, [logs](https://209.132.184.41:8493/logs/pull-11720-20190501-200202-d1c89099-verify-rhel-8-0-distropkg/log.html)
