### ISSUE TITLE
SELinux is preventing pmdalinux from module_request access on the system labeled kernel_t

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11660]
Audit messages like:
`audit: type=1400 audit(1556081714.160:467): avc:  denied  { module_request } for  pid=946 comm="pmdalinux" kmod="netdev-vnet0" scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0`

Downstream report:
https://bugzilla.redhat.com/show_bug.cgi?id=1690542

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDisk (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9952/devtools/browser/c27bd808-e14f-4e42-9874-cecc09421c22
[0505/120200.862050:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 37277: Permission denied (13)
[0505/120200.874617:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0505/120200.877348:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[0505/120201.060151:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 37309: Permission denied (13)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
audit: type=1400 audit(1557057743.076:472): avc:  denied  { module_request } for  pid=959 comm="pmdalinux" kmod="netdev-vnet0" scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
audit: type=1400 audit(1557057743.089:473): avc:  denied  { module_request } for  pid=959 comm="pmdalinux" kmod="netdev-vnet0" scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
Wrote JS log to TestMachinesDBus-testAddDisk-fedora-30-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachinesDBus-testAddDisk-fedora-30-127.0.0.2-2501-FAIL.log
Wrote screenshot to TestMachinesDBus-testAddDisk-fedora-30-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMachinesDBus-testAddDisk-fedora-30-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMachinesDBus-testAddDisk-fedora-30-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachinesDBus-testAddDisk-fedora-30-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 954, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1557057743.076:472): avc:  denied  { module_request } for  pid=959 comm="pmdalinux" kmod="netdev-vnet0" scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0

not ok 68 testAddDisk (check_machines_dbus.TestMachinesDBus) # duration: 56s
```
First occurrence: 2019-05-05T12:02:29.096917 | revision 266fc1516f1320a3453ea21360cb64d6c1331a79, [logs](https://209.132.184.41:8493/logs/pull-11741-20190505-111919-266fc151-verify-fedora-30/log.html)
Times recorded: 1
Latest occurrences:

- 2019-05-05T12:02:29.096917 | revision 266fc1516f1320a3453ea21360cb64d6c1331a79, [logs](https://209.132.184.41:8493/logs/pull-11741-20190505-111919-266fc151-verify-fedora-30/log.html)
