### ISSUE TITLE
ubuntu-stable: firewalld fails to start: FATAL ERROR: No IPv4 and IPv6 firewall

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11670]
Downstream report: https://launchpad.net/bugs/1826187

**Comment by martinpitt** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddServices (__main__.TestFirewall)
#

DevTools listening on ws://127.0.0.1:9315/devtools/browser/3e662cad-1ff6-47ab-b686-e94616ec25bf
[0425/174829.650756:ERROR:vaapi_wrapper.cc(327)] vaInitialize failed: unknown libva error
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: 
Error: 'inet firewalld filter_IN_public jump filter_IN_public_allow'
Wrote screenshot to TestFirewall-testAddServices-ubuntu-stable-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestFirewall-testAddServices-ubuntu-stable-127.0.0.2-2201-FAIL.html
Wrote JS log to TestFirewall-testAddServices-ubuntu-stable-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestFirewall-testAddServices-ubuntu-stable-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-networking-firewall", line 191, in testAddServices
    m.execute("firewall-cmd --permanent --new-service=empty && firewall-cmd --reload")
  File "/home/martin/upstream/cockpit/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'firewall-cmd --permanent --new-service=empty && firewall-cmd --reload' returned non-zero exit status 254.

not ok 1 testAddServices (__main__.TestFirewall) # duration: 33s
```
First occurrence: 2019-04-25T17:48:41.331542
Times recorded: 1
Latest occurrences:

- 2019-04-25T17:48:41.331542

**Comment by martinpitt** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFirewallPage (__main__.TestFirewall)
#

DevTools listening on ws://127.0.0.1:9457/devtools/browser/94941149-95df-4c4f-bd7e-b23f01da566e
[0425/174852.243479:ERROR:vaapi_wrapper.cc(327)] vaInitialize failed: unknown libva error
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 
Error: 'inet firewalld filter_IN_public jump filter_IN_public_allow'
Wrote screenshot to TestFirewall-testFirewallPage-ubuntu-stable-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestFirewall-testFirewallPage-ubuntu-stable-127.0.0.2-2301-FAIL.html
Wrote JS log to TestFirewall-testFirewallPage-ubuntu-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestFirewall-testFirewallPage-ubuntu-stable-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-networking-firewall", line 123, in testFirewallPage
    m.execute("firewall-cmd --permanent --new-service=empty && firewall-cmd --reload && firewall-cmd --add-service=empty")
  File "/home/martin/upstream/cockpit/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'firewall-cmd --permanent --new-service=empty && firewall-cmd --reload && firewall-cmd --add-service=empty' returned non-zero exit status 254.

not ok 1 testFirewallPage (__main__.TestFirewall) # duration: 33s
```
First occurrence: 2019-04-25T17:49:02.132701
Times recorded: 1
Latest occurrences:

- 2019-04-25T17:49:02.132701

**Comment by marusak** [comment]
Naughty for this is not used in the end. Closing
