### ISSUE TITLE
SELinux is preventing chronyd from sendto access on the unix_dgram_socket

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11671]
SELinux violations like:
`type=1400 audit(1556197202.146:5): avc:  denied  { sendto } for  pid=2758 comm="chronyd" path="/host/run/chrony/chronyc.5500.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0`

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1703192

**Comment by cockpituous** [comment]
verify/rhel-atomic
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_sosreport.TestSOS)
#
[0425/193115.881411:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9596/devtools/browser/a44f4d53-8c81-4277-8acb-8a35c1b6d6e2
[0425/193115.886773:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 31253: Permission denied (13)
[0425/193115.896819:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0425/193115.899458:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0425/193116.043829:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 31280: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: PackageKit went away from D-Bus
> warning: Checking for available updates failed: not-found
> warning: Checking for available updates failed: not-found
> log: PackageKit went away from D-Bus
Unexpected journal messages:
type=1400 audit(1556220790.419:5): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5494.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220791.427:6): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5494.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220793.429:7): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5494.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220798.616:8): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5575.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220799.620:9): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5575.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220801.626:10): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5575.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220806.718:11): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5820.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220807.719:12): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5820.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220809.723:13): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5820.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220814.674:14): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.6468.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220815.671:15): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.6468.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220817.676:16): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.6468.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220822.665:17): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7010.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220823.665:18): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7010.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220825.672:19): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7010.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220830.600:20): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7191.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220831.605:21): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7191.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220833.607:22): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7191.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220838.455:23): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7269.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220839.456:24): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7269.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
type=1400 audit(1556220841.459:25): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.7269.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0
Wrote JS log to TestSOS-testBasic-rhel-atomic-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSOS-testBasic-rhel-atomic-127.0.0.2-2401-FAIL.log
Wrote screenshot to TestSOS-testBasic-rhel-atomic-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSOS-testBasic-rhel-atomic-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSOS-testBasic-rhel-atomic-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSOS-testBasic-rhel-atomic-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 959, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1556220790.419:5): avc:  denied  { sendto } for  pid=2767 comm="chronyd" path="/host/run/chrony/chronyc.5494.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0

not ok 211 testBasic (check_sosreport.TestSOS) # duration: 378s
```
First occurrence: 2019-04-25T19:35:50.475937 | revision 6bf52aa3d1dfe3130739302f66ca9fa86f0ff3fe, [logs](https://209.132.184.41:8493/logs/pull-11666-20190425-191111-6bf52aa3-verify-rhel-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-25T19:35:50.475937 | revision 6bf52aa3d1dfe3130739302f66ca9fa86f0ff3fe, [logs](https://209.132.184.41:8493/logs/pull-11666-20190425-191111-6bf52aa3-verify-rhel-atomic/log.html)

**Comment by martinpitt** [comment]
Bump, we are not currently exercising our RHEL 7 naughties enough.

**Comment by marusak** [comment]
Bump, we are not currently exercising our RHEL 7 naughties enough.
