### ISSUE TITLE
SELinux is preventing iscsid from 'map' accesses

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11724]
Downstream report for rhel-8-1:
https://bugzilla.redhat.com/show_bug.cgi?id=1705044
Downstream report for Fedora 30:
https://bugzilla.redhat.com/show_bug.cgi?id=1706490

Avcs like:
`audit: type=1400 audit(1556695246.724:4): avc:  denied  { map } for  pid=3730 comm="iscsid" path="/usr/lib/modules/4.18.0-80.23.el8.x86_64/modules.dep.bin" dev="dm-0" ino=9082811 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:modules_dep_t:s0 tclass=file permissive=0`

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#
[0501/202418.877179:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10113/devtools/browser/a9a3a966-8a48-457c-bb92-e9e0ae64a96a
[0501/202418.880961:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 40329: Permission denied (13)
[0501/202418.892706:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0501/202418.896819:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0501/202419.070242:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 40364: Permission denied (13)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: GET_STORAGE_POOL action failed failed for path /org/libvirt/QEMU/storagepool/_2474bc6d_9ff7_4f96_916f_aabe1bdee183 
> warning: GET_STORAGE_POOL action failed failed for path /org/libvirt/QEMU/storagepool/_47e31b6f_d370_4cd9_b8ff_d5f682f123d5 
Unexpected journal messages:
audit: type=1400 audit(1556742272.752:4): avc:  denied  { map } for  pid=3738 comm="iscsid" path="/usr/lib/modules/4.18.0-80.23.el8.x86_64/modules.dep.bin" dev="dm-0" ino=9082811 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:modules_dep_t:s0 tclass=file permissive=0
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2201-FAIL.log
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 959, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1556742272.752:4): avc:  denied  { map } for  pid=3738 comm="iscsid" path="/usr/lib/modules/4.18.0-80.23.el8.x86_64/modules.dep.bin" dev="dm-0" ino=9082811 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:modules_dep_t:s0 tclass=file permissive=0

not ok 87 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 50s
```
First occurrence: 2019-05-01T20:24:48.333285 | revision d1c89099698e6fa1dc3da251e090b5455a7d3170, [logs](https://209.132.184.41:8493/logs/pull-11720-20190501-200202-d1c89099-verify-rhel-8-1/log.html)
Times recorded: 1
Latest occurrences:

- 2019-05-01T20:24:48.333285 | revision d1c89099698e6fa1dc3da251e090b5455a7d3170, [logs](https://209.132.184.41:8493/logs/pull-11720-20190501-200202-d1c89099-verify-rhel-8-1/log.html)

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9440/devtools/browser/6ea3c8ec-1ef3-466b-aea8-e39384522fb0
[0505/052408.225903:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 32991: Permission denied (13)
[0505/052408.240994:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0505/052408.242622:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[0505/052408.424758:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 33029: Permission denied (13)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

{"exceptionId":1,"text":"Uncaught","lineNumber":173332,"columnNumber":45,"url":"http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/machines/machines.js","stackTrace":{"callFrames":[{"functionName":"","scriptId":"32","url":"http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/machines/machines.js","lineNumber":173332,"columnNumber":45},{"functionName":"s","scriptId":"27","url":"http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js","lineNumber":962,"columnNumber":32},{"functionName":"","scriptId":"27","url":"http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js","lineNumber":974,"columnNumber":16},{"functionName":"n","scriptId":"27","url":"http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js","lineNumber":880,"columnNumber":16}]},"exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read property 'v' of undefined\n    at Function.<anonymous> (http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/machines/machines.js:173333:46)\n    at s (http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js:963:33)\n    at http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js:975:17\n    at n (http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js:881:17)","objectId":"{\"injectedScriptId\":5,\"id\":1}","preview":{"type":"object","subtype":"error","description":"TypeError: Cannot read property 'v' of undefined\n    at Function.<anonymous> (http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/machines/machines.js:173333:46)\n    at s (http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js:963:33)\n    at http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js:975:17\n    at n (http://127.0.0.2:9491/cockpit/$79ff970c8e17b6564f2a86abfbba7bd85f3331f13f05a36a054ecb048174b90b/base1/cockpit.js:881:17)","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Cannot read property 'v' of undefined\n …3f05a36a054ecb048174b90b/base1/cockpit.js:881:17)"},{"name":"message","type":"string","value":"Cannot read property 'v' of undefined"}]}},"executionContextId":5}
Unexpected journal messages:
audit: type=1400 audit(1557033870.107:479): avc:  denied  { map } for  pid=7748 comm="iscsid" path="/usr/lib/modules/5.0.10-300.fc30.x86_64/modules.dep.bin" dev="dm-0" ino=12735 scontext=system_u:system_r:iscsid_t:s0 tcontext=unconfined_u:object_r:modules_dep_t:s0 tclass=file permissive=0
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2601-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-fedora-30-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 951, in check_journal_messages
    self.copy_js_log("FAIL")
  File "/build/cockpit/test/common/testlib.py", line 1038, in copy_js_log
    self.browser.copy_js_log(title, label)
  File "/build/cockpit/test/common/testlib.py", line 586, in copy_js_log
    logs = list(self.get_js_log())
  File "/build/cockpit/test/common/testlib.py", line 580, in get_js_log
    return self.cdp.get_js_log()
  File "/build/cockpit/test/common/cdp.py", line 247, in get_js_log
    messages = self.command("Promise.resolve(messages)")
  File "/build/cockpit/test/common/cdp.py", line 114, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: Cannot read property 'v' of undefined

not ok 78 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 51s
```
First occurrence: 2019-05-05T05:24:38.419906 | revision df9b92f2c4468a26df0f35886d7148edca1bff58
Times recorded: 1
Latest occurrences:

- 2019-05-05T05:24:38.419906 | revision df9b92f2c4468a26df0f35886d7148edca1bff58
