### ISSUE TITLE
check-storage-lvm2: lvcreate --thinpool is unreliable

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#11735]
It sometimes fails like so:
```
  Logical volume TEST/lvol1 in use.
  Unable to deactivate pool metadata spare LV. Manual intervention required.
```

The `TEST/lvol1` volume is one that it creates for itself, and then maybe udev keeps it busy for a bit while lvcreate wants to deactivate it.

**Comment by mvollmer** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSnapshots (__main__.TestStorage)
#

DevTools listening on ws://127.0.0.1:9404/devtools/browser/6bb2f0d5-2b73-4053-a617-e4815d346e26
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[0503/152932.488767:ERROR:vaapi_wrapper.cc(327)] vaInitialize failed: unknown libva error
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

  Logical volume TEST/lvol1 in use.
  Unable to deactivate pool metadata spare LV. Manual intervention required.
Wrote screenshot to TestStorage-testSnapshots-centos-7-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testSnapshots-centos-7-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testSnapshots-centos-7-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testSnapshots-centos-7-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "./test/verify/check-storage-lvm2", line 284, in testSnapshots
    m.execute("lvcreate TEST --thinpool pool -L 20m")
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'lvcreate TEST --thinpool pool -L 20m' returned non-zero exit status 5.

not ok 1 testSnapshots (__main__.TestStorage) # duration: 33s
```
First occurrence: 2019-05-03T15:29:45.485159
Times recorded: 1
Latest occurrences:

- 2019-05-03T15:29:45.485159

**Comment by martinpitt** [comment]
obsolete
