### ISSUE TITLE
Podman does not recognize env variable

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11902]
Reported as: https://github.com/containers/libpod/issues/3182
Also behind this issue hides: https://github.com/containers/libpod/issues/3183

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRunImage (__main__.TestApplication)
#
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket

DevTools listening on ws://127.0.0.1:9257/devtools/browser/6ae7403c-ed78-4a08-ad3d-7b5bbb6ee6de
[0522/114602.910792:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0522/114602.912963:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/check-application", line 427, in testRunImage
    b.wait_not_present("div.modal-dialog")
  File "test/common/testlib.py", line 343, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "test/common/testlib.py", line 334, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "test/common/testlib.py", line 331, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("div.modal-dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 211, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 210, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 222, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:223:24', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1558525566873.97, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000080570.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 5 testRunImage (__main__.TestApplication) # duration: 94s
```
First occurrence: 2019-05-22T11:47:15.761253 | revision c09b9e7b9045704484f0df72d687e668e0c47b3c
Times recorded: 1
Latest occurrences:

- 2019-05-22T11:47:15.761253 | revision c09b9e7b9045704484f0df72d687e668e0c47b3c
