### ISSUE TITLE
SELinux: avc:  denied  { getattr } comm="iscsid"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11917]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1698702

**Comment by cockpituous** [comment]
verify/rhel-7-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9247/devtools/browser/3125cdd3-306d-4f1c-b052-e9945cda18fb
[0524/070230.267159:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0524/070230.302499:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: GET_STORAGE_POOL action failed failed for path /org/libvirt/QEMU/storagepool/_21da2729_c1f4_4483_9dab_86166172a487 
ls: cannot access /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_DISK1: No such file or directory
Information: You may need to update /etc/fstab.

> warning: GET_STORAGE_POOL action failed failed for path /org/libvirt/QEMU/storagepool/_e3a7c835_1399_4303_99cb_0b90121160d7 
Unexpected journal messages:
type=1400 audit(1558681371.134:4): avc:  denied  { getattr } for  pid=3858 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9221 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
type=1400 audit(1558681371.146:5): avc:  denied  { getattr } for  pid=3858 comm="iscsid" path="/dev/dm-1" dev="devtmpfs" ino=9326 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-7-7-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-7-7-127.0.0.2-2301-FAIL.log
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-rhel-7-7-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-rhel-7-7-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-7-7-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-7-7-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 955, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1558681371.134:4): avc:  denied  { getattr } for  pid=3858 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9221 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0

not ok 260 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 53s
```
First occurrence: 2019-05-24T07:02:56.385083 | revision 7605cf82275c57c5a9f83c0cf042174da070ab69, [logs](https://209.132.184.41:8493/logs/pull-11907-20190524-065151-7605cf82-verify-rhel-7-7/log.html)
Times recorded: 1
Latest occurrences:

- 2019-05-24T07:02:56.385083 | revision 7605cf82275c57c5a9f83c0cf042174da070ab69, [logs](https://209.132.184.41:8493/logs/pull-11907-20190524-065151-7605cf82-verify-rhel-7-7/log.html)

**Comment by martinpitt** [comment]
Let's keep this open for now, the downstream bug is still open. I'll send a rhel-7.7 branch PR to exercise our images and naughties.
