### ISSUE TITLE
cockpit-ws segfaults with glib 2.36.3

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#1193]
We seem to run into

     https://bugzilla.gnome.org/show_bug.cgi?id=701283

It's fixed in 2.37.4 with this commit

    https://git.gnome.org/browse/glib/commit/?id=1d5c815ecd3a5ac6032e7931491296e693b51ccd

Backtrace

```
#0  g_main_context_remove_poll_unlocked (context=0x0, fd=0x6d2530) at gmain.c:4159
#1  0x00007ffff754d6e4 in block_source (source=0x6d24d0) at gmain.c:2947
#2  0x00007ffff754d738 in block_source (source=0x6d2420) at gmain.c:2959
#3  0x00007ffff754f560 in g_source_add_child_source (source=0x6d9aa0, child_source=0x6d2420) at gmain.c:1427
#4  0x00007ffff2a47f87 in gnutls_source_sync (gnutls_source=gnutls_source@entry=0x6d9aa0)
    at gtlsconnection-gnutls.c:881
#5  0x00007ffff2a48084 in gnutls_source_dispatch (source=source@entry=0x6d9aa0, callback=<optimized out>, 
    user_data=<optimized out>) at gtlsconnection-gnutls.c:895
#6  0x00007ffff7550ac6 in g_main_dispatch (context=0x6cd450) at gmain.c:3058
#7  g_main_context_dispatch (context=context@entry=0x6cd450) at gmain.c:3634
#8  0x00007ffff7550e48 in g_main_context_iterate (context=0x6cd450, block=block@entry=1, dispatch=dispatch@entry=1, 
    self=<optimized out>) at gmain.c:3705
#9  0x00007ffff755125a in g_main_loop_run (loop=0x655f60) at gmain.c:3899
#10 0x000000000040965d in main (argc=1, argv=0x7fffffffe4f8) at src/ws/main.c:168
```

To reproduce, start cockpit-ws and connect to it over https.

**Comment by stefwalter** [comment]
Fixed by 7f0a31e44b6f590728c02689784a031f14e07e85. We refuse to build on this version.
