### ISSUE TITLE
avc: denied { write } for comm="dhclient" name="NetworkManager" dev="tmpfs"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#12057]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1720070

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBondingMainSlowly (check_networking_bond.TestNetworking)
#
NAME             UUID                                  TYPE      DEVICE 
System eth0      5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
static-52:54:01  d63e7cf2-d590-475c-8ee1-b93b2c285d47  ethernet  eth1   
virbr0           330940f0-da7a-4e60-b6e1-9225e698624d  bridge    virbr0 
System eth1      9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2             3fddaa3d-b689-41bb-9e98-ae5fa73dc697  ethernet  --     

52:54:01:00:00:01 -> eth1

DevTools listening on ws://127.0.0.1:9642/devtools/browser/749c1b95-0238-428c-8f29-5da9950fcdd8
[0613/070659.092936:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0613/070659.095106:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Unexpected journal messages:
audit: type=1400 audit(1560409617.759:5): avc:  denied  { write } for  pid=1722 comm="dhclient" name="NetworkManager" dev="tmpfs" ino=22168 scontext=system_u:system_r:dhcpc_t:s0 tcontext=system_u:object_r:NetworkManager_var_run_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1560409617.935:6): avc:  denied  { write } for  pid=1722 comm="dhclient" name="NetworkManager" dev="tmpfs" ino=22168 scontext=system_u:system_r:dhcpc_t:s0 tcontext=system_u:object_r:NetworkManager_var_run_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1560409618.053:7): avc:  denied  { write } for  pid=1722 comm="dhclient" name="NetworkManager" dev="tmpfs" ino=22168 scontext=system_u:system_r:dhcpc_t:s0 tcontext=system_u:object_r:NetworkManager_var_run_t:s0 tclass=dir permissive=0
Wrote JS log to TestNetworking-testBondingMainSlowly-rhel-8-1-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestNetworking-testBondingMainSlowly-rhel-8-1-127.0.0.2-2501-FAIL.log
Journal extracted to TestNetworking-testBondingMainSlowly-fedora-30-127.0.0.2-2502-FAIL.log
Wrote screenshot to TestNetworking-testBondingMainSlowly-rhel-8-1-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestNetworking-testBondingMainSlowly-rhel-8-1-127.0.0.2-2501-FAIL.html
Wrote JS log to TestNetworking-testBondingMainSlowly-rhel-8-1-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestNetworking-testBondingMainSlowly-rhel-8-1-127.0.0.2-2501-FAIL.log
Journal extracted to TestNetworking-testBondingMainSlowly-fedora-30-127.0.0.2-2502-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1560409617.759:5): avc:  denied  { write } for  pid=1722 comm="dhclient" name="NetworkManager" dev="tmpfs" ino=22168 scontext=system_u:system_r:dhcpc_t:s0 tcontext=system_u:object_r:NetworkManager_var_run_t:s0 tclass=dir permissive=0

not ok 131 testBondingMainSlowly (check_networking_bond.TestNetworking) # duration: 36s
```
First occurrence: 2019-06-13T07:07:09.803954 | revision 3c2146d8f07c98f9a8a982fabe6338463365c593, [logs](https://209.132.184.41:8493/logs/pull-12056-20190613-064848-3c2146d8-verify-rhel-8-1/log.html)
Times recorded: 1
Latest occurrences:

- 2019-06-13T07:07:09.803954 | revision 3c2146d8f07c98f9a8a982fabe6338463365c593, [logs](https://209.132.184.41:8493/logs/pull-12056-20190613-064848-3c2146d8-verify-rhel-8-1/log.html)
