### ISSUE TITLE
rhel-8-1 Adding service into permanent configuration via DBus api suddenly requires 9 values

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12086]
Cockpit version: 196
OS: rhel-8-1
Page: network/firewall

https://bugzilla.redhat.com/show_bug.cgi?id=1721414

Description of problem:
Caught by cockpit tests.

Adding service into permanent configuration via DBus api suddenly requires 9 values. While the documentation clearly states only 8 are required to make up the settings structure.

Version-Release number of selected component (if applicable):
0.7.0

How reproducible:
A dbus call to
object path: /org/fedoraproject/FirewallD1/config
interface:   org.fedoraproject.FirewallD1.config
method:      addService
arguments:   [service, ["", name, "", ports, [], {}, [], []]*

*with name and ports as valid arguments

Actual results:
org.freedesktop.DBus.Error.InvalidArgs: Too few values in tuple/struct

Using [service, ["", name, "", ports, [], {}, [], [], []] as the arguments works.

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddCustomServices (check_networking_firewall.TestFirewall)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       91d188ae-7487-408e-a20f-d895c2a00b30  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         d9cd1e3d-8d4e-4434-8c51-4b464cc2c586  ethernet  --     


DevTools listening on ws://127.0.0.1:9327/devtools/browser/7fe7b0ed-09df-46ae-bc12-ffe4a94d67ac
[0618/102408.644689:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0618/102408.646419:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestFirewall-testAddCustomServices-rhel-8-1-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestFirewall-testAddCustomServices-rhel-8-1-127.0.0.2-2601-FAIL.html
Wrote JS log to TestFirewall-testAddCustomServices-rhel-8-1-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestFirewall-testAddCustomServices-rhel-8-1-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-networking-firewall", line 302, in testAddCustomServices
    save("custom--https-irc-50000", "https, irc, 50000", "443", "194, 50000")
  File "/build/cockpit/bots/../test/verify/check-networking-firewall", line 288, in save
    b.wait_not_present("#add-services-dialog")
  File "/build/cockpit/test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#add-services-dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 215, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 214, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1560853449262.74, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '1000089914.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]

not ok 103 testAddCustomServices (check_networking_firewall.TestFirewall) # duration: 85s
```
First occurrence: 2019-06-18T10:25:14.660589 | revision 4441eca48a1f55978e9da102a98f7d66a52f0bfd, [logs](https://209.132.184.41:8493/logs/pull-12087-20190618-094949-4441eca4-verify-rhel-8-1/log.html)
Times recorded: 1
Latest occurrences:

- 2019-06-18T10:25:14.660589 | revision 4441eca48a1f55978e9da102a98f7d66a52f0bfd, [logs](https://209.132.184.41:8493/logs/pull-12087-20190618-094949-4441eca4-verify-rhel-8-1/log.html)
