### ISSUE TITLE
podman crashes on fedora-30 when doing bulk deletion of images and calling ListImages in parallel

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#12098]
Issue in libpod repository https://github.com/containers/libpod/issues/3316

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRunImage (__main__.TestApplication)
#
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket

DevTools listening on ws://127.0.0.1:9515/devtools/browser/465914e9-79b9-4a6c-86a9-2920959cd6d9
[0619/174409.684296:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0619/174409.769592:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Failed to do Update Container: {"error":"io.podman.ContainerNotFound","parameters":{"id":"0945803dd844dbfbe53ba4280e121545fbd379cd5539f40c0f52dacf8c826709","reason":"no container with name or ID 0945803dd844dbfbe53ba4280e121545fbd379cd5539f40c0f52dacf8c826709 found: no such container"}}
> warning: Failed to do Update Container: {"name":"ConnectionClosed","parameters":{}}
> warning: Failed to do Update Container: {"error":"io.podman.ContainerNotFound","parameters":{"id":"28cb886405eedf06dc87d890653d93ba981a616ba3ec5f8609c266e4132cb8f6","reason":"no container with name or ID 28cb886405eedf06dc87d890653d93ba981a616ba3ec5f8609c266e4132cb8f6 found: no such container"}}
> warning: Failed to do varlinkcall: {"error":"io.podman.ErrorOccurred","parameters":{"reason":"container 28cb886405eedf06dc87d890653d93ba981a616ba3ec5f8609c266e4132cb8f6 does not exist in database: no such container"}}
> warning: Failed to do Update Container: {"error":"io.podman.ErrorOccurred","parameters":{"reason":"container 28cb886405eedf06dc87d890653d93ba981a616ba3ec5f8609c266e4132cb8f6 does not exist in database: no such container"}}
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Failed to do varlinkcall: {"name":"ConnectionClosed","parameters":{}}
> warning: Failed to do Update Images: {"name":"ConnectionClosed","parameters":{}}
Unexpected journal messages:
Process 6960 (podman) of user 0 dumped core.
Stack trace of thread 7296:
#0  0x00005569f14e47f1 n/a (podman)
#1  0x00005569f14cb4c8 n/a (podman)
#2  0x00005569f14ca5e0 n/a (podman)
#3  0x00005569f14e4ae3 n/a (podman)
#4  0x00007fb9dd2f7e80 __restore_rt (libpthread.so.0)
#5  0x00005569f14e47f1 n/a (podman)
#6  0x00005569f14cb0da n/a (podman)
#7  0x00005569f14b5a36 n/a (podman)
#8  0x00005569f14b53f9 n/a (podman)
#9  0x00005569f14cae55 n/a (podman)
#10 0x00005569f23bf091 n/a (podman)
#11 0x00005569f23a999c n/a (podman)
#12 0x00005569f239de5d n/a (podman)
#13 0x00005569f239e21d n/a (podman)
#14 0x00005569f14e2eb1 n/a (podman)
Wrote JS log to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.log
Core dumps downloaded to /build/cockpit/TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.core
Wrote screenshot to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.log
Core dumps downloaded to /build/cockpit/TestApplication-testRunImage-fedora-30-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: Process 6960 (podman) of user 0 dumped core.

not ok 5 testRunImage (__main__.TestApplication) # duration: 57s
```
First occurrence: 2019-06-19T17:44:44.788589 | revision c5532f82a4b7c0ec293d3eb590cb6e5a80f1a235
Times recorded: 1
Latest occurrences:

- 2019-06-19T17:44:44.788589 | revision c5532f82a4b7c0ec293d3eb590cb6e5a80f1a235
