### ISSUE TITLE
SELinux is preventing mdadm from 'read' 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#12228]
Example: https://209.132.184.41:8493/logs/pull-12223-20190704-071010-397e4516-verify-fedora-30/log.html#204

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1721644

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNotRemovingDisks (check_storage_mdraid.TestStorage)
#

DevTools listening on ws://127.0.0.1:9748/devtools/browser/bc3432bd-fff8-416b-96a7-877cd1b5dfdc
[0704/153602.602612:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 14774: Permission denied (13)
[0704/153602.619493:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0704/153602.621167:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[0704/153602.801485:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 14853: Permission denied (13)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
audit: type=1400 audit(1562254574.677:322): avc:  denied  { read } for  pid=7285 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=2466316 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-30-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-30-127.0.0.2-2301-FAIL.log
Wrote screenshot to TestStorage-testNotRemovingDisks-fedora-30-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorage-testNotRemovingDisks-fedora-30-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-30-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-30-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 780, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 958, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1562254574.677:322): avc:  denied  { read } for  pid=7285 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=2466316 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0

not ok 204 testNotRemovingDisks (check_storage_mdraid.TestStorage) # duration: 34s
```
First occurrence: 2019-07-04T15:36:17.669090 | revision 7441ce5b8ed28c82d739a2eeea1ace5393e835c2, [logs](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12211-20190704-154343-7441ce5b-verify-fedora-30/log.html)
Times recorded: 1
Latest occurrences:

- 2019-07-04T15:36:17.669090 | revision 7441ce5b8ed28c82d739a2eeea1ace5393e835c2, [logs](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12211-20190704-154343-7441ce5b-verify-fedora-30/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNotRemovingDisks (check_storage_mdraid.TestStorage)
#

DevTools listening on ws://127.0.0.1:10019/devtools/browser/24877195-dcb2-4183-a7cd-1a4e357f821d
[0718/174741.286219:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 21327: Permission denied (13)
[0718/174741.301187:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0718/174741.302935:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[0718/174741.479351:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 21362: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
audit: type=1400 audit(1563472071.837:317): avc:  denied  { read } for  pid=7205 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=18593990 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
audit: type=1400 audit(1563472071.837:317): avc:  denied  { read } for  pid=7205 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.pag" dev="dm-0" ino=18593991 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-i386-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-i386-127.0.0.2-2301-FAIL.log
Wrote screenshot to TestStorage-testNotRemovingDisks-fedora-i386-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorage-testNotRemovingDisks-fedora-i386-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-i386-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-i386-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 781, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 955, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1563472071.837:317): avc:  denied  { read } for  pid=7205 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=18593990 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0

not ok 204 testNotRemovingDisks (check_storage_mdraid.TestStorage) # duration: 35s
```
First occurrence: 2019-07-18T17:47:59.831201 | revision a54612869cba5158de7c54c5302863a8ee6839ac, [logs](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12357-20190718-173838-a5461286-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2019-07-18T17:47:59.831201 | revision a54612869cba5158de7c54c5302863a8ee6839ac, [logs](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12357-20190718-173838-a5461286-verify-fedora-i386/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRaid (check_storage_mdraid.TestStorage)
#

DevTools listening on ws://127.0.0.1:9463/devtools/browser/a3ddebcf-c5c7-4632-8b8b-284ea20e1836
[0718/174735.531886:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 21212: Permission denied (13)
[0718/174735.547312:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0718/174735.548880:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
[0718/174735.739014:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 21250: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
audit: type=1400 audit(1563472066.816:315): avc:  denied  { read } for  pid=7121 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=18593990 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
audit: type=1400 audit(1563472066.816:315): avc:  denied  { read } for  pid=7121 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.pag" dev="dm-0" ino=18593991 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
Wrote JS log to TestStorage-testRaid-fedora-i386-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-i386-127.0.0.2-2701-FAIL.log
Wrote screenshot to TestStorage-testRaid-fedora-i386-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorage-testRaid-fedora-i386-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorage-testRaid-fedora-i386-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-i386-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 781, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 955, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1563472066.816:315): avc:  denied  { read } for  pid=7121 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=18593990 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0

not ok 205 testRaid (check_storage_mdraid.TestStorage) # duration: 48s
```
First occurrence: 2019-07-18T17:48:04.230013 | revision a54612869cba5158de7c54c5302863a8ee6839ac, [logs](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12357-20190718-173838-a5461286-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2019-07-18T17:48:04.230013 | revision a54612869cba5158de7c54c5302863a8ee6839ac, [logs](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12357-20190718-173838-a5461286-verify-fedora-i386/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNotRemovingDisks (check_storage_mdraid.TestStorage)
#

DevTools listening on ws://127.0.0.1:9635/devtools/browser/73e8497d-f504-41ae-9bae-02c9bddf22ae
[0723/225414.700257:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0723/225414.702169:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
audit: type=1400 audit(1563922464.910:321): avc:  denied  { read } for  pid=7310 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=26662490 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-testing-127.0.0.2-2201-FAIL.log
Wrote screenshot to TestStorage-testNotRemovingDisks-fedora-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testNotRemovingDisks-fedora-testing-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-testing-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 782, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 956, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1563922464.910:321): avc:  denied  { read } for  pid=7310 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=26662490 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0

not ok 204 testNotRemovingDisks (check_storage_mdraid.TestStorage) # duration: 34s
```
First occurrence: 2019-07-23T22:54:29.812516 | revision 303969dd876130aa53faf920c6e1f52d281b0d4d
Times recorded: 1
Latest occurrences:

- 2019-07-23T22:54:29.812516 | revision 303969dd876130aa53faf920c6e1f52d281b0d4d

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRaid (check_storage_mdraid.TestStorage)
#

DevTools listening on ws://127.0.0.1:9375/devtools/browser/8fa6aa04-f9ee-4a4a-9c83-190437c8fca2
[0723/225409.335670:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0723/225409.337505:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Unexpected journal messages:
audit: type=1400 audit(1563922455.593:311): avc:  denied  { read } for  pid=7251 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=26662490 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
audit: type=1400 audit(1563922455.593:311): avc:  denied  { read } for  pid=7251 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.pag" dev="dm-0" ino=26662491 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0
Wrote JS log to TestStorage-testRaid-fedora-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-testing-127.0.0.2-2401-FAIL.log
Wrote screenshot to TestStorage-testRaid-fedora-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorage-testRaid-fedora-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorage-testRaid-fedora-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-testing-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 782, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 956, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1563922455.593:311): avc:  denied  { read } for  pid=7251 comm="mdadm" path="/var/lib/pcp/pmdas/linux/help.dir" dev="dm-0" ino=26662490 scontext=system_u:system_r:mdadm_t:s0 tcontext=system_u:object_r:pcp_var_lib_t:s0 tclass=file permissive=0

not ok 205 testRaid (check_storage_mdraid.TestStorage) # duration: 48s
```
First occurrence: 2019-07-23T22:54:36.953376 | revision 303969dd876130aa53faf920c6e1f52d281b0d4d
Times recorded: 1
Latest occurrences:

- 2019-07-23T22:54:36.953376 | revision 303969dd876130aa53faf920c6e1f52d281b0d4d
