### ISSUE TITLE
podman Commit Container is extremely slow

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#12264]
Issue in libpod repository: https://github.com/containers/libpod/issues/3526

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestApplication)
#
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket

DevTools listening on ws://127.0.0.1:9727/devtools/browser/6dd213c6-4015-4317-b4ca-80380ed95cd6
[0709/124354.385353:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0709/124354.387084:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Failed to do Update Container: {"error":"io.podman.ContainerNotFound","parameters":{"id":"0ff43992105faa06af25aaa00d81e66dd051236d6bb5c9da1ec6557715a5a482","reason":"no container with name or ID 0ff43992105faa06af25aaa00d81e66dd051236d6bb5c9da1ec6557715a5a482 found: no such container"}}
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> log: Container commit: Getting image source signatures

> log: Container commit: Copying blob sha256:256a7af3acb11f89914205b6eef07e05e4196e898329575d97185758b450eb52

Copying blob sha256:a9de4d7ff3c298fdfec1106da7a6751b62da86dda6089558182a67177271a54c

> log: Container commit: Copying config sha256:ac259b99cc6a9cd53856537b13529eecc65e9b9b0297ad697db7aeee5718eee4

> log: Container commit: Writing manifest to image destination

Storing signatures

> log: Container commit: Getting image source signatures

Copying blob sha256:6194458b07fcf01f1483d96cd6c34302ffff7f382bb151a6d023c4e80ba3050a

Copying blob sha256:0e9b36a20ddaa651b38e7ab42e343df75cd333400fd4f3e03b28f158ec6dea2f

> log: Container commit: Copying config sha256:a37a19045ca35475d10d96a9b6976dd169c9ca3b3da58707f262131b61b283a0

> log: Container commit: Writing manifest to image destination

Storing signatures

Wrote screenshot to TestApplication-testBasic-fedora-29-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestApplication-testBasic-fedora-29-127.0.0.2-2601-FAIL.html
Wrote JS log to TestApplication-testBasic-fedora-29-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestApplication-testBasic-fedora-29-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "test/check-application", line 126, in testBasic
    container_commit("test-sh")
  File "test/check-application", line 107, in container_commit
    b.wait_not_present(".modal-dialog div")
  File "test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present(".modal-dialog div")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 215, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 214, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1562676238599.85, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '1000002556.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Failed to do Update Container: {"error":"io.podman.ContainerNotFound","parameters":{"id":"0ff43992105faa06af25aaa00d81e66dd051236d6bb5c9da1ec6557715a5a482","reason":"no container with name or ID 0ff43992105faa06af25aaa00d81e66dd051236d6bb5c9da1ec6557715a5a482 found: no such container"}}
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
log: Container commit: Getting image source signatures

log: Container commit: Copying blob sha256:256a7af3acb11f89914205b6eef07e05e4196e898329575d97185758b450eb52

Copying blob sha256:a9de4d7ff3c298fdfec1106da7a6751b62da86dda6089558182a67177271a54c

log: Container commit: Copying config sha256:ac259b99cc6a9cd53856537b13529eecc65e9b9b0297ad697db7aeee5718eee4

log: Container commit: Writing manifest to image destination

Storing signatures

log: Container commit: Getting image source signatures

Copying blob sha256:6194458b07fcf01f1483d96cd6c34302ffff7f382bb151a6d023c4e80ba3050a

Copying blob sha256:0e9b36a20ddaa651b38e7ab42e343df75cd333400fd4f3e03b28f158ec6dea2f

log: Container commit: Copying config sha256:a37a19045ca35475d10d96a9b6976dd169c9ca3b3da58707f262131b61b283a0

log: Container commit: Writing manifest to image destination

Storing signatures


not ok 1 testBasic (__main__.TestApplication) # duration: 121s
```
First occurrence: 2019-07-09T12:45:33.809085 | revision 80298aafc629171346004908f0e1bb7cc54e510f
Times recorded: 1
Latest occurrences:

- 2019-07-09T12:45:33.809085 | revision 80298aafc629171346004908f0e1bb7cc54e510f

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestApplication)
#
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket

DevTools listening on ws://127.0.0.1:9850/devtools/browser/1381612f-f1a2-4a47-bc62-fe90f10227c6
[0713/075750.200632:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0713/075750.278835:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Failed to do Update Container: {"error":"io.podman.ContainerNotFound","parameters":{"id":"7e2dcf65c9fc10529c71e50416744327f978d03092a6f293a4b746856d985fe7","reason":"no container with name or ID 7e2dcf65c9fc10529c71e50416744327f978d03092a6f293a4b746856d985fe7 found: no such container"}}
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> log: Container commit: Getting image source signatures

Copying blob sha256:1bfeebd65323b8ddf5bd6a51cc7097b72788bc982e9ab3280d53d3c613adffa7

Copying blob sha256:b916d729bd874025110e63892be9c9c5db8663d4ff810b3cecc177d1e421f929

> log: Container commit: Copying config sha256:c4a5ead108af0cd468cca82ea717de393df7d27786529b732ee77da909b30b3b

> log: Container commit: Writing manifest to image destination

Storing signatures

> log: Container commit: Getting image source signatures

Copying blob sha256:6194458b07fcf01f1483d96cd6c34302ffff7f382bb151a6d023c4e80ba3050a

Copying blob sha256:be81f15dcac1f54c173da16c7e1e16cd086322b0da33026ade0d7440e1d2a342

> log: Container commit: Copying config sha256:665728ca7d3a96dc0097f62871c3945fe9d26b1b3cf584354326bd0aa4eaea8a

> log: Container commit: Writing manifest to image destination

Storing signatures

Wrote screenshot to TestApplication-testBasic-fedora-30-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestApplication-testBasic-fedora-30-127.0.0.2-2601-FAIL.html
Wrote JS log to TestApplication-testBasic-fedora-30-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestApplication-testBasic-fedora-30-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "test/check-application", line 126, in testBasic
    container_commit("test-sh")
  File "test/check-application", line 107, in container_commit
    b.wait_not_present(".modal-dialog div")
  File "test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present(".modal-dialog div")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 215, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 214, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '{"injectedScriptId":5,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1563004673685.8, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '1000007131.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Failed to do Update Container: {"error":"io.podman.ContainerNotFound","parameters":{"id":"7e2dcf65c9fc10529c71e50416744327f978d03092a6f293a4b746856d985fe7","reason":"no container with name or ID 7e2dcf65c9fc10529c71e50416744327f978d03092a6f293a4b746856d985fe7 found: no such container"}}
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
log: Container commit: Getting image source signatures

Copying blob sha256:1bfeebd65323b8ddf5bd6a51cc7097b72788bc982e9ab3280d53d3c613adffa7

Copying blob sha256:b916d729bd874025110e63892be9c9c5db8663d4ff810b3cecc177d1e421f929

log: Container commit: Copying config sha256:c4a5ead108af0cd468cca82ea717de393df7d27786529b732ee77da909b30b3b

log: Container commit: Writing manifest to image destination

Storing signatures

log: Container commit: Getting image source signatures

Copying blob sha256:6194458b07fcf01f1483d96cd6c34302ffff7f382bb151a6d023c4e80ba3050a

Copying blob sha256:be81f15dcac1f54c173da16c7e1e16cd086322b0da33026ade0d7440e1d2a342

log: Container commit: Copying config sha256:665728ca7d3a96dc0097f62871c3945fe9d26b1b3cf584354326bd0aa4eaea8a

log: Container commit: Writing manifest to image destination

Storing signatures


not ok 1 testBasic (__main__.TestApplication) # duration: 124s
```
First occurrence: 2019-07-13T07:59:31.618960 | revision fa24ac97fe81cf2c0b9b54db2830ad97fd78a759
Times recorded: 1
Latest occurrences:

- 2019-07-13T07:59:31.618960 | revision fa24ac97fe81cf2c0b9b54db2830ad97fd78a759
