### ISSUE TITLE
SELinux is preventing sssd_be and cockpit_ssh from search access to krb5

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#12355]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1731066

Messages like:

```
audit: type=1400 audit(1563371925.700:5): avc:  denied  { search } for  pid=1904 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0

audit: type=1400 audit(1563372302.428:5): avc:  denied  { search } for  pid=2019 comm="cockpit-ssh" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:cockpit_session_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
```

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpaUnqualifiedUsers (check_realms.TestRealms)
#
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2019-05-18 22:23:23
    Valid Until: 2039-05-18 22:23:23

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
This program will set up IPA client.
Version 4.8.0


Using default chrony configuration.
Client configuration complete.
The ipa-client-install command was successful
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * Successfully enrolled machine in realm
su: warning: cannot change directory to /home/admin: Permission denied
id: cannot find name for group ID 71600000
-bash: /home/admin/.bash_profile: Permission denied

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
su: warning: cannot change directory to /home/admin: Permission denied
-bash: /home/admin/.bash_profile: Permission denied

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: 
DevTools listening on ws://127.0.0.1:9407/devtools/browser/a9cc03b3-624e-4931-96fa-7105b689c299
[0718/095024.095046:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0718/095024.096675:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Shutdown scheduled for Thu 2019-07-18 05:50:34 EDT, use 'shutdown -c' to cancel.

> warning: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
kex_exchange_identification: read: Connection reset by peer
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"9"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"10"}
Unexpected journal messages:
audit: type=1400 audit(1563443404.191:5): avc:  denied  { search } for  pid=1811 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1563443417.170:6): avc:  denied  { search } for  pid=1947 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-rhel-8-1-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-rhel-8-1-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2902-FAIL.log
Wrote screenshot to TestRealms-testIpaUnqualifiedUsers-rhel-8-1-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestRealms-testIpaUnqualifiedUsers-rhel-8-1-127.0.0.2-2901-FAIL.html
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-rhel-8-1-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-rhel-8-1-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2902-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 781, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 955, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1563443404.191:5): avc:  denied  { search } for  pid=1811 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0

not ok 144 testIpaUnqualifiedUsers (check_realms.TestRealms) # duration: 141s
```
First occurrence: 2019-07-18T09:51:08.829003 | revision ac5e242dc7125930d238ddc887ae41b00b3d58c4
Times recorded: 1
Latest occurrences:

- 2019-07-18T09:51:08.829003 | revision ac5e242dc7125930d238ddc887ae41b00b3d58c4

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNegotiate (check_realms.TestKerberos)
#
++ seq 1 20
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ break
+ echo foobarfoo
+ realm join -vU admin cockpit.lan
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2019-05-18 22:23:23
    Valid Until: 2039-05-18 22:23:23

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
This program will set up IPA client.
Version 4.8.0


Using default chrony configuration.
Client configuration complete.
The ipa-client-install command was successful
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * Successfully enrolled machine in realm
++ seq 1 20
+ for x in $(seq 1 20)
+ echo foobarfoo
+ KRB5_TRACE=/dev/stderr
+ kinit -f admin@COCKPIT.LAN
[1996] 1563443441.433273: Getting initial credentials for admin@COCKPIT.LAN
[1996] 1563443441.433275: Sending unauthenticated request
[1996] 1563443441.433276: Sending request (183 bytes) to COCKPIT.LAN
[1996] 1563443441.433277: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[1996] 1563443441.433278: No URI records found
[1996] 1563443441.433279: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[1996] 1563443441.433280: SRV answer: 0 100 88 "f0.cockpit.lan."
[1996] 1563443441.433281: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[1996] 1563443441.433282: SRV answer: 0 100 88 "f0.cockpit.lan."
[1996] 1563443441.433283: Resolving hostname f0.cockpit.lan.
[1996] 1563443441.433284: Resolving hostname f0.cockpit.lan.
[1996] 1563443441.433285: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[1996] 1563443441.433286: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[1996] 1563443441.433287: Initiating TCP connection to stream 172.27.0.15:88
[1996] 1563443441.433288: Terminating TCP connection to stream 172.27.0.15:88
[1996] 1563443441.433289: Initiating TCP connection to stream 10.111.112.100:88
[1996] 1563443441.433290: Sending TCP request to stream 10.111.112.100:88
[1996] 1563443441.433291: Received answer (524 bytes) from stream 10.111.112.100:88
[1996] 1563443441.433292: Terminating TCP connection to stream 10.111.112.100:88
[1996] 1563443441.433293: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[1996] 1563443441.433294: No URI records found
[1996] 1563443441.433295: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[1996] 1563443441.433296: SRV answer: 0 100 88 "f0.cockpit.lan."
[1996] 1563443441.433297: Response was from master KDC
[1996] 1563443441.433298: Received error from KDC: -1765328359/Additional pre-authentication required
[1996] 1563443441.433301: Preauthenticating using KDC method data
[1996] 1563443441.433302: Processing preauth types: PA-PK-AS-REQ (16), PA-PK-AS-REP_OLD (15), PA-PK-AS-REQ_OLD (14), PA-FX-FAST (136), PA-ETYPE-INFO2 (19), PA-PKINIT-KX (147), PA-SPAKE (151), PA-ENC-TIMESTAMP (2), PA_AS_FRESHNESS (150), PA-FX-COOKIE (133)
[1996] 1563443441.433303: Selected etype info: etype aes256-cts, salt "uo@TM5S:>{^U$TVM", params ""
[1996] 1563443441.433304: Received cookie: MIT1\x00\x00\x00\x01\xd0Z\xadxa\x83\xa1[\xb7\xe2\xc5#o\xd4\xc1.\xb3\xa2\x890\xba\xef\xd4!\xaa5\xde(\xf7\xc3\x80}[\x84s\x07\x90<\xcdfZ\xdb!\x84\xcd6U\xab\xa8}9\x8d\xfb(\xef\x17jR\xafA\xaf{q\xcf\x8c:\x9e\xa7R\xc4\x0c!\x1f\xf0\x90\xde~\xb2\xc7\xab\x06\xfc\xe3'\xe1\xa1\xc5\xa7\xb0+s;\x89C=\xa4B\x84\x03\x82\xfc\x1dCW\xb8\xc3\x9c\xfaZ\xa8\xf1\xb2\xf7$Z\xcc\xf4\x89!\x03\x83\xd7DV6\xd4\x19E\xe2\xfc
[1996] 1563443441.433305: SPAKE challenge received with group 1, pubkey 46A132AAD9E74A20FCA6FE07C67CF1CAD8324537EA71476979926CFD133B4D50
[1996] 1563443441.433306: SPAKE key generated with pubkey 00ACDB16DFD175EEF50806BF05D66F90DB0654DA3A01A5778FD0242001620D0F
[1996] 1563443441.433307: SPAKE algorithm result: 4D0702FF328CAB33AA47B6C07327C79AECCBDBAF9ACDD8254ECC190A017E334B
[1996] 1563443441.433308: SPAKE final transcript hash: CFED66600544E274BDB832878A9A24376CCB1322A1BBD57485AD297F71AFA984
[1996] 1563443441.433309: Sending SPAKE response
[1996] 1563443441.433310: Preauth module spake (151) (real) returned: 0/Success
[1996] 1563443441.433311: Produced preauth for next request: PA-FX-COOKIE (133), PA-SPAKE (151)
[1996] 1563443441.433312: Sending request (442 bytes) to COCKPIT.LAN
[1996] 1563443441.433313: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[1996] 1563443441.433314: No URI records found
[1996] 1563443441.433315: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[1996] 1563443441.433316: SRV answer: 0 100 88 "f0.cockpit.lan."
[1996] 1563443441.433317: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[1996] 1563443441.433318: SRV answer: 0 100 88 "f0.cockpit.lan."
[1996] 1563443441.433319: Resolving hostname f0.cockpit.lan.
[1996] 1563443441.433320: Resolving hostname f0.cockpit.lan.
[1996] 1563443441.433321: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[1996] 1563443441.433322: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[1996] 1563443441.433323: Initiating TCP connection to stream 172.27.0.15:88
[1996] 1563443441.433324: Terminating TCP connection to stream 172.27.0.15:88
[1996] 1563443441.433325: Initiating TCP connection to stream 10.111.112.100:88
[1996] 1563443441.433326: Sending TCP request to stream 10.111.112.100:88
[1996] 1563443441.433327: Received answer (724 bytes) from stream 10.111.112.100:88
[1996] 1563443441.433328: Terminating TCP connection to stream 10.111.112.100:88
[1996] 1563443441.433329: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[1996] 1563443441.433330: No URI records found
[1996] 1563443441.433331: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[1996] 1563443441.433332: SRV answer: 0 100 88 "f0.cockpit.lan."
[1996] 1563443441.433333: Response was from master KDC
[1996] 1563443441.433334: Processing preauth types: PA-ETYPE-INFO2 (19)
[1996] 1563443441.433335: Selected etype info: etype aes256-cts, salt "uo@TM5S:>{^U$TVM", params ""
[1996] 1563443441.433336: Produced preauth for next request: (empty)
[1996] 1563443441.433337: AS key determined by preauth: aes256-cts/F5CF
[1996] 1563443441.433338: Decrypted AS reply; session key is: aes256-cts/CE55
[1996] 1563443441.433339: FAST negotiation: available
[1996] 1563443441.433340: Initializing KCM:0 with default princ admin@COCKPIT.LAN
[1996] 1563443441.433341: Storing admin@COCKPIT.LAN -> krbtgt/COCKPIT.LAN@COCKPIT.LAN in KCM:0
[1996] 1563443441.433342: Storing config in KCM:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: fast_avail: yes
[1996] 1563443441.433343: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/fast_avail/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KCM:0
[1996] 1563443441.433344: Storing config in KCM:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: pa_type: 151
[1996] 1563443441.433345: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/pa_type/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KCM:0
+ break
+ locale -a
+ grep -iq '^C\.utf'
+ loc=C.UTF-8
+ type ipa
+ LC_ALL=C.UTF-8
+ ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN
+ ipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab
+ sed -i '/^sudoers:/ s/files sss/sss files/' /etc/nsswitch.conf
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin
+ break
+ getent passwd admin
+ chown -R admin /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin x0.cockpit.lan true
Warning: Permanently added 'x0.cockpit.lan' (ECDSA) to the list of known hosts.
Connection closed by UNKNOWN port 65535
+ sss_cache -E
+ systemctl restart sssd.service
+ sleep 1
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin x0.cockpit.lan true
+ break

DevTools listening on ws://127.0.0.1:10035/devtools/browser/0abecd5e-4da3-46b9-a2dc-e8e86dd45991
[0718/095056.346042:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0718/095056.347808:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

Unexpected journal messages:
audit: type=1400 audit(1563443438.021:5): avc:  denied  { search } for  pid=1899 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1563443446.578:6): avc:  denied  { search } for  pid=2029 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
Journal extracted to TestKerberos-testNegotiate-rhel-8-1-127.0.0.2-2601-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2602-FAIL.log
Journal extracted to TestKerberos-testNegotiate-rhel-8-1-127.0.0.2-2601-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2602-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 781, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 955, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1563443438.021:5): avc:  denied  { search } for  pid=1899 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0

not ok 140 testNegotiate (check_realms.TestKerberos) # duration: 116s
```
First occurrence: 2019-07-18T09:51:16.820798 | revision ac5e242dc7125930d238ddc887ae41b00b3d58c4
Times recorded: 1
Latest occurrences:

- 2019-07-18T09:51:16.820798 | revision ac5e242dc7125930d238ddc887ae41b00b3d58c4

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#

DevTools listening on ws://127.0.0.1:9632/devtools/browser/925ca666-908a-478f-aaba-5e7fc43b0617
[0718/094921.159346:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0718/094921.161255:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1001' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Warning: Permanently added 'x0.cockpit.lan' (ECDSA) to the list of known hosts.
Connection closed by UNKNOWN port 65535
+ sss_cache -E
+ systemctl restart sssd.service
+ sleep 1
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sss_cache -E
+ systemctl restart sssd.service
+ sleep 2
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sss_cache -E
+ systemctl restart sssd.service
+ sleep 3
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
Can't use SSL_get_servername
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: # Warning: cockpit.service changed on disk, the version systemd has loaded is outdated.
# This output shows the current version of the unit's original fragment and drop-in files.
# If fragments or drop-ins were added or removed, they are not properly reflected in this output.
# Run 'systemctl daemon-reload' to reload units.
Failed to cat /etc/systemd/system/cockpit.service.d/notls.conf: No such file or directory
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Removing principal HTTP/x0.cockpit.lan@COCKPIT.LAN

> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> log: Failed to join domain: cockpit.lan: Already running another action
Unexpected journal messages:
audit: type=1400 audit(1563443408.827:5): avc:  denied  { search } for  pid=3799 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1563443416.540:6): avc:  denied  { search } for  pid=4661 comm="ipa-submit" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1563443417.221:7): avc:  denied  { search } for  pid=4703 comm="ipa-submit" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1563443417.222:8): avc:  denied  { search } for  pid=4703 comm="ipa-submit" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1563443434.077:9): avc:  denied  { search } for  pid=4819 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
Wrote JS log to TestRealms-testIpa-rhel-8-1-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestRealms-testIpa-rhel-8-1-127.0.0.2-2801-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2802-FAIL.log
Wrote screenshot to TestRealms-testIpa-rhel-8-1-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestRealms-testIpa-rhel-8-1-127.0.0.2-2801-FAIL.html
Wrote JS log to TestRealms-testIpa-rhel-8-1-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestRealms-testIpa-rhel-8-1-127.0.0.2-2801-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2802-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 781, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 955, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1563443408.827:5): avc:  denied  { search } for  pid=3799 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0

not ok 143 testIpa (check_realms.TestRealms) # duration: 171s
```
First occurrence: 2019-07-18T09:51:47.470844 | revision ac5e242dc7125930d238ddc887ae41b00b3d58c4
Times recorded: 1
Latest occurrences:

- 2019-07-18T09:51:47.470844 | revision ac5e242dc7125930d238ddc887ae41b00b3d58c4
