### ISSUE TITLE
ubuntu-1804: Manual IPv6 routes are not set

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#12369]
Downstream report: https://launchpad.net/bugs/1837233

**Comment by martinpitt** [comment]
verify/ubuntu-1804
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (__main__.TestNetworking)
#
NAME                UUID                                  TYPE      DEVICE 
Wired connection 1  cc94f4e1-a94e-342e-87eb-e06312d0a7c7  ethernet  eth1   
virbr0              03a03dd4-2fa2-4975-94d0-e38e2eeadbb3  bridge    virbr0 

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2

DevTools listening on ws://127.0.0.1:9575/devtools/browser/a2b73a51-5a46-45e2-aafe-27eaef09eb6c
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


(process:6689): GLib-GIO-WARNING **: 12:08:30.961: ../../../../gio/gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP4Config/7 but no object proxy exists

(process:6689): GLib-GIO-WARNING **: 12:08:30.963: ../../../../gio/gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP6Config/7 but no object proxy exists
Wrote screenshot to TestNetworking-testOtherSettings-ubuntu-1804-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-ubuntu-1804-127.0.0.2-2201-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-ubuntu-1804-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-ubuntu-1804-127.0.0.2-2201-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-30-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-networking-settings", line 130, in testOtherSettings
    wait(lambda: "metric 42" in m.execute(show_cmd))
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 1464, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

not ok 1 testOtherSettings (__main__.TestNetworking) # duration: 99s
```
First occurrence: 2019-07-19T18:09:37.268753
Times recorded: 1
Latest occurrences:

- 2019-07-19T18:09:37.268753

**Comment by martinpitt** [comment]
Turns out that using a bogus address  doesn't work, an existing address does. This is somewhere in between "bug" and "intended", so closing this. I adjusted the test case to work everywhere.
