### ISSUE TITLE
SELinux is preventing qemu-kvm to access /proc when running in tcg mode

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#12405]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1732500
Messages be like:
```
avc: denied { search } for pid=6542 comm="^Cmu-kvm" name="1636" dev="proc" ino=33592 scontext=system_u:system_r:svirt_tcg_t:s0:c638,c665 tcontext=system_u:system_r:virtd_t:s0-s0:c0.c1023 tclass=dir permissive=0
```

**Comment by marusak** [comment]
I believe that https://github.com/cockpit-project/cockpit/blob/master/test/verify/machineslib.py#L270 should catch this, right?

**Comment by KKoukiou** [comment]
> I believe that https://github.com/cockpit-project/cockpit/blob/master/test/verify/machineslib.py#L270 should catch this, right?

Actually the test does reach that line always.
The thing is that this selinux denial makes the tests actually fail much earlier. In general we don't check the journal messages for fails tests, but for this one specifically I do, because most of the failures are caused by external issues.

See https://github.com/cockpit-project/cockpit/blob/master/test/verify/machineslib.py#L205

So what I can do, is remove that line from the end of the test and add the naughy.

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreate (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9347/devtools/browser/671ceacf-97c1-42f1-8cfe-f092f210f437
[0723/143727.359315:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0723/143727.361293:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

    *
    * validation errors and ui info/warn messages expected:
    * 
> warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Operation not supported (15)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Operation not supported (15)
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
{"exceptionId":8,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$950dbd78d7ccba34b587f4c9a5856728604091c1d0053f0bb4799b3aa0ea4363/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate14-state not found"},"executionContextId":7}
{"exceptionId":10,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$950dbd78d7ccba34b587f4c9a5856728604091c1d0053f0bb4799b3aa0ea4363/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate15-state not found"},"executionContextId":7}
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)
> warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
{"exceptionId":12,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$950dbd78d7ccba34b587f4c9a5856728604091c1d0053f0bb4799b3aa0ea4363/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate18-state not found"},"executionContextId":7}
{"exceptionId":14,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$950dbd78d7ccba34b587f4c9a5856728604091c1d0053f0bb4799b3aa0ea4363/machines/index.html#/","exception":{"type":"string","value":"#vm-subVmTestCreate19-state not found"},"executionContextId":7}
> warning: Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_6aa80cba_8f07_40ff_85c3_19fdaa5cfa29 
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
> warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_f3589632_e63d_400c_8aaf_9812bdda3533 
> warning: ERROR    End of file while reading data: Input/output error
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate21
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    End of file while reading data: Input/output error\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate21\notherwise, please restart your installation."}", data: """"
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Unexpected journal messages:
Process 1633 (libvirtd) of user 0 dumped core.
Stack trace of thread 1638:
#0  0x00007f885b1c0b2f virDomainDefFree (libvirt.so.0)
#1  0x00007f882de48cde qemuDomainDefineXMLFlags (libvirt_driver_qemu.so)
#2  0x00007f885b3136ef virDomainDefineXML (libvirt.so.0)
#3  0x000055fb2dc5d340 remoteDispatchDomainDefineXMLHelper (libvirtd)
#4  0x00007f885b24c034 virNetServerProgramDispatch (libvirt.so.0)
#5  0x00007f885b2524ec virNetServerHandleJob (libvirt.so.0)
#6  0x00007f885b181ff0 virThreadPoolWorker (libvirt.so.0)
#7  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#8  0x00007f8857ff12de start_thread (libpthread.so.0)
#9  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1634:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1635:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1636:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1637:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1639:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b182084 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1640:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b182084 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1641:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b182084 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1642:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b182084 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1643:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b182084 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1644:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1645:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1646:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1647:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1648:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f885b1820d3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f885b1812fc virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1732:
#0  0x00007f8857ff747c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f885b18159a virCondWait (libvirt.so.0)
#2  0x00007f882e96d0e4 udevEventHandleThread (libvirt_driver_nodedev.so)
#3  0x00007f885b18132a virThreadHelper (libvirt.so.0)
#4  0x00007f8857ff12de start_thread (libpthread.so.0)
#5  0x00007f8857d22463 __clone (libc.so.6)
Stack trace of thread 1633:
#0  0x00007f8857d171e1 __poll (libc.so.6)
#1  0x00007f885b124025 virEventPollRunOnce (libvirt.so.0)
#2  0x00007f885b122ba5 virEventRunDefaultImpl (libvirt.so.0)
#3  0x00007f885b251d4d virNetDaemonRun (libvirt.so.0)
#4  0x000055fb2dc30773 main (libvirtd)
#5  0x00007f8857c49843 __libc_start_main (libc.so.6)
#6  0x000055fb2dc31a4e _start (libvirtd)
audit: type=1400 audit(1563892750.529:5): avc:  denied  { search } for  pid=5390 comm="qemu-kvm" name="1633" dev="proc" ino=33649 scontext=system_u:system_r:svirt_tcg_t:s0:c310,c833 tcontext=system_u:system_r:virtd_t:s0-s0:c0.c1023 tclass=dir permissive=0
audit: type=1400 audit(1563892762.766:6): avc:  denied  { search } for  pid=6247 comm="qemu-kvm" name="1633" dev="proc" ino=33649 scontext=system_u:system_r:svirt_tcg_t:s0:c138,c295 tcontext=system_u:system_r:virtd_t:s0-s0:c0.c1023 tclass=dir permissive=0
Wrote JS log to TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.log
Core dumps downloaded to /build/cockpit/TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.core
Wrote screenshot to TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.log
Core dumps downloaded to /build/cockpit/TestMachinesDBus-testCreate-rhel-8-1-127.0.0.2-2301-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/test/verify/machineslib.py", line 1464, in testCreate
    start_vm=True,))
  File "/build/cockpit/test/verify/machineslib.py", line 1270, in createTest
    runner.deleteVm(dialog) \
  File "/build/cockpit/test/verify/machineslib.py", line 2153, in deleteVm
    b.wait_not_present("#vm-{0}-delete-modal-dialog".format(dialog.name))
  File "/build/cockpit/test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTestCreate21-delete-modal-dialog")): {'exceptionId': 15, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '641', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '641', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '641', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":10,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1563892647972.52, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '1000103341.8'}
info: index.js: Setting LibvirtDBus as virt provider.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

info: index.js: Setting LibvirtDBus as virt provider.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
warning: Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Operation not supported (15)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Operation not supported (15)
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
warning: Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)
warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
warning: Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)
warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_6aa80cba_8f07_40ff_85c3_19fdaa5cfa29 
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

info: index.js: Setting LibvirtDBus as virt provider.
warning: Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
warning: GET_VM action failed failed for path /org/libvirt/QEMU/domain/_f3589632_e63d_400c_8aaf_9812bdda3533 
warning: ERROR    End of file while reading data: Input/output error
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate21
otherwise, please restart your installation.

info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    End of file while reading data: Input/output error\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate21\notherwise, please restart your installation."}", data: """"
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]

not ok 167 testCreate (check_machines_dbus.TestMachinesDBus) # duration: 206s
Traceback (most recent call last):
  File "/build/cockpit/test/verify/machineslib.py", line 209, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 956, in check_journal_messages
    raise Error(first)
testlib.Error: Process 1633 (libvirtd) of user 0 dumped core.

not ok 167 testCreate (check_machines_dbus.TestMachinesDBus) # duration: 206s
```
First occurrence: 2019-07-23T14:40:33.824115 | revision e50c78297907c19d6839b832bc8239e452f252e1
Times recorded: 1
Latest occurrences:

- 2019-07-23T14:40:33.824115 | revision e50c78297907c19d6839b832bc8239e452f252e1
