### ISSUE TITLE
Unix listener path too long for Unix domain socket - breaks `make check` from running in Jenkins workspace

### ISSUE THREAD

**Issue by tarnjotsingh** [cockpit-project/cockpit#12482]
Cockpit version: 197.1
OS: Fedora Server 30
Page: 

A recent change to [bots/machine/machine_core/ssh_connection.py](https://github.com/cockpit-project/cockpit/commit/385b7b592ded8e09feae4289d86f6f4e4175d66d) causes `make check` (from the starter project) to fail when running in a Jenkins workspace environment.
This is due to there being a [104/108 character limit](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars) being in place for the socket path length.

Run `make check` from a directory that is somewhat far into the file system (such as a Jenkins workspace).

```
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.35bDJq
+ umask 022
+ cd /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/rpmbuild
+ '[' /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64 '!=' / ']'
+ rm -rf /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64
++ dirname /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64
+ mkdir -p /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build
+ mkdir /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64
+ cd cs-cockpit-plugins
+ /usr/bin/make install DESTDIR=/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64 'INSTALL=/usr/bin/install -p'
make[1]: Entering directory '/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/rpmbuild/cs-cockpit-plugins'
mkdir -p /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64/usr/share/cockpit/cs-cockpit-plugins
cp -r dist/* /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64/usr/share/cockpit/cs-cockpit-plugins
mkdir -p /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64/usr/share/metainfo/
cp org.clearswift.cs-cockpit-plugins.metainfo.xml /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64/usr/share/metainfo/
make[1]: Leaving directory '/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/rpmbuild/cs-cockpit-plugins'
+ appstream-util validate-relax --nonet /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64//usr/share/metainfo/org.clearswift.cs-cockpit-plugins.metainfo.xml
/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64//usr/share/metainfo/org.clearswift.cs-cockpit-plugins.metainfo.xml: OK
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1 0
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
Processing files: cs-cockpit-plugins-0.2.2-1.fc30.noarch
Provides: cs-cockpit-plugins = 0.2.2-1.fc30 metainfo() metainfo(org.clearswift.cs-cockpit-plugins.metainfo.xml)
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64
Wrote: /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/output/noarch/cs-cockpit-plugins-0.2.2-1.fc30.noarch.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.C7cKNI
+ umask 022
+ cd /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/rpmbuild
+ cd cs-cockpit-plugins
+ /usr/bin/rm -rf /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/build/cs-cockpit-plugins-0.2.2-1.fc30.x86_64
+ exit 0
find `pwd`/output -name '*.rpm' -printf '%f\n' -exec mv {} . \;
cs-cockpit-plugins-0.2.2-1.fc30.noarch.rpm
rm -r "`pwd`/rpmbuild"
rm -r "`pwd`/output" "`pwd`/build"
git fetch --depth=1 https://github.com/cockpit-project/cockpit.git
warning: no common commits
From https://github.com/cockpit-project/cockpit
 * branch            HEAD       -> FETCH_HEAD
git checkout --force FETCH_HEAD -- bots/
git reset bots
rm -f /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/test/images/centos-7 /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/test/images/centos-7.qcow2
bots/image-customize -v -i cockpit -i `pwd`/cs-cockpit-plugins-*.noarch.rpm -s /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/test/vm.install centos-7
 > https://8.43.84.246:443/
 x https://209.132.184.41:8493/
 > https://8.43.84.246:443/centos-7-922bac1abc825856411290cd776361b648175c0d8a47c39566699a5cc0a3f303.qcow2
Waiting for concurrent image-download of centos-7-922bac1abc825856411290cd776361b648175c0d8a47c39566699a5cc0a3f303.qcow2...
libvirt: XML-RPC error : Failed to connect socket to '/run/user/1000/libvirt/libvirt-sock': No such file or directory
c5e92cd7-6f4c-458f-8c87-2c2f56bcc4bd
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.BeH9ab3zVszWrw5I" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.0iUuEkyutUdNZYMc" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.4rIuL6DDZZu2iMim" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.hHYIR25L4HV8RjxD" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.8W4UBIZ5YUtAZf6X" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.66RtG6YD0EmlsNqj" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.UtRtYv1sKmhU1ove" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.lXD1wiCL708BaB5I" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.3bIMyApLBieDnlxW" too long for Unix domain socket
unix_listener: path "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/tmp/ssh-127.0.0.2-2201-root-2432.3x5xg0HLsUbFHR3A" too long for Unix domain socket
+ ! test -f /run/nologin && cat /proc/sys/kernel/random/boot_id
ssh: connection refused, trying again
ssh: connection refused, trying again
ssh: connection refused, trying again
ssh: connection refused, trying again
ssh: connection refused, trying again
ssh: connection refused, trying again
ssh: connection refused, trying again
ssh: connection refused, trying again
ssh: connection refused, trying again
Traceback (most recent call last):
  File "bots/image-customize", line 143, in <module>
    install_packages(machine, args.packagelist, args.installcommand)
  File "bots/image-customize", line 121, in install_packages
    machine_instance.upload([foo], "/var/tmp/" + pname)
  File "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/bots/machine/machine_core/machine.py", line 125, in upload
    super(Machine, self).upload(sources, dest, relative_dir)
  File "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/bots/machine/machine_core/ssh_connection.py", line 358, in upload
    self._ensure_ssh_master()
  File "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/bots/machine/machine_core/ssh_connection.py", line 232, in _ensure_ssh_master
    self._start_ssh_master()
  File "/var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/bots/machine/machine_core/ssh_connection.py", line 183, in _start_ssh_master
    raise exceptions.Failure("SSH master process exited with code: {0}".format(proc.returncode))
machine_core.exceptions.Failure: SSH master process exited with code: 255
make: *** [Makefile:160: /var/lib/jenkins/workspace/latform_cs-cockpit-plugins_PR-61/test/images/centos-7] Error 1
```

**Comment by martinpitt** [comment]
As a workaround you can set `export TEST_DATA=/tmp/cockpit/` or a similarly short path.

**Comment by tarnjotsingh** [comment]
Thanks for the suggestion, appreciate the quick response.
