### ISSUE TITLE
kexec: failed to load kdump kernel in 4.18.0-131 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#12597]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1740443

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_kdump.TestKdump)
#
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.

DevTools listening on ws://127.0.0.1:9919/devtools/browser/fca3904d-279e-4653-9585-511c05973149
[0819/090320.082820:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0819/090320.084621:ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestKdump-testBasic-rhel-8-1-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestKdump-testBasic-rhel-8-1-127.0.0.2-2601-FAIL.html
Wrote JS log to TestKdump-testBasic-rhel-8-1-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-8-1-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 87, in testBasic
    b.wait_in_text("#app", "Service is running")
  File "/build/cockpit/test/common/testlib.py", line 382, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#app","Service is running")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":6,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1566205401495.73, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '1000112927.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]

not ok 52 testBasic (check_kdump.TestKdump) # duration: 150s
```
First occurrence: 2019-08-19T09:05:23.861857 | revision afef82f00ebfa89ab820186d87ee942a586578b0
Times recorded: 1
Latest occurrences:

- 2019-08-19T09:05:23.861857 | revision afef82f00ebfa89ab820186d87ee942a586578b0
