### ISSUE TITLE
Selinux prevents setting timezone via timedatectl, prevents write to /etc/localtime

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12721]
OS: fedora-31

Selinux prevents setting timezone via timedatectl.

```
timedatectl set-timezone Europe/Helsinki

> Failed to set time zone: Failed to update /etc/localtime

audit: type=1400 audit(1567689788.617:317): avc:  denied  { write } for  pid=7096 comm="timedatex" name="etc" dev="dm-0" ino=130051 scontext=system_u:system_r:timedatex_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=dir permissive=0
```

https://bugzilla.redhat.com/show_bug.cgi?id=1749375

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTime (check_system_info.TestSystemInfo)
#
[0;1;31mFailed to set time zone: Failed to update /etc/localtime[0m
Journal extracted to TestSystemInfo-testTime-fedora-31-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-system-info", line 247, in testTime
    m.execute("timedatectl set-timezone Europe/Helsinki")
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'timedatectl set-timezone Europe/Helsinki' returned non-zero exit status 1.

not ok 209 testTime (check_system_info.TestSystemInfo) # duration: 19s
```
First occurrence: 2019-09-05T18:18:53.514495 | revision 67b99f79dc9f4de30e48a0886ec6d7324072b171
Times recorded: 1
Latest occurrences:

- 2019-09-05T18:18:53.514495 | revision 67b99f79dc9f4de30e48a0886ec6d7324072b171
