### ISSUE TITLE
build fails on RHEL 7 missing gio

### ISSUE THREAD

**Issue by llamafilm** [cockpit-project/cockpit#12731]
Cockpit version: 202
OS: RHEL 7.7

The RHEL repo includes an old version of cockpit 195 so I am trying to install the latest 202.  Trying to compile the source I get an error about missing gio-2.0 and gio-unix-2.0.  What is needed exactly?  I already have gio 2.56

```
$  ./configure 
checking that PACKAGE_VERSION is properly set... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for ranlib... ranlib
checking for library containing strerror... none required
checking for ANSI C header files... (cached) yes
checking whether ln -s works... yes
checking size of void *... 8
checking whether make supports nested variables... (cached) yes
checking whether to install to prefix only... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GIO... no
configure: error: Package requirements (gio-unix-2.0 >= 2.37.4 gio-2.0 >= 2.37.4) were not met:

No package 'gio-unix-2.0' found
No package 'gio-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GIO_CFLAGS
and GIO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

$ which gio
/usr/bin/gio
$ gio --version
2.56.1
```

**Comment by martinpitt** [comment]
Most likely you are missing the `glib2-devel` package. Seems easiest to `yum builddep cockpit`.

**Comment by llamafilm** [comment]
Thanks.  Installing glib2-devel does help, but it looks like there are loads of other dependencies.

`yum-builddep cockpit` fails with this:

```
Error: No Package found for go-toolset-7-golang-bin
Error: No Package found for go-toolset-7-golang-src
```

I read that this is in the RedHat Developer Tools repo, but I don't have access to this with my self-support subscription.  I did install golang 1.11.5 from epel, is that different than go-toolset ?

**Comment by martinpitt** [comment]
Ah, sorry about the troubles with go -- unfortunately the Go packaging is rather messy in RHEL/CentOS 7. Also, you don't need these at all any more to build recent cockpit. You can look into tools/cockpit.spec to see which ones you need.

**Comment by llamafilm** [comment]
Great, so I've installed all the dependencies from `cockpit.spec`.  I also had to install `npm` for `autogen.sh` to work, so maybe that should be listed as a dependency.  Now autogen completes successfully and I have this error with `make`:

```
ERROR in ./pkg/apps/index.jsx
Module build failed (from ./node_modules/eslint-loader/dist/cjs.js):
/root/cockpit/node_modules/eslint-loader/dist/getOptions.js:19
    ..._loaderUtils.default.getOptions(loaderContext)
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/cockpit/node_modules/eslint-loader/dist/index.js:8:42)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
 @ multi ./pkg/apps/index.jsx apps/apps[0]
make[1]: *** [dist/apps/stamp] Error 1
make[1]: Leaving directory `/root/cockpit'
make: *** [all] Error 2
```

I think this happens because the [rest spread operator](https://github.com/tc39/proposal-object-rest-spread) is fairly new syntax in Javascript and not yet part of ECMAScript spec.  How can I make this compile?

**Comment by martinpitt** [comment]
@llamafilm : you don't need npm if you build from the officially released tarballs. This will skip all the webpack stuff as it's pre-built in the release tarballs; otherwise you'll need a whole lot more  to build things. Not  sure what happens on your system,  this is normally being transpiled by babel in the webpack config.

**Comment by llamafilm** [comment]
But the 202 tarball doesn't compile due to bug #12713.  I just read there you dropped support for RHEL 7, is that really true?  RHEL 8 was just released last month, that seems hasty.

**Comment by martinpitt** [comment]
@llamafilm : We'll do a 203 release tomorrow due to [some major CSS regression](https://bugzilla.redhat.com/show_bug.cgi?id=1749586), which will also include that gnutls compile fix.

We maintain RHEL 7 support in the [rhel-7.x branches](https://github.com/cockpit-project/cockpit/branches), but not on master any more. We also cut releases from that, like 195.x.

**Comment by llamafilm** [comment]
Oh, thank you I hadn't seen the other branches.  I guess I'll stick to that, to avoid future issues
