### ISSUE TITLE
Denied NetworkManager write to /var/tmp/dracut.*/systemd-cat while generating initrd image

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12744]
https://bugzilla.redhat.com/show_bug.cgi?id=1750428

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_kdump.TestKdump)
#
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.

DevTools listening on ws://127.0.0.1:9801/devtools/browser/642ad9af-3d22-4761-acab-c8ed4a1c1f42
[0909/154205.055873:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0909/154205.067799:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[0909/154205.076112:WARNING:gpu_process_host.cc(1205)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: transport closed: disconnected
Unexpected journal messages:
audit: type=1400 audit(1568043945.886:503): avc:  denied  { write } for  pid=15284 comm="NetworkManager" path="/var/tmp/dracut.6iIn9M/systemd-cat" dev="dm-0" ino=139022 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-fedora-31-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-31-127.0.0.2-2301-FAIL.log
Wrote screenshot to TestKdump-testBasic-fedora-31-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-31-127.0.0.2-2301-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-31-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-31-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 785, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 959, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1568043945.886:503): avc:  denied  { write } for  pid=15284 comm="NetworkManager" path="/var/tmp/dracut.6iIn9M/systemd-cat" dev="dm-0" ino=139022 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0

not ok 26 testBasic (check_kdump.TestKdump) # duration: 382s
```
First occurrence: 2019-09-09T15:47:59.363274 | revision ed0e575d5eec9496e85e9d3fba20fd1e3db6fedc
Times recorded: 1
Latest occurrences:

- 2019-09-09T15:47:59.363274 | revision ed0e575d5eec9496e85e9d3fba20fd1e3db6fedc
