### ISSUE TITLE
firewall: Mismatch between cockpit page and the cli 

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12759]
Cockpit version: 201
OS: rhel-8-1
Page: network/firewall

There's a mismatch sometimes between the cli and the cockpit page. The libvirt zone doesn't appear. 

There seems to be a lag between the enabling of the firewall and the being active of the libvirt zone (this is also visible on the cli). Yet the firewall page only gets the signal that firewalld was enabled, and not that the libvirt zone is now active.

There doesn't seem to be any usable signal to listen for activation of the libvirt zone (the "InterfaceAdded" and "SourceAdded" signals don't get fired).

Steps to reproduce:
1. stop firewalld from the cli
2. go to the firewall page, and enable the service
3. No libvirt zone? After waiting a little, it's enabled on the cli, but the page doesn't get updated.

I asked a question here: https://bugzilla.redhat.com/show_bug.cgi?id=1750816

When doing the shell test on fedora-31, it's also visible there. However the fedora 31 tests do no seem to be failing in the same way, maybe the timings are different, and there cockpit is slow enough to catch all active zones?

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFirewallPage (check_networking_firewall.TestFirewall)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       ef0b6008-bf7f-4fe3-b5c3-f5bdd9744435  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         2e52194e-7eed-46f4-b764-1ac9f693bb05  ethernet  --     


DevTools listening on ws://127.0.0.1:10174/devtools/browser/7a3c08f5-96ab-4203-a58c-035fdf0d4215
[0910/110529.656243:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0910/110529.658185:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[0910/110529.661019:WARNING:gpu_process_host.cc(1205)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: 
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestFirewall-testFirewallPage-rhel-8-1-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestFirewall-testFirewallPage-rhel-8-1-127.0.0.2-2401-FAIL.html
Wrote JS log to TestFirewall-testFirewallPage-rhel-8-1-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestFirewall-testFirewallPage-rhel-8-1-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-networking-firewall", line 116, in testFirewallPage
    b.call_js_func("ph_count_check", "#services-listing tbody", len(active_rules))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 195, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 181, in eval_js
    self.raise_cdp_exception("eval_js", code, result["exceptionDetails"])
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: eval_js(ph_count_check("#services-listing tbody",8)): found 4 #services-listing tbody not 8

not ok 245 testFirewallPage (check_networking_firewall.TestFirewall) # duration: 43s
```
First occurrence: 2019-09-10T11:05:44.478735 | revision d0c852a46d7f9b891abe461521c1ba0d7a76a6db
Times recorded: 1
Latest occurrences:

- 2019-09-10T11:05:44.478735 | revision d0c852a46d7f9b891abe461521c1ba0d7a76a6db

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNetworkingPage (check_networking_firewall.TestFirewall)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       733672f2-e6b2-4452-9540-e0c6d680b727  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         2e52194e-7eed-46f4-b764-1ac9f693bb05  ethernet  --     


DevTools listening on ws://127.0.0.1:9567/devtools/browser/2c26a7c5-5ed2-4a85-a970-d8bf0bab9e53
[0910/110527.018605:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0910/110527.053734:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[0910/110527.078424:WARNING:gpu_process_host.cc(1205)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: 
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestFirewall-testNetworkingPage-rhel-8-1-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestFirewall-testNetworkingPage-rhel-8-1-127.0.0.2-2201-FAIL.html
Wrote JS log to TestFirewall-testNetworkingPage-rhel-8-1-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestFirewall-testNetworkingPage-rhel-8-1-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-networking-firewall", line 59, in testNetworkingPage
    b.wait_in_text("#networking-firewall-summary", "{} Active Rule".format(len(active_rules)))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 385, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 338, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 335, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#networking-firewall-summary","7 Active Rule")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":6,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1568113530020.7, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000013460.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: 
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]

not ok 247 testNetworkingPage (check_networking_firewall.TestFirewall) # duration: 101s
```
First occurrence: 2019-09-10T11:06:42.024085 | revision d0c852a46d7f9b891abe461521c1ba0d7a76a6db
Times recorded: 1
Latest occurrences:

- 2019-09-10T11:06:42.024085 | revision d0c852a46d7f9b891abe461521c1ba0d7a76a6db

**Comment by cockpituous** [comment]
verify/rhel-8-1-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFirewallPage (check_networking_firewall.TestFirewall)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       0e969ada-8bd8-4a94-aecb-2f23860adc28  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         2e52194e-7eed-46f4-b764-1ac9f693bb05  ethernet  --     


DevTools listening on ws://127.0.0.1:9308/devtools/browser/01a14290-89f5-4055-a5d0-c81d630e8462
[0910/121505.596778:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0910/121505.642759:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[0910/121505.659850:WARNING:gpu_process_host.cc(1205)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: 
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestFirewall-testFirewallPage-rhel-8-1-distropkg-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestFirewall-testFirewallPage-rhel-8-1-distropkg-127.0.0.2-2401-FAIL.html
Wrote JS log to TestFirewall-testFirewallPage-rhel-8-1-distropkg-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestFirewall-testFirewallPage-rhel-8-1-distropkg-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-networking-firewall", line 115, in testFirewallPage
    b.call_js_func("ph_count_check", "#services-listing tbody", len(active_rules))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 195, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 181, in eval_js
    self.raise_cdp_exception("eval_js", code, result["exceptionDetails"])
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: eval_js(ph_count_check("#services-listing tbody",8)): found 4 #services-listing tbody not 8

not ok 245 testFirewallPage (check_networking_firewall.TestFirewall) # duration: 44s
```
First occurrence: 2019-09-10T12:15:22.830278 | revision 8d40f21149ee0703f3bfc91a9d7e26333b4d6200
Times recorded: 1
Latest occurrences:

- 2019-09-10T12:15:22.830278 | revision 8d40f21149ee0703f3bfc91a9d7e26333b4d6200

**Comment by cockpituous** [comment]
verify/rhel-8-1-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNetworkingPage (check_networking_firewall.TestFirewall)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       2b47ef83-dbf1-4aa2-82e1-2f2e68c2acda  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         2e52194e-7eed-46f4-b764-1ac9f693bb05  ethernet  --     


DevTools listening on ws://127.0.0.1:9972/devtools/browser/dbba3c94-9fe0-4508-a743-9dee73ff3cb3
[0910/121506.928215:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0910/121506.929838:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[0910/121506.932466:WARNING:gpu_process_host.cc(1205)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: 
> warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]
Wrote screenshot to TestFirewall-testNetworkingPage-rhel-8-1-distropkg-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestFirewall-testNetworkingPage-rhel-8-1-distropkg-127.0.0.2-2201-FAIL.html
Wrote JS log to TestFirewall-testNetworkingPage-rhel-8-1-distropkg-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestFirewall-testNetworkingPage-rhel-8-1-distropkg-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-networking-firewall", line 59, in testNetworkingPage
    b.wait_in_text("#networking-firewall-summary", "{} Active Rule".format(len(active_rules)))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 385, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 338, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 335, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#networking-firewall-summary","7 Active Rule")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":5,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1568117709302.07, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000011351.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: 
warning: Checking for available updates failed: Error: cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]

not ok 247 testNetworkingPage (check_networking_firewall.TestFirewall) # duration: 101s
```
First occurrence: 2019-09-10T12:16:20.261968 | revision 8d40f21149ee0703f3bfc91a9d7e26333b4d6200
Times recorded: 1
Latest occurrences:

- 2019-09-10T12:16:20.261968 | revision 8d40f21149ee0703f3bfc91a9d7e26333b4d6200
