### ISSUE TITLE
sssd 2.2.2 regression: SSH GSS authentication fails with "Ticket expired"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#12898]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1757299

**Comment by martinpitt** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNegotiate (__main__.TestKerberos)
#
++ seq 1 20
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ break
+ realm join -vU admin cockpit.lan
+ echo foobarfoo
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2019-09-17 13:59:51
    Valid Until: 2039-09-17 13:59:51

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Unable to find 'admin' user with 'getent passwd admin@cockpit.lan'!
Unable to reliably detect configuration. Check NSS setup manually.
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful
This program will set up FreeIPA client.
Version 4.8.1


Using default chrony configuration.
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * Successfully enrolled machine in realm
++ seq 1 20
+ for x in $(seq 1 20)
+ KRB5_TRACE=/dev/stderr
+ kinit -f admin@COCKPIT.LAN
+ echo foobarfoo
[9150] 1569913117.115696: Getting initial credentials for admin@COCKPIT.LAN
[9150] 1569913117.115698: Sending unauthenticated request
[9150] 1569913117.115699: Sending request (180 bytes) to COCKPIT.LAN
[9150] 1569913117.115700: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[9150] 1569913117.115701: No URI records found
[9150] 1569913117.115702: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[9150] 1569913117.115703: SRV answer: 0 100 88 "f0.cockpit.lan."
[9150] 1569913117.115704: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[9150] 1569913117.115705: SRV answer: 0 100 88 "f0.cockpit.lan."
[9150] 1569913117.115706: Resolving hostname f0.cockpit.lan.
[9150] 1569913117.115707: Resolving hostname f0.cockpit.lan.
[9150] 1569913117.115708: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[9150] 1569913117.115709: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[9150] 1569913117.115710: Initiating TCP connection to stream 172.27.0.15:88
[9150] 1569913117.115711: Terminating TCP connection to stream 172.27.0.15:88
[9150] 1569913117.115712: Initiating TCP connection to stream 10.111.112.100:88
[9150] 1569913117.115713: Sending TCP request to stream 10.111.112.100:88
[9150] 1569913117.115714: Received answer (524 bytes) from stream 10.111.112.100:88
[9150] 1569913117.115715: Terminating TCP connection to stream 10.111.112.100:88
[9150] 1569913117.115716: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[9150] 1569913117.115717: No URI records found
[9150] 1569913117.115718: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[9150] 1569913117.115719: SRV answer: 0 100 88 "f0.cockpit.lan."
[9150] 1569913117.115720: Response was from master KDC
[9150] 1569913117.115721: Received error from KDC: -1765328359/Additional pre-authentication required
[9150] 1569913117.115724: Preauthenticating using KDC method data
[9150] 1569913117.115725: Processing preauth types: PA-PK-AS-REQ (16), PA-PK-AS-REP_OLD (15), PA-PK-AS-REQ_OLD (14), PA-FX-FAST (136), PA-ETYPE-INFO2 (19), PA-PKINIT-KX (147), PA-SPAKE (151), PA-ENC-TIMESTAMP (2), PA_AS_FRESHNESS (150), PA-FX-COOKIE (133)
[9150] 1569913117.115726: Selected etype info: etype aes256-cts, salt "l:K,,[Lz]sB#.N*/", params ""
[9150] 1569913117.115727: Received cookie: MIT1\x00\x00\x00\x01\xfe\xae\xbdg\xfdm\x95\xdbo\xc1m\xa85\xe7\x84\xdcP\xa9\xd2\xbbRB\x9d\xa3\xcd\xf2\x00B5\xb7\xc0\x0a`+\xc0]5@\xbf\x81\xacr3[8\x19lHE\xa0\x8d|}94\x86\\x81\xb8zMk\xca\x14YL\x85\xd2\xeb:\xfcw\xfb\xe0\xc7E\x0b\x1a\xe2J|\xd9\x87\xc1|\xfa?\x1e\xf0\x0f`\x18niE\x9c\x92\x9a\x9cW"\x90m\x8d\x1a\xc5:2\xa0\xc5\x8e\x81\x8f\x89\x17\x9e\xaa\x0a\xe5=GNy\x94(\x16\x112\xef 
[9150] 1569913117.115728: SPAKE challenge received with group 1, pubkey 252327CB56428B8E7D5AA50A1FB2ED20669414FC9055886079669F8E7AE82332
[9150] 1569913117.115729: SPAKE key generated with pubkey 2AE110F117533C5D8D87F1E6956CE5D9EF09AA7F7CCBF7175953D41688DE9C56
[9150] 1569913117.115730: SPAKE algorithm result: 53221F0E64B850CD4E2BF887A31C62C426C4A8B76E8C89DAC5E3575403E27E28
[9150] 1569913117.115731: SPAKE final transcript hash: 0A5CFCEF6DCFC3A405995DF729124AF1B4B59A0F9D4FB0EB8F500B8ED0B21355
[9150] 1569913117.115732: Sending SPAKE response
[9150] 1569913117.115733: Preauth module spake (151) (real) returned: 0/Success
[9150] 1569913117.115734: Produced preauth for next request: PA-FX-COOKIE (133), PA-SPAKE (151)
[9150] 1569913117.115735: Sending request (439 bytes) to COCKPIT.LAN
[9150] 1569913117.115736: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[9150] 1569913117.115737: No URI records found
[9150] 1569913117.115738: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[9150] 1569913117.115739: SRV answer: 0 100 88 "f0.cockpit.lan."
[9150] 1569913117.115740: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[9150] 1569913117.115741: SRV answer: 0 100 88 "f0.cockpit.lan."
[9150] 1569913117.115742: Resolving hostname f0.cockpit.lan.
[9150] 1569913117.115743: Resolving hostname f0.cockpit.lan.
[9150] 1569913117.115744: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[9150] 1569913117.115745: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[9150] 1569913117.115746: Initiating TCP connection to stream 172.27.0.15:88
[9150] 1569913117.115747: Terminating TCP connection to stream 172.27.0.15:88
[9150] 1569913117.115748: Initiating TCP connection to stream 10.111.112.100:88
[9150] 1569913117.115749: Sending TCP request to stream 10.111.112.100:88
[9150] 1569913117.115750: Received answer (724 bytes) from stream 10.111.112.100:88
[9150] 1569913117.115751: Terminating TCP connection to stream 10.111.112.100:88
[9150] 1569913117.115752: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[9150] 1569913117.115753: No URI records found
[9150] 1569913117.115754: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[9150] 1569913117.115755: SRV answer: 0 100 88 "f0.cockpit.lan."
[9150] 1569913117.115756: Response was from master KDC
[9150] 1569913117.115757: Processing preauth types: PA-ETYPE-INFO2 (19)
[9150] 1569913117.115758: Selected etype info: etype aes256-cts, salt "l:K,,[Lz]sB#.N*/", params ""
[9150] 1569913117.115759: Produced preauth for next request: (empty)
[9150] 1569913117.115760: AS key determined by preauth: aes256-cts/F44A
[9150] 1569913117.115761: Decrypted AS reply; session key is: aes256-cts/6A15
[9150] 1569913117.115762: FAST negotiation: available
[9150] 1569913117.115763: Initializing KCM:0 with default princ admin@COCKPIT.LAN
[9150] 1569913117.115764: Storing admin@COCKPIT.LAN -> krbtgt/COCKPIT.LAN@COCKPIT.LAN in KCM:0
[9150] 1569913117.115765: Storing config in KCM:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: fast_avail: yes
[9150] 1569913117.115766: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/fast_avail/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KCM:0
[9150] 1569913117.115767: Storing config in KCM:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: pa_type: 151
[9150] 1569913117.115768: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/pa_type/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KCM:0
+ break
+ grep -iq '^C\.utf'
+ locale -a
+ loc=C.UTF-8
+ type ipa
+ LC_ALL=C.UTF-8
+ ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN
+ ipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab
+ sed -i '/^sudoers:/ s/files sss/sss files/' /etc/nsswitch.conf
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sss_cache -E
+ systemctl restart sssd.service
+ sleep 1
+ for x in $(seq 1 60)
+ getent passwd admin
+ systemctl --quiet is-failed sssd.service
+ sss_cache -E
+ systemctl restart sssd.service
+ sleep 2
+ for x in $(seq 1 60)
+ getent passwd admin
+ break
+ getent passwd admin
+ chown -R admin /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin x0.cockpit.lan true
+ break

DevTools listening on ws://127.0.0.1:9628/devtools/browser/de19931f-7f7b-44e5-bc79-a1565b8eb306
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Tabs)
> warning: Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TabContent, Uncontrolled(Tabs)
> warning: Login failed
> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

Wrote screenshot to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2201-FAIL.html
Wrote JS log to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2201-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-realms", line 517, in testNegotiate
    b.wait_popdown('troubleshoot-dialog')
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 420, in wait_popdown
    self.wait_not_visible('#' + id)
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 385, in wait_not_visible
    self.wait_js_func('!ph_is_visible', selector)
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 342, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 339, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_visible("#troubleshoot-dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":2,"id":1}'}}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Tabs)
warning: Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TabContent, Uncontrolled(Tabs)
warning: Login failed
warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory


not ok 1 testNegotiate (__main__.TestKerberos) # duration: 168s
```
First occurrence: 2019-10-01T08:59:59.901317
Times recorded: 1
Latest occurrences:

- 2019-10-01T08:59:59.901317
