### ISSUE TITLE
test-websocket test crashes on sparc64 due to unaligned access

### ISSUE THREAD

**Issue by glaubitz** [cockpit-project/cockpit#13434]
On Debian unstable, ```cockpit``` fails to build from source on sparc64 due to the testsuite crashing in ```test-websocket```:

```
ERROR: test-websocket
=====================

# ./tools/tap-driver --test-name test-websocket --log-file test-websocket.log --trs-file test-websocket.trs --color-tests no --enable-hard-errors yes --expect-failure no -- sh -c "$0" "$@" --tap ./test-websocket
# random seed: R02S40d838f626fc3b1116de4331736d0b0c
1..40
# Start of web-socket tests
ok 1 /web-socket/parse-url
ok 2 /web-socket/parse-url-no-out
ok 3 /web-socket/parse-url-bad
ok 4 /web-socket/parse-url-no-path
ok 5 /web-socket/parse-url-with-user
ok 6 /web-socket/parse-req
ok 7 /web-socket/parse-req-no-out
ok 8 /web-socket/parse-req-not-enough
ok 9 /web-socket/parse-req-bad
ok 10 /web-socket/parse-status
ok 11 /web-socket/parse-status-no-out
ok 12 /web-socket/parse-status-not-enough
ok 13 /web-socket/parse-status-bad
ok 14 /web-socket/parse-version-1-0
ok 15 /web-socket/parse-version-1-1
ok 16 /web-socket/parse-headers
ok 17 /web-socket/parse-headers-no-out
# WebSocket-DEBUG: received invalid header line: Header1 value3


# WebSocket-DEBUG: received invalid header
ok 18 /web-socket/parse-headers-bad
ok 19 /web-socket/parse-headers-not-enough
ok 20 /web-socket/header-equals
ok 21 /web-socket/header-contains
ok 22 /web-socket/header-empty
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued rfc6455 handshake request
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued response to rfc6455 handshake
# WebSocket-DEBUG: open: responded to handshake
# WebSocket-DEBUG: stopping output source
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: verified rfc6455 handshake
# WebSocket-DEBUG: open: handshake completed
# WebSocket-DEBUG: stopping output source
# WebSocket-DEBUG: stopping input source
# WebSocket-DEBUG: closing io stream
# WebSocket-DEBUG: stopping input source
# WebSocket-DEBUG: closing io stream
ok 23 /web-socket/handshake
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued rfc6455 handshake request
# WebSocket-DEBUG: closed: completed io stream close
# WebSocket-DEBUG: closed: completed io stream close
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued response to rfc6455 handshake
# WebSocket-DEBUG: open: responded to handshake
# WebSocket-DEBUG: stopping output source
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: verified rfc6455 handshake
# WebSocket-DEBUG: open: handshake completed
# WebSocket-DEBUG: stopping output source
Bus error
```

Backtrace:

```
Thread 1 "test-websocket" received signal SIGBUS, Bus error.
0x000001000000ebf8 in send_prefixed_message_rfc6455 (self=0x10000138460, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, 
    payload=0x10000121860 "this is a test", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
434           mask = outer + bytes->len;
(gdb) bt
#0  0x000001000000ebf8 in send_prefixed_message_rfc6455
    (self=0x10000138460, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, payload=0x10000121860 "this is a test", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
#1  0x0000010000010268 in web_socket_connection_send (self=0x10000138460, type=<optimized out>, prefix=<optimized out>, message=0x10000129430)
    at src/websocket/websocketconnection.c:1754
#2  0x000001000000992c in test_send_client_to_server (test=0x10000129ca0, data=0x0) at src/websocket/test-websocket.c:607
#3  0xffff8001005a475c in  () at /usr/lib/sparc64-linux-gnu/libglib-2.0.so.0
(gdb)
```

Full build log in: https://buildd.debian.org/status/fetch.php?pkg=cockpit&arch=sparc64&ver=210-1&stamp=1578525899&raw=0

Note: There a multiple crashes due to unaligned access, just grep the build log for "Bus error".

Access to a fast sparc64 porterbox running Debian unstable is available through the GCC compile farm, see: https://gcc.gnu.org/wiki/CompileFarm

Debian also provides a sparc64 porterbox available to all Debian Developers and users with a Debian guest account.

**Comment by glaubitz** [comment]
Here's the backtrace for ```test-handlers```:

```
Thread 1 "test-handlers" received signal SIGBUS, Bus error.
0x0000010000032360 in send_prefixed_message_rfc6455 (self=0x1000016d0d0, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, 
    payload=0x7feffffea98 "\003\351\200\001", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
434           mask = outer + bytes->len;
(gdb) bt
#0  0x0000010000032360 in send_prefixed_message_rfc6455
    (self=0x1000016d0d0, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, payload=0x7feffffea98 "\003\351\200\001", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
#1  0x0000010000032480 in send_message_rfc6455
    (payload_len=<optimized out>, payload=0x7feffffea98 "\003\351\200\001", opcode=8 '\b', flags=WEB_SOCKET_QUEUE_NORMAL, self=0x1000016d0d0)
    at src/websocket/websocketconnection.c:480
#2  0x0000010000032480 in send_close_rfc6455 (self=0x1000016d0d0, flags=<optimized out>, code=<optimized out>, reason=0x0) at src/websocket/websocketconnection.c:480
#3  0x0000010000033bf4 in web_socket_connection_close (self=0x1000016d0d0, code=<optimized out>, data=0x0) at src/websocket/websocketconnection.c:1798
#4  0x0000010000034374 in receive_close_rfc6455 (len=<optimized out>, data=<optimized out>, self=0x1000016d0d0) at src/websocket/websocketconnection.c:669
#5  0x0000010000034374 in process_contents_rfc6455
    (payload_len=12, payload=0x10000171142, opcode=<optimized out>, fin=<optimized out>, control=<optimized out>, self=0x1000016d0d0)
    at src/websocket/websocketconnection.c:709
#6  0x0000010000034374 in process_frame_rfc6455 (self=0x1000016d0d0) at src/websocket/websocketconnection.c:910
#7  0x0000010000034374 in process_incoming (self=0x1000016d0d0) at src/websocket/websocketconnection.c:940
#8  0x00000100000345e8 in on_web_socket_input (pollable_stream=0x10000148210, user_data=0x1000016d0d0) at src/websocket/websocketconnection.c:988
#9  0xffff8001001c1440 in  () at /usr/lib/sparc64-linux-gnu/libgio-2.0.so.0
(gdb)
```

**Comment by glaubitz** [comment]
```test-websocketstream``` crashes at the same position as ```test-websocket```:

```
(gdb) bt
#0  0x0000010000021a88 in send_prefixed_message_rfc6455
    (self=0x100001570f0, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, payload=0x10000151550 "Message", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
#1  0x00000100000230f8 in web_socket_connection_send (self=0x100001570f0, type=<optimized out>, prefix=<optimized out>, message=0x10000141ca0)
    at src/websocket/websocketconnection.c:1754
#2  0x0000010000010ed0 in process_recv (payload=0x10000141ca0, self=0x10000152120) at src/common/cockpitchannel.c:175
#3  0x0000010000010ed0 in on_transport_recv (transport=<optimized out>, channel_id=0x100001592c0 "444", data=0x10000141ca0, user_data=0x10000152120)
    at src/common/cockpitchannel.c:191
#4  0xffff800101462518 in  () at /usr/lib/sparc64-linux-gnu/libffi.so.7
#5  0xffff8001003de5c8 in g_cclosure_marshal_generic () at /usr/lib/sparc64-linux-gnu/libgobject-2.0.so.0
#6  0xffff8001003ddc5c in g_closure_invoke () at /usr/lib/sparc64-linux-gnu/libgobject-2.0.so.0
#7  0xffff8001003f2be4 in  () at /usr/lib/sparc64-linux-gnu/libgobject-2.0.so.0
(gdb)
```

**Comment by glaubitz** [comment]
So does ```test-webservice```:

```
(gdb) bt
#0  0x0000010000012d50 in send_prefixed_message_rfc6455
    (self=0x100001600d0, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, payload=0x10000166a10 "\n{\"command\":\"ping\"}:28 U", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
#1  0x00000100000143c0 in web_socket_connection_send (self=0x100001600d0, type=<optimized out>, prefix=<optimized out>, message=0x1000014ff60)
    at src/websocket/websocketconnection.c:1754
#2  0x000001000000b3b0 in send_control_message (ws=0x100001600d0, command=0x1000002b850 "ping", channel=0x0) at src/ws/test-webservice.c:344
#3  0x000001000000de4c in test_no_init (test=0x1000015e930, data=0x0) at src/ws/test-webservice.c:707
#4  0xffff8001005a475c in  () at /usr/lib/sparc64-linux-gnu/libglib-2.0.so.0
(gdb)
```

**Comment by glaubitz** [comment]
I think this should fix the issue:

```diff
--- cockpit-210.orig/src/websocket/websocketconnection.c
+++ cockpit-210/src/websocket/websocketconnection.c
@@ -432,7 +432,7 @@ send_prefixed_message_rfc6455 (WebSocket
     {
       outer[1] |= 0x80;
       mask = outer + bytes->len;
-      * ((guint32 *)mask) = g_random_int ();
+      memcpy (mask, g_random_int (), sizeof(guint32));
       bytes->len += 4;
     }
```

Testing this now.
