### ISSUE TITLE
testBasic (check_accounts.TestAccounts) is flaky

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13446]
Happens on F30 a lot. Fails like this:
```
Traceback (most recent call last):
  File "test/verify/check-accounts", line 44, in testBasic
    b.wait_not_attr('#account-real-name', 'data-dirty', 'true')
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 413, in wait_not_attr
    self.wait_js_func('!ph_has_attr', selector, attr, val)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 373, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 370, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
```

[Example](https://209.132.184.41:8493/logs/pull-12948-20200126-171313-29d74ff6-fedora-30/log.html#79-2)

**Comment by marusak** [comment]
It is not even flaky, seems to be utterly broken on Fedora 30.
