### ISSUE TITLE
testNoConnectionSettings (check_networking_settings.TestNetworking) is flaky

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13464]
It is crashing like this:
```
Traceback (most recent call last):
  File "test/verify/check-networking-settings", line 57, in testNoConnectionSettings
    b.wait_in_text("tr:contains('IPv4')", "Address 1.2.3.4/24")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 421, in wait_in_text
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 391, in wait_visible
    self.wait_js_func('ph_is_visible', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 372, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 174, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_visible("tr:contains('IPv4')")): tr:contains('IPv4') not found
```

[Example](https://209.132.184.41:8493/logs/pull-13462-20200129-115959-ecc88014-fedora-30/log.html#159-2)

**Comment by martinpitt** [comment]
This reproduces easily locally. I updated the description, as the relevant failure is unrelated to the "incomplete connection object" noise. When this happens, I see a "Connection will be lost" checkpoint dialog.

The actual thing that it's looking for is still in the DOM, though:

     <tr><td>IPv4</td><td><a tabindex="0" class="network-privileged" title="" data-stable="yes">Address 1.2.3.4/24</a></td></tr>

but supposedly due to the "Connection lost" modal that doesn't count as visible?

**Comment by martinpitt** [comment]
With an extra sleep(5) to let the VM settle down a bit, it's stable. But that'd be a bit unsatisfying.

In the log and the interactive browser I see that it does take some time, precisely the 7 seconds of `rollback_time`
```
06:22:18 NetworkManager[640]: <info>  [1581592938.6514] audit: op="checkpoint-create" arg="/org/freedesktop/NetworkManager/Checkpoint/1" pid=7039 uid=0 result="success"
06:22:24 NetworkManager[640]: <info>  [1581592944.5087] policy: auto-activating connection 'eth2' (8fce8162-ae49-4192-9174-b5deaae992ae)
06:22:24 NetworkManager[640]: <info>  [1581592944.5095] device (eth2): Activation: starting connection 'eth2' (8fce8162-ae49-4192-9174-b5deaae992ae)
06:22:24 NetworkManager[640]: <info>  [1581592944.5108] device (eth2): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
06:22:24 NetworkManager[640]: <info>  [1581592944.5125] device (eth2): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
06:22:24 NetworkManager[640]: <info>  [1581592944.5657] device (eth2): state change: config -> ip-config (reason 'none', sys-iface-state: 'managed')
06:22:24 NetworkManager[640]: <info>  [1581592944.5772] device (eth2): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'managed')
06:22:24 NetworkManager[640]: <info>  [1581592944.6251] device (eth2): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'managed')
06:22:24 NetworkManager[640]: <info>  [1581592944.6258] device (eth2): state change: secondaries -> activated (reason 'none', sys-iface-state: 'managed')
06:22:24 NetworkManager[640]: <info>  [1581592944.6312] device (eth2): Activation: successful, device activated.
06:22:24 systemd[1]: iscsi.service: Unit cannot be reloaded because it is inactive.
06:22:25 systemd[1]: /usr/lib/systemd/system/oddjobd.service:7: PIDFile= references a path below legacy directory /var/run/, updating /var/run/oddjobd.pid → /run/oddjobd.pid; please update the unit file accordingly.
06:22:25 NetworkManager[640]: <info>  [1581592945.6512] checkpoint[0x7fbde0003f10]: rollback of /org/freedesktop/NetworkManager/Checkpoint/1
06:22:25 NetworkManager[640]: <info>  [1581592945.6516] device (eth2): state change: activated -> deactivating (reason 'user-requested', sys-iface-state: 'managed')
06:22:25 NetworkManager[640]: <info>  [1581592945.6815] device (eth2): state change: deactivating -> disconnected (reason 'user-requested', sys-iface-state: 'managed')
```

**Comment by martinpitt** [comment]
When I bump the rollback_time from 7 to 10s, it is reasonably reliable, but that would reintroduce the original issue #7859, i. e. why we reduced it from 15 to 7s in the first place. So it makes more sense to adjust the test to just get along with the checkpoint dialog coming up.

My initial approach was to check for 10s that the checkpoint dialog either does not come up, or if it does, click on "Change settings". However, when that happens, NM does not activate the device, so one needs to manually activate it (using the toggle button). I'm not sure if that's intended or a bug. 

The other approach would be to have a sleeping loop at the start of the test that lets the VM settle down a bit. I'll send a PR to at least see how this fares.

@mvollmer, any opinion?
