### ISSUE TITLE
testSnapshots (check_storage_lvm2.TestStorage) is flaky

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13499]
Traceback like:
```
Traceback (most recent call last):
  File "test/verify/check-storage-lvm2", line 285, in testSnapshots
    self.content_dropdown_action(2, "Create Snapshot")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 79, in content_dropdown_action
    self.browser.click(dropdown + " a:contains('%s')" % title)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 213, in click
    self.mouse(selector + ":not([disabled])", "click", 0, 0, 0)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 209, in mouse
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 390, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 381, in wait_present
    self.wait_js_func('ph_is_present', selector)
```

Happens on all OSes.
Example [centos-8-stream](https://209.132.184.41:8493/logs/pull-13497-20200206-080000-548ee53e-centos-8-stream/log.html#154-2), [ubuntu-stable](https://209.132.184.41:8493/logs/pull-13497-20200206-080000-548ee53e-ubuntu-stable/log.html), [rhel-8-2-distropkg](https://209.132.184.41:8493/logs/pull-499-20200206-032828-b6c8cd4c-rhel-8-2-distropkg-cockpit-project-cockpit/log.html#230-2), [fedora-31](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13497-20200206-103939-548ee53e-fedora-31/log.html#154-2)

snapshot on failure:
![failed snapshot](https://209.132.184.41:8493/logs/pull-13497-20200206-080000-548ee53e-centos-8-stream/TestStorage-testSnapshots-centos-8-stream-127.0.0.2-2301-FAIL.png)

**Comment by martinpitt** [comment]
It seems the test expects the "Snapshot" menu entry on the "pool" device. Is that supported? I. e. is it a bug in the test that it should instead look at the /dev/TEST/thin device, or a bug in the code that it doesn't have Snapshot for pool?

**Comment by martinpitt** [comment]
Marius confirmed that "pool" should not have a snapshot menu entry. I'll look at fixing the test.
