### ISSUE TITLE
Machines testCreate fails: Error validating install location: Could not find an installable distribution at https...

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#13834]
We often see [this failure](https://logs.cockpit-project.org/logs/pull-13782-20200401-212952-5668a168-fedora-31/log.html#202):
```
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 1524, in testCreate
    start_vm=True, delete=False))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 1405, in createDownloadAnOSTest
    dialog.open() \
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 2055, in createAndVerifyVirtInstallArgs
    wait(lambda: self.machine.execute(virt_install_cmd), delay=3)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1569, in wait
    val = func()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 2055, in <lambda>
    wait(lambda: self.machine.execute(virt_install_cmd), delay=3)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'ps aux | grep 'virt\-install\ \-\-connect'' returned non-zero exit status 1.
```

The [screenshot](https://logs.cockpit-project.org/logs/pull-13782-20200401-212952-5668a168-fedora-31/TestMachinesDBus-testCreate-fedora-31-127.0.0.2-2201-FAIL.png) shows that VM creation indeed failed, and that seems to be the root cause:

    info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    Error validating install location: Could not find an installable distribution at 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/': The URL could not be accessed, maybe you mistyped?\n\nThe location must be the root directory of an install tree.\nSee virt-install man page for various distro examples."}", data: """"

But I wonder how this can fail only sometimes -- what's the race condition that makes this  try to access the internet only sometimes?

**Comment by martinpitt** [comment]
Fails on [rhel-8-2](https://logs.cockpit-project.org/logs/pull-13782-20200401-212958-5668a168-rhel-8-2/log.html) as well, so it's not related to the debug build that we do on Fedora 31.
