### ISSUE TITLE
cockpit-bridge crash in process_connection → g_dbus_connection_signal_subscribe → _g_dbus_worker_send_message

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#13918]
Our tests spot quite a lot of core dumps (#13854), in particular in cockpit-bridge. I stumbled over this again in [cockpit-podman Fedora tests](https://src.fedoraproject.org/rpms/cockpit-podman/pull-request/3#), but that doesn't have useful debug info.

Stack trace:
```
#0  0x00007f152fa31b5d _g_dbus_worker_send_message (libgio-2.0.so.0 + 0x124b5d)
#1  0x00007f152fa1b6bc g_dbus_connection_send_message_unlocked (libgio-2.0.so.0 + 0x10e6bc)
#2  0x00007f152fa22170 g_dbus_connection_signal_subscribe (libgio-2.0.so.0 + 0x115170)
#3  0x00007f152fa2a0b2 has_connection (libgio-2.0.so.0 + 0x11d0b2)
#4  0x00007f152fa2ae6f g_bus_watch_name_on_connection (libgio-2.0.so.0 + 0x11de6f)
#5  0x000055cf501614fd process_connection (cockpit-bridge + 0x1a4fd)
#6  0x000055cf5016575a cockpit_dbus_json_prepare (cockpit-bridge + 0x1e75a)
#7  0x000055cf501870a1 on_idle_prepare (cockpit-bridge + 0x400a1)
#8  0x00007f152f7d844b g_idle_dispatch (libglib-2.0.so.0 + 0x4e44b)
#9  0x00007f152f7dc76f g_main_context_dispatch (libglib-2.0.so.0 + 0x5276f)
#10 0x00007f152f7dcaf8 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x52af8)
#11 0x00007f152f7dcbc3 g_main_context_iteration (libglib-2.0.so.0 + 0x52bc3)
#12 0x000055cf5015e744 run_bridge (cockpit-bridge + 0x17744)
#13 0x00007f152f493042 __libc_start_main (libc.so.6 + 0x27042)
#14 0x000055cf5015f3ae _start (cockpit-bridge + 0x183ae)

Stack trace of thread 37879:
#0  0x00007f152f562b6f __poll (libc.so.6 + 0xf6b6f)
#1  0x00007f152f7dca8d g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x52a8d)
#2  0x00007f152f7dce0b g_main_loop_run (libglib-2.0.so.0 + 0x52e0b)
#3  0x00007f152fa2f7ea gdbus_shared_thread_func (libgio-2.0.so.0 + 0x1227ea)
#4  0x00007f152f806652 g_thread_proxy (libglib-2.0.so.0 + 0x7c652)
#5  0x00007f152f63f432 start_thread (libpthread.so.0 + 0x9432)
#6  0x00007f152f56d9d3 __clone (libc.so.6 + 0x1019d3)
```
(other two threads skipped, they don't have anything relevant)

Occurrences:
 * [testIpa@f32](https://logs.cockpit-project.org/logs/pull-13879-20200416-171942-1ca19797-fedora-32/), [journal](https://logs.cockpit-project.org/logs/pull-13879-20200416-171942-1ca19797-fedora-32/TestRealms-testIpa-fedora-32-127.0.0.2-2401-FAIL.log.gz)
 * [testIpa@f31](https://logs.cockpit-project.org/logs/pull-13879-20200409-090258-dff7021b-fedora-31/), [journal](https://logs.cockpit-project.org/logs/pull-13879-20200409-090258-dff7021b-fedora-31/TestRealms-testIpa-fedora-31-127.0.0.2-2801-FAIL.log.gz)
 * [testIpa@debian-stable](https://logs.cockpit-project.org/logs/pull-13898-20200414-102916-39787155-debian-stable/), [journal](https://logs.cockpit-project.org/logs/pull-13898-20200414-102916-39787155-debian-stable/TestRealms-testIpa-debian-stable-127.0.0.2-2301-FAIL.log.gz)

**Comment by martinpitt** [comment]
Then there's one which is not about a D-Bus signal, but process_control → cockpit_dbus_json_finalize → g_source_set_ready_time:
```
#0  0x00007f5e561cc2ef g_source_set_ready_time (libglib-2.0.so.0 + 0x4e2ef)
#1  0x00007f5e56354266 n/a (libgio-2.0.so.0 + 0x50266)
#2  0x00007f5e562b9206 n/a (libgobject-2.0.so.0 + 0x14206)
#3  0x00007f5e562d78d4 g_signal_emit_valist (libgobject-2.0.so.0 + 0x328d4)
#4  0x00007f5e562d7edf g_signal_emit (libgobject-2.0.so.0 + 0x32edf)
#5  0x00007f5e56354958 g_cancellable_cancel (libgio-2.0.so.0 + 0x50958)
#6  0x00007f5e5641b924 n/a (libgio-2.0.so.0 + 0x117924)
#7  0x00007f5e5641b995 n/a (libgio-2.0.so.0 + 0x117995)
#8  0x00007f5e564090a1 n/a (libgio-2.0.so.0 + 0x1050a1)
#9  0x00007f5e562be023 g_object_unref (libgobject-2.0.so.0 + 0x19023)
#10 0x000055d3a470c662 cockpit_dbus_json_finalize (cockpit-bridge + 0x1b662)
#11 0x00007f5e562be09e g_object_unref (libgobject-2.0.so.0 + 0x1909e)
#12 0x00007f5e562e2f94 g_value_unset (libgobject-2.0.so.0 + 0x3df94)
#13 0x00007f5e562d73ed g_signal_emit_valist (libgobject-2.0.so.0 + 0x323ed)
#14 0x00007f5e562d7edf g_signal_emit (libgobject-2.0.so.0 + 0x32edf)
#15 0x000055d3a472c65c process_control (cockpit-bridge + 0x3b65c)
#16 0x00007f5e55dc1ccd n/a (libffi.so.7 + 0x6ccd)
#17 0x00007f5e55dc125a n/a (libffi.so.7 + 0x625a)
#18 0x00007f5e562b97fc g_cclosure_marshal_generic (libgobject-2.0.so.0 + 0x147fc)
#19 0x00007f5e562b8fd2 g_closure_invoke (libgobject-2.0.so.0 + 0x13fd2)
#20 0x00007f5e562cc784 n/a (libgobject-2.0.so.0 + 0x27784)
#21 0x00007f5e562d7078 g_signal_emit_valist (libgobject-2.0.so.0 + 0x32078)
#22 0x00007f5e562d7edf g_signal_emit (libgobject-2.0.so.0 + 0x32edf)
#23 0x000055d3a4735a83 cockpit_transport_emit_control (cockpit-bridge + 0x44a83)
#24 0x000055d3a4735fd8 cockpit_transport_default_recv (cockpit-bridge + 0x44fd8)
#25 0x00007f5e55dc1ccd n/a (libffi.so.7 + 0x6ccd)
#26 0x00007f5e55dc125a n/a (libffi.so.7 + 0x625a)
#27 0x00007f5e562b97fc g_cclosure_marshal_generic (libgobject-2.0.so.0 + 0x147fc)
#28 0x00007f5e562b8fd2 g_closure_invoke (libgobject-2.0.so.0 + 0x13fd2)
#29 0x00007f5e562cbf06 n/a (libgobject-2.0.so.0 + 0x26f06)
#30 0x00007f5e562d7078 g_signal_emit_valist (libgobject-2.0.so.0 + 0x32078)
#31 0x00007f5e562d7edf g_signal_emit (libgobject-2.0.so.0 + 0x32edf)
#32 0x000055d3a473597b cockpit_transport_emit_recv (cockpit-bridge + 0x4497b)
#33 0x000055d3a473322f cockpit_transport_read_from_pipe (cockpit-bridge + 0x4222f)
#34 0x00007f5e55dc1ccd n/a (libffi.so.7 + 0x6ccd)
#35 0x00007f5e55dc125a n/a (libffi.so.7 + 0x625a)
#36 0x00007f5e562b9cae g_cclosure_marshal_generic_va (libgobject-2.0.so.0 + 0x14cae)
#37 0x00007f5e562b9206 n/a (libgobject-2.0.so.0 + 0x14206)
#38 0x00007f5e562d78d4 g_signal_emit_valist (libgobject-2.0.so.0 + 0x328d4)
#39 0x00007f5e562d7edf g_signal_emit (libgobject-2.0.so.0 + 0x32edf)
#40 0x000055d3a47303e9 dispatch_input (cockpit-bridge + 0x3f3e9)
#41 0x00007f5e561ce4de g_main_context_dispatch (libglib-2.0.so.0 + 0x504de)
#42 0x00007f5e561ce890 n/a (libglib-2.0.so.0 + 0x50890)
#43 0x00007f5e561ce91f g_main_context_iteration (libglib-2.0.so.0 + 0x5091f)
#44 0x000055d3a4705524 run_bridge (cockpit-bridge + 0x14524)
#45 0x00007f5e55ebbe0b __libc_start_main (libc.so.6 + 0x26e0b)
#46 0x000055d3a470619a _start (cockpit-bridge + 0x1519a)
```

They are similar enough that they could possibly have the same root cause.

Occurrences:
 * [testLogging@debian-testing](https://logs.cockpit-project.org/logs/pull-732-20200408-091058-4ac14094-debian-testing-cockpit-project-cockpit/), [journal](https://logs.cockpit-project.org/logs/pull-732-20200408-091058-4ac14094-debian-testing-cockpit-project-cockpit/TestLogin-testLogging-debian-testing-127.0.0.2-2201-FAIL.log.gz)
 * [testAuthorize@debian-testing](https://logs.cockpit-project.org/logs/pull-13897-20200414-100442-05d099a1-debian-testing/), [journal](https://logs.cockpit-project.org/logs/pull-13897-20200414-100442-05d099a1-debian-testing/TestKeys-testAuthorizedKeys-debian-testing-127.0.0.2-2501-FAIL.log.gz): This one does *not* go through process_control(), but still cockpit_dbus_json_finalize → g_source_set_ready_time
 * [test{Basic,DetachDisk}@ubuntu-2004](https://logs.cockpit-project.org/logs/pull-13864-20200407-113854-fdb1d3fd-ubuntu-2004/), [journal(https://logs.cockpit-project.org/logs/pull-13864-20200407-113854-fdb1d3fd-ubuntu-2004/TestMachinesDBus-testDetachDisk-ubuntu-2004-127.0.0.2-2201-FAIL.log.gz)

**Comment by martinpitt** [comment]
I got a backtrace with debug symbols for the first occurence (F31), which shows that the g_dbus worker is `NULL`:

```
#0  _g_dbus_worker_ref (worker=0x0) at ../gio/gdbusprivate.c:1634
No locals.
#1  _g_dbus_worker_send_message (worker=0x0, message=0x5622b8d56850, blob=0x5622b8c89e00 "l\001", blob_len=304) at ../gio/gdbusprivate.c:1634
        data = 0x7ff47000f600
        __FUNCTION__ = "_g_dbus_worker_send_message"
#2  0x00007ff489eb840f in g_dbus_connection_send_message_unlocked (connection=connection@entry=0x5622b8bd9790, message=message@entry=0x5622b8d56850, 
    flags=flags@entry=G_DBUS_SEND_MESSAGE_FLAGS_NONE, out_serial=out_serial@entry=0x0, error=error@entry=0x7ffc91bea218) at ../gio/gdbusconnection.c:1690
        blob = 0x5622b8c89e00 "l\001"
        blob_size = 304
        serial_to_use = 10
        ret = 0
        __FUNCTION__ = "g_dbus_connection_send_message_unlocked"
#3  0x00007ff489ebeea7 in add_match_rule (
    match_rule=0x5622b8bbc820 "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='com.redhat.tuned'", connection=0x5622b8bd9790) at ../gio/gdbusconnection.c:3335
        error = 0x0
        message = 0x5622b8d56850
        error = <optimized out>
        message = <optimized out>
#4  g_dbus_connection_signal_subscribe (connection=0x5622b8bd9790, sender=sender@entry=0x7ff489efb5ba "org.freedesktop.DBus", 
    interface_name=interface_name@entry=0x7ff489efb5ba "org.freedesktop.DBus", member=member@entry=0x7ff489efb629 "NameOwnerChanged", 
    object_path=object_path@entry=0x7ff489f13e49 "/org/freedesktop/DBus", arg0=0x5622b8c5e310 "com.redhat.tuned", flags=G_DBUS_SIGNAL_FLAGS_NONE, 
    callback=0x7ff489ec7080 <on_name_owner_changed>, user_data=0x1b, user_data_free_func=0x0) at ../gio/gdbusconnection.c:3547
        rule = 0x5622b8bbc820 "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='com.redhat.tuned'"
        signal_data = 0x5622b8c437b0
        subscriber = {callback = 0x7ff489ec7080 <on_name_owner_changed>, user_data = 0x1b, user_data_free_func = 0x0, id = 117, context = 0x5622b8bc78f0}
        signal_data_array = <optimized out>
        sender_unique_name = 0x7ff489efb5ba "org.freedesktop.DBus"
        __FUNCTION__ = "g_dbus_connection_signal_subscribe"
#5  0x00007ff489ec6d22 in has_connection (client=0x5622b8e04590) at ../gio/gdbusnamewatching.c:488
No locals.
#6  0x00007ff489ec7632 in g_bus_watch_name_on_connection (connection=0x5622b8bd9790, name=0x5622b8c5dc00 "com.redhat.tuned", 
    flags=flags@entry=G_BUS_NAME_WATCHER_FLAGS_AUTO_START, name_appeared_handler=name_appeared_handler@entry=0x5622b6faa8b0 <on_name_appeared>, 
    name_vanished_handler=name_vanished_handler@entry=0x5622b6faa7f0 <on_name_vanished>, user_data=user_data@entry=0x5622b8bf1b80, user_data_free_func=0x0)
    at ../gio/gdbusnamewatching.c:687
        client = 0x5622b8e04590
        __FUNCTION__ = "g_bus_watch_name_on_connection"
#7  0x00005622b6fa5ec9 in process_connection (self=self@entry=0x5622b8bf1b80, error=error@entry=0x0) at src/bridge/cockpitdbusjson.c:2775
        channel = <optimized out>
        flags = G_BUS_NAME_WATCHER_FLAGS_AUTO_START
#8  0x00005622b6faa5aa in cockpit_dbus_json_prepare (channel=<optimized out>) at src/bridge/cockpitdbusjson.c:3034
        bus_address = 0x5622b8be7ca0 "unix:path=/var/run/dbus/system_bus_socket"
        key = 0x5622b8c4db40 "cockpit1:x0.cockpit.lan/system:unix:path=/var/run/dbus/system_bus_socket"
        error = 0x0
        connection = <optimized out>
        flags = G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT
        self = 0x5622b8bf1b80
        options = <optimized out>
        bus = 0x5622b8c33eb0 "system"
        address = 0x0
        group = 0x7ff470014b00 "cockpit1:x0.cockpit.lan/system"
        internal = <optimized out>
#9  0x00005622b6fcb531 in on_idle_prepare (data=data@entry=0x5622b8bf1b80) at src/common/cockpitchannel.c:146
        self = 0x5622b8bf1b80
        priv = 0x5622b8bf1ae0
#10 0x00007ff489c78e8b in g_idle_dispatch (source=source@entry=0x5622b8c302d0, callback=0x5622b6fcb4f0 <on_idle_prepare>, user_data=0x5622b8bf1b80)
```

However, this doesn't really give away why that happens. This smells like an @allisonkarlitskaya problem :grin:

**Comment by martinpitt** [comment]
We have not seen these in a while any more.
