### ISSUE TITLE
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#14011]
Recently, storage tests have started to fail with
```
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7fb30d260048>>
```

[example 1](https://logs.cockpit-project.org/logs/pull-824-20200504-050245-c1ebbd08-centos-8-stream-cockpit-project-cockpit/log.html#219-2), [example 2](https://logs.cockpit-project.org/logs/pull-824-20200504-050244-c1ebbd08-rhel-8-3-cockpit-project-cockpit/log.html#219-2)

This seems related to commit cc5157e9fdac2772334032454a3feb9672ef2391 ("storage: Don't leave udevadm processes behind on page reload").

**Comment by martinpitt** [comment]
The full stack trace is not that useful, but I'm fairly sure it's related to the atexit:
```
cockpit-bridge[1812]: Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f0d4eb98048>>
cockpit-bridge[1812]: Traceback (most recent call last):
cockpit-bridge[1812]:   File "/usr/lib64/python3.6/subprocess.py", line 785, in __del__
cockpit-bridge[1812]:     _warn("subprocess %s is still running" % self.pid,
cockpit-bridge[1812]:   File "<stdin>", line 115, in sigexit    
```

**Comment by martinpitt** [comment]
It also happened [in the original PR](https://logs.cockpit-project.org/logs/pull-13983-20200429-093800-7acd8538-rhel-8-3/log.html#263-2), we just merged it overzealously :/
