### ISSUE TITLE
test/common/run-tests fail with BlockingIOError

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#14214]
I've tried using `test/common/run-tests` in cockpit-composer's RHEL gating, but it fails with this stacktrace:

```run-tests:
 Traceback (most recent call last):
  File "test/common/run-tests", line 316, in <module>
    sys.exit(main())
  File "test/common/run-tests", line 312, in main
    return run(opts, image)
  File "test/common/run-tests", line 233, in run
    retry_reason, test_result = finish_test(opts, test)
  File "test/common/run-tests", line 70, in finish_test
    print_test(test, not opts.list)
  File "test/common/run-tests", line 45, in print_test
    sys.stdout.buffer.write(line)
BlockingIOError: [Errno 11] write could not complete without blocking
```

I cannot reproduce this on my machine, and it doesn't happen in upstream CI.

**Comment by martinpitt** [comment]
I [saw the same](https://jenkins.osci.redhat.com/job/rhel-8-pr-pipeline/4929/artifact/package-tests/cockpit/logs/FAIL-str_verify.log).
