### ISSUE TITLE
NetworkManager can get broken in nond tests on ubuntu-stable

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14877]
See for example [this](https://logs.cockpit-project.org/logs/pull-14875-20201106-104848-2dd3c321-ubuntu-stable/log.html#153-2) run.

We see logs like:
```
# testActive (__main__.TestBonding)
Error: NetworkManager is not running.
Error: NetworkManager is not running.
Error: NetworkManager is not running.
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/netlib.py", line 97, in setUp
    print(m.execute("nmcli con show"))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'nmcli con show' returned non-zero exit status 8.
```

Last successful ND test was:
```
# testNoService (__main__.TestNetworkingBasic)
NAME    UUID                                  TYPE    DEVICE 
virbr0  3467843d-7a9f-4c5b-8f15-894a4b863fc5  bridge  virbr0 


DevTools listening on ws://127.0.0.1:9832/devtools/browser/7a1c4664-32f9-4e07-9142-062a664219ea
[1106/111909.978949:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1106/111909.983006:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$41bf4781d0caa050039ecb7b56fb0a2aab356fda6ae196121e9a56dc53369e7a/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1604661551048.815,"url":"http://127.0.0.2:9091/network"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Removed /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service.
Removed /etc/systemd/system/multi-user.target.wants/NetworkManager.service.
Removed /etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service.
> log: 
> log: 
> warning: transport closed: disconnected
# Result testNoService (__main__.TestNetworkingBasic) succeeded
# 1 TEST PASSED [22s on 1-ci-srv-02]
ok 152 test/verify/check-networking-basic TestNetworkingBasic.testNoService [ND]
```

I would like to collect more runs like this to see if it always starts to be broken from the same test or if it is random.

**Comment by marusak** [comment]
https://logs.cockpit-project.org/logs/pull-14927-20201119-104043-0eba091a-ubuntu-stable/log.html#153-2 another example
Last successful ND test was:
```
DevTools listening on ws://127.0.0.1:9525/devtools/browser/a7d041e1-d047-417e-b663-be07a687e0f1
[1119/112222.259358:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1119/112222.260954:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9191/cockpit/@localhost/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1605784943082.885,"url":"http://127.0.0.2:9191/network/firewall"}
> warning: 
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
# Result testAddCustomServices (__main__.TestFirewall) succeeded
# 1 TEST PASSED [22s on 2-cockpit-10]
ok 164 test/verify/check-networking-firewall TestFirewall.testAddCustomServices [ND]
# ----------------------------------------------------------------------
# testNondestructive (__main__.TestExample)

DevTools listening on ws://127.0.0.1:9920/devtools/browser/8158f5f0-47e8-4b7d-a6dc-a9c1a7b479cf
[1119/112244.700787:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1119/112244.702392:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9191/cockpit/@localhost/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1605784965523.942,"url":"http://127.0.0.2:9191/system"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
# Result testNondestructive (__main__.TestExample) succeeded
# 1 TEST PASSED [6s on 2-cockpit-10]
ok 39 test/verify/check-example TestExample.testNondestructive [ND]

```

in both cases `TestFirewall.testMultipleZones` failed before this test.

**Comment by marusak** [comment]
Ok, I know how the firewall test can fail. I can fake this behavior easily (it is actual bug that I'll send fix for) so now I'll try to see if it actually can break the VM. If that is the case, I'll fix this issue with the aforementioned fix.

**Comment by marusak** [comment]
```
RuntimeError: TypeError: Cannot read property 'filter' of undefined

# Result testMultipleZones (__main__.TestFirewall) failed
# 1 TEST FAILED [6s on vypocetnik]
not ok 1 test/verify/check-networking-firewall TestFirewall.testMultipleZones [ND]# ----------------------------------------------------------------------
# testActive (__main__.TestBonding)
NAME    UUID                                  TYPE    DEVICE 
virbr0  7705cd19-b9b3-4392-8e37-881de9f2d92c  bridge  virbr0 


DevTools listening on ws://127.0.0.1:9806/devtools/browser/284c7ede-52b2-43a8-815d-377ef30f2ee2
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$da50a5e7a21ba3d4f8a2390fe7c2ac818ed35bb34fa99d52756880c963b704f6/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1605794316897.496,"url":"http://127.0.0.2:9091/network"}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: 
> log: mac
> warning: transport closed: disconnected
# Result testActive (__main__.TestBonding) succeeded
# 1 TEST PASSED [13s on vypocetnik]
ok 2 test/verify/check-networking-bond TestBonding.testActive [ND]
```

ok, so it was not it. This failing test does not break the VM. But at least I have fix for that firewall oops.
