### ISSUE TITLE
unit tests fail if chromium is available, but not node_modules/

### ISSUE THREAD

**Issue by fluxcap1** [cockpit-project/cockpit#15116]
Cockpit version: 199
OS: openSUSE Leap Version 15.2

I am trying to compile and install cockpit-199 from source, my configuration and make succeeds but the check fails.

Running configure as -
````./configure --prefix=/usr --sbindir=/usr/bin --sysconfdir=/etc --localstatedir=/var --disable-pcp --disable-doc
````
Make status -
````
.
.
.
CCLD     pam_ssh_add.so
rm src/ws/ca.po pkg/pcp/manifest.json pkg/shell/manifest.json pkg/apps/manifest.json pkg/dashboard/manifest.json pkg/ssh/manifest.json src/ws/cs.po src/ws/ko.po pkg/realmd/manifest.json src/ws/zh_TW.po src/ws/pt_BR.po pkg/users/manifest.json pkg/systemd/manifest.json src/ws/es.po pkg/networkmanager/manifest.json pkg/kdump/manifest.json pkg/storaged/manifest.json src/ws/pl.po pkg/playground/manifest.json src/ws/uk.po pkg/machines/manifest.json src/ws/ru.po src/ws/it.po pkg/tuned/manifest.json src/ws/fi.po pkg/sosreport/manifest.json pkg/selinux/manifest.json src/ws/zh_CN.po pkg/docker/manifest.json src/ws/fr.po src/ws/de.po src/ws/ja.po pkg/packagekit/manifest.json src/ws/sv.po
make[1]: Leaving directory '/usr/local/src/cockpit-199'
````
The make check error -
````
[Fri Jan 08 22:00:49 root@flux /usr/local/src/cockpit-199] 
# make check
make  check-am
make[1]: Entering directory '/usr/local/src/cockpit-199'
make  test-server 
make[2]: Entering directory '/usr/local/src/cockpit-199'
make[2]: Leaving directory '/usr/local/src/cockpit-199'
make  check-TESTS check-local
make[2]: Entering directory '/usr/local/src/cockpit-199'
make[3]: Entering directory '/usr/local/src/cockpit-199'
PASS: pkg/users/test-list-public-keys.sh 1 mock/ssh/1-input
PASS: pkg/users/test-list-public-keys.sh 2 mock/ssh/2-input
PASS: pkg/users/test-list-public-keys.sh 3 mock/ssh/3-input
authorized_keys is not a public key file.
PASS: pkg/users/test-list-public-keys.sh 4 mock/ssh/4-input

DevTools listening on ws://127.0.0.1:9920/devtools/browser/97601b34-aeaf-471c-b949-73b12e311d00
[0108/220208.173171:ERROR:gl_initializer_linux_x11.cc(122)] eglGetProcAddress not found.
[0108/220208.175612:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[0108/220208.194623:WARNING:vaapi_wrapper.cc(523)] VAAPI video acceleration not available for disabled
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'chrome-remote-interface'
Require stack:
- /usr/local/src/cockpit-199/test/common/cdp-driver.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/src/cockpit-199/test/common/cdp-driver.js:31:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/src/cockpit-199/test/common/cdp-driver.js' ]
}
Traceback (most recent call last):
  File "./test/common/tap-cdp", line 77, in <module>
    cdp.invoke("Page.navigate", url=address + '/' + opts.test)
  File "/usr/local/src/cockpit-199/test/common/cdp.py", line 85, in invoke
    res = self.command(cmd)
  File "/usr/local/src/cockpit-199/test/common/cdp.py", line 102, in command
    raise RuntimeError("CDP broken")
RuntimeError: CDP broken
````

I tried building a rpm from src.rpm but the error is persistent. Please help.

**Comment by fluxcap1** [comment]
For some reason configure parameter vanished above -
````
./configure --prefix=/usr --sbindir=/usr/bin --sysconfdir=/etc --localstatedir=/var --disable-pcp --disable-doc
````

**Comment by martinpitt** [comment]
The "eglGetProcAddress not found" is irrelevant, it's just some logging of chromium. The real error is

    Error: Cannot find module 'chrome-remote-interface'
    
This is because you have chromium (or chrome) installed, but did not run `npm install` to make the [chrome-remote-interface](https://www.npmjs.com/package/chrome-remote-interface) module available.

So either drop chromium from your build environment (which is what I'd recommend), or you need to at least run

    npm install chrome-remote-interface

during the build (this needs internet access, or you need to include node_modules/chrome-remote-interface into your tarball).

Upstream we may fix that by only running the browser unit tests if  both a browser and node_modules/ exist.

**Comment by fluxcap1** [comment]
> The "eglGetProcAddress not found" is irrelevant, it's just some logging of chromium. The real error is
> 
> ```
> Error: Cannot find module 'chrome-remote-interface'
> ```
> 
> This is because you have chromium (or chrome) installed, but did not run `npm install` to make the [chrome-remote-interface](https://www.npmjs.com/package/chrome-remote-interface) module available.
> 
> So either drop chromium from your build environment (which is what I'd recommend), or you need to at least run
> 
> ```
> npm install chrome-remote-interface
> ```
> 
> during the build (this needs internet access, or you need to include node_modules/chrome-remote-interface into your tarball).
> 
> Upstream we may fix that by only running the browser unit tests if both a browser and node_modules/ exist.

I have user installed chrome-remote-interface

````
[Sat Jan 09 01:41:19 flux@flux ~] 
# npm list -g
/usr/local/lib
└─┬ chrome-remote-interface@0.29.0
  ├── commander@2.11.0
  └── ws@7.4.2
````

**Comment by fluxcap1** [comment]
After purging the source, extracting the tar and `npm install chrome-remote-interface` I compiled and installed cockit-199.
