### ISSUE TITLE
check-storage-mounting TestStorageMounting.testEncryptedMountingHelp fails a lot on debian-testing

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#16358]
[This failure](https://logs.cockpit-project.org/logs/pull-14109-20210915-131047-376af3d1-debian-testing/log.html#182-2) happens all the time (also in [other PRs](https://logs.cockpit-project.org/logs/pull-16342-20210915-090454-0c7df0ed-debian-testing/log.html), it's not specific to this one). The [screenshot](https://logs.cockpit-project.org/logs/pull-14109-20210915-131047-376af3d1-debian-testing/TestStorageMounting-testEncryptedMountingHelp-debian-testing-127.0.0.2-2801-FAIL.png) shows a "No such interface" D-Bus error.

At first I thought it was a symptom of the dbus proxy bug that you fixed two days ago, but it still happens. curiously, the journal says nothing about "dm_2d" at all. But it feels like a device disappearing underneath udisks unexpectedly/. 

```
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-mounting", line 234, in testEncryptedMountingHelp
    self.dialog({"passphrase": "vainu-reku-toma-rolle-kaja"})
testlib.Error: timeout
wait_js_cond(ph_is_present("#dialog [data-field=\"passphrase\"]")): Uncaught (in promise) Error: condition did not become true
```

[journal](https://logs.cockpit-project.org/logs/pull-14109-20210915-131047-376af3d1-debian-testing/TestStorageMounting-testEncryptedMountingHelp-debian-testing-127.0.0.2-2801-FAIL.log.gz)

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit/issues/14109#issuecomment-920106847_

**Comment by martinpitt** [comment]
This does reproduce locally with some effort:

    while TEST_OS=debian-testing test/verify/check-storage-mounting TestStorageMounting.testEncryptedMountingHelp -stv; do :; done

I also got another failure a bit later on:
```
Traceback (most recent call last):
  File "/var/home/martin/upstream/cockpit/test/verify/check-storage-mounting", line 243, in testEncryptedMountingHelp
    b.wait_not_present(fsys_tab + " button:contains(Do not mount automatically on boot)")
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 421, in wait_not_present
```
but it's the same symptom -- the screenshot shows the same error message.
