### ISSUE TITLE
check-multi-machine fails

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1654]
This seems like a race. check-multi-machine fails most of the time here on my machine. This happened after @mvollmer updated images. A bug in the system is suspect.

**Comment by stefwalter** [comment]
![check-multi-machine-testbasic-fail](https://cloud.githubusercontent.com/assets/795070/5736367/4d34f50e-9bd5-11e4-9fe7-2cd6b6f82c33.png)

**Comment by stefwalter** [comment]
The main machine logs say:

```
Jan 14 10:58:16 localhost.localdomain cockpit-ws[751]: 10.111.111.16: couldn't authenticate: Socket error: disconnected
```

The machine being added says:

```
Jan 14 10:58:16 localhost.localdomain sshd[722]: Connection closed by 10.111.111.14 [preauth]
Jan 14 10:58:16 localhost.localdomain sshd[724]: Failed password for admin from 10.111.111.14 port 54774 ssh2
Jan 14 10:58:16 localhost.localdomain sshd[724]: fatal: Access denied for user admin by PAM account configuration [preauth]
```

**Comment by stefwalter** [comment]
Backtrace

```
======================================================================
ERROR: testBasic (__main__.TestMultiMachine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-multi-machine", line 96, in testBasic
    add_machine(b, m3.address)
  File "./check-multi-machine", line 53, in add_machine
    b.wait_text('#dashboard_setup_next', "Add host")
  File "/data/src/cockpit/test/testlib.py", line 225, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/data/src/cockpit/test/testlib.py", line 201, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/data/src/cockpit/test/testlib.py", line 506, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/data/src/cockpit/test/testlib.py", line 472, in run
    raise Error("timeout")
Error: timeout

----------------------------------------------------------------------
Ran 1 test in 738.207s
```

**Comment by stefwalter** [comment]
Tried removing ```wait_for_port()``` as I thought it was confusing things, but had no effect.
