### ISSUE TITLE
@nd NFS tests on TMT (packit)

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#17142]
So, after some debugging with TMT a few times I manged to get screenshots and some output:

```
14:17:42                 out: -> wait: ph_has_val("#dialog [data-field=\"remote\"]","/home/foo")
14:17:42                 out: <- {'exceptionDetails': {'exception': {'type': 'string', 'value': 'timeout'}}}
14:17:42                 out: Traceback (most recent call last):
14:17:42                 out:   File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
14:17:42                 out:     method()
14:17:42                 out:   File "/var/tmp/tmt/run-012/plans/all/discover/default/tests/test/verify/check-storage-nfs", line 47, in testNfsClient
14:17:42                 out:     self.dialog_set_val("remote", "/home/foo")
14:17:42                 out:   File "/var/tmp/tmt/run-012/plans/all/discover/default/tests/test/verify/storagelib.py", line 269, in dialog_set_val
14:17:42                 out:     self.browser.set_input_text(sel, val)
14:17:42                 out:   File "/var/tmp/tmt/run-012/plans/all/discover/default/tests/test/common/testlib.py", line 402, in set_input_text
14:17:42                 out:     self.wait_val(selector, val)
14:17:42                 out:   File "/var/tmp/tmt/run-012/plans/all/discover/default/tests/test/common/testlib.py", line 487, in wait_val
14:17:42                 out:     self.wait_js_func('ph_has_val', selector, val)
14:17:42                 out:   File "/var/tmp/tmt/run-012/plans/all/discover/default/tests/test/common/testlib.py", line 467, in wait_js_func
14:17:42                 out:     self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
14:17:42                 out:   File "/var/tmp/tmt/run-012/plans/all/discover/default/tests/test/common/testlib.py", line 457, in wait_js_cond
14:17:42                 out:     self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
14:17:42                 out:   File "/var/tmp/tmt/run-012/plans/all/discover/default/tests/test/common/testlib.py", line 241, in raise_cdp_exception
14:17:42                 out:     raise Error("%s(%s): %s" % (func, arg, msg))
14:17:42                 out: testlib.Error: timeout
```

![image](https://user-images.githubusercontent.com/67428/158441904-a93b8900-e3c3-4928-bc67-3722c204b1dc.png)

Locally I can at least reproduce the empty input field, but the test passes.

So in the test it goes into:
```
          elif ftype == "text-input":
              self.browser.set_input_text(sel, val)
```

While the shown component is:

```
<div data-field="remote" data-field-type="combobox"><div class="pf-c-select" data-ouia-component-type="PF4/Select" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Select-typeahead-1"><div class="pf-c-select__toggle pf-m-typeahead"><div class="pf-c-select__toggle-wrapper"><input class="pf-c-form-control pf-c-select__toggle-typeahead" id="pf-select-toggle-id-0-select-typeahead" aria-label="" placeholder="" type="text" autocomplete="off" value=""></div><button id="pf-select-toggle-id-0" aria-labelledby=" pf-select-toggle-id-0" aria-expanded="false" aria-haspopup="listbox" type="button" class="pf-c-button pf-c-select__toggle-button pf-m-plain" aria-label="Options menu" tabindex="-1"><svg style="vertical-align: -0.125em;" fill="currentColor" height="1em" width="1em" viewBox="0 0 320 512" aria-hidden="true" role="img" class="pf-c-select__toggle-arrow"><path d="M31.3 192h257.3c17.8 0 26.7 21.5 14.1 34.1L174.1 354.8c-7.8 7.8-20.5 7.8-28.3 0L17.2 226.1C4.6 213.5 13.5 192 31.3 192z"></path></svg></button></div></div></div>
```

Adding a bunch of `time.sleep`'s before `remote` seems to fix it locally with tmt:

```
        time.sleep(4)
        self.dialog_set_val("remote", "/home/foo")
```

So it's a fun race condition...

@mvollmer do you have an idea how we can stop this from flaking? On TMT the issue is that the tests are run a bit slower so while checking if the input has the correct value it has been changed into Typeahead by the dialog. I think the solution would be to stop replacing the Input by a Typeahead or disable it while loading.

Additionally when editing an nfs share I noticed that the "Path on server" field does not select the correct path but shows an empty field. (Related issue).

_Originally posted by @jelly in https://github.com/cockpit-project/cockpit/pull/17005#issuecomment-1068307332_

**Comment by mvollmer** [comment]
@jelly, right, with your investigation, this should be easy to solve: the `ComboBox` dialog element render as a "textinput" when there are no choices to pick from, see f0dd29c421fe0295d234dbfbc80348be513a66dc.  Since the choices are retrieved in the background while the dialog is open, the test needs to wait for this to stabilize. By waiting for `[data-field=remote][data-field-type=combobox]` to be present, say.

**Comment by jelly** [comment]
Would it be a problem if we change the Combox box into a typeahead or should it also be able to input text as a textinput?
