### ISSUE TITLE
Python 3.11 test suite compatibility

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#17491]
Our test suite depends on private classes/members in Python's unittest module, which changed in [Python 3.11](https://github.com/python/cpython/commit/664448d81f41c5fa971d8523a71b0f19e76cc136#diff-c6fe1ffe930def48a6adf1fa99b974737bac586fdacccacd1474e7b2f11370ebL79).

we override the `unittest.case._Outcome` class in `_DebugOutcome` and modify `testPartExecutor` so we can print the exception and take a snapshot, copy journal, JavaScript errors and coredumps. Finaly sit() is invoked if opts.sit is True.

In Python 3.11 the errors member no longer exists and errors are now recorded in `result` however, they errors are not appended anymore.

Fixing `sit()` is easy we can move it to tearDown() but we need to detect when an error occurs.

Interesting links:
https://stackoverflow.com/questions/4414234/getting-pythons-unittest-results-in-a-teardown-method
https://stackoverflow.com/questions/30647772/python-unittest-do-something-only-if-test-fails

Small reproducer:

```
#!/bin/python

import unittest


class _DebugOutcome(unittest.case._Outcome):
    """Run debug actions after test methods
    This will do screenshots, HTML dumps, and sitting before cleanup handlers run.
    """
    def testPartExecutor(self, test_case, isTest=False):
        print(f"testPartExecutor, testcase: {test_case}, isTest: {isTest}")
        # we want to do the debug actions after the test function got called (isTest==True), but before
        # TestCase.run() calls tearDown(); thus remember whether we are after isTest and already ran
        if isTest:
            self.ran_debug = False
        else:
            print(getattr(self, "ran_debug", None))
            if getattr(self, "ran_debug", None) is False:
                print("Our special runner runs now")
                self.ran_debug = True

        return super().testPartExecutor(test_case, isTest)


unittest.case._Outcome = _DebugOutcome
class MachineCase(unittest.TestCase):

    def test_good(self):
        self.assertEqual(1, 1)

    def test_fail(self):
        self.assertEqual(1, 2)
```

On python 3.11
```
[jelle@toolbox][~/projects/cockpit/python3.11]%python3 -m unittest example.py
testPartExecutor, testcase: test_fail (example.MachineCase.test_fail), isTest: False
None
testPartExecutor, testcase: test_fail (example.MachineCase.test_fail), isTest: False
None
FtestPartExecutor, testcase: test_fail (example.MachineCase.test_fail), isTest: False
None
testPartExecutor, testcase: test_good (example.MachineCase.test_good), isTest: False
None
testPartExecutor, testcase: test_good (example.MachineCase.test_good), isTest: False
None
testPartExecutor, testcase: test_good (example.MachineCase.test_good), isTest: False
None
```

On Python 3.10
```
[jelle@t14s][~/projects/cockpit/python3.11]%python3 -m unittest example.py                                                                                          [12/46]
testPartExecutor, testcase: test_fail (example.MachineCase), isTest: False
None
testPartExecutor, testcase: test_fail (example.MachineCase), isTest: True
testPartExecutor, testcase: test_fail (example.MachineCase), isTest: False
False
Our special runner runs now
FtestPartExecutor, testcase: test_good (example.MachineCase), isTest: False
None
testPartExecutor, testcase: test_good (example.MachineCase), isTest: True
testPartExecutor, testcase: test_good (example.MachineCase), isTest: False
False
Our special runner runs now
```

**Comment by martinpitt** [comment]
Thanks for digging out these stackoverflow questions! How about something like this?

```py
#!/bin/python

import unittest

class MachineCase(unittest.TestCase):
    def handleFailure(self, testcase, exc_info):
        print("XXX handleFailure testcase", testcase, "exc_info", exc_info)

    def run(self, result=None):
        if result:
            errs = len(result.errors)
            fails = len(result.failures)

        super().run(result)

        if result:
            if len(result.errors) > errs:
                self.handleFailure(*result.errors[-1])
            elif len(result.failures) > fails:
                self.handleFailure(*result.failures[-1])

    def test_1_good(self):
        self.assertEqual(1, 1)

    def test_fail(self):
        self.assertEqual(1, 2)

    def test_err(self):
        open("/nonexisting")

    def test_good(self):
        self.assertEqual(1, 1)
```

This works with Python 3.10 and 3.11 in the same way:
```
❱❱❱ python3 -m unittest onfail.py -v
test_1_good (onfail.MachineCase) ... ok
test_err (onfail.MachineCase) ... ERROR
XXX handleFailure testcase test_err (onfail.MachineCase) exc_info Traceback (most recent call last):
  File "/var/home/martin/onfail.py", line 29, in test_err
    open("/nonexisting")
FileNotFoundError: [Errno 2] No such file or directory: '/nonexisting'

test_fail (onfail.MachineCase) ... FAIL
XXX handleFailure testcase test_fail (onfail.MachineCase) exc_info Traceback (most recent call last):
  File "/var/home/martin/onfail.py", line 26, in test_fail
    self.assertEqual(1, 2)
AssertionError: 1 != 2

test_good (onfail.MachineCase) ... ok

======================================================================
ERROR: test_err (onfail.MachineCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/home/martin/onfail.py", line 29, in test_err
    open("/nonexisting")
FileNotFoundError: [Errno 2] No such file or directory: '/nonexisting'

======================================================================
FAIL: test_fail (onfail.MachineCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/home/martin/onfail.py", line 26, in test_fail
    self.assertEqual(1, 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 4 tests in 0.000s

FAILED (failures=1, errors=1)
```

**Comment by jelly** [comment]
Podman try out to see if it works https://github.com/cockpit-project/cockpit-podman/pull/1026 previous PRs had failing tests due to 3.11 issues.
