### ISSUE TITLE
_variables.scss is imported multiple times (5 times!)

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#17556]
### Explain what happens

1. Browser to https://127.0.0.1:9090/users
2. Open developer tools
3. Click inspect element and select the `body` of the users page
4. Look at the `styles` imported and notice that `:root { }` is imported multiple times from `_variables.scss`

What seems to happen is:

`pkg/lib/users.scss` imports `@import "global-variables.scss";` which imports `@import "@patternfly/patternfly/base/patternfly-variables.scss";` to override the breakpoints.

variables.scss is imported multiple times, probably the cause of our issue.
```
[jelle@t14s][~/projects/cockpit/dark-theme]%git grep variables.scss
pkg/Makefile.am:        pkg/lib/patternfly/patternfly-overrides-variables.scss \
pkg/lib/_global-variables.scss:@import "@patternfly/patternfly/base/patternfly-variables.scss";
pkg/lib/cockpit-components-table.scss:@use "@patternfly/patternfly/base/patternfly-variables.scss";
pkg/lib/ct-card.scss:@use "_global-variables.scss" as *;
pkg/systemd/logs.scss:@import "global-variables.scss";
pkg/systemd/services/service-details.scss:@use "_global-variables.scss";
pkg/users/users.scss:@import "global-variables.scss";
pkg/users/users.scss:// @import "@patternfly/patternfly/sass-utilities/scss-variables.scss";
webpack.config.js:                // [Redefine grid breakpoints] section in pkg/lib/_global-variables.scss for more details
```

```
[jelle@t14s][~/projects/cockpit/dark-theme]%git grep patternfly-variables
pkg/lib/_global-variables.scss:@import "@patternfly/patternfly/base/patternfly-variables.scss";
pkg/lib/cockpit-components-table.scss:@use "@patternfly/patternfly/base/patternfly-variables.scss";
```

**Comment by garrett** [comment]
Breakpoints are separate from this problem. This problem is with `:root {}` PF varibles being imported several times.

**Comment by jelly** [comment]
We can't import `scss-variables.scss` as it depends on `$pf-color-white`

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
   ╷
26 │ $pf-global--BackgroundColor--100: $pf-color-white !default;
   │                                   ^^^^^^^^^^^^^^^
   ╵
  node_modules/@patternfly/patternfly/sass-utilities/scss-variables.scss 26:35  @import
  pkg/lib/_global-variables.scss 1:9                                            @use
  pkg/lib/ct-card.scss 1:1                                                      @use
  pkg/users/users.scss 1:1                                                      root stylesheet
    at processResult (/home/jelle/projects/cockpit/dark-theme/node_modules/webpack/lib/NormalModule.js:758:19)
    at /home/jelle/projects/cockpit/dark-theme/node_modules/webpack/lib/NormalModule.js:860:5
    at /home/jelle/projects/cockpit/dark-theme/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /home/jelle/projects/cockpit/dark-theme/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/home/jelle/projects/cockpit/dark-theme/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/jelle/projects/cockpit/dark-theme/node_modules/sass-loader/dist/index.js:69:5)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:442:9)

2 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.72.0 compiled with 4 errors in 13093 ms
```

**Comment by jelly** [comment]
`pkg/users/authorized-keys-panel.jsx` should be ported to PF4 JSX components instead of using PF html, that would also help out a bit.

**Comment by jelly** [comment]
So the easiest package to look at is probably `networkmanager`, the `firewall.css` file has a duplicate `:root {}` which is almost the same except:

![image](https://user-images.githubusercontent.com/67428/179002127-b63312e8-5e30-4ea2-b8a4-db453b005eed.png)

`patternfly-fonts-fake-path` comes from `pkg/lib/patternfly/patternfly-4-cockpit.scss`
`./assets/fonts` comes from `@patternfly/patternfly/base/patternfly-variables.css`

```
[jelle@t14s][~/projects/cockpit/pf-css-removal]%git grep patternfly-4-cockpit.scss pkg/networkmanager
pkg/networkmanager/app.jsx:import '../lib/patternfly/patternfly-4-cockpit.scss';
pkg/networkmanager/firewall.jsx:import '../lib/patternfly/patternfly-4-cockpit.scss';
```

So app.jsx is for the `network` page and `firewall.jsx` for the firewall page these also have a seperate html file so that should be fine.

**Comment by jelly** [comment]
Checking our pf-global-font-path includes again with our latest main, I get:

```
[jelle@t14s][~/projects/cockpit/main]%zgrep -c "\-\-pf-global--font-path" dist/*/*.css.gz

dist/apps/apps.css.gz:1
dist/kdump/kdump.css.gz:1
dist/metrics/index.css.gz:1
dist/networkmanager/firewall.css.gz:1
dist/networkmanager/network.css.gz:1
dist/packagekit/updates.css.gz:1
dist/playground/exception.css.gz:1
dist/playground/index.css.gz:1
dist/playground/journal.css.gz:1
dist/playground/metrics.css.gz:1
dist/playground/pkgs.css.gz:1
dist/playground/plot.css.gz:0
dist/playground/react-patterns.css.gz:1
dist/playground/service.css.gz:1
dist/playground/speed.css.gz:1
dist/playground/test.css.gz:1
dist/playground/translate.css.gz:1
dist/selinux/selinux.css.gz:1
dist/shell/index.css.gz:1
dist/sosreport/sosreport.css.gz:1
dist/storaged/storage.css.gz:1
dist/systemd/hwinfo.css.gz:1
dist/systemd/logs.css.gz:1
dist/systemd/overview.css.gz:1
dist/systemd/services.css.gz:1
dist/systemd/terminal.css.gz:1
dist/tuned/performance.css.gz:0
dist/users/users.css.gz:1
```

**Comment by jelly** [comment]
Looking at our css with `css-purge`

```
[jelle@t14s][~/projects/cockpit/webpack-profile]%npx css-purge -v -i dist/selinux/selinux.css -o selinux.css
Input - CSS File : dist/selinux/selinux.css
Process - CSS
Process - Rules - Remove Comment
Process - Rules - Group Duplicate Rule : .pf-c-divider
Process - Rules - Group Duplicate Rule : .pf-c-divider::after
Process - Rules - Group Duplicate Rule : .pf-c-alert
Process - Rules - Group Duplicate Rule : .pf-c-alert__title
Process - Rules - Group Duplicate Rule : .pf-l-flex
Process - Rules - Group Duplicate Rule : .pf-c-page__sidebar.pf-m-light
Process - Rules - Group Duplicate Rule : .pf-c-page__sidebar.pf-m-light
Process - Declaration - Group Duplicate Declarations : .pf-c-page__sidebar.pf-m-light - --pf-global--Color--100
Process - Declaration - Group Duplicate Declarations : .pf-c-page__sidebar.pf-m-light - --pf-global--Color--200
Process - Declaration - Group Duplicate Declarations : .pf-c-page__sidebar.pf-m-light - --pf-global--BorderColor--100
Process - Declaration - Group Duplicate Declarations : .pf-c-page__sidebar.pf-m-light - --pf-global--primary-color--100
Process - Declaration - Group Duplicate Declarations : .pf-c-page__sidebar.pf-m-light - --pf-global--link--Color
Process - Declaration - Group Duplicate Declarations : .pf-c-page__sidebar.pf-m-light - --pf-global--link--Color--hover
Process - Declaration - Group Duplicate Declarations : .pf-c-page__sidebar.pf-m-light - --pf-global--BackgroundColor--100
Process - Rules - Group Duplicate Rule : .pf-c-page__header-tools-group, .pf-c-page__header-tools-item
```

Note, that's just a snippet from the output.

```
[jelle@t14s][~/projects/cockpit/webpack-profile]%grep .pf-c-page__sidebar.pf-m-light dist/selinux/selinux.css
.pf-c-page__sidebar.pf-m-light {
.pf-c-page__sidebar.pf-m-light, .pf-t-light {
.pf-c-page__sidebar.pf-m-light {
.pf-c-page__sidebar.pf-m-light {
```

The first and last declarations look the same to me.

**Comment by garrett** [comment]
> The SELinux page has a minimal set of imports, one of them is @use "page" which imports page.scss which imports @import "@patternfly/patternfly/components/Page/page.scss";

Probably due to rewriting breakpoint variables in SASS?

Can WebPack let us just rewrite the px values for `@media.*-width: .*px` after compilation? It'd be less hacky than trying to work around it in CSS, really, as we import both SCSS and (already compiled) CSS, and not everything is doing the right thing right now.

**Comment by jelly** [comment]
> 



> > The SELinux page has a minimal set of imports, one of them is @use "page" which imports page.scss which imports @import "@patternfly/patternfly/components/Page/page.scss";
> 
> Probably due to rewriting breakpoint variables in SASS?

For that we have `global-variables` right?

> Can WebPack let us just rewrite the px values for `@media.*-width: .*px` after compilation? It'd be less hacky than trying to work around it in CSS, really, as we import both SCSS and (already compiled) CSS, and not everything is doing the right thing right now.

**Comment by garrett** [comment]
> For that we have global-variables right?

Exactly. It's only used when it's included (not used) and then a file comes after it.

This is why there's so much breakpoint mess. We do not have a way to alter breakpoints on files that are included via React only nor do we for any statically included CSS. Or even SCSS that's included without the import.

Ideally, we'd inject the changed variables in PatternFly itself and rebuild PatternFly with it. Otherwise, the next best thing would be to just build everything and adjust the specific breakpoint variables in the resulting CSS afterward. But we're doing neither of these things.

(And we do absolutely *need* to adjust the breakpoints, as PatternFly is incorrectly setting breakpoints when you have iframes with navigation in the mix, which is what we do. They're assuming breakpoints are for whole documents, not partials in iframes like what we have.)

**Comment by garrett** [comment]
Both @jelly and I worked on making this less of a problem.

There's still an issue.

The best approach would be to redo the way we do breakpoints, then this should hopefully not be an issue afterward. Related: https://github.com/cockpit-project/cockpit/issues/17629

**Comment by Venefilyn** [comment]
This should no longer be an issue with the `@use` and `@forward` - closing
