### ISSUE TITLE
testTeam regularly fails

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#17824]
### Explain what happens

I can't reproduce this locally with our fedora-rawhide image, but this keeps failing in all our PR's.

```
Error: Connection activation failed: IP configuration could not be reserved (no available address, timeout, etc.)
```

This sounds like it's some packit specific environment issue. @martinpitt any ideas?

Seems the NIC is stuck in configuring IP

https://artifacts.dev.testing-farm.io/a0b5d072-246e-440b-bba6-44c3a4456488/work-allziB7pq/plans/all/execute/data/test/browser/data/TestTeam-testBasic-fedora-36-localhost-22-FAIL.png

# Result testBasic (__main__.TestTeam.testBasic) failed

https://artifacts.dev.testing-farm.io/a0b5d072-246e-440b-bba6-44c3a4456488/work-allziB7pq/plans/all/execute/data/test/browser/output.txt

```
# ----------------------------------------------------------------------
# testBasic (__main__.TestTeam.testBasic)
NAME             UUID                                  TYPE      DEVICE 
cloud-init eth0  1dd9a779-d327-56e1-8454-c65e2556c12c  ethernet  eth0   

bash: line 1: virsh: command not found
restorecon: SELinux: Could not get canonical path for /tmp/tmps16rf9j2/.mozilla/firefox/* restorecon: No such file or directory.
*** You are running in headless mode.
Warning no default label for /tmp/tmps16rf9j2/.mozilla/firefox/Crash Reports
Warning no default label for /tmp/tmps16rf9j2/.mozilla/firefox/Pending Pings
Warning no default label for /tmp/tmps16rf9j2/.mozilla/firefox/cxxf6kyj.blank
Warning no default label for /tmp/tmps16rf9j2/.mozilla/firefox/profiles.ini
*** You are running in headless mode.
[GFX1-]: glxtest: libGL.so.1 missing
[GFX1-]: glxtest: libEGL missing
WebDriver BiDi listening on ws://127.0.0.1:10188
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
DevTools listening on ws://127.0.0.1:10188/devtools/browser/fe37d40e-cc60-469e-b617-ae8a85224353
> warning: failed to poll tuned [object Object]
CDP: {"source":"other","level":"warning","text":"XrayWrapper denied access to property \"toString\" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.","timestamp":1665677810292,"url":"chrome://remote/content/cdp/sessions/ContentProcessSession.jsm","lineNumber":57}
> warning: [object Object]
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /30_ecbdcbcc : {"command":"close","channel":"1:2!5"}
> warning: loading available updates failed: {"detail":"PackageKit crashed","code":"close"}
Error: Connection activation failed: IP configuration could not be reserved (no available address, timeout, etc.)
Hint: use 'journalctl -xe NM_CONNECTION=8982d977-3634-48c0-833a-de196a284f12 + NM_DEVICE=cockpit1' to get more details.
Traceback (most recent call last):
  File "/var/ARTIFACTS/work-allziB7pq/plans/all/discover/default/tests/test/verify/check-networkmanager-team", line 40, in testBasic
    self.nm_activate_eth(iface1)
  File "/var/ARTIFACTS/work-allziB7pq/plans/all/discover/default/tests/test/common/netlib.py", line 58, in nm_activate_eth
    m.execute(f"nmcli con up {iface} ifname {iface}")
  File "/var/ARTIFACTS/work-allziB7pq/plans/all/discover/default/tests/bots/machine/machine_core/ssh_connection.py", line 307, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', 'localhost', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-30077', 'set -e;', 'nmcli con up cockpit1 ifname cockpit1']' returned non-zero exit status 4.

Wrote screenshot to TestTeam-testBasic-fedora-36-localhost-22-FAIL.png
Wrote HTML dump to TestTeam-testBasic-fedora-36-localhost-22-FAIL.html
Wrote JS log to TestTeam-testBasic-fedora-36-localhost-22-FAIL.js.log
Journal extracted to TestTeam-testBasic-fedora-36-localhost-22-FAIL.log.gz
> warning: transport closed: disconnected
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Traceback (most recent call last):
  File "/var/ARTIFACTS/work-allziB7pq/plans/all/discover/default/tests/test/verify/check-networkmanager-team", line 40, in testBasic
    self.nm_activate_eth(iface1)
  File "/var/ARTIFACTS/work-allziB7pq/plans/all/discover/default/tests/test/common/netlib.py", line 58, in nm_activate_eth
    m.execute(f"nmcli con up {iface} ifname {iface}")
  File "/var/ARTIFACTS/work-allziB7pq/plans/all/discover/default/tests/bots/machine/machine_core/ssh_connection.py", line 307, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', 'localhost', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-30077', 'set -e;', 'nmcli con up cockpit1 ifname cockpit1']' returned non-zero exit status 4.

# Result testBasic (__main__.TestTeam.testBasic) failed
# 1 TEST FAILED [92s on ip-172-31-17-67]
not ok 25 test/verify/check-networkmanager-team TestTeam.testBasic [ND@-1] # RETRY 2 (be robust against unstable tests)
```

**Comment by jelly** [comment]
Maybe a different test influences this test and causes it to flake/fail.

**Comment by martinpitt** [comment]
Retitling to be more specific -- rawhide currently fails for another reason.

**Comment by martinpitt** [comment]
Also, I don't think that's specific to the Testing Farm -- it's one of our [top flakes](https://cockpit-logs.us-east-1.linodeobjects.com/prometheus) on our own CI as well. Only the auto-retry saves us.

**Comment by jelly** [comment]
Strange, I have ran the test 10 times and could never reproduce this. Host related?

**Comment by martinpitt** [comment]
I can reproduce this 100% with running through tmt:

    tmt run --until report provision --how virtual --image fedora-rawhide prepare --how shell --script 'dnf install -y cockpit cockpit-storaged cockpit-tests'

in fact it's even worse, not even a retry works -- it fails three times in a row.

**Comment by jelly** [comment]
Ah ok, tmt doesn't work really well for me on Arch or on toolbox. On toolbox the issue is that the libvirt storage is not in the toolbox so it get's all kinds of confused.

**Comment by KKoukiou** [comment]
Just checked grafana, it's not there anymore.
