### ISSUE TITLE
Unknown / random page gives a KeyError in the Python bridge

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#18214]
### Explain what happens

Go to an unknown page with the Cockpit Python bridge:

For example: http://localhost:9999/wjefiwjfoew
```
asyncio-ERROR: Exception in callback _Transport._read_ready()
handle: <Handle _Transport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/transports.py", line 98, in _read_ready
    self._protocol.data_received(data)
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/protocol.py", line 173, in data_received
    while (result := self.consume_one_frame(self.buffer)) > 0:
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/protocol.py", line 116, in consume_one_frame
    self.frame_received(view[start:end])
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/protocol.py", line 75, in frame_received
    self.channel_control_received(channel, command, message)
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/router.py", line 183, in channel_control_received
    endpoint.do_channel_control(channel, command, message)
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/channel.py", line 115, in do_channel_control
    self.do_control(command, message)
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/channel.py", line 102, in do_control
    self.do_done()
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/channels/packages.py", line 65, in do_done
    self.router.packages.serve_file(path, self)
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/packages.py", line 402, in serve_file
    self.serve_package_file(path, channel)
  File "/home/jelle/projects/cockpit/pybridge-expose-headers/src/cockpit/packages.py", line 378, in serve_package_file
    self.packages[package].serve_file(package_path, channel)
KeyError: 'wjefiwjfoew'
```

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by martinpitt** [comment]
Fixed in commit 46f58282dfdbd98e2df9f8675a645d65bdac7c3e , but the syntax was wrong for auto-closing.
