### ISSUE TITLE
pybridge, dbus: async with self.watch_processing_lock fails with "Event loop is closed"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#18355]
Spotted in [this run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18318-20230216-081609-14b766f7-fedora-37-pybridge/log.html#124) with the [journal](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18318-20230216-081609-14b766f7-fedora-37-pybridge/TestPages-testBasic-fedora-37-127.0.0.2-2801-FAIL.log.gz) having the complete backtrace:

```
Exception ignored in: <coroutine object DBusChannel.setup_path_watch.<locals>.handler at 0x7fcc7b905540>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cockpit/channels/dbus.py", line 420, in handler
    async with self.watch_processing_lock:
  File "/usr/lib64/python3.11/asyncio/locks.py", line 21, in __aexit__
    self.release()
  File "/usr/lib64/python3.11/asyncio/locks.py", line 138, in release
 cockpit-wsinstance-http.service - Cockpit Web Service http instance.
    self._wake_up_first()
  File "/usr/lib64/python3.11/asyncio/locks.py", line 155, in _wake_up_first
    fut.set_result(True)
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
asyncio-ERROR: Task was destroyed but it is pending!
```

@allisonkarlitskaya is that by any chance addressed in the router rework #18292?

**Comment by martinpitt** [comment]
It just [happened again](https://cockpit-logs.us-east-1.linodeobjects.com/pull-958-20230222-054708-d6cfdce6-fedora-37-pybridge/log.html#38), so #18292 did *not* suffice to fix this.

**Comment by martinpitt** [comment]
This also regularly happens in cockpit-machines, mostly the [TestMachinesLifecycle.testBasicAdminUser test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1018-20230412-083643-20237448-fedora-37-pybridge/log.html#63)

**Comment by martinpitt** [comment]
Also [happens on Debian](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18757-20230511-095928-314617d6-debian-testing/log.html#56)

**Comment by martinpitt** [comment]
This happens particularly often in TestUpdates.testTracer these days, e.g. [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18824-20230523-072539-913e9904-fedora-38-pybridge/log.html#111) or [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18824-20230523-072539-913e9904-fedora-38-pybridge/log.html#111). I'll add an ignore to #18824 for now.

**Comment by martinpitt** [comment]
[related error](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1337-20231205-064658-75c719f7-rhel-9-4/log.html#38), looks like this:
```
task: <Task pending name='Task-2014' coro=<DBusChannel.do_add_match.<locals>.match_hit() running at /usr/lib/python3.9/site-packages/cockpit/channels/dbus.py:367> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe5a008f640>()]> cb=[Channel._task_done()]>
Exception ignored in: <coroutine object DBusChannel.setup_path_watch.<locals>.handler at 0x7fe5a0084240>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cockpit/channels/dbus.py", line 440, in handler
    self.send_json(notify=notify)
  File "/usr/lib64/python3.9/asyncio/locks.py", line 20, in __aexit__
    self.release()
  File "/usr/lib64/python3.9/asyncio/locks.py", line 144, in release
    self._wake_up_first()
  File "/usr/lib64/python3.9/asyncio/locks.py", line 161, in _wake_up_first
    fut.set_result(True)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
asyncio-ERROR: Task was destroyed but it is pending!
```

**Comment by allisonkarlitskaya** [comment]
I think the router rework won't fix this.  I've seen it a couple of times as well.
