### ISSUE TITLE
pybridge: TestNetworkingBasic.testNoService often fails with org.freedesktop.DBus.Error.AccessDenied: Failed to get file context on /usr/lib/systemd/system/NetworkManager.service

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#18364]
Since we dropped the /pybridge scenario unexpected message filters, we now have [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18318-20230217-053559-67899c6c-fedora-37-pybridge/log.html#72) on main. The [journal](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18318-20230217-053559-67899c6c-fedora-37-pybridge/TestNetworkingBasic-testNoService-fedora-37-127.0.0.2-3001-FAIL.log.gz) gives a more readable version:
```
asyncio-ERROR: Task exception was never retrieved    
future: <Task finished name='Task-10958' coro=<DBusChannel.setup_path_watch.<locals>.handler() done, defined at /usr/local/lib/python3.11/site-packages/cockpit/channels/dbus.py:414> exception=BusError('org.freedesktop.DBus.Error.AccessDenied: Failed to get file context on /usr/lib/systemd/system/NetworkManager.service.')>
Traceback (most recent call last):    
  File "/usr/local/lib/python3.11/site-packages/cockpit/channels/dbus.py", line 420, in handler                                                reply, = await self.bus.call_method_async(self.name, path,    
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "/usr/local/lib/python3.11/site-packages/systemd_ctypes/bus.py", line 385, in call_method_async    
    message = await self.call_async(message, timeout)    
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "/usr/local/lib/python3.11/site-packages/systemd_ctypes/bus.py", line 379, in call_async    
    return await pending.future    
           ^^^^^^^^^^^^^^^^^^^^    
systemd_ctypes.bus.BusError: org.freedesktop.DBus.Error.AccessDenied: Failed to get file context on /usr/lib/systemd/system/NetworkManager.service.
```

This was initially discovered and discussed in https://github.com/cockpit-project/cockpit/pull/18356#discussion_r1108273661 .  That PR exposed the error (I think), but it really has been there all along.

**Comment by allisonkarlitskaya** [comment]
This is a dup of #18358 I think?

**Comment by martinpitt** [comment]
Right, it is.
