### ISSUE TITLE
Virtual machines Operating system dropdown list empty

### ISSUE THREAD

**Issue by ItzMiracleOwO** [cockpit-project/cockpit#18801]
### Explain what happens

![image](https://github.com/cockpit-project/cockpit/assets/76854136/63132956-edfe-4add-a7b2-a761836b0fc9)
As in the screenshot, when I try to create a virtual machine, the required flag "Operating system" dropdown list is empty, so I cannot create a vm.

I am on Fedora server 38
![image](https://github.com/cockpit-project/cockpit/assets/76854136/ae1eb631-c400-4000-aafd-9cdbada21570)

I have also checked #15381 and I didnt find anything useful.

For `python3 getOSList.py`:
```
Traceback (most recent call last):
  File "getOSList.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

Try import `gi` in python3 console:
```
python3
Python 3.8.12 (default, Mar 14 2023, 21:11:35)
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
>>>
```

Try import `gi` in python console:
```
python
Python 3.11.3 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230401 (Red Hat 13.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>>
```

Running ``getOSList.py` with python:
(A large array of output)

`ls -la $(which python)`:
```
lrwxrwxrwx. 1 root root 9  4月  5 08:00 /usr/bin/python -> ./python3
```

### Version of Cockpit

250.1.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Fedora

### Server operating system version

Fedora server 38

### What browsers are you using?

Chrome, Edge, Brave

**Comment by wolf-yuan-6115** [comment]
> ### Explain what happens
> 
> ![image](https://github.com/cockpit-project/cockpit/assets/76854136/63132956-edfe-4add-a7b2-a761836b0fc9)
> As in the screenshot, when I try to create a virtual machine, the required flag "Operating system" dropdown list is empty, so I cannot create a vm.
> 
> I am on Fedora server 38
> ![image](https://github.com/cockpit-project/cockpit/assets/76854136/ae1eb631-c400-4000-aafd-9cdbada21570)
> 
> I have also checked #15381 and I didnt find anything useful.
> 
> For `python3 getOSList.py`:
> ```
> Traceback (most recent call last):
>   File "getOSList.py", line 4, in <module>
>     import gi
> ModuleNotFoundError: No module named 'gi'
> ```
> 
> Try import `gi` in python3 console:
> ```
> python3
> Python 3.8.12 (default, Mar 14 2023, 21:11:35)
> [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import gi
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'gi'
> >>>
> ```
> 
> Try import `gi` in python console:
> ```
> python
> Python 3.11.3 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230401 (Red Hat 13.0.1-0)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import gi
> >>>
> ```
> 
> Running `getOSList.py` with python:
> (A large array of output)
> 
> `ls -la $(which python)`:
> ```
> lrwxrwxrwx. 1 root root 9  4月  5 08:00 /usr/bin/python -> ./python3
> ```
> 
> 
> ### Version of Cockpit
> 
> 250.1.1
> 
> ### Where is the problem in Cockpit?
> 
> Unknown or not applicable
> 
> ### Server operating system
> 
> Fedora
> 
> ### Server operating system version
> 
> Fedora server 38
> 
> ### What browsers are you using?
> 
> Chrome, Edge, Brave
> 
> ### System log
> 
> _No response_

Follow up here, I'm another sysadmim using same server. We already updated all packages to latest version.
