### ISSUE TITLE
"init" root pybridge gets stopped when finishing manifest reading

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#19014]
Trying to enable the pybridge on fedora-38 in PR #19009 creates an "interesting" bug, see [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19009-20230626-062301-a02c31c2-fedora-38-devel-expensive/log.html#23-2). The test fails because it expects the UI to be in admin mode (the default with our test API). However, it is in limited mode.

This reproduces locally very well. To shorten the test, I did

```patch
--- test/verify/check-pages
+++ test/verify/check-pages
@@ -119,6 +119,8 @@ OnCalendar=daily
         b.enter_page("/system/services")
         b.wait_text(".service-name", "Test Service")
         b.switch_to_top()
+        b.check_superuser_indicator("Administrative access")
+        return
         self.checkDocs(["Managing services"])
         b.click("#toggle-docs")
         b.wait_visible(f'#toggle-docs + ul a:contains("Managing services")[href="{RHEL_DOC_BASE}/'
```

I then enabled running the root bridge in debugging mode. Relevant logs:

```
sudo[9285]:    admin : PWD=/ ; USER=root ; COMMAND=/usr/bin/env COCKPIT_DEBUG=all cockpit-bridge --privileged
audit[9285]: CRED_REFR pid=9285 uid=1000 auid=1000 ses=38 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_localuser,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? re
sudo[9285]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
audit[9285]: USER_START pid=9285 uid=1000 auid=1000 ses=38 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" e
cockpit-ws[9292]: asyncio-DEBUG: Using selector: Selector
cockpit-ws[9292]: cockpit.bridge-DEBUG: Hi. How are you today?
cockpit-ws[9292]: cockpit.bridge-DEBUG: Starting the router.
cockpit-ws[9292]: cockpit.internal_endpoints-DEBUG: COCKPIT_LOGIN_MESSAGES_MEMFD wasn't set.  No login messages today.
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(/machines.d): defaulting to /machines.d
cockpit-ws[9292]: cockpit._vendor.systemd_ctypes.pathwatch-DEBUG: Starting path walk
cockpit-ws[9292]: cockpit._vendor.systemd_ctypes.pathwatch-DEBUG: r=['machines.d', '/'] dfd=-1
cockpit-ws[9292]: cockpit._vendor.systemd_ctypes.pathwatch-DEBUG: r=['machines.d'] dfd=11
cockpit-ws[9292]: cockpit._vendor.systemd_ctypes.pathwatch-DEBUG: walk ended in error 2
cockpit-ws[9292]: cockpit._vendor.systemd_ctypes.pathwatch-DEBUG: Ending existing watches.
cockpit-ws[9292]: cockpit._vendor.systemd_ctypes.pathwatch-DEBUG: Notifying of new error state 2
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(cockpit.conf): found /etc/cockpit/cockpit.conf
cockpit-ws[9292]: cockpit.config-DEBUG: cockpit.Config: loading /etc/cockpit/cockpit.conf
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(apps.override.json): defaulting to /etc/cockpit/apps.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(base1.override.json): defaulting to /etc/cockpit/base1.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(kdump.override.json): defaulting to /etc/cockpit/kdump.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(metrics.override.json): defaulting to /etc/cockpit/metrics.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(networkmanager.override.json): defaulting to /etc/cockpit/networkmanager.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(packagekit.override.json): defaulting to /etc/cockpit/packagekit.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(pcp.override.json): defaulting to /etc/cockpit/pcp.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(playground.override.json): defaulting to /etc/cockpit/playground.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(selinux.override.json): defaulting to /etc/cockpit/selinux.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(shell.override.json): defaulting to /etc/cockpit/shell.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(sosreport.override.json): defaulting to /etc/cockpit/sosreport.override.json
systemd[9269]: Created slice session.slice - User Core Session Slice.
systemd[9269]: Starting dbus-broker.service - D-Bus User Message Bus...
systemd[9269]: Started dbus-broker.service - D-Bus User Message Bus.
dbus-broker-launch[9296]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
dbus-broker-launch[9296]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
dbus-broker-launch[9296]: Ready
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(ssh.override.json): defaulting to /etc/cockpit/ssh.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(static.override.json): defaulting to /etc/cockpit/static.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(storaged.override.json): defaulting to /etc/cockpit/storaged.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(systemd.override.json): found /etc/cockpit/systemd.override.json
cockpit-ws[9292]: cockpit.config-DEBUG: lookup_config(users.override.json): defaulting to /etc/cockpit/users.override.json
cockpit-ws[9292]: cockpit.superuser-DEBUG: set_configs() with 7 items
cockpit-ws[9292]: cockpit.superuser-DEBUG:   bridges are now ['sudo', 'pkexec']
cockpit-ws[9292]: cockpit.transports-DEBUG: Created transport <cockpit.transports.StdioTransport object at 0x7f5b0e8e4710> for protocol <cockpit.bridge.Bridge object at 0x7f5b0e89ba90>, fds 0 1
cockpit-ws[9292]: cockpit.protocol-DEBUG: connection_made(<cockpit.transports.StdioTransport object at 0x7f5b0e8e4710>)
cockpit-ws[9292]: cockpit.protocol-DEBUG: sending message  {'command': 'init', 'version': 1, 'checksum': '850ddd57f79491d0f7b3741ca9c113b1632a6f821f06de793d6b1c33fa57f227', 'packages': {'apps': None, 'base1': None, 'kdump': None, 'm
cockpit-ws[9292]: cockpit.protocol-DEBUG: writing to transport <cockpit.transports.StdioTransport object at 0x7f5b0e8e4710>
cockpit-ws[9292]: cockpit.bridge-DEBUG: Startup done.  Looping until connection closes.
cockpit-ws[9292]: cockpit.transports-DEBUG: Read ready on <cockpit.transports.StdioTransport object at 0x7f5b0e8e4710> <cockpit.bridge.Bridge object at 0x7f5b0e89ba90> 0
cockpit-ws[9292]: cockpit.transports-DEBUG:   got EOF
cockpit-ws[9292]: cockpit.protocol-DEBUG: connection_lost
sudo[9285]: pam_unix(sudo:session): session closed for user root
```

There are no tracebacks, errors, or warnings. I suppose the development mode changes the timing, as it has to hash a lot bigger files. But this feels like a more fundamental race condition?

**Comment by martinpitt** [comment]
connection_lost() gets called with a `None` `exc`eption, which means that transport.abort(), i.e. it was not called through a failure in `_{read,write}_ready()`.

What happens is that the superuser bridge gets started through the "magic" `superuser: "any"` localStore mechanism in `Browser.try_login()`. Both the user (10587) and the root (10592) bridge then parse packages, and finally read the superuser manifests, almost in parallel. Then the user bridge decides that the currently running root bridge is not in the config, and stops it, but does not restart it again:

```
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(apps.override.json): defaulting to /etc/cockpit/apps.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(base1.override.json): defaulting to /etc/cockpit/base1.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(kdump.override.json): defaulting to /etc/cockpit/kdump.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(metrics.override.json): defaulting to /etc/cockpit/metrics.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(networkmanager.override.json): defaulting to /etc/cockpit/networkmanager.override.json
cockpit-ws[10592]: cockpit.config-DEBUG: lookup_config(users.override.json): defaulting to /etc/cockpit/users.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(packagekit.override.json): defaulting to /etc/cockpit/packagekit.override.json
cockpit-ws[10592]: cockpit.superuser-DEBUG: set_configs() with 7 items
cockpit-ws[10592]: cockpit.superuser-DEBUG:   bridges are now ['sudo', 'pkexec']
cockpit-ws[10592]: cockpit.transports-DEBUG: Created transport <cockpit.transports.StdioTransport object at 0x7ff119470a10> for protocol <cockpit.bridge.Bridge object at 0x7ff119a878d0>, fds 0 1
cockpit-ws[10592]: cockpit.protocol-DEBUG: connection_made(<cockpit.transports.StdioTransport object at 0x7ff119470a10>)
cockpit-ws[10592]: cockpit.protocol-DEBUG: sending message  {'command': 'init', 'version': 1, 'checksum': 'def022f6105e3e67e07e2a41c59a44682541a0e68a9a18fda3122b0979807748', 'packages': {'apps': None, 'base1': None, 'kdump': None, '>
cockpit-ws[10592]: cockpit.protocol-DEBUG: writing to transport <cockpit.transports.StdioTransport object at 0x7ff119470a10>
cockpit-ws[10592]: cockpit.bridge-DEBUG: Startup done.  Looping until connection closes.
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(pcp.override.json): defaulting to /etc/cockpit/pcp.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(playground.override.json): defaulting to /etc/cockpit/playground.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(selinux.override.json): defaulting to /etc/cockpit/selinux.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(shell.override.json): defaulting to /etc/cockpit/shell.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(sosreport.override.json): defaulting to /etc/cockpit/sosreport.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(ssh.override.json): defaulting to /etc/cockpit/ssh.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(static.override.json): defaulting to /etc/cockpit/static.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(storaged.override.json): defaulting to /etc/cockpit/storaged.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(systemd.override.json): found /etc/cockpit/systemd.override.json
cockpit-ws[10587]: cockpit.config-DEBUG: lookup_config(users.override.json): defaulting to /etc/cockpit/users.override.json
cockpit-ws[10587]: cockpit.superuser-DEBUG: set_configs() with 7 items
cockpit-ws[10587]: cockpit.superuser-DEBUG:   bridges are now ['sudo', 'pkexec']
cockpit-ws[10587]: cockpit.superuser-DEBUG:   stopping current superuser bridge, as it disappeared from configs
cockpit-ws[10587]: cockpit.protocol-DEBUG: connection_lost: None
cockpit-ws[10592]: cockpit.transports-DEBUG: Read ready on <cockpit.transports.StdioTransport object at 0x7ff119470a10> <cockpit.bridge.Bridge object at 0x7ff119a878d0> 0
cockpit-ws[10592]: cockpit.transports-DEBUG:   got EOF
cockpit-ws[10592]: cockpit.protocol-DEBUG: connection_lost: None
cockpit-ws[10592]: asyncio-ERROR: Exception in callback None()
cockpit-ws[10592]: handle: <Handle cancelled>
cockpit-ws[10592]: Traceback (most recent call last):
cockpit-ws[10592]:   File "/usr/lib64/python3.11/asyncio/events.py", line 80, in _run
cockpit-ws[10592]:     self._context.run(self._callback, *self._args)
cockpit-ws[10592]:   File "/usr/lib/python3.11/site-packages/cockpit/transports.py", line 114, in _read_ready
cockpit-ws[10592]:     self.close()
cockpit-ws[10592]:   File "/usr/lib/python3.11/site-packages/cockpit/transports.py", line 244, in close
cockpit-ws[10592]:     self.abort()
cockpit-ws[10592]:   File "/usr/lib/python3.11/site-packages/cockpit/transports.py", line 143, in abort
cockpit-ws[10592]:     self._protocol.connection_lost(exc)
cockpit-ws[10592]:   File "/usr/lib/python3.11/site-packages/cockpit/protocol.py", line 158, in connection_lost
cockpit-ws[10592]:     assert False
cockpit-ws[10592]: AssertionError
```

I added `assert False` to get an easy backtrace. But on the root bridge side this just means that the user-side stopping of the root bridge via EOF works as intended. There's nothing wrong with the root bridge (except perhaps the way it gets started), this needs to be fixed on the user bridge side.

**Comment by martinpitt** [comment]
@mvollmer says that the initial root bridge shouldn't be called "init". It should be "any" perhaps, but to me it seems it should really be called "sudo". We don't duplicate/hardcode the sudo bridge invocation anywhere, I suppose the user bridge just somehow re-reads the manifests after startup.
