### ISSUE TITLE
Command `cockpit-bridge --version` doesn't exit peacefully

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit#19233]
### Explain what happens

Running `cockpit-bridge --version` gets stuck and throws an error when Enter/Return is pressed.

```
[subho@fedora cockpit-podman]$ cockpit-bridge --version
1426

{
  "command": "init",
  "version": 1,
  "capabilities": {
    "explicit-superuser": true
  },
  "os-release": {
    "NAME": "Fedora Linux",
    "VERSION": "38 (Workstation Edition)",
    "ID": "fedora",
    "VERSION_ID": "38",
    "VERSION_CODENAME": "",
    "PLATFORM_ID": "platform:f38",
    "PRETTY_NAME": "Fedora Linux 38 (Workstation Edition)",
    "ANSI_COLOR": "0;38;2;60;110;180",
    "LOGO": "fedora-logo-icon",
    "CPE_NAME": "cpe:/o:fedoraproject:fedora:38",
    "DEFAULT_HOSTNAME": "fedora",
    "HOME_URL": "https://fedoraproject.org/",
    "DOCUMENTATION_URL": "https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/",
    "SUPPORT_URL": "https://ask.fedoraproject.org/",
    "BUG_REPORT_URL": "https://bugzilla.redhat.com/",
    "REDHAT_BUGZILLA_PRODUCT": "Fedora",
    "REDHAT_BUGZILLA_PRODUCT_VERSION": "38",
    "REDHAT_SUPPORT_PRODUCT": "Fedora",
    "REDHAT_SUPPORT_PRODUCT_VERSION": "38",
    "SUPPORT_END": "2024-05-14",
    "VARIANT": "Workstation Edition",
    "VARIANT_ID": "workstation"
  },
  "packages": {
    "playground": null,
    "apps": null,
    "users": null,
    "base1": null,
    "network": null,
    "kdump": null,
    "metrics": null,
    "storage": null,
    "selinux": null,
    "system": null,
    "sosreport": null,
    "shell": null,
    "static": null,
    "updates": null,
    "machines": null,
    "podman": null,
    "ssh": null,
    "pcp": null
  }
}

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/cockpit/protocol.py", line 130, in consume_one_frame
    length = int(header[:newline])
             ^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: b''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/cockpit-bridge", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/cockpit/bridge.py", line 283, in main
    run_async(run(args), debug=args.debug)
  File "/usr/lib/python3.11/site-packages/cockpit/_vendor/systemd_ctypes/event.py", line 109, in run_async
    asyncio.run(main, debug=debug)
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cockpit/bridge.py", line 174, in run
    await router.communicate()
  File "/usr/lib/python3.11/site-packages/cockpit/protocol.py", line 221, in communicate
    await self._communication_done
  File "/usr/lib/python3.11/site-packages/cockpit/protocol.py", line 207, in data_received
    result = self.consume_one_frame(self.buffer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cockpit/protocol.py", line 132, in consume_one_frame
    raise CockpitProtocolError("frame size is not an integer") from exc
cockpit.protocol.CockpitProtocolError: frame size is not an integer
```

### Version of Cockpit

main branch

### Where is the problem in Cockpit?

None

### Server operating system

Fedora

### Server operating system version

Fedora-38

**Comment by subhoghoshX** [comment]
`cockpit-bridge --version` is fixed :tada: but now the same error occurs when executing the other commands :(

`cockpit-bridge`
`cockpit-bridge --privileged`
`cockpit-bridge --bridges` -> this one is a little different
`cockpit-bridge --debug`

**Comment by martinpitt** [comment]
@subhoghoshX These are not an error. Without arguments or `--privileged` (or --debug) it enters protocol mode, and an empty line is just invalid protocol.
