### ISSUE TITLE
cockpit-bridge --bridges crashes: Object of type BridgeConfig is not JSON serializable

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#19319]
### Explain what happens

Run:

```
cockpit-bridge --bridges
```

Got greeted by:
```
[leomoty@europa ~]$ cockpit-bridge --bridges
Traceback (most recent call last):
  File "/usr/bin/cockpit-bridge", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/cockpit/bridge.py", line 283, in main
    print(json.dumps(Packages().get_bridge_configs(), indent=2))
  File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.9/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib64/python3.9/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BridgeConfig is not JSON serializable
```

### Version of Cockpit

300.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

None

### Server operating system version

Rocky 9.2

**Comment by martinpitt** [comment]
Thanks! This is harmless, but let's fix it.
