### ISSUE TITLE
Admin access fails  

### ISSUE THREAD

**Issue by jtyvy8080** [cockpit-project/cockpit#19338]
### Explain what happens

1.  Accessing the web interface works. The problem is that elevating privileges fails after asking for pin and then touch on yubikey
2. I have yubikey configured to work via u2f for sudo access on the system in question
3. 

### Version of Cockpit

Latest cockpit on fedora 38

### Where is the problem in Cockpit?

Accounts

### Server operating system

Fedora

### Server operating system version

38

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
This is very similar to #17323 . Please show the "system log" during a sudo attempt, i.e. `sudo journalctl -f`. This should all be in PAM.

**Comment by martinpitt** [comment]
No response in 3 months and most likely a duplicate of #17323.

**Comment by skewballfox** [comment]
not a duplicate,  tried  here's the process and logs. 
1. logged into console via `127.0.0.1:9090` as sudo capable user
2. attempted to turn on administrative access, recieved prompt to insert key and press enter
3. pressed enter

result: `Authenticating` with a loading circle.

output of `journalctl -f`
```
❯ journalctl -f
Jan 29 13:55:13 <hostname> systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 29 13:55:13 <hostname> audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 29 13:55:13 <hostname> audit: BPF prog-id=122 op=UNLOAD
Jan 29 13:55:13 <hostname> audit: BPF prog-id=121 op=UNLOAD
Jan 29 13:55:13 <hostname> audit: BPF prog-id=120 op=UNLOAD
Jan 29 13:55:13 <hostname> systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 29 13:55:13 <hostname> audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-timedated comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 29 13:55:13 <hostname> audit: BPF prog-id=125 op=UNLOAD
Jan 29 13:55:13 <hostname> audit: BPF prog-id=124 op=UNLOAD
Jan 29 13:55:13 <hostname> audit: BPF prog-id=123 op=UNLOAD
Jan 29 13:56:02 <hostname> audit: BPF prog-id=126 op=LOAD
Jan 29 13:56:02 <hostname> audit: BPF prog-id=127 op=LOAD
Jan 29 13:56:02 <hostname> audit: BPF prog-id=128 op=LOAD
Jan 29 13:56:02 <hostname> systemd[1]: Starting systemd-timedated.service - Time & Date Service...
Jan 29 13:56:02 <hostname> systemd[1]: Started systemd-timedated.service - Time & Date Service.
Jan 29 13:56:02 <hostname> audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-timedated comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 29 13:56:06 <hostname> /usr/bin/cockpit-bridge[25516]: Exception in callback BusMessage._coroutine_task_complete(<cockpit._ven...x7fb943793770>)(<Task finishe...is too long')>)
                                                         handle: <Handle BusMessage._coroutine_task_complete(<cockpit._ven...x7fb943793770>)(<Task finishe...is too long')>)>
                                                         Traceback (most recent call last):
                                                           File "/usr/lib/python3.12/site-packages/cockpit/protocol.py", line 127, in consume_one_frame
                                                             newline = header.index(b'\n')
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                         ValueError: subsection not found
                                                         
                                                         The above exception was the direct cause of the following exception:
                                                         
                                                         Traceback (most recent call last):
                                                           File "/usr/lib64/python3.12/asyncio/events.py", line 84, in _run
                                                             self._context.run(self._callback, *self._args)
                                                           File "/usr/lib/python3.12/site-packages/cockpit/_vendor/systemd_ctypes/bus.py", line 179, in _coroutine_task_complete
                                                             self.reply_method_function_return_value(out_type, task.result())
                                                                                                               ^^^^^^^^^^^^^
                                                           File "/usr/lib/python3.12/site-packages/cockpit/superuser.py", line 233, in start
                                                             await self.go(name, self)
                                                           File "/usr/lib/python3.12/site-packages/cockpit/superuser.py", line 181, in go
                                                             await self.peer.start(init_host=self.router.init_host)
                                                           File "/usr/lib/python3.12/site-packages/cockpit/peer.py", line 100, in start
                                                             init_message = await self.init_future
                                                                            ^^^^^^^^^^^^^^^^^^^^^^
                                                           File "/usr/lib/python3.12/site-packages/cockpit/protocol.py", line 196, in data_received
                                                             result = self.consume_one_frame(self.buffer)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                           File "/usr/lib/python3.12/site-packages/cockpit/protocol.py", line 132, in consume_one_frame
                                                             raise CockpitProtocolError("size line is too long") from exc
                                                         cockpit.protocol.CockpitProtocolError: size line is too long
Jan 29 13:56:06 <hostname> python3[26006]: detected unhandled Python exception in '/usr/libexec/cockpit-askpass'
Jan 29 13:56:06 <hostname> sudo[25948]: pam_unix(sudo:auth): conversation failed
Jan 29 13:56:06 <hostname> sudo[25948]: pam_unix(sudo:auth): auth could not identify password for [<user>]
Jan 29 13:56:06 <hostname> audit[25948]: USER_AUTH pid=25948 uid=1000 auid=1000 ses=6 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=? acct="<user>" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=failed'
Jan 29 13:56:06 <hostname> audit[25948]: USER_CMD pid=25948 uid=1000 auid=1000 ses=6 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/" cmd=636F636B7069742D627269646765202D2D70726976696C65676564 exe="/usr/bin/sudo" terminal=? res=failed'
Jan 29 13:56:06 <hostname> abrt-server[26007]: Deleting problem directory Python3-2024-01-29-13:56:06-26006 (dup of Python3-2024-01-29-13:54:50-25639)
Jan 29 13:56:06 <hostname> abrt-notification[26014]: [🡕] Process 25639 (cockpit-askpass) of user 1000 encountered an uncaught BrokenPipeError exception

```

**Comment by sigonzal3** [comment]
## Reproduced on RHEL 10.1 and Rocky Linux 10.1

`pam_u2f` from **EPEL** works for Gnome GDM, SSH/login and terminal sudo, but breaks Cockpit web UI privilege elevation.

---

## Setup

```sh
# I'm using local profile, check yours
authselect current

# enable pam u2f
sudo authselect enable-feature with-pam-u2f

# create resident key with PIN + touch
pamu2fcfg -r -N > ~/.config/Yubico/u2f_keys 
```

## Problem

Cockpit fails when elevating privileges. journalctl shows:

```sh
ValueError: invalid literal for int() with base 10: b'Please touch the device.'
cockpit.protocol.CockpitProtocolError: frame size is not an integer
```

Cause: pam_u2f with cue prints “Please touch the device.” to stdout, corrupting Cockpit’s protocol.

## Workaround

In /etc/pam.d/system-auth, change:

```diff
- auth        sufficient    pam_u2f.so cue
+ auth        sufficient    pam_u2f.so
```

After this:

* U2F still works
* Terminal sudo still requires YubiKey
* Cockpit privilege escalation works

## Limitation

Cockpit’s web terminal still cannot handle sudo with U2F, but SSH or local terminal continues to work.
