### ISSUE TITLE
Beiboot is broken on ubuntu-2204

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#19412]
Beiboot is broken [in an interesting way on ubuntu-2204](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19401-20230928-054506-d7f3fa3e-ubuntu-2204-other/log.html#161). I poked at this for half an hour, but I think I'd like to confer with @allisonkarlitskaya about that:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/cockpit/beiboot.py", line 353, in <module>
    main()
  File "/usr/lib/python3/dist-packages/cockpit/beiboot.py", line 349, in main
    asyncio.run(run(args), debug=args.debug)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/cockpit/beiboot.py", line 297, in run
    message = await bridge.ssh_peer.start()
  File "/usr/lib/python3/dist-packages/cockpit/peer.py", line 100, in start
    init_message = await self.init_future
  File "/usr/lib/python3/dist-packages/cockpit/transports.py", line 237, in write
    n_bytes = os.write(self._out_fd, data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by martinpitt** [comment]
Nevermind, that needs handling in #19401 proper -- it affects all OSes.
