### ISSUE TITLE
After update, cannot sign-in (Wrong user name or password)

### ISSUE THREAD

**Issue by derekcentrico** [cockpit-project/cockpit#19592]
### Explain what happens

1. Go to web portal
2. Type in normal username and password I used since installing cockpit (it is not root)
3. Get a notice that "Wrong user name or password"

### Version of Cockpit

264-1ubuntu0.22.04.1

### Where is the problem in Cockpit?

Accounts

### Server operating system

Ubuntu

### Server operating system version

22.04.03

### What browsers are you using?

Chrome

### System log

```shell
# journalctl -q SYSLOG_FACILITY=10 SYSLOG_FACILITY=4 --since "today" | grep cockpit
Nov 08 12:26:39 homeserver cockpit-session[3791111]: pam_unix(cockpit:session): session opened for user derek(uid=1000) by (uid=0)
Nov 08 12:26:39 homeserver cockpit-session[3791111]: pam_unix(cockpit:session): session closed for user derek
Nov 08 12:27:18 homeserver cockpit-session[3791864]: pam_unix(cockpit:session): session opened for user derek(uid=1000) by (uid=0)
Nov 08 12:27:18 homeserver cockpit-session[3791864]: pam_unix(cockpit:session): session closed for user derek
Nov 08 12:29:21 homeserver cockpit-session[3797752]: pam_unix(cockpit:session): session opened for user derek(uid=1000) by (uid=0)
Nov 08 12:29:21 homeserver cockpit-session[3797752]: pam_unix(cockpit:session): session closed for user derek
Nov 08 12:32:31 homeserver cockpit-session[3802008]: pam_unix(cockpit:session): session opened for user derek(uid=1000) by (uid=0)
Nov 08 12:32:31 homeserver cockpit-session[3802008]: pam_unix(cockpit:session): session closed for user derek


derek@homeserver:~$ journalctl --since -10m |grep cockpit
Nov 08 13:33:03 homeserver cockpit-tls[3873336]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-tls[3873336]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-tls[3873336]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:33:03 homeserver systemd[1]: cockpit-wsinstance-https-factory@5-3873336-140.service: Deactivated successfully.
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-ws[3873374]: cockpit-ws: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:04 homeserver cockpit-session[3873377]: pam_ssh_add: Identity added: /home/derek/.ssh/id_rsa (/home/derek/.ssh/id_rsa)
Nov 08 13:33:04 homeserver cockpit-session[3873377]: pam_unix(cockpit:session): session opened for user derek(uid=1000) by (uid=0)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]: Traceback (most recent call last):
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/bin/cockpit-bridge", line 8, in <module>
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     sys.exit(main())
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3/dist-packages/cockpit/bridge.py", line 291, in main
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     run_async(run(args), debug=args.debug)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3/dist-packages/cockpit/_vendor/systemd_ctypes/event.py", line 109, in run_async
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     asyncio.run(main, debug=debug)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     return loop.run_until_complete(main)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     return future.result()
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3/dist-packages/cockpit/bridge.py", line 174, in run
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     router = Bridge(args)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3/dist-packages/cockpit/bridge.py", line 77, in __init__
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     self.internal_bus.export('/config', Config())
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3/dist-packages/cockpit/config.py", line 51, in __init__
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     self.reload()
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3/dist-packages/cockpit/config.py", line 81, in reload
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     self.config.read(cockpit_conf)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3.10/configparser.py", line 699, in read
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     self._read(fp, filename)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:   File "/usr/lib/python3.10/configparser.py", line 1087, in _read
Nov 08 13:33:04 homeserver cockpit-ws[3873384]:     raise MissingSectionHeaderError(fpname, lineno, line)
Nov 08 13:33:04 homeserver cockpit-ws[3873384]: configparser.MissingSectionHeaderError: File contains no section headers.
Nov 08 13:33:04 homeserver cockpit-ws[3873384]: file: PosixPath('/etc/cockpit/cockpit.conf'), line: 1
Nov 08 13:33:04 homeserver cockpit-ws[3873384]: 'AllowUnencrypted = true\n'
Nov 08 13:33:04 homeserver cockpit-session[3873377]: pam_unix(cockpit:session): session closed for user derek
```

**Comment by derekcentrico** [comment]
With or without /etc/cockpit/cockpit.conf having "AllowUnencrypted = true" the below is dumped out as well:

Nov 08 12:26:38 homeserver systemd[1]: Started Cockpit Web Service.
Nov 08 12:26:39 homeserver cockpit-tls[3791103]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 12:26:39 homeserver cockpit-tls[3791103]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 12:26:39 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:27:48 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:29:17 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:29:17 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:29:21 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:31:06 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:32:10 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:32:10 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:32:10 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:32:22 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:32:22 homeserver cockpit-tls[3791103]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 12:34:21 homeserver systemd[1]: cockpit.service: Deactivated successfully.
Nov 08 12:34:21 homeserver systemd[1]: cockpit.service: Consumed 56.620s CPU time.
Nov 08 13:33:03 homeserver systemd[1]: Starting Cockpit Web Service...
Nov 08 13:33:03 homeserver systemd[1]: Started Cockpit Web Service.
Nov 08 13:33:03 homeserver cockpit-tls[3873336]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-tls[3873336]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:33:03 homeserver cockpit-tls[3873336]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:35:45 homeserver systemd[1]: cockpit.service: Deactivated successfully.
Nov 08 13:56:43 homeserver systemd[1]: Starting Cockpit Web Service...
Nov 08 13:56:43 homeserver systemd[1]: Started Cockpit Web Service.
Nov 08 13:56:43 homeserver cockpit-tls[3900371]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:56:43 homeserver cockpit-tls[3900371]: cockpit-tls: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true
Nov 08 13:56:43 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:56:44 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:56:44 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:57:41 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:57:47 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:57:47 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:57:47 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:57:47 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:57:47 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:58:17 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 08 13:58:18 homeserver cockpit-tls[3900371]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.

**Comment by martinpitt** [comment]
Yes, pretty much exactly what the error message says: 

    /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypted = true

You need to put `[WebService]` before that setting.

**Comment by derekcentrico** [comment]
Sure, so if that's the fix, what happened with the deb where an update must've messed that up?

Upon adding that portion and restarting the cockpit service, I just loop back to the login page now.

Journal:
Nov 09 06:41:39 homeserver cockpit-session[1280804]: pam_unix(cockpit:session): session opened for user derek(uid=1000) by (uid=0)
Nov 09 06:41:40 homeserver sudo[1280869]:    derek : PWD=/ ; USER=root ; COMMAND=/usr/bin/cockpit-bridge --privileged
Nov 09 06:41:54 homeserver cockpit-session[1280804]: pam_unix(cockpit:session): session closed for user derek
Nov 09 06:42:55 homeserver cockpit-session[1283322]: pam_unix(cockpit:session): session opened for user derek(uid=1000) by (uid=0)
Nov 09 06:42:55 homeserver sudo[1283330]:    derek : PWD=/ ; USER=root ; COMMAND=/usr/bin/cockpit-bridge --privileged
Nov 09 06:43:10 homeserver cockpit-session[1283322]: pam_unix(cockpit:session): session closed for user derek

What's this about?

**Comment by martinpitt** [comment]
So it successfully logged in, and after 15 seconds the session terminates. That's roughly the session timeout after disconnecting the browser. What *exactly* do you see after logging in? Please also open the browser console (Ctrl+Shift+J) at the login page and copy&paste all messages here.

**Comment by derekcentrico** [comment]
Yeah so just to be clear,  installed the debs from apt.  I had no issues originally.  An update happened and it went bonkers on me not being able to get in.

One issue is when I put in the user/password and click "Log in" it just reloads to the login page immediately.  Now, I have to click a dropdown for "connect to" and add the LAN IP address.  

I receive the below in the Chrome logs without doing the "connect to" portion:

>        GET http://192.168.1.49:9090/cockpit+=192.168.1.49/login 401 (Authentication failed: unknown-host)

Upon doing the Connect to option for the first time, I received a message to run "ssh-keyscan -t ecdsa-sha2-nistp256 localhost | ssh-keygen -lf -" on the host.  Great I did that.

Upon signing in this way, I was able to get in but I see errors/messages:

>       Failed to load resource: the server responded with a status of 404 (ERROR)
po.js:1 
>        Failed to load resource: the server responded with a status of 404 (ERROR)
> :9090/=192.168.1.49:1 Refused to execute script from 'http://192.168.1.49:9090/cockpit+=192.168.1.49/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
> :9090/=192.168.1.49:1 Refused to execute script from 'http://192.168.1.49:9090/cockpit+=192.168.1.49/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
> updates.js:155 Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 3, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"

It's just super strange how all worked great and after an update it decided to stop working.

**Comment by martinpitt** [comment]
This was fixed in commit b85d3fab7383c4a5571d089abce6581085774903 aka https://bugzilla.redhat.com/show_bug.cgi?id=2324979

**Comment by maenmustafa** [comment]
the problem solved here : 

https://github.com/maenmustafa/keycloak
