### ISSUE TITLE
Get a better error message when wrong data type is passed as dbus arguement

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit#19645]
### Explain what happens

I don't have a minimal reproducer at the moment, but I've been noticing it past few months.

Some of the errors I get:

> Traceback (most recent call last): File "/usr/lib/python3.11/site-packages/cockpit/channels/dbus.py", line 340, in do_call method_call = self.bus.message_new_method_call(self.name, path, iface, method, signature, *args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/site-packages/cockpit/_vendor/systemd_ctypes/bus.py", line 302, in message_new_method_call message.append(types, *args) File "/usr/lib/python3.11/site-packages/cockpit/_vendor/systemd_ctypes/bus.py", line 131, in append type_.writer(self, arg) File "/usr/lib/python3.11/site-packages/cockpit/_vendor/systemd_ctypes/bustypes.py", line 374, in dict_writer value_writer(message, value) # value ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/site-packages/cockpit/_vendor/systemd_ctypes/bustypes.py", line 374, in dict_writer value_writer(message, value) # value ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/site-packages/cockpit/_vendor/systemd_ctypes/bustypes.py", line 407, in variant_writer type_.writer(message, contents) File "/usr/lib/python3.11/site-packages/cockpit/_vendor/systemd_ctypes/bustypes.py", line 206, in fixed_writer setter(variable, value) TypeError: 'float' object cannot be interpreted as an integer

Showing it in the UI is too much info and handling all the cases in JS code seems redundant:

![image](https://github.com/cockpit-project/cockpit/assets/108616679/bbc6aae9-7dc2-49ae-98f7-5451ca223098)

### Version of Cockpit

main (305-29)

### Where is the problem in Cockpit?

None

### Server operating system

Fedora

### Server operating system version

Fedora-38

### What browsers are you using?

Brave

**Comment by garrett** [comment]
1. This is very verbose. Alerts should be succinct, showing only a line or so of a human-friendly error message.
2. There are ways to expand alerts.
   - https://www.patternfly.org/components/alert#alert-variations
   - https://www.patternfly.org/components/alert#expandable-alerts
   - (we usually prefer to do the more obvious method of having a link that expands/collapses instead of the newer expandable version)
3. Who is this error message for? Why is there a traceback? Is that actually useful to anyone aside from developers?
4. Why is the preformatted traceback not shown in a preformatted manner? Part of the information is in the preformatting.

What were you trying to do? Were you trying to "save" something? If so, what? Or were you trying to do something else and this is a generic message? Where is this error message coming from?

**Comment by garrett** [comment]
These are very quick and I have no clue what you're trying to do or where the error message is coming from or anything else, so this is not only visually inaccurate, it's not really designed for purpose. It's just to give you a basic overview of the way we usually do expanders in Cockpit for error messages (versus what PF implemented), and how to hide and show a traceback (if there's really no better option).

Remember that sizing, spacing, and the content are all probably a good bit off, so "take it with a grain of salt" (in other words, don't treat this a an real design suggestion :wink:):

![Alert, inline, error details(2)](https://github.com/cockpit-project/cockpit/assets/10246/57e75f58-5a2e-4323-b3aa-e2b7278f5b49)

![Alert, inline, error details(1)](https://github.com/cockpit-project/cockpit/assets/10246/2b4085b9-aa2c-4513-a311-0c36bda15a5e)

**Comment by allisonkarlitskaya** [comment]
I like the trackback here — if you hit this then it's by definition a developer error.  Hiding it behind a closure is reasonable, but I don't think we should strip it out.
