### ISSUE TITLE
TestStorageswap.test fails on Fedora Rawhide

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#19683]
It failed in https://github.com/fedora-selinux/selinux-policy/pull/1950 [log](https://artifacts.dev.testing-farm.io/80ff6af0-7971-421e-b58b-af89cc622c86/) and https://github.com/stratis-storage/stratisd/pull/3514 [log](https://artifacts.dev.testing-farm.io/f486dff7-0d49-4e77-bf9d-e62930c615b9/):

```
Traceback (most recent call last):
  File "/var/ARTIFACTS/work-optionala1z0qc33/plans/cockpit/optional/discover/default-0/tests/test/verify/check-storage-swap", line 42, in test
    b.wait_text(self.card_desc("Swap", "Used"), "0")
  File "/var/ARTIFACTS/work-optionala1z0qc33/plans/cockpit/optional/discover/default-0/tests/test/common/testlib.py", line 675, in wait_text
    self.wait_js_cond("ph_text_is(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/var/ARTIFACTS/work-optionala1z0qc33/plans/cockpit/optional/discover/default-0/tests/test/common/testlib.py", line 601, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/var/ARTIFACTS/work-optionala1z0qc33/plans/cockpit/optional/discover/default-0/tests/test/common/testlib.py", line 305, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("[data-test-card-title='Swap'] [data-test-desc-title='Used'] [data-test-value=true]","0")): actual text: Unknown
```

but after that it fails to clean up: It prints a bunch of "rmmod: ERROR: Module scsi_debug is in use" and from then on all following storaged tests fail on the same thing. Presumably it's kept busy by `swapon`, we need to clean this up robustly. 

@mvollmer I'm happy to look at the general cleanup, but the actual failure ("Unknown" instead of swap) feels like a race condition between cockpit, udisks, and udev. Could you have a look, please?

**Comment by mvollmer** [comment]
> feels like a race condition between cockpit, udisks, and udev.

Swap sizes come directly via PCP, hmm.

**Comment by martinpitt** [comment]
PR #19686 fixes the cleanup failure.

**Comment by martinpitt** [comment]
FTR: I tried this on `test/image-prepare -q fedora-rawhide` and it passes. I then upgraded to current rawhide:

```
Installing:
 kernel-core                                       x86_64        6.7.0-0.rc3.20231201git994d5c58e50e.32.fc40           rawhide         16 M
Upgrading:
 aardvark-dns                                      x86_64        1.9.0-1.fc40                                          rawhide        915 k
 acl                                               x86_64        2.3.1-11.fc40                                         rawhide         73 k
 binutils                                          x86_64        2.41-15.fc40                                          rawhide        6.3 M
 binutils-gold                                     x86_64        2.41-15.fc40                                          rawhide        797 k
 capstone                                          x86_64        5.0.1-1.fc40                                          rawhide        1.8 M
 clevis-pin-tpm2                                   x86_64        0.5.3-2.fc40                                          rawhide        938 k
 container-selinux                                 noarch        2:2.226.0-1.fc40                                      rawhide         56 k
 criu                                              x86_64        3.19-2.fc40                                           rawhide        560 k
 criu-libs                                         x86_64        3.19-2.fc40                                           rawhide         33 k
 cryptsetup                                        x86_64        2.7.0~rc0-1.fc40                                      rawhide        325 k
 cryptsetup-libs                                   x86_64        2.7.0~rc0-1.fc40                                      rawhide        508 k
 device-mapper-multipath                           x86_64        0.9.7-4.fc40                                          rawhide        168 k
 device-mapper-multipath-libs                      x86_64        0.9.7-4.fc40                                          rawhide        288 k
 edk2-ovmf                                         noarch        20231122-3.fc40                                       rawhide         10 M
 elfutils                                          x86_64        0.190-4.fc40                                          rawhide        550 k
 elfutils-debuginfod-client                        x86_64        0.190-4.fc40                                          rawhide         38 k
 elfutils-default-yama-scope                       noarch        0.190-4.fc40                                          rawhide         13 k
 elfutils-libelf                                   x86_64        0.190-4.fc40                                          rawhide        194 k
 elfutils-libs                                     x86_64        0.190-4.fc40                                          rawhide        259 k
 ethtool                                           x86_64        2:6.6-1.fc40                                          rawhide        244 k
 firewalld                                         noarch        2.0.2-1.fc40                                          rawhide        523 k
 firewalld-filesystem                              noarch        2.0.2-1.fc40                                          rawhide        9.6 k
 gdb                                               x86_64        13.2-12.fc40                                          rawhide        139 k
 gdb-headless                                      x86_64        13.2-12.fc40                                          rawhide        4.7 M
 glibc                                             x86_64        2.38.9000-26.fc40                                     rawhide        2.2 M
 glibc-common                                      x86_64        2.38.9000-26.fc40                                     rawhide        367 k
 glibc-gconv-extra                                 x86_64        2.38.9000-26.fc40                                     rawhide        1.7 M
 glibc-langpack-de                                 x86_64        2.38.9000-26.fc40                                     rawhide        640 k
 glibc-langpack-en                                 x86_64        2.38.9000-26.fc40                                     rawhide        686 k
 glibc-langpack-pt                                 x86_64        2.38.9000-26.fc40                                     rawhide        621 k
 gnutls                                            x86_64        3.8.2-2.fc40                                          rawhide        1.1 M
 gnutls-dane                                       x86_64        3.8.2-2.fc40                                          rawhide         38 k
 gnutls-utils                                      x86_64        3.8.2-2.fc40                                          rawhide        313 k
 kernel-tools                                      x86_64        6.7.0-0.rc3.git0.1.fc40                               rawhide        313 k
 kernel-tools-libs                                 x86_64        6.7.0-0.rc3.git0.1.fc40                               rawhide         29 k
 kmod                                              x86_64        31-3.fc40                                             rawhide        121 k
 kmod-libs                                         x86_64        31-3.fc40                                             rawhide         67 k
 kpartx                                            x86_64        0.9.7-4.fc40                                          rawhide         49 k
 libacl                                            x86_64        2.3.1-11.fc40                                         rawhide         24 k
 libsmbclient                                      x86_64        2:4.19.3-2.fc40                                       rawhide         79 k
 libvirt-client                                    x86_64        9.10.0-1.fc40                                         rawhide        428 k
 libvirt-daemon-common                             x86_64        9.10.0-1.fc40                                         rawhide        118 k
 libvirt-daemon-config-network                     x86_64        9.10.0-1.fc40                                         rawhide         13 k
 libvirt-daemon-driver-interface                   x86_64        9.10.0-1.fc40                                         rawhide        161 k
 libvirt-daemon-driver-network                     x86_64        9.10.0-1.fc40                                         rawhide        198 k
 libvirt-daemon-driver-nodedev                     x86_64        9.10.0-1.fc40                                         rawhide        181 k
 libvirt-daemon-driver-qemu                        x86_64        9.10.0-1.fc40                                         rawhide        896 k
 libvirt-daemon-driver-storage-core                x86_64        9.10.0-1.fc40                                         rawhide        214 k
 libvirt-daemon-driver-storage-disk                x86_64        9.10.0-1.fc40                                         rawhide         21 k
 libvirt-daemon-driver-storage-iscsi               x86_64        9.10.0-1.fc40                                         rawhide         19 k
 libvirt-daemon-driver-storage-iscsi-direct        x86_64        9.10.0-1.fc40                                         rawhide         21 k
 libvirt-daemon-driver-storage-logical             x86_64        9.10.0-1.fc40                                         rawhide         22 k
 libvirt-daemon-log                                x86_64        9.10.0-1.fc40                                         rawhide         52 k
 libvirt-glib                                      x86_64        5.0.0-1.fc40                                          rawhide         54 k
 libvirt-libs                                      x86_64        9.10.0-1.fc40                                         rawhide        4.9 M
 libwbclient                                       x86_64        2:4.19.3-2.fc40                                       rawhide         48 k
 linux-system-roles                                noarch        1.61.1-1.fc40                                         rawhide        2.6 M
 llvm-libs                                         x86_64        17.0.6-1.fc40                                         rawhide         27 M
 mesa-dri-drivers                                  x86_64        23.3.0-1.fc40                                         rawhide         25 M
 mesa-filesystem                                   x86_64        23.3.0-1.fc40                                         rawhide         18 k
 mesa-libEGL                                       x86_64        23.3.0-1.fc40                                         rawhide        133 k
 mesa-libGL                                        x86_64        23.3.0-1.fc40                                         rawhide        175 k
 mesa-libgbm                                       x86_64        23.3.0-1.fc40                                         rawhide         45 k
 mesa-libglapi                                     x86_64        23.3.0-1.fc40                                         rawhide         52 k
 mesa-va-drivers                                   x86_64        23.3.0-1.fc40                                         rawhide        3.8 M
 mock-core-configs                                 noarch        39.3-1.fc40                                           rawhide        146 k
 nbdkit                                            x86_64        1.37.3-1.fc40                                         rawhide         15 k
 nbdkit-basic-filters                              x86_64        1.37.3-1.fc40                                         rawhide        332 k
 nbdkit-basic-plugins                              x86_64        1.37.3-1.fc40                                         rawhide        216 k
 nbdkit-curl-plugin                                x86_64        1.37.3-1.fc40                                         rawhide         45 k
 nbdkit-selinux                                    noarch        1.37.3-1.fc40                                         rawhide         30 k
 nbdkit-server                                     x86_64        1.37.3-1.fc40                                         rawhide        131 k
 nbdkit-ssh-plugin                                 x86_64        1.37.3-1.fc40                                         rawhide         35 k
 netavark                                          x86_64        1.9.0-1.fc40                                          rawhide        3.2 M
 nspr                                              x86_64        4.35.0-16.fc40                                        rawhide        138 k
 nss                                               x86_64        3.95.0-1.fc40                                         rawhide        695 k
 nss-softokn                                       x86_64        3.95.0-1.fc40                                         rawhide        414 k
 nss-softokn-freebl                                x86_64        3.95.0-1.fc40                                         rawhide        351 k
 nss-sysinit                                       x86_64        3.95.0-1.fc40                                         rawhide         18 k
 nss-tools                                         x86_64        3.95.0-1.fc40                                         rawhide        542 k
 nss-util                                          x86_64        3.95.0-1.fc40                                         rawhide         87 k
 pcsc-lite                                         x86_64        2.0.1-1.fc40                                          rawhide         95 k
 pcsc-lite-libs                                    x86_64        2.0.1-1.fc40                                          rawhide         28 k
 podman                                            x86_64        5:4.8.0-1.fc40                                        rawhide         15 M
 python3-cryptography                              x86_64        41.0.5-2.fc40                                         rawhide        1.2 M
 python3-firewall                                  noarch        2.0.2-1.fc40                                          rawhide        508 k
 python3-idna                                      noarch        3.6-1.fc40                                            rawhide        107 k
 python3-linux-procfs                              noarch        0.7.3-2.fc40                                          rawhide         36 k
 python3-perf                                      x86_64        6.7.0-0.rc3.git0.1.fc40                               rawhide        128 k
 python3-pexpect                                   noarch        4.9.0-2.fc40                                          rawhide        175 k
 python3-pyasn1                                    noarch        0.5.1-1.fc40                                          rawhide        197 k
 python3-pyasn1-modules                            noarch        0.5.1-1.fc40                                          rawhide        377 k
 python3-rpm                                       x86_64        4.19.0-3.fc40                                         rawhide         69 k
 qemu-audio-spice                                  x86_64        2:8.1.2-2.fc40                                        rawhide         18 k
 qemu-block-curl                                   x86_64        2:8.1.2-2.fc40                                        rawhide         23 k
 qemu-char-spice                                   x86_64        2:8.1.2-2.fc40                                        rawhide         19 k
 qemu-common                                       x86_64        2:8.1.2-2.fc40                                        rawhide        593 k
 qemu-device-usb-host                              x86_64        2:8.1.2-2.fc40                                        rawhide         29 k
 qemu-device-usb-redirect                          x86_64        2:8.1.2-2.fc40                                        rawhide         36 k
 qemu-guest-agent                                  x86_64        2:8.1.2-2.fc40                                        rawhide        315 k
 qemu-img                                          x86_64        2:8.1.2-2.fc40                                        rawhide        1.9 M
 qemu-kvm-core                                     x86_64        2:8.1.2-2.fc40                                        rawhide         11 k
 qemu-system-x86-core                              x86_64        2:8.1.2-2.fc40                                        rawhide        8.0 M
 qemu-ui-opengl                                    x86_64        2:8.1.2-2.fc40                                        rawhide         24 k
 qemu-ui-spice-core                                x86_64        2:8.1.2-2.fc40                                        rawhide         34 k
 qemu-user-static                                  x86_64        2:8.1.2-2.fc40                                        rawhide         24 k
 qemu-user-static-aarch64                          x86_64        2:8.1.2-2.fc40                                        rawhide        2.3 M
 qemu-user-static-alpha                            x86_64        2:8.1.2-2.fc40                                        rawhide        1.2 M
 qemu-user-static-arm                              x86_64        2:8.1.2-2.fc40                                        rawhide        1.9 M
 qemu-user-static-cris                             x86_64        2:8.1.2-2.fc40                                        rawhide        1.2 M
 qemu-user-static-hexagon                          x86_64        2:8.1.2-2.fc40                                        rawhide        1.6 M
 qemu-user-static-hppa                             x86_64        2:8.1.2-2.fc40                                        rawhide        1.3 M
 qemu-user-static-loongarch64                      x86_64        2:8.1.2-2.fc40                                        rawhide        1.3 M
 qemu-user-static-m68k                             x86_64        2:8.1.2-2.fc40                                        rawhide        1.3 M
 qemu-user-static-microblaze                       x86_64        2:8.1.2-2.fc40                                        rawhide        1.5 M
 qemu-user-static-mips                             x86_64        2:8.1.2-2.fc40                                        rawhide        3.5 M
 qemu-user-static-nios2                            x86_64        2:8.1.2-2.fc40                                        rawhide        1.2 M
 qemu-user-static-or1k                             x86_64        2:8.1.2-2.fc40                                        rawhide        1.2 M
 qemu-user-static-ppc                              x86_64        2:8.1.2-2.fc40                                        rawhide        2.3 M
 qemu-user-static-riscv                            x86_64        2:8.1.2-2.fc40                                        rawhide        1.8 M
 qemu-user-static-s390x                            x86_64        2:8.1.2-2.fc40                                        rawhide        1.3 M
 qemu-user-static-sh4                              x86_64        2:8.1.2-2.fc40                                        rawhide        1.5 M
 qemu-user-static-sparc                            x86_64        2:8.1.2-2.fc40                                        rawhide        1.9 M
 qemu-user-static-x86                              x86_64        2:8.1.2-2.fc40                                        rawhide        1.8 M
 qemu-user-static-xtensa                           x86_64        2:8.1.2-2.fc40                                        rawhide        2.0 M
 qt6-srpm-macros                                   noarch        6.6.1-1.fc40                                          rawhide        8.6 k
 rpm                                               x86_64        4.19.0-3.fc40                                         rawhide        537 k
 rpm-build                                         x86_64        4.19.0-3.fc40                                         rawhide         79 k
 rpm-build-libs                                    x86_64        4.19.0-3.fc40                                         rawhide         96 k
 rpm-libs                                          x86_64        4.19.0-3.fc40                                         rawhide        313 k
 rpm-plugin-audit                                  x86_64        4.19.0-3.fc40                                         rawhide         20 k
 rpm-plugin-selinux                                x86_64        4.19.0-3.fc40                                         rawhide         21 k
 rpm-plugin-systemd-inhibit                        x86_64        4.19.0-3.fc40                                         rawhide         20 k
 rpm-sequoia                                       x86_64        1.5.0-2.fc40                                          rawhide        879 k
 rpm-sign-libs                                     x86_64        4.19.0-3.fc40                                         rawhide         27 k
 samba-client-libs                                 x86_64        2:4.19.3-2.fc40                                       rawhide        5.3 M
 samba-common                                      noarch        2:4.19.3-2.fc40                                       rawhide        153 k
 samba-common-libs                                 x86_64        2:4.19.3-2.fc40                                       rawhide        110 k
 seabios-bin                                       noarch        1.16.3-1.fc40                                         rawhide        185 k
 seavgabios-bin                                    noarch        1.16.3-1.fc40                                         rawhide         38 k
 selinux-policy                                    noarch        40.6-1.fc40                                           rawhide         58 k
 selinux-policy-devel                              noarch        40.6-1.fc40                                           rawhide        916 k
 selinux-policy-targeted                           noarch        40.6-1.fc40                                           rawhide        6.9 M
 setup                                             noarch        2.14.5-1.fc40                                         rawhide        155 k
 stratisd                                          x86_64        3.6.3-1.fc40                                          rawhide        3.6 M
 systemd                                           x86_64        255~rc4-3.fc40                                        rawhide        4.9 M
 systemd-container                                 x86_64        255~rc4-3.fc40                                        rawhide        588 k
 systemd-libs                                      x86_64        255~rc4-3.fc40                                        rawhide        702 k
 systemd-networkd                                  x86_64        255~rc4-3.fc40                                        rawhide        679 k
 systemd-oomd-defaults                             noarch        255~rc4-3.fc40                                        rawhide         27 k
 systemd-pam                                       x86_64        255~rc4-3.fc40                                        rawhide        383 k
 systemd-resolved                                  x86_64        255~rc4-3.fc40                                        rawhide        298 k
 systemd-rpm-macros                                noarch        255~rc4-3.fc40                                        rawhide         31 k
 systemd-udev                                      x86_64        255~rc4-3.fc40                                        rawhide        2.3 M
 xkeyboard-config                                  noarch        2.40-2.fc40                                           rawhide        972 k
Installing dependencies:
 kernel-modules-core                               x86_64        6.7.0-0.rc3.20231201git994d5c58e50e.32.fc40           rawhide         33 M
```

the test still passes right after upgrade before rebooting, with the old kernel 6.7.0-0.rc2. After rebooting into the new kernel 6.7.0-0.rc3 it still passes. But the TF test installs a lot of stuff from the "testing-farm-tag-repository", which is packages which were uploaded/built but haven't reached the mirrors yet.

I'll check how to access that.
