### ISSUE TITLE
 Browser Console Error: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by SteveOverSea** [cockpit-project/cockpit#20089]
### Explain what happens

1.  Logging into Cockpit
2.  Seeing "Ooops Unexpected error in Dashboard"
3. Opening browser console and seeing:

```
updates.js:55 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at Function.<anonymous> (updates.js:55:1725)
    at G (cockpit.js:5:5607)
    at cockpit.js:5:5802
    at k (cockpit.js:5:4658)
```
I am basically not missing any functionality. I just find the error a bit annoying - and I don't know what it is about.

### Version of Cockpit

300.1

### Where is the problem in Cockpit?

Overview

### Server operating system

other

### Server operating system version

AlmaLinux 8.9

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
I decoded that stack trace, it crashes exactly here: https://github.com/cockpit-project/cockpit/blob/8b286778ad98962835ef5f5058f7d30603b9b97d/pkg/packagekit/kpatch.jsx#L132

This means that your `uname -r` does not have a release part i.e. nothing after the `-`. Can you please give me the output of `uname -r`? I'll fix it either way, but  I'm curious.

Thanks!

**Comment by SteveOverSea** [comment]
`uname  -r` gives

```bash
4.18.0
```

Thanks for the quick update. Unfortunately I can't easily check if it's working for me now, because somehow the cockpit version in my the default-configured yum package manager in AlmaLinux seems to be frozen at 300.1

**Comment by martinpitt** [comment]
Thanks @SteveOverSea , so what I thought. This should be fixed then. If you want to, you can use the EPEL 8 build from https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/
