### ISSUE TITLE
Cannot login. cockpit-ws[60693]: ModuleNotFoundError: No module named 'cockpit'

### ISSUE THREAD

**Issue by dontdieych** [cockpit-project/cockpit#20465]
### Explain what happens

1. Install cockpit. `enable --now cockpit.socket`. (ArchlinuxArm)
2. Open ssh tunnel from my laptop. `ssh myhost -L 9090:localhost:9090 -NT`
3. open `http://localhost:9090`. try login as my server user account/password.(wheel group, sudo capable)
4. 'Wrong user name or password' error and got this log msg from journal

```
May 14 09:31:38 alarm systemd[1]: Started Cockpit Web Service http instance.
May 14 09:31:46 alarm cockpit-session[60687]: pam_unix(cockpit:session): session opened for user alarm(uid=1000) by alarm(uid=0)
May 14 09:31:46 alarm cockpit-ws[60687]: cockpit-session: pam: Web console: https://localhost:9090/ or https://10.0.0.43:9090/
May 14 09:31:46 alarm systemd-logind[442]: New session 15 of user alarm.
May 14 09:31:46 alarm systemd[1]: Started Session 15 of User alarm.
May 14 09:31:46 alarm cockpit-ws[60693]: Traceback (most recent call last):
May 14 09:31:46 alarm cockpit-ws[60693]:   File "/usr/bin/cockpit-bridge", line 5, in <module>
May 14 09:31:46 alarm cockpit-ws[60693]:     from cockpit.bridge import main
May 14 09:31:46 alarm cockpit-ws[60693]: ModuleNotFoundError: No module named 'cockpit'
May 14 09:31:46 alarm cockpit-session[60687]: pam_unix(cockpit:session): session closed for user alarm
May 14 09:31:46 alarm systemd[1]: session-15.scope: Deactivated successfully.
May 14 09:31:46 alarm systemd-logind[442]: Session 15 logged out. Waiting for processes to exit.
May 14 09:31:46 alarm systemd-logind[442]: Removed session 15.
```

`cockpit 300.1-1`

### Version of Cockpit

300.1-1

### Where is the problem in Cockpit?

Accounts

### Server operating system

Arch Linux

### Server operating system version

ArchlinuxArm

### What browsers are you using?

Chrome

### System log

```shell
May 14 09:31:38 alarm systemd[1]: Started Cockpit Web Service http instance.
May 14 09:31:46 alarm cockpit-session[60687]: pam_unix(cockpit:session): session opened for user alarm(uid=1000) by alarm(uid=0)
May 14 09:31:46 alarm cockpit-ws[60687]: cockpit-session: pam: Web console: https://localhost:9090/ or https://10.0.0.43:9090/
May 14 09:31:46 alarm systemd-logind[442]: New session 15 of user alarm.
May 14 09:31:46 alarm systemd[1]: Started Session 15 of User alarm.
May 14 09:31:46 alarm cockpit-ws[60693]: Traceback (most recent call last):
May 14 09:31:46 alarm cockpit-ws[60693]:   File "/usr/bin/cockpit-bridge", line 5, in <module>
May 14 09:31:46 alarm cockpit-ws[60693]:     from cockpit.bridge import main
May 14 09:31:46 alarm cockpit-ws[60693]: ModuleNotFoundError: No module named 'cockpit'
May 14 09:31:46 alarm cockpit-session[60687]: pam_unix(cockpit:session): session closed for user alarm
May 14 09:31:46 alarm systemd[1]: session-15.scope: Deactivated successfully.
May 14 09:31:46 alarm systemd-logind[442]: Session 15 logged out. Waiting for processes to exit.
May 14 09:31:46 alarm systemd-logind[442]: Removed session 15.
```

**Comment by dontdieych** [comment]
I've found arch arm version is quite behind for official.

Compiled 316 version from arch x86 abs repo. Now login fine.

Sorry for bothering.

PKGBUILD  (just added 'aarch64' to arch field)

https://gist.github.com/dontdieych/415048744e34e42e1cddf3fff66e914f
