### ISSUE TITLE
[Clear Linux] Cannot login - `ModuleNotFoundError: No module named '_lzma'`

### ISSUE THREAD

**Issue by ThaDaVos** [cockpit-project/cockpit#20677]
### Explain what happens

1. Open web-interface
2. Login with only user available
3. Get error that login is incorrect

### Version of Cockpit

Bundle version 41960

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Clear Linux

### Server operating system version

41960

### What browsers are you using?

Firefox, Edge

### System log

```shell
Jun 29 17:10:52 clr-live.vos.local cockpit-session[689]: pam_unix(cockpit:session): session opened for user vossystems(uid=1000) by vossystems(uid=0)
Jun 29 17:10:52 clr-live.vos.local systemd-logind[357]: New session 10 of user vossystems.
Jun 29 17:10:52 clr-live.vos.local systemd[1]: Started session-10.scope.
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]: Traceback (most recent call last):
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:   File "/usr/bin/cockpit-bridge", line 5, in <module>
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:     from cockpit.bridge import main
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:   File "/usr/lib/python3.12/site-packages/cockpit/bridge.py", line 45, in <module>
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:     from .superuser import SuperuserRoutingRule
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:   File "/usr/lib/python3.12/site-packages/cockpit/superuser.py", line 32, in <module>
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:     from .beipack import BridgeBeibootHelper
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:   File "/usr/lib/python3.12/site-packages/cockpit/beipack.py", line 19, in <module>
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:     import lzma
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:   File "/usr/lib/python3.12/lzma.py", line 27, in <module>
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]:     from _lzma import *
Jun 29 17:10:53 clr-live.vos.local cockpit-ws[694]: ModuleNotFoundError: No module named '_lzma'
Jun 29 17:10:53 clr-live.vos.local cockpit-session[689]: pam_unix(cockpit:session): session closed for user vossystems
Jun 29 17:10:53 clr-live.vos.local systemd[1]: session-10.scope: Deactivated successfully.
Jun 29 17:10:53 clr-live.vos.local systemd-logind[357]: Session 10 logged out. Waiting for processes to exit.
Jun 29 17:10:53 clr-live.vos.local systemd-logind[357]: Removed session 10.
```

**Comment by martinpitt** [comment]
This is a broken python 3.12 package in ClearLinux, `python3 -c 'import lzma` fails. Please report this against ClearLinux, there's nothing that we can do about it in the upstream cockpit project.

**Comment by ThaDaVos** [comment]
But just to be sure, it's the cause for me not being able to login, correct?

**Comment by jelly** [comment]
@ThaDaVos yes
