### ISSUE TITLE
cockpit-tls high CPU utilization - Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by tucsy90** [cockpit-project/cockpit#20913]
### Explain what happens

If I open the web console of cockpit, the CPU usage of cockpit-tls is 100% and the whole system is slow down.
I installed the latest version of cockpit from Ubuntu reposítory with apt install.

![cockpit high cpu](https://github.com/user-attachments/assets/45c0708b-8f22-409d-8e2c-379537e1f145)
![ubuntu-release](https://github.com/user-attachments/assets/27bcb2b4-e62b-4f21-861e-ff92f26a78f8)

### Where is the problem in Cockpit?

None

### Server operating system

Ubuntu

### What browsers are you using?

Firefox

### System log

```shell
Aug 19 15:50:35 tucsysrv systemd[1]: Configuration file /run/systemd/system/netplan-ovs-cleanup.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anywa>
Aug 19 15:50:35 tucsysrv systemd[1]: Starting Cockpit Web Service Socket...
Aug 19 15:50:35 tucsysrv systemd[1]: Listening on Cockpit Web Service Socket.
Aug 19 15:50:35 tucsysrv systemd[1]: Starting Cockpit motd updater service...
Aug 19 15:50:35 tucsysrv systemd[1]: cockpit-motd.service: Deactivated successfully.
Aug 19 15:50:35 tucsysrv systemd[1]: Finished Cockpit motd updater service.
Aug 19 15:50:41 tucsysrv dbus-daemon[1852]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.34' (uid=0 pid=11546 comm="/usr/bin/gdbus call --system --dest org.freedes>
Aug 19 15:50:41 tucsysrv systemd[1]: Starting PackageKit Daemon...
Aug 19 15:50:41 tucsysrv PackageKit[11549]: daemon start
Aug 19 15:50:41 tucsysrv dbus-daemon[1852]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Aug 19 15:50:41 tucsysrv systemd[1]: Started PackageKit Daemon.
Aug 19 15:50:41 tucsysrv sudo[10123]: pam_unix(sudo:session): session closed for user root
Aug 19 15:50:50 tucsysrv systemd[1]: Starting Socket for Cockpit Web Service http instance...
Aug 19 15:50:50 tucsysrv systemd[1]: Starting Socket for Cockpit Web Service https instance factory...
Aug 19 15:50:50 tucsysrv systemd[1]: Listening on Socket for Cockpit Web Service http instance.
Aug 19 15:50:50 tucsysrv systemd[1]: Listening on Socket for Cockpit Web Service https instance factory.
Aug 19 15:50:50 tucsysrv systemd[1]: Starting Cockpit Web Service...
Aug 19 15:50:50 tucsysrv systemd[1]: Started Cockpit Web Service.
Aug 19 15:50:51 tucsysrv cockpit-tls[11842]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
Aug 19 15:50:51 tucsysrv systemd[1]: Created slice Slice /system/cockpit-wsinstance-https-factory.
Aug 19 15:50:51 tucsysrv systemd[1]: Started Cockpit Web Service https instance factory (PID 11842/UID 116).
Aug 19 15:50:51 tucsysrv systemd[1]: Created slice Slice /system/cockpit-wsinstance-https.
Aug 19 15:50:51 tucsysrv systemd[1]: Created slice Resource limits for all cockpit-ws-https@.service instances.
Aug 19 15:50:51 tucsysrv systemd[1]: Starting Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855...
Aug 19 15:50:51 tucsysrv systemd[1]: Listening on Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Aug 19 15:50:51 tucsysrv systemd[1]: Started Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Aug 19 15:50:51 tucsysrv systemd[1]: cockpit-wsinstance-https-factory@0-11842-116.service: Deactivated successfully.
Aug 19 15:50:51 tucsysrv cockpit-tls[11842]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
Aug 19 15:50:51 tucsysrv cockpit-tls[11842]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
Aug 19 15:50:51 tucsysrv cockpit-tls[11842]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
Aug 19 15:50:51 tucsysrv cockpit-tls[11842]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
Aug 19 15:50:51 tucsysrv cockpit-tls[11842]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
Aug 19 15:51:08 tucsysrv sudo[11921]:    jimre : TTY=pts/0 ; PWD=/home/jimre ; USER=root ; COMMAND=/usr/bin/journalctl --since -10m
Aug 19 15:51:08 tucsysrv sudo[11921]: pam_unix(sudo:session): session opened for user root(uid=0) by jimre(uid=1000)
Aug 19 15:51:23 tucsysrv sudo[11921]: pam_unix(sudo:session): session closed for user root
Aug 19 15:51:24 tucsysrv cockpit-ws[11847]: request timed out, closing
Aug 19 15:51:25 tucsysrv sudo[12099]:    jimre : TTY=pts/0 ; PWD=/home/jimre ; USER=root ; COMMAND=/usr/bin/journalctl --since -10m
Aug 19 15:51:25 tucsysrv sudo[12099]: pam_unix(sudo:session): session opened for user root(uid=0) by jimre(uid=1000)
Aug 19 15:51:30 tucsysrv sudo[12099]: pam_unix(sudo:session): session closed for user root
Aug 19 15:51:40 tucsysrv sudo[12216]:    jimre : TTY=pts/0 ; PWD=/home/jimre ; USER=root ; COMMAND=/usr/bin/journalctl --since -10m
Aug 19 15:51:40 tucsysrv sudo[12216]: pam_unix(sudo:session): session opened for user root(uid=0) by jimre(uid=1000)
```

**Comment by aborniak** [comment]
The same for Fedora 40. 
<img width="1095" alt="Screenshot 2024-11-01 at 18 14 31" src="https://github.com/user-attachments/assets/20205fae-63bc-4a73-a11c-5b6f7b950523">


```
root@aborniakFC:~# rpm -qa | grep cockpit
cockpit-bridge-326-1.fc40.x86_64
cockpit-system-326-1.fc40.noarch
cockpit-networkmanager-326-1.fc40.noarch
cockpit-selinux-326-1.fc40.noarch
cockpit-storaged-326-1.fc40.noarch
cockpit-packagekit-326-1.fc40.noarch
cockpit-ws-326-1.fc40.x86_64
cockpit-326-1.fc40.x86_64
cockpit-podman-97-1.fc40.noarch
root@aborniakFC:~#
```

**Comment by jelly** [comment]
Does `strace` show anything interesting? What kind of hardware is this? And how does `/etc/cockpit/ws-certs.d` look like?

**Comment by aborniak** [comment]
This is VM on Vmware
```
root@aborniakFC:~# systemctl list-units --type=device
  UNIT                                                                                LOAD   ACTIVE SUB     DESCRIPTION
  sys-devices-pci0000:00-0000:00:07.1-ata1-host0-target0:0:0-0:0:0:0-block-sr0.device loaded active plugged VMware_Virtual_IDE_CDROM_Drive
  sys-devices-pci0000:00-0000:00:10.0-host2-target2:0:0-2:0:0:0-block-sda-sda1.device loaded active plugged Virtual_disk 1
  sys-devices-pci0000:00-0000:00:10.0-host2-target2:0:0-2:0:0:0-block-sda-sda2.device loaded active plugged Virtual_disk 2
  sys-devices-pci0000:00-0000:00:10.0-host2-target2:0:0-2:0:0:0-block-sda.device      loaded active plugged Virtual_disk
  sys-devices-pci0000:00-0000:00:11.0-0000:02:00.0-net-ens32.device                   loaded active plugged 82545EM Gigabit Ethernet Controller (Copper) (PRO/1000 MT Single Port Adapter)
  sys-devices-platform-serial8250-serial8250:0-serial8250:0.0-tty-ttyS0.device        loaded active plugged /sys/devices/platform/serial8250/serial8250:0/serial8250:0.0/tty/ttyS0
  sys-devices-platform-serial8250-serial8250:0-serial8250:0.1-tty-ttyS1.device        loaded active plugged /sys/devices/platform/serial8250/serial8250:0/serial8250:0.1/tty/ttyS1
  sys-devices-platform-serial8250-serial8250:0-serial8250:0.2-tty-ttyS2.device        loaded active plugged /sys/devices/platform/serial8250/serial8250:0/serial8250:0.2/tty/ttyS2
  sys-devices-platform-serial8250-serial8250:0-serial8250:0.3-tty-ttyS3.device        loaded active plugged /sys/devices/platform/serial8250/serial8250:0/serial8250:0.3/tty/ttyS3
  sys-devices-virtual-block-dm\x2d0.device                                            loaded active plugged /sys/devices/virtual/block/dm-0
  sys-devices-virtual-block-zram0.device                                              loaded active plugged /sys/devices/virtual/block/zram0
  sys-devices-virtual-misc-rfkill.device                                              loaded active plugged /sys/devices/virtual/misc/rfkill
  sys-module-configfs.device                                                          loaded active plugged /sys/module/configfs
  sys-module-fuse.device                                                              loaded active plugged /sys/module/fuse
  sys-subsystem-net-devices-ens32.device                                              loaded active plugged 82545EM Gigabit Ethernet Controller (Copper) (PRO/1000 MT Single Port Adapter)

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

15 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
root@aborniakFC:~#
```

ws-certs.d directory: (I use letsencrypt for certificate)
```
root@aborniakFC:~# ls /etc/cockpit/ws-certs.d
0-self-signed-ca.pem  0-self-signed.cert  1-my-clouds.cert  1-my-clouds.key  update-letsencrypt-cert.txt
root@aborniakFC:~# ls -la  /etc/cockpit/ws-certs.d
total 12
drwxr-xr-x. 2 root root  142 Oct  9 03:00 .
drwxr-xr-x. 4 root root   66 Oct  9 03:00 ..
-rw-r--r--. 1 root root 2187 Jan 11  2021 0-self-signed-ca.pem
-rw-r-----. 1 root  991 3461 Jan 11  2021 0-self-signed.cert
lrwxrwxrwx. 1 root root   52 Dec 14  2021 1-my-clouds.cert -> /etc/letsencrypt/live/fc.my-clouds.net/fullchain.pem
lrwxrwxrwx. 1 root root   50 Dec 14  2021 1-my-clouds.key -> /etc/letsencrypt/live/fc.my-clouds.net/privkey.pem
-rw-r--r--. 1 root root 1208 Dec 14  2021 update-letsencrypt-cert.txt
root@aborniakFC:~#
```

strace output when trying to log in cockpit web UI:
```
root@aborniakFC:~# strace -p 419281
strace: Process 419281 attached
epoll_wait(5, [{events=EPOLLIN, data={u32=3, u64=3}}], 1, -1) = 1
accept4(3, NULL, NULL, SOCK_CLOEXEC)    = 14
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fb906a00990, parent_tid=0x7fb906a00990, exit_signal=0, stack=0x7fb906200000, stack_size=0x7ffd80, tls=0x7fb906a006c0} => {parent_tid=[419473]}, 88) = 419473
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
epoll_wait(5, [{events=EPOLLIN, data={u32=3, u64=3}}], 1, -1) = 1
accept4(3, NULL, NULL, SOCK_CLOEXEC)    = 16
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fb90e600990, parent_tid=0x7fb90e600990, exit_signal=0, stack=0x7fb90de00000, stack_size=0x7ffd80, tls=0x7fb90e6006c0} => {parent_tid=[419474]}, 88) = 419474
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
epoll_wait(5, [{events=EPOLLIN, data={u32=3, u64=3}}], 1, -1) = 1
accept4(3, NULL, NULL, SOCK_CLOEXEC)    = 19
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb90e800000
mprotect(0x7fb90e801000, 8388608, PROT_READ|PROT_WRITE) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fb90f000990, parent_tid=0x7fb90f000990, exit_signal=0, stack=0x7fb90e800000, stack_size=0x7ffd80, tls=0x7fb90f0006c0} => {parent_tid=[419478]}, 88) = 419478
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
epoll_wait(5, [{events=EPOLLIN, data={u32=3, u64=3}}], 1, -1) = 1
accept4(3, NULL, NULL, SOCK_CLOEXEC)    = 8
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fb906a00990, parent_tid=0x7fb906a00990, exit_signal=0, stack=0x7fb906200000, stack_size=0x7ffd80, tls=0x7fb906a006c0} => {parent_tid=[419496]}, 88) = 419496
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
epoll_wait(5, ^Cstrace: Process 419281 detached
 <detached ...>

root@aborniakFC:~#

```

**Comment by jayache80** [comment]
I believe I'm experiencing the same issue. The cockpit web interface will be non-responsive, and the server will have a cockpit-cls process pinned at 100% CPU. When this was occurring, I attached gdb to the cockpit-tls process and got these backtraces (which are perhaps not interesting):
```
(gdb) thread apply all bt

Thread 5 (Thread 0x7f714970c6c0 (LWP 73573) "cockpit-tls"):
#0  0x00007f714ccc063d in __GI___poll (fds=fds@entry=0x7f7149702be0, nfds=nfds@entry=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00005d6b78b6a951 in poll (__fds=0x7f7149702be0, __nfds=2, __timeout=-1) at /usr/include/bits/poll2.h:44
#2  connection_thread_loop (self=<optimized out>) at src/tls/connection.c:678
#3  connection_thread_main (fd=<optimized out>) at src/tls/connection.c:820
#4  0x00005d6b78b6b429 in server_connection_thread_start_routine (data=<optimized out>) at src/tls/server.c:92
#5  0x00007f714cc4939d in start_thread (arg=<optimized out>) at pthread_create.c:447
#6  0x00007f714ccce49c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 3 (Thread 0x7f714af0f6c0 (LWP 73607) "cockpit-tls"):
#0  0x00007f714ccc063d in __GI___poll (fds=fds@entry=0x7f714af05be0, nfds=nfds@entry=2, timeout=timeout@entry=0) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00005d6b78b6a951 in poll (__fds=0x7f714af05be0, __nfds=2, __timeout=0) at /usr/include/bits/poll2.h:44
#2  connection_thread_loop (self=<optimized out>) at src/tls/connection.c:678
#3  connection_thread_main (fd=<optimized out>) at src/tls/connection.c:820
#4  0x00005d6b78b6b429 in server_connection_thread_start_routine (data=<optimized out>) at src/tls/server.c:92
#5  0x00007f714cc4939d in start_thread (arg=<optimized out>) at pthread_create.c:447
#6  0x00007f714ccce49c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 2 (Thread 0x7f714b7106c0 (LWP 73629) "cockpit-tls"):
#0  0x00007f714ccc063d in __GI___poll (fds=fds@entry=0x7f714b706be0, nfds=nfds@entry=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00005d6b78b6a951 in poll (__fds=0x7f714b706be0, __nfds=2, __timeout=-1) at /usr/include/bits/poll2.h:44
#2  connection_thread_loop (self=<optimized out>) at src/tls/connection.c:678
#3  connection_thread_main (fd=<optimized out>) at src/tls/connection.c:820
#4  0x00005d6b78b6b429 in server_connection_thread_start_routine (data=<optimized out>) at src/tls/server.c:92
#5  0x00007f714cc4939d in start_thread (arg=<optimized out>) at pthread_create.c:447
#6  0x00007f714ccce49c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7f714c713940 (LWP 73530) "cockpit-tls"):
#0  0x00007f714ccce8b2 in epoll_wait (epfd=5, events=events@entry=0x7ffd77d2f3b0, maxevents=maxevents@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00005d6b78b687fc in server_poll_event (timeout=-1) at src/tls/server.c:328
#2  server_run () at src/tls/server.c:361
#3  main (argc=<optimized out>, argv=<optimized out>) at src/tls/main.c:135
```
This is running Arch Linux, 6.11.9 kernel, Cockpit 329

**Comment by LennyLip** [comment]
Same thing, debian

```
# apt-cache policy cockpit
cockpit:
  Installed: 287.1-0+deb12u3
  Candidate: 287.1-0+deb12u3
  Version table:
```

**Comment by LennyLip** [comment]
> As mentioned by @gen-angry on #21098 (thanks!!) a workaround is to allow plain HTTP access by creating `/etc/cockpit/cockpit.conf` file (if it doesn't already exist) and placing into it:
> 
> ```
> [WebService]
> AllowUnencrypted=true
> ```
> 
> As this is a local network server, this workaround is fine for me.

I set this config, change https to http://ip:9090, it show Login window, but when I trying to login it give me 401 Error (the same login works for https://ip:9090
![Screenshot 2024-12-19 022652](https://github.com/user-attachments/assets/964fb32a-fc69-49e0-83bb-ab26a9bedffb)

**Comment by jayache80** [comment]
> I set this config, change https to http://ip:9090, it show Login window, but when I trying to login it give me 401 Error (the same login works for https://ip:9090 

Did you clear cookies? Maybe try a fresh browser or private/incognito mode. I had trouble logging in at first as well upon switching to HTTP, but got past that.

**Comment by zhaojing1987** [comment]
the same problem on ubuntu 22.04  cockpit-329
When I click on a menu, it keeps loading. When I use top to check, I find that the cock tls occupy 100% or even 200% of the CPU, which lasts for a long time. When its CPU usage drops to normal, the page loads successfully。
This situation occurs frequently, which limits the normal use of the cock to a certain extent

![Image](https://github.com/user-attachments/assets/939af5f3-51f6-481c-89ed-c907eae7a445)

![Image](https://github.com/user-attachments/assets/308026d1-ccf9-4f73-af26-3d1f354f0343)

**Comment by screwyrabbit** [comment]
Same problem on a Rocky Linux server, but a slightly different manifestation.
Logging in to Cockpit works fine at first, as cockpit-tls appears normal (almost no CPU usage). But some time later (a few minutes to half an hour) cockpit-tls goes to 100% on one CPU and stays there. I need to log-out and log back in to Cockpit in order to get it back to normal.
The server has ten hyper-threaded cores, so loosing one CPU isn't a big deal, but it annoys me anyway.

**Comment by anatol-grabowski** [comment]
Maybe this is somehow related to **nginx**. For me the problem appeared after installing nginx and it was resolved after stoping nginx service and removing everything related to nginx. Using nginx in docker now.

**Comment by screwyrabbit** [comment]
An update to the Rocky Linux issue:
By the way: The cockpit client is Ubuntu 24.04.2 LTS, and mayb that's where the issue is.
My issue seems to be different - It is related to monitoring Virtual Machines. There is no problem exploring anywhere in Cockpit except VMs. If I log in to Cockpit and select "Virtual machines" in the sidebar, I still don't have a problem. But as soon as I open a VM to check its status, cockpit-tls goes to 100% on one core. It will stay that way, even when leaving "Virtual machines". It will only be cleared by closing and re-opening cockpit on the client.

**Comment by Gloryandel** [comment]
如果是使用的自签名证书，以下操作可以极大缓解 cockpit-tls 高占用，页面低延时。

**Comment by martinpitt** [comment]
Tracking this in #22274
