### ISSUE TITLE
Logical volume TEST2/one contains a filesystem in use.

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2629]
The lvremove command is failing sporadically with this message. 
```
Error deleting logical volume: Command-line `lvremove -f "TEST2"/"one"' exited with non-zero exit status 5: Logical volume TEST2/one contains a filesystem in use.
```

Test failure:

```
Wrote check-storage-lvm2-testLvm-FAIL.png
Journal database copied to check-storage-lvm2-testLvm-10.111.111.11-FAIL.journal
EWarning: Permanently added '10.111.111.11' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testLvm (__main__.TestStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-storage-lvm2", line 125, in testLvm
    self.confirm()
  File "/home/hubbot/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/test/storagelib.py", line 126, in confirm
    self.dialog({})
  File "/home/hubbot/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/test/storagelib.py", line 123, in dialog
    self.dialog_wait_close()
  File "/home/hubbot/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/test/storagelib.py", line 108, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/hubbot/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/test/testlib.py", line 232, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/home/hubbot/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/test/testlib.py", line 223, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/test/testlib.py", line 637, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/test/testlib.py", line 600, in run
    raise Error("timeout")
Error: timeout

----------------------------------------------------------------------
Ran 1 test in 105.201s

FAILED (errors=1)
```

**Comment by stefwalter** [comment]
![check-storage-lvm2-testlvm-fail](https://cloud.githubusercontent.com/assets/795070/9505112/b56de2ea-4c40-11e5-9308-1dcf3d03d992.png)

**Comment by stefwalter** [comment]
Failure here: http://files.cockpit-project.org/hubbot/d29758b2b745cc494fb2bc33888f1fd24742f7ad_f22_x86-64/hubbot.html

**Comment by stefwalter** [comment]
Another case of this, same stack trace and screenshot: http://files.cockpit-project.org/hubbot/f07eecdae7398e1c27ca423e3e076974b1c2969a_f22_x86-64/hubbot.html

**Comment by mvollmer** [comment]
Seems to have gone away....
