### ISSUE TITLE
"Unrecognized Data" not found in TestStorage.testMounting

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2630]
This test failure shows up on my machine sometimes:

```
Wrote check-storage-mounting-testMounting-FAIL.png
Journal database copied to check-storage-mounting-testMounting-10.111.111.10-FAIL.journal
EWarning: Permanently added '10.111.111.10' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testMounting (__main__.TestStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-storage-mounting", line 125, in testMounting
    b.wait_in_text("#content", "Unrecognized Data")
  File "/data/src/cockpit/test/testlib.py", line 250, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/data/src/cockpit/test/testlib.py", line 223, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/data/src/cockpit/test/testlib.py", line 637, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/data/src/cockpit/test/testlib.py", line 600, in run
    raise Error("timeout")
Error: timeout
```

**Comment by stefwalter** [comment]
![check-storage-mounting-testmounting-fail](https://cloud.githubusercontent.com/assets/795070/9505213/61dbd9d8-4c41-11e5-8046-2917c5e7f175.png)

**Comment by mvollmer** [comment]
Does this still happen?

**Comment by stefwalter** [comment]
I haven't seen it since above.

**Comment by mvollmer** [comment]
Let's close this, fingers crossed.
