### ISSUE TITLE
check-networking test failure when veth1xxx exists

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2647]
When a device with a name like veth1xxxx exists, check-networking fails.

```

OK
Wrote check-networking-testBridge-FAIL.png
Journal database copied to check-networking-testBridge-10.111.111.12-FAIL.journal
..Page error: label:contains('eth1') input is ambigous
EWarning: Permanently added '10.111.111.12' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBridge (__main__.TestNetworking)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-networking", line 201, in testBridge
    b.set_checked("label:contains('%s') input" % iface1, True)
  File "/home/hubbot/hubbot/3e0abb2a7cf3a663d261bab5becda05e5f9eadf2_f22-atomic_x86-64/test/testlib.py", line 196, in set_checked
    self.call_js_func('ph_set_checked', selector, val)
  File "/home/hubbot/hubbot/3e0abb2a7cf3a663d261bab5becda05e5f9eadf2_f22-atomic_x86-64/test/testlib.py", line 170, in call_js_func
    return self.phantom.do("return %s(%s);" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/3e0abb2a7cf3a663d261bab5becda05e5f9eadf2_f22-atomic_x86-64/test/testlib.py", line 644, in do
    return self.run({'cmd': 'do', 'code': code})
  File "/home/hubbot/hubbot/3e0abb2a7cf3a663d261bab5becda05e5f9eadf2_f22-atomic_x86-64/test/testlib.py", line 608, in run
    raise Error(res['error'])
Error: label:contains('eth1') input is ambigous
```

**Comment by stefwalter** [comment]
![check-networking-testbridge-fail](https://cloud.githubusercontent.com/assets/795070/9542541/e5a7e942-4d71-11e5-899f-77c86854eada.png)

**Comment by mvollmer** [comment]
The test now uses code like this:
```
b.set_checked("input[data-iface='%s']" % iface1, True)
```
so this issue should be gone.
