### ISSUE TITLE
check-kubernetes frequently fails

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#2673]
Like this:

```
Wrote check-kubernetes-testDashboard-FAIL.png
Journal database copied to check-kubernetes-testDashboard-10.111.111.13-FAIL.journal
.EWarning: Permanently added '10.111.111.13' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testDashboard (__main__.TestKubernetes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-kubernetes", line 113, in testDashboard
    b.wait_text("#service-list tr[data-name='mock']:first-of-type td.containers", "1")
  File "/home/hubbot/hubbot/0f5b9b0d313f4f0211ef194b5ae7929c986f2416_f22_x86-64/test/testlib.py", line 256, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/home/hubbot/hubbot/0f5b9b0d313f4f0211ef194b5ae7929c986f2416_f22_x86-64/test/testlib.py", line 223, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/0f5b9b0d313f4f0211ef194b5ae7929c986f2416_f22_x86-64/test/testlib.py", line 647, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/0f5b9b0d313f4f0211ef194b5ae7929c986f2416_f22_x86-64/test/testlib.py", line 610, in run
    raise Error("timeout")
Error: timeout

----------------------------------------------------------------------
Ran 2 tests in 126.126s

FAILED (errors=1)
```

**Comment by mvollmer** [comment]
For example here: http://files.cockpit-project.org/hubbot/0f5b9b0d313f4f0211ef194b5ae7929c986f2416_f22_x86-64/hubbot.html

**Comment by stefwalter** [comment]
I fixed a firewall issue on files.cockpit-project.org, and I believe that fixed this issue. In addition I increased the timeout in 2fcb2c72cc8ffc3063909d5ee7018d2e7d96806a #2668
