### ISSUE TITLE
./check-storage-mdraid fails at     b.wait_in_text("#drives", "VirtIO")

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2810]
![failure](http://files.cockpit-project.org/hubbot/5cb0d0976a6b6f197c06e885066ba137efd63484_f22_x86-64/test/check-storage-mdraid-testRaid-FAIL.png)

As seen here:

http://files.cockpit-project.org/hubbot/5cb0d0976a6b6f197c06e885066ba137efd63484_f22_x86-64/hubbot.html

```
./check-storage-mdraid
Wrote check-storage-mdraid-testRaid-FAIL.png
Journal database copied to check-storage-mdraid-testRaid-10.111.111.12-FAIL.journal
EWarning: Permanently added '10.111.111.12' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testRaid (__main__.TestStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-storage-mdraid", line 62, in testRaid
    b.wait_in_text("#drives", "VirtIO")
  File "/home/hubbot/hubbot/5cb0d0976a6b6f197c06e885066ba137efd63484_f22_x86-64/test/testlib.py", line 245, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/hubbot/hubbot/5cb0d0976a6b6f197c06e885066ba137efd63484_f22_x86-64/test/testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/5cb0d0976a6b6f197c06e885066ba137efd63484_f22_x86-64/test/testlib.py", line 643, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/5cb0d0976a6b6f197c06e885066ba137efd63484_f22_x86-64/test/testlib.py", line 606, in run
    raise Error("timeout")
Error: timeout
```

**Comment by mvollmer** [comment]
This seems to have gone away, maybe due to #2829, maybe due to something else.

**Comment by stefwalter** [comment]
Happened again here: https://fedorapeople.org/groups/cockpit/logs/master-b706dd6c-fedora-22-x86_64/log

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 68, in testRaid
    b.wait_in_text("#drives", "VirtIO")
  File "/home/hubbot/hubbot/fedora-22-x86_64-1446199292/test/testlib.py", line 240, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/hubbot/hubbot/fedora-22-x86_64-1446199292/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/fedora-22-x86_64-1446199292/test/testlib.py", line 669, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/fedora-22-x86_64-1446199292/test/testlib.py", line 692, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3106-ea191cad-fedora-22-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 68, in testRaid
    b.wait_in_text("#drives", "VirtIO")
  File "/build/cockpit/test/testlib.py", line 240, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 669, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 692, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://files.cockpit-project.org/logs/pull-3106-ea191cad-fedora-23-x86_64/log

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 68, in testRaid
    b.wait_in_text("#drives", "VirtIO")
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446200437/test/testlib.py", line 240, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446200437/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446200437/test/testlib.py", line 669, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446200437/test/testlib.py", line 692, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3106-ea191cad-rhel-7-x86_64/

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 68, in testRaid
    b.wait_in_text("#drives", "VirtIO")
  File "/data/src/cockpit/test/testlib.py", line 240, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/data/src/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/data/src/cockpit/test/testlib.py", line 669, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/data/src/cockpit/test/testlib.py", line 692, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3106-ea191cad-fedora-22-x86_64/

**Comment by stefwalter** [comment]
@mvollmer This is probably worth closing and removing the naughty file if it hasn't happened in 6 months.

**Comment by stefwalter** [comment]
No response so closing in PR above.
