### ISSUE TITLE
Timeout at b.wait_in_text("#jobs", "Erasing")

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2859]
```

./check-storage-jobs
Wrote check-storage-jobs-testJobs-FAIL.png
Journal database copied to check-storage-jobs-testJobs-10.111.111.11-FAIL.journal
EWarning: Permanently added '10.111.111.11' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testJobs (__main__.TestStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-storage-jobs", line 48, in testJobs
    b.wait_in_text("#jobs", "Erasing")
  File "/home/hubbot/hubbot/81ab931ea1ace15437287c40f3a3992741607a1b_r7_x86-64/test/testlib.py", line 238, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/hubbot/hubbot/81ab931ea1ace15437287c40f3a3992741607a1b_r7_x86-64/test/testlib.py", line 208, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/81ab931ea1ace15437287c40f3a3992741607a1b_r7_x86-64/test/testlib.py", line 644, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/81ab931ea1ace15437287c40f3a3992741607a1b_r7_x86-64/test/testlib.py", line 607, in run
    raise Error("timeout")
Error: timeout
```

**Comment by stefwalter** [comment]
Seen here: http://files.cockpit-project.org/hubbot/81ab931ea1ace15437287c40f3a3992741607a1b_r7_x86-64/hubbot.html

**Comment by mvollmer** [comment]
This test is the definition of a race condition...
