### ISSUE TITLE
Error: #networking-interfaces tr:contains('ens2') is not visible

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2903]
This is happening very regularly:

```
./check-networking
Wrote check-networking-testBasic-FAIL.png
Journal database copied to check-networking-testBasic-10.111.112.102-FAIL.journal
Page error: #networking-interfaces tr:contains('ens2') is not visible
EWarning: Permanently added '10.111.112.102' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBasic (__main__.TestNetworking)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./check-networking", line 106, in testBasic
b.click("#networking-interfaces tr:contains('%s')" % iface)
File "/home/hubbot/hubbot/a7391a8d5d1a7f66f008b500bde2709a89a48be6_f22_x86-64/test/testlib.py", line 163, in click
self.call_js_func('ph_click', selector, force)
File "/home/hubbot/hubbot/a7391a8d5d1a7f66f008b500bde2709a89a48be6_f22_x86-64/test/testlib.py", line 155, in call_js_func
return self.phantom.do("return %s(%s);" % (func, ','.join(map(jsquote, args))))
File "/home/hubbot/hubbot/a7391a8d5d1a7f66f008b500bde2709a89a48be6_f22_x86-64/test/testlib.py", line 664, in do
return self.run({'cmd': 'do', 'code': code})
File "/home/hubbot/hubbot/a7391a8d5d1a7f66f008b500bde2709a89a48be6_f22_x86-64/test/testlib.py", line 628, in run
raise Error(res['error'])
Error: #networking-interfaces tr:contains('ens2') is not visible

----------------------------------------------------------------------
Ran 1 test in 36.315s

FAILED (errors=1)
```

Example: http://files.cockpit-project.org/hubbot/a7391a8d5d1a7f66f008b500bde2709a89a48be6_f22_x86-64/hubbot.html

Example: http://files.cockpit-project.org/hubbot/a7391a8d5d1a7f66f008b500bde2709a89a48be6_r7_x86-64/hubbot.html

**Comment by mvollmer** [comment]
Potential simplistic fix in #2904.

**Comment by stefwalter** [comment]
Seems like a phantomjs bug where it craps out on this CSS:

```
/* HACK: https://bugzilla.mozilla.org/show_bug.cgi?id=409254 */
tbody:empty {
    display: none;
}
```

**Comment by stefwalter** [comment]
Removing that code from the listing-pattern branch fixed the issue.
