### ISSUE TITLE
Test: error while resolving ip

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2905]
Somehow the ip address doesn't always get resolved. Either the system isn't booting properly or the code to get the ip address isn't robust enough.
Maybe we get more than one mac address?

```
======================================================================
ERROR: testBasic (__main__.TestMultiMachine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-multi-machine", line 65, in setUp
    MachineCase.setUp(self)
  File "/home/hubbot/hubbot/2eea475a702ab6cdfedc9a694e0fcc5533f769e0_f22_x86-64/test/testlib.py", line 431, in setUp
    self.machine.start(macaddr=macaddr)
  File "/home/hubbot/hubbot/2eea475a702ab6cdfedc9a694e0fcc5533f769e0_f22_x86-64/test/testvm.py", line 823, in start
    self._start_qemu(maintain=maintain, macaddr=macaddr)
  File "/home/hubbot/hubbot/2eea475a702ab6cdfedc9a694e0fcc5533f769e0_f22_x86-64/test/testvm.py", line 806, in _start_qemu
    self.address = self._ip_from_mac(self.macaddr)
  File "/home/hubbot/hubbot/2eea475a702ab6cdfedc9a694e0fcc5533f769e0_f22_x86-64/test/testvm.py", line 850, in _ip_from_mac
    return self._wait_for_ip(mac, timeout_sec)
  File "/home/hubbot/hubbot/2eea475a702ab6cdfedc9a694e0fcc5533f769e0_f22_x86-64/test/testvm.py", line 842, in _wait_for_ip
    raise Failure("Can't resolve IP of %s" % mac)
Failure: Can't resolve IP of 52:54:00:cb:de:bb
```

**Comment by stefwalter** [comment]
http://files.cockpit-project.org/hubbot/2eea475a702ab6cdfedc9a694e0fcc5533f769e0_f22_x86-64/hubbot.html
