### ISSUE TITLE
testBridge fails in self.wait_for_iface(iface1)

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2916]
As seen here: http://files.cockpit-project.org/hubbot/bfb11995a251d108a5ae4842599ccf24a0b5526f_r7_x86-64/hubbot.html

```
./check-networking
Wrote check-networking-testBridge-FAIL.png
Journal database copied to check-networking-testBridge-10.111.112.102-FAIL.journal
.> Subscribing to systemd signals failed File exists
.EWarning: Permanently added '10.111.112.102' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBridge (__main__.TestNetworking)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-networking", line 228, in testBridge
    self.wait_for_iface(iface1)
  File "./check-networking", line 52, in wait_for_iface
    self.browser.wait_present(sel)
  File "/home/hubbot/hubbot/bfb11995a251d108a5ae4842599ccf24a0b5526f_r7_x86-64/test/testlib.py", line 223, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/bfb11995a251d108a5ae4842599ccf24a0b5526f_r7_x86-64/test/testlib.py", line 217, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/bfb11995a251d108a5ae4842599ccf24a0b5526f_r7_x86-64/test/testlib.py", line 667, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/bfb11995a251d108a5ae4842599ccf24a0b5526f_r7_x86-64/test/testlib.py", line 630, in run
    raise Error("timeout")
Error: timeout
```

**Comment by stefwalter** [comment]
Again:

```
./check-networking
Wrote check-networking-testBridge-FAIL.png
Journal database copied to check-networking-testBridge-10.111.112.102-FAIL.journal
..EWarning: Permanently added '10.111.112.102' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBridge (__main__.TestNetworking)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-networking", line 229, in testBridge
    self.wait_for_iface(iface2)
  File "./check-networking", line 52, in wait_for_iface
    self.browser.wait_present(sel)
  File "/home/hubbot/hubbot/991dc2ce42c1350255b14ce566dca13f447be6eb_r7_x86-64/test/testlib.py", line 223, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/991dc2ce42c1350255b14ce566dca13f447be6eb_r7_x86-64/test/testlib.py", line 217, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/991dc2ce42c1350255b14ce566dca13f447be6eb_r7_x86-64/test/testlib.py", line 667, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/991dc2ce42c1350255b14ce566dca13f447be6eb_r7_x86-64/test/testlib.py", line 630, in run
    raise Error("timeout")
Error: timeout

----------------------------------------------------------------------
Ran 3 tests in 187.857s
```

http://files.cockpit-project.org/hubbot/991dc2ce42c1350255b14ce566dca13f447be6eb_r7_x86-64/hubbot.html

**Comment by mvollmer** [comment]
One common pattern is that usually the interfaces are named `ens6` and `ens7`, but when the test fails, the UI shows `ens2` and `ens7`.

#2932 add debugging output which should show if there is any confusion regarding interface names.

**Comment by stefwalter** [comment]
Here's the result of that debugging output: http://files.cockpit-project.org/hubbot/0164e7aecd87482f0efd4653bd711de1fbdeac10_r7_x86-64/hubbot.html

```

OK
./check-networking
52:54:00:9e:00:F2 -> ens2
52:54:00:12:34:56 -> ens2
52:54:00:12:34:57 -> ens7
52:54:00:12:34:56 -> eth1
52:54:00:12:34:57 -> ens7
Interface eth1 didn't show up.
 <div class="panel-heading"> <span>Interfaces</span> <div style="float:right"> <button id="networking-add-bond" class="btn btn-default network-privileged" data-original-title="" title="">Add Bond</button> <button id="networking-add-bridge" class="btn btn-default network-privileged" data-original-title="" title="">Add Bridge</button> <button id="networking-add-vlan" class="btn btn-default network-privileged" data-original-title="" title="">Add VLAN</button> </div> </div> <table class="table table-hover"> <thead> <tr> <th>Name</th> <th>IP Address</th> <th style="width:20%">Sending</th> <th style="width:20%">Receiving</th> </tr> </thead> <tbody><tr data-interface="ens2"><td>ens2</td><td><span></span></td><td colspan="2">Inactive</td></tr><tr data-interface="ens7"><td>ens7</td><td><span></span></td><td colspan="2">Inactive</td></tr><tr data-interface="eth0" data-sample-id="eth0"><td>eth0</td><td><span>10.111.125.71/20</span></td><td>7.8 Kbps</td><td>4.8 Kbps</td></tr></tbody> </table> 
/sys/class/net/ens2/address:52:54:00:12:34:56
/sys/class/net/ens7/address:52:54:00:12:34:57
/sys/class/net/eth0/address:52:54:00:29:1b:cc
/sys/class/net/lo/address:00:00:00:00:00:00

Journal database copied to check-networking-testBridge-10.111.125.71-FAIL.journal
..EWrote check-networking-testBridge-FAIL.png
Warning: Permanently added '10.111.125.71' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBridge (__main__.TestNetworking)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-networking", line 235, in testBridge
    self.wait_for_iface(iface1)
  File "./check-networking", line 54, in wait_for_iface
    self.browser.wait_present(sel)
  File "/home/hubbot/hubbot/0164e7aecd87482f0efd4653bd711de1fbdeac10_r7_x86-64/test/testlib.py", line 220, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/0164e7aecd87482f0efd4653bd711de1fbdeac10_r7_x86-64/test/testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/0164e7aecd87482f0efd4653bd711de1fbdeac10_r7_x86-64/test/testlib.py", line 609, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/0164e7aecd87482f0efd4653bd711de1fbdeac10_r7_x86-64/test/testlib.py", line 632, in _invoke
    raise Error(res['error'])
Error: timeout

----------------------------------------------------------------------
Ran 3 tests in 241.258s
```

**Comment by mvollmer** [comment]
> Here's the result of that debugging output

Thanks.  Alright, this looks like the interface with mac 52:54:00:12:34:56 starts out as eth1 and then gets renamed to ens2.  We pick up its name when it is still called eth1, but it appears in the UI when it is called ens2.

Maybe some udev settle is enough.
