### ISSUE TITLE
Fedora: stdout: '', stderr: 'wipefs: error: /dev/sdb: probing initialization failed: Device or resource busy', Child process exited with code 1

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2938]
http://files.cockpit-project.org/hubbot/fd52c8c58307ecdfcac412b6d665101cf92964c0_f22_x86-64/hubbot.html

```

OK
./check-storage-lvm2
Wrote check-storage-lvm2-testLvm-FAIL.png
Journal database copied to check-storage-lvm2-testLvm-10.111.118.201-FAIL.journal
EWarning: Permanently added '10.111.118.201' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testLvm (__main__.TestStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-storage-lvm2", line 97, in testLvm
    "DISK2": True }})
  File "/home/hubbot/hubbot/fd52c8c58307ecdfcac412b6d665101cf92964c0_f22_x86-64/test/storagelib.py", line 184, in dialog_with_retry
    self.dialog_wait_close()
  File "/home/hubbot/hubbot/fd52c8c58307ecdfcac412b6d665101cf92964c0_f22_x86-64/test/storagelib.py", line 100, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/hubbot/hubbot/fd52c8c58307ecdfcac412b6d665101cf92964c0_f22_x86-64/test/testlib.py", line 226, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/home/hubbot/hubbot/fd52c8c58307ecdfcac412b6d665101cf92964c0_f22_x86-64/test/testlib.py", line 217, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/fd52c8c58307ecdfcac412b6d665101cf92964c0_f22_x86-64/test/testlib.py", line 667, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/fd52c8c58307ecdfcac412b6d665101cf92964c0_f22_x86-64/test/testlib.py", line 630, in run
    raise Error("timeout")
Error: timeout
```

**Comment by stefwalter** [comment]
Another case of this here: http://files.cockpit-project.org/hubbot/1eea0afc81856fb7f6032e83549987c05b27ac69_f22_x86-64/test/check-storage-lvm2-testLvm-FAIL.png

http://files.cockpit-project.org/hubbot/1eea0afc81856fb7f6032e83549987c05b27ac69_f22_x86-64/hubbot.html

**Comment by stefwalter** [comment]
Another case of this: http://files.cockpit-project.org/hubbot/1fe599e44574f0bc62a57df4fe0c4b39b11ee37e_f22_x86-64/test/check-storage-lvm2-testLvm-FAIL.png

http://files.cockpit-project.org/hubbot/1fe599e44574f0bc62a57df4fe0c4b39b11ee37e_f22_x86-64/hubbot.html

**Comment by mvollmer** [comment]
This is mysterious.  /dev/sdb should be free (in the sense of open("/dev/sdb", O_EXCL)) all the time since no logical volume is ever created on it.

**Comment by stefwalter** [comment]
This has happened again after the above work made it into git master: 

http://files.cockpit-project.org/hubbot/ed4a87e7ea180f70f8efa9262ac25b9c7b2cdd72_f22_x86-64/test/check-storage-lvm2-testLvm-FAIL.png

http://files.cockpit-project.org/hubbot/ed4a87e7ea180f70f8efa9262ac25b9c7b2cdd72_f22_x86-64/hubbot.html

**Comment by mvollmer** [comment]
Another try in #2971.  Maybe lvmetad is still doing things with that disk...

If that also doesn't work, I'll either split the test, or use two sets of independent disks.

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mounting", line 123, in testMounting
    self.dialog({ "type": "empty" })
  File "storagelib.py", line 115, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 100, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 227, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://stefw.fedorapeople.org/logs/pull-3311-dfee8f80-fedora-22/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mounting", line 123, in testMounting
    self.dialog({ "type": "empty" })
  File "storagelib.py", line 118, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 103, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 231, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 726, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 749, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mounting", line 123, in testMounting
    self.dialog({ "type": "empty" })
  File "storagelib.py", line 118, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 103, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 126, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 111, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mounting", line 124, in testMounting
    self.dialog({ "type": "empty" })
  File "storagelib.py", line 126, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 111, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 124, in dialog
    self.dialog_set_val(f, values[f])
  File "storagelib.py", line 78, in dialog_set_val
    self.browser.set_val(self.dialog_field(field), val)
  File "testlib.py", line 160, in set_val
    self.call_js_func('ph_set_val', selector, val)
  File "testlib.py", line 139, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: #dialog [data-field="size"] does not have a value
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 124, in dialog
    self.dialog_set_val(f, values[f])
  File "storagelib.py", line 78, in dialog_set_val
    self.browser.set_val(self.dialog_field(field), val)
  File "testlib.py", line 160, in set_val
    self.call_js_func('ph_set_val', selector, val)
  File "testlib.py", line 139, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: #dialog [data-field="size"] does not have a value
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 126, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 111, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 126, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 111, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mounting", line 124, in testMounting
    self.dialog({ "type": "empty" })
  File "storagelib.py", line 130, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 115, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 658, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 681, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mounting", line 124, in testMounting
    self.dialog({ "type": "empty" })
  File "storagelib.py", line 130, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 115, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by mvollmer** [comment]
verify/debian-unstable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 136, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 121, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-04-08T15:03:46.172228
Times recorded: 1
Latest occurrences:

- 2016-04-08T15:03:46.172228

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mounting", line 124, in testMounting
    self.dialog({ "type": "empty" })
  File "storagelib.py", line 136, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 121, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-04-13T13:43:07.808717 | revision f7de58fddd889debe4d8df4354892cbf4f67130e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4204-f7de58fd-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-04-13T13:43:07.808717 | revision f7de58fddd889debe4d8df4354892cbf4f67130e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4204-f7de58fd-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 136, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 121, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 664, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 687, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-06-29T08:24:28.921629 | revision 062b9b14243bd89a64bf3c8d9268ae83c51f7cfa, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4649-062b9b14-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-06-29T08:24:28.921629 | revision 062b9b14243bd89a64bf3c8d9268ae83c51f7cfa, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4649-062b9b14-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 136, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 121, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 220, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 665, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 688, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-09T20:16:41.177598 | revision 58797f24d7d808d374f06eb4d646e71a430ab0c9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4705-58797f24-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-09T20:16:41.177598 | revision 58797f24d7d808d374f06eb4d646e71a430ab0c9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4705-58797f24-verify-centos-7/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 148, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 133, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 220, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 689, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 712, in _invoke
    raise Error(res['error'])
Error: timeout
Message recipient disconnected from message bus without replying
```
First occurrence: 2016-10-24T10:50:55.970552 | revision 3a7a912f2c6b6cec641021df5d5f268a1a0cc689, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5222-3a7a912f-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-24T10:50:55.970552 | revision 3a7a912f2c6b6cec641021df5d5f268a1a0cc689, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5222-3a7a912f-verify-fedora-25/log.html)

**Comment by mvollmer** [comment]
verify/ubuntu-1604
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 54, in testLuks
    "mount_point": mount_point_secret })
  File "storagelib.py", line 151, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 136, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 220, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 692, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 715, in _invoke
    raise Error(res['error'])
Error: TypeError: undefined is not an object (evaluating 'client.blocks[partition].Format')
```
First occurrence: 2016-10-31T12:52:12.051909
Times recorded: 1
Latest occurrences:

- 2016-10-31T12:52:12.051909
