### ISSUE TITLE
Error: #content-user-name is not visible

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#2954]
http://files.cockpit-project.org/hubbot/571b11dcd86fd449a8aaa3f6133acdcbe6d15812_r7_x86-64/hubbot.html

```
ERROR: testBasic (__main__.TestSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-session", line 54, in testBasic
    b.logout()
  File "/home/hubbot/hubbot/571b11dcd86fd449a8aaa3f6133acdcbe6d15812_r7_x86-64/test/testlib.py", line 372, in logout
    self.click("#content-user-name")
  File "/home/hubbot/hubbot/571b11dcd86fd449a8aaa3f6133acdcbe6d15812_r7_x86-64/test/testlib.py", line 159, in click
    self.call_js_func('ph_click', selector, force)
  File "/home/hubbot/hubbot/571b11dcd86fd449a8aaa3f6133acdcbe6d15812_r7_x86-64/test/testlib.py", line 151, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/571b11dcd86fd449a8aaa3f6133acdcbe6d15812_r7_x86-64/test/testlib.py", line 610, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/571b11dcd86fd449a8aaa3f6133acdcbe6d15812_r7_x86-64/test/testlib.py", line 633, in _invoke
    raise Error(res['error'])
Error: #content-user-name is not visible
```

**Comment by stefwalter** [comment]
Fixed by #2957
