### ISSUE TITLE
domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid ...

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2969]
As seen here: http://files.cockpit-project.org/hubbot/744bb9246fc48e5bfc6231f9e72e5c7ed627ce7c_r7_x86-64/hubbot.html

```
Password for admin@COCKPIT.LAN: 
Journal database copied to check-realms-testIpa-10.111.112.177-FAIL.journal
.libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
libvirt: Domain Config error : operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
EWrote check-realms-testIpa-FAIL.png
Warning: Permanently added '10.111.112.177' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testIpa (__main__.TestRealms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-realms", line 40, in testIpa
    ipa.start()
  File "/home/hubbot/hubbot/744bb9246fc48e5bfc6231f9e72e5c7ed627ce7c_r7_x86-64/test/testvm.py", line 856, in start
    self._start_qemu(maintain=maintain, macaddr=macaddr)
  File "/home/hubbot/hubbot/744bb9246fc48e5bfc6231f9e72e5c7ed627ce7c_r7_x86-64/test/testvm.py", line 814, in _start_qemu
    dom = self.virt_connection.createXML(test_domain_desc, libvirt.VIR_DOMAIN_START_AUTODESTROY)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3427, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirtError: operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid e4034777-1b0b-4e68-acbd-eebd6cdde165
```

**Comment by stefwalter** [comment]
If I watch the tests running via virt-manager, with TEST_JOBS=4 ... I see that there are often 5 VMs running at a time, one of which is shutting down. Is it possible we're not waiting long enough for VMs to shutdown before returning from a test?

**Comment by dperpeet** [comment]
> Is it possible we're not waiting long enough for VMs to shutdown before returning from a test?

Yes, I think we need to wait longer. The changes in https://github.com/cockpit-project/cockpit/commit/a66eb7f6f530cd14a2b466770aa19fd60102e685 actually mean that checking for duplicate virtual machines is stricter now! Before we'd expire the lock files as soon as the test object was destroyed, now we need to wait for libvirt to free the previous domain.

Possible solutions I see:
* wait longer: most practical, easiest solution to implement
* use static ip machines only in one test, although I don't believe this is feasible in the case of IPA (who would want a second image just for a different ip address?)
* wait longer, but also spread out the tests that use the same resources: not sure this is a good thing, since we shouldn't really mess with test scheduling

**Comment by stefwalter** [comment]
Another failure: 

http://files.cockpit-project.org/hubbot/744bb9246fc48e5bfc6231f9e72e5c7ed627ce7c_f22_x86-64/hubbot.html

```
======================================================================
ERROR: testIpa (__main__.TestRealms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-realms", line 40, in testIpa
    ipa.start()
  File "/home/hubbot/hubbot/744bb9246fc48e5bfc6231f9e72e5c7ed627ce7c_f22_x86-64/test/testvm.py", line 856, in start
    self._start_qemu(maintain=maintain, macaddr=macaddr)
  File "/home/hubbot/hubbot/744bb9246fc48e5bfc6231f9e72e5c7ed627ce7c_f22_x86-64/test/testvm.py", line 814, in _start_qemu
    dom = self.virt_connection.createXML(test_domain_desc, libvirt.VIR_DOMAIN_START_AUTODESTROY)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3427, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirtError: operation failed: domain 'ipa-fedora-22-x86_64-3_f0.cockpit.lan' already exists with uuid 29f60b47-302c-4126-91af-b4556275f44d

----------------------------------------------------------------------
```

**Comment by stefwalter** [comment]
Another case of this: 

http://files.cockpit-project.org/hubbot/744bb9246fc48e5bfc6231f9e72e5c7ed627ce7c_r7_x86-64/hubbot.html

**Comment by stefwalter** [comment]
This also happens with openshift VM:

```
./check-openshift
Warning: Permanently added '10.111.112.101' (ECDSA) to the list of known hosts.
.libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
libvirt: Domain Config error : operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
E
======================================================================
ERROR: testDelete (__main__.TestOpenshift)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-openshift", line 30, in setUp
    self.openshift.start()
  File "/home/hubbot/hubbot/0386011ac508f8be10937ed1bb93c6004b1632d1_f22_x86-64/test/testvm.py", line 856, in start
    self._start_qemu(maintain=maintain, macaddr=macaddr)
  File "/home/hubbot/hubbot/0386011ac508f8be10937ed1bb93c6004b1632d1_f22_x86-64/test/testvm.py", line 814, in _start_qemu
    dom = self.virt_connection.createXML(test_domain_desc, libvirt.VIR_DOMAIN_START_AUTODESTROY)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3427, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirtError: operation failed: domain 'openshift-fedora-22-x86_64-1_f1.cockpit.lan' already exists with uuid 5bd88876-cf01-40e5-9904-0822489cc4a8
```

**Comment by mvollmer** [comment]
I have seen this again when manually testing Fedora 23.

This fails always with the error in the subject:
```
check-realms
```
while this always succeeds:
```
./check-realms TestRealms.testIpa && ./check-realms TestKerberos.testNegotiate
```

If one watches the virt-manager window while `check-realms` runs, one can see that the ipa VM immediately disappears when a test ends.

Maybe some internal state of testvm.py gets confused?  (Maybe because we fork?)

**Comment by mvollmer** [comment]
> Maybe some internal state of testvm.py gets confused? (Maybe because we fork?)

Yes, hacking out the forking from TapRunner seems to help... hm.

**Comment by mvollmer** [comment]
Heh, sorry, `check-realms` by itself will run the two tests in parallel.  Only `check-verify` is careful not to run tests from the same file concurrently, right?

**Comment by stefwalter** [comment]
> Heh, sorry, check-realms by itself will run the two tests in parallel. Only check-verify is careful not to run tests from the same file concurrently, right?

Yes, but only if you tell it to. It'll only run in mulitple jobs (and fork) if you pass in --jobs or TEST_JOBS
