### ISSUE TITLE
assertion self->priv->closed failed at cockpit_pipe_transport_send

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2978]
https://github.com/cockpit-project/cockpit/pull/2973
http://files.cockpit-project.org/hubbot/48efbf7c5c5f458619c0f5f94de4cb43254ce2f9_f22_x86-64/hubbot.html

```
# ----------------------------------------------------------------------
# testBasic (check_shutdown_restart.TestShutdownRestart)
#
> transport closed: disconnected
> transport not ready (0), dropped message:  
{"command":"open","channel":"1:1!6","payload":"metrics1","interval":1000,"source":"direct","metrics":[{"name":"kernel.all.cpu.nice","units":"millisec","derive":"rate"},{"name":"kernel.all.cpu.user","units":"millisec","derive":"rate"},{"name":"kernel.all.cpu.sys","units":"millisec","derive":"rate"}],"host":"localhost","group":"cockpit1:localhost/dashboard"}
> transport not ready (0), dropped message:  
{"command":"open","channel":"1:1!7","payload":"metrics1","interval":1000,"source":"direct","metrics":[{"name":"mem.util.used","units":"bytes"}],"host":"localhost","group":"cockpit1:localhost/dashboard"}
> transport not ready (0), dropped message:  
{"command":"open","channel":"1:1!8","payload":"metrics1","interval":1000,"source":"direct","metrics":[{"name":"network.interface.total.bytes","units":"bytes","derive":"rate"}],"omit-instances":["lo"],"host":"localhost","group":"cockpit1:localhost/dashboard"}
> transport not ready (0), dropped message:  
{"command":"open","channel":"1:1!9","payload":"metrics1","interval":1000,"source":"direct","metrics":[{"name":"disk.dev.total_bytes","units":"bytes","derive":"rate"}],"host":"localhost","group":"cockpit1:localhost/dashboard"}
> health check failed
> transport closed, dropped message:  
{"command":"open","channel":"1","payload":"null","host":"localhost"}
> transport closed, dropped message:  
{"command":"logout","disconnect":true}
> Error during WebSocket handshake: location mismatch: ws://10.111.112.103:9090/cockpit/socket != ws://10.111.112.103:9090/
Unexpected journal message 'assertion self->priv-closed failed at cockpit_pipe_transport_send 287'
Unexpected journal message 'assertion self->priv-closed failed at cockpit_pipe_transport_send 288'
Warning: Permanently added '10.111.112.103' (ECDSA) to the list of known hosts.
Journal database copied to TestShutdownRestart-testBasic-10.111.112.103-FAIL.journal
not ok 57 testBasic (check_shutdown_restart.TestShutdownRestart)
Traceback (most recent call last):
  File "./check-shutdown-restart", line 54, in testBasic
    self.check_journal_messages()
  File "/home/hubbot/hubbot/48efbf7c5c5f458619c0f5f94de4cb43254ce2f9_f22_x86-64/test/testlib.py", line 570, in check_journal_messages
    raise Error("There were unexpected journal messages")
Error: There were unexpected journal messages
Wrote TestShutdownRestart-testBasic-FAIL.png
Warning: Permanently added '10.111.112.103' (ECDSA) to the list of known hosts.
Journal database copied to TestShutdownRestart-testBasic-10.111.112.103-FAIL.journal
```

**Comment by mvollmer** [comment]
Has happened here: http://files.cockpit-project.org/hubbot/661aba517ca41d44a9199d9bd18fa33cfc5f0ec1_f22_x86-64/hubbot.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by dperpeet** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "./check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-example", line 52, in testTwo
    self.assertFalse(True)
AssertionError: True is not false
```

**Comment by mvollmer** [comment]
It starts happening again with the `test-kerberos` unit test:

```
cockpit-session: can't exec cockpit-bridge: No such file or directory
(test-kerberos:9335): cockpit-protocol-CRITICAL **: assertion self->priv->closed check failed at cockpit_pipe_transport_send 296
./test-kerberos terminated with SIGTRAP
FAIL: test-kerberos 1 /kerberos/authenticate
```

https://fedorapeople.org/groups/cockpit/logs/pull-3761-78cf7d5d-verify-fedora-atomic/build-results/build.log

**Comment by stefwalter** [comment]
> It starts happening again with the test-kerberos unit test:

I think I figured out the cause, the cockpit-session process dies before we can start the session.
