### ISSUE TITLE
check-storage-mdraid fails at self.dialog({ "type": "gpt" })

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3040]
Starting to see this failure ... on fedora-23

https://stefw.fedorapeople.org/logs/test-89e21ab8-fedora-23-x86_64/log

```
Wrote TestStorage-testRaid-FAIL.png
Warning: Permanently added '10.111.116.137' (ECDSA) to the list of known hosts.
Journal database copied to TestStorage-testRaid-10.111.116.137-FAIL.journal
Journal extracted to TestStorage-testRaid-10.111.116.137-FAIL.log
not ok 43 testRaid (check_storage_mdraid.TestStorage)
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/data/src/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/data/src/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/data/src/cockpit/test/testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/data/src/cockpit/test/testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/data/src/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/data/src/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
Error: /dev/md127: unrecognised disk label
Model: Linux Software RAID Array (md)
Disk /dev/md127: 103MB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 

NAME            MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda               8:0    0   50M  0 disk  
└─md127           9:127  0   98M  0 raid5 
sdb               8:16   0   50M  0 disk  
└─md127           9:127  0   98M  0 raid5 
sdc               8:32   0   50M  0 disk  
└─md127           9:127  0   98M  0 raid5 
sdd               8:48   0   50M  0 disk  
sr0              11:0    1  368K  0 rom   
vda             252:0    0    8G  0 disk  
├─vda1          252:1    0  500M  0 part  /boot
└─vda2          252:2    0  7,5G  0 part  
  ├─fedora-root 253:0    0  6,7G  0 lvm   /
  └─fedora-swap 253:1    0  820M  0 lvm   [SWAP]
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-2921-a3645e40-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-2921-9c527504-fedora-23-x86_64/log

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/home/hubbot/hubbot/rhel-7-x86_64-1445975449/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/home/hubbot/hubbot/rhel-7-x86_64-1445975449/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/home/hubbot/hubbot/rhel-7-x86_64-1445975449/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1445975449/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1445975449/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1445975449/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-2921-9c527504-rhel-7-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-3054-f2c454d8-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-3058-b4adee17-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-3059-d3acdff7-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/master-3d9220d8-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-3033-0f37e5ae-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 662, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 685, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/master-9a86d3fa-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-3071-6c3b2a51-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/pull-3072-a2bb24df-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://cockpit.fedorapeople.org/logs/master-6ad7326a-fedora-23-x86_64/log

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/data/src/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/data/src/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/data/src/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/data/src/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/data/src/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/data/src/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/master-b706dd6c-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3079-d9b45a4d-fedora-23-x86_64/

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446062212/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446062212/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446062212/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446062212/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446062212/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446062212/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3079-d9b45a4d-rhel-7-x86_64/

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446064547/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446064547/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446064547/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446064547/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446064547/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446064547/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3068-10c7a71e-rhel-7-x86_64/

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446068254/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446068254/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446068254/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446068254/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446068254/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446068254/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3007-b15e9040-rhel-7-x86_64/

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446070938/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446070938/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446070938/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446070938/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446070938/test/testlib.py", line 667, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446070938/test/testlib.py", line 690, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3018-0481f8e2-rhel-7-x86_64/

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446079122/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446079122/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446079122/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446079122/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446079122/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446079122/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-2776-eb4c9d45-rhel-7-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3080-7b594610-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3082-678bafb3-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/build/cockpit/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/build/cockpit/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 663, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 686, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3084-a92fdcc6-fedora-23-x86_64/

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 128, in testRaid
    self.dialog({ "type": "gpt" })
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446140594/test/storagelib.py", line 109, in dialog
    self.dialog_wait_open()
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446140594/test/storagelib.py", line 56, in dialog_wait_open
    self.browser.wait_present('#dialog')
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446140594/test/testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446140594/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446140594/test/testlib.py", line 669, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/hubbot/hubbot/rhel-7-x86_64-1446140594/test/testlib.py", line 692, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3081-dcf0cb69-rhel-7-x86_64/
