### ISSUE TITLE
systemd-timedated not in use 'null' is not an object (s.server_time.timedate)

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3053]
Saw this error, different than the others:

http://cockpit.fedorapeople.org/logs/pull-3037-2d666d91-fedora-23-x86_64/log

```
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: # ----------------------------------------------------------------------
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: # testTime (check_system_info.TestSystemInfo)
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: #
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: > systemd-timedated not in use, ntp server configuration not supported
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: Page error: TypeError: 'null' is not an object (evaluating 's.server_time.timedate')
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/system/bundle.js 11 i
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 73
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 73
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 73
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 67
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 74
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 74
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 67 i
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 67 d
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 67 p
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 67 B
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 67
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: http://10.111.115.25:9090/cockpit/$e2f698d276b39c144390ceb3d43f84b5081f3821/base1/bundle.js 67 t
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: Wrote TestSystemInfo-testTime-FAIL.png
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: Warning: Permanently added '10.111.115.25' (ECDSA) to the list of known hosts.
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: Journal database copied to TestSystemInfo-testTime-10.111.115.25-FAIL.journal
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: Journal extracted to TestSystemInfo-testTime-10.111.115.25-FAIL.log
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: not ok 19 testTime (check_system_info.TestSystemInfo)
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: Traceback (most recent call last):
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: File "check-system-info", line 115, in testTime
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: b.wait_text("#system_information_systime_button", "2020-01-24 08:03")
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: File "/build/cockpit/test/testlib.py", line 246, in wait_text
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: return self.wait_js_func('ph_text_is', selector, text)
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: File "/build/cockpit/test/testlib.py", line 662, in <lambda>
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: return lambda *args: self._invoke(name, *args)
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: File "/build/cockpit/test/testlib.py", line 685, in _invoke
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: raise Error(res['error'])
Okt 27 18:16:09 falcon.thewalter.lan sh[7350]: Error: TypeError: 'null' is not an object (evaluating 's.server_time.timedate')
```

**Comment by mvollmer** [comment]
Doesn't seem to happen anymore, right?
