### ISSUE TITLE
Fedora: check-storage-luks assert m.execute("grep 'UUID=' /etc/crypttab") != ""

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3055]
```
# ----------------------------------------------------------------------
# testLuks (check_storage_luks.TestStorage)
#
Wrote TestStorage-testLuks-FAIL.png
Warning: Permanently added '10.111.127.234' (ECDSA) to the list of known hosts.
Journal database copied to TestStorage-testLuks-10.111.127.234-FAIL.journal
Journal extracted to TestStorage-testLuks-10.111.127.234-FAIL.log
not ok 51 testLuks (check_storage_luks.TestStorage)
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 271, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://cockpit.fedorapeople.org/logs/pull-3056-3e62749e-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://cockpit.fedorapeople.org/logs/pull-3065-a4c183a4-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://cockpit.fedorapeople.org/logs/pull-3069-deb0ebc4-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://cockpit.fedorapeople.org/logs/pull-3077-ad2523f2-fedora-23-x86_64/log

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://fedorapeople.org/groups/cockpit/logs/pull-3078-afe5460e-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://fedorapeople.org/groups/cockpit/logs/master-b706dd6c-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://fedorapeople.org/groups/cockpit/logs/pull-3079-d9b45a4d-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://fedorapeople.org/groups/cockpit/logs/pull-3085-e3104503-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://fedorapeople.org/groups/cockpit/logs/pull-3088-f7b72d49-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 60, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "/build/cockpit/test/testvm.py", line 256, in execute
    raise subprocess.CalledProcessError(proc.returncode, command)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
http://fedorapeople.org/groups/cockpit/logs/pull-3089-c46c8111-fedora-23-x86_64/

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-luks", line 61, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "testvm.py", line 299, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 61, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "testvm.py", line 394, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
First occurrence: 2016-06-02T13:08:56.255095 | revision 65367ca2cd28f0dba13729564ec7a2d8816963f1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4529-65367ca2-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-06-02T13:08:56.255095 | revision 65367ca2cd28f0dba13729564ec7a2d8816963f1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4529-65367ca2-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/debian-unstable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 61, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "testvm.py", line 394, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
First occurrence: 2016-06-29T18:51:26.705074 | revision 60b63f2587dccf38622c0b79b7ca1d277fa465a7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4651-60b63f25-verify-debian-unstable/log.html)
Times recorded: 1
Latest occurrences:

- 2016-06-29T18:51:26.705074 | revision 60b63f2587dccf38622c0b79b7ca1d277fa465a7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4651-60b63f25-verify-debian-unstable/log.html)

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 61, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "testvm.py", line 396, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
First occurrence: 2016-07-14T18:03:09.154080 | revision 32e96aeef87bce3a916ed746e9dd27ca3745cdc7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4734-32e96aee-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-14T18:03:09.154080 | revision 32e96aeef87bce3a916ed746e9dd27ca3745cdc7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4734-32e96aee-verify-centos-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 61, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "testvm.py", line 403, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
First occurrence: 2016-08-11T09:18:36.998947 | revision fdb0bd8572c4d739e8b076dddb076aebf9babe36, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4860-fdb0bd85-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-11T09:18:36.998947 | revision fdb0bd8572c4d739e8b076dddb076aebf9babe36, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4860-fdb0bd85-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 61, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "testvm.py", line 412, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
First occurrence: 2016-10-11T16:35:41.976075 | revision dc7d383493a305d9530701445491d76a7dface35, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5149-dc7d3834-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-11T16:35:41.976075 | revision dc7d383493a305d9530701445491d76a7dface35, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5149-dc7d3834-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-luks", line 61, in testLuks
    assert m.execute("grep 'UUID=' /etc/crypttab") != ""
  File "testvm.py", line 412, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'grep 'UUID=' /etc/crypttab' returned non-zero exit status 1
```
First occurrence: 2016-10-25T07:30:38.714675 | revision 356d3a18f7b37e9def70cafda6f02feacc9a1256, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5222-356d3a18-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-25T07:30:38.714675 | revision 356d3a18f7b37e9def70cafda6f02feacc9a1256, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5222-356d3a18-verify-fedora-25/log.html)
