### ISSUE TITLE
Error wiping device: Command-line `wipefs -a "/dev/sda" exited with non-zero exit status 1: wipefs: error:/dev/sda:probing initialization failed: Device or Resource Busy

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3092]
![x](https://fedorapeople.org/groups/cockpit/logs/pull-3090-a9cca67b-fedora-23-x86_64/TestStorage-testMounting-FAIL.png)

https://fedorapeople.org/groups/cockpit/logs/pull-3090-a9cca67b-fedora-23-x86_64/log

```
# ----------------------------------------------------------------------
# testMounting (check_storage_mounting.TestStorage)
#
Wrote TestStorage-testMounting-FAIL.png
Warning: Permanently added '10.111.126.12' (ECDSA) to the list of known hosts.
Journal database copied to TestStorage-testMounting-10.111.126.12-FAIL.journal
Journal extracted to TestStorage-testMounting-10.111.126.12-FAIL.log
not ok 63 testMounting (check_storage_mounting.TestStorage)
Traceback (most recent call last):
  File "check-storage-mounting", line 123, in testMounting
    self.dialog({ "type": "empty" })
  File "/build/cockpit/test/storagelib.py", line 115, in dialog
    self.dialog_wait_close()
  File "/build/cockpit/test/storagelib.py", line 100, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 669, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 692, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
Duplicate of #2938
