### ISSUE TITLE
Joining realm failed: RPC failed at server.  cannot connect to 'ldapi://%2fvar%2frun%2fslapd-COCKPIT-LAN.socket':

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3097]
Test failure while joining a domain here:

https://fedorapeople.org/groups/cockpit/logs/master-77073b9b-fedora-23-x86_64/log

```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
> * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
> * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
> Discovery was successful!
> Client hostname: x0.cockpit.lan
> Realm: COCKPIT.LAN
> DNS Domain: cockpit.lan
> IPA Server: f0.cockpit.lan
> BaseDN: dc=cockpit,dc=lan
> Synchronizing time with KDC...
> Attempting to sync time using ntpd.  Will timeout after 15 seconds
> Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  Tue Sep 29 12:58:45 2015 UTC
    Valid Until: Sat Sep 29 12:58:45 2035 UTC
> Joining realm failed: RPC failed at server.  cannot connect to 'ldapi://%2fvar%2frun%2fslapd-COCKPIT-LAN.socket':
> Installation failed. Rolling back changes.
> IPA client is not configured on this system.
> 
> ! Running ipa-client-install failed
> Failed to join domain: cockpit.lan: Running ipa-client-install failed
Wrote TestRealms-testIpa-FAIL.png
Warning: Permanently added '10.111.112.233' (ECDSA) to the list of known hosts.
Journal database copied to TestRealms-testIpa-10.111.112.233-FAIL.journal
Journal extracted to TestRealms-testIpa-10.111.112.233-FAIL.log
Warning: Permanently added '10.111.112.100' (ECDSA) to the list of known hosts.
Journal database copied to TestRealms-testIpa-10.111.112.100-FAIL.journal
Journal extracted to TestRealms-testIpa-10.111.112.100-FAIL.log
not ok 47 testIpa (check_realms.TestRealms)
Traceback (most recent call last):
  File "check-realms", line 71, in testIpa
    b.wait_popdown("realms-op")
  File "/build/cockpit/test/testlib.py", line 265, in wait_popdown
    self.wait_not_visible('#' + id)
  File "/build/cockpit/test/testlib.py", line 237, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "/build/cockpit/test/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 669, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 692, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
No longer seems to happen. No naughty file for this.
