### ISSUE TITLE
check-docker: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3099]
https://fedorapeople.org/groups/cockpit/logs/pull-3083-6b16cff5-rhel-7-x86_64/log

```
# ----------------------------------------------------------------------
# testBasic (check_docker.TestDocker)
#
Wrote TestDocker-testBasic-FAIL.png
Warning: Permanently added '10.111.123.198' (ECDSA) to the list of known hosts.
Journal database copied to TestDocker-testBasic-10.111.123.198-FAIL.journal
Journal extracted to TestDocker-testBasic-10.111.123.198-FAIL.log
not ok 34 testBasic (check_docker.TestDocker)
Traceback (most recent call last):
  File "check-docker", line 126, in testBasic
    self.assertEqual(set(info[0]["HostConfig"]["Links"]),
TypeError: 'NoneType' object is not iterable
```

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-docker", line 126, in testBasic
    self.assertEqual(set(info[0]["HostConfig"]["Links"]),
TypeError: 'NoneType' object is not iterable
```
http://fedorapeople.org/groups/cockpit/logs/pull-3112-746286e7-rhel-7-x86_64/log.html

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-docker", line 126, in testBasic
    self.assertEqual(set(info[0]["HostConfig"]["Links"]),
TypeError: 'NoneType' object is not iterable
```
http://fedorapeople.org/groups/cockpit/logs/pull-3134-71f74c16-rhel-7-x86_64/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-docker", line 126, in testBasic
    self.assertEqual(set(info[0]["HostConfig"]["Links"]),
TypeError: 'NoneType' object is not iterable
```

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-docker", line 126, in testBasic
    self.assertEqual(set(info[0]["HostConfig"]["Links"]),
TypeError: 'NoneType' object is not iterable
```
http://fedorapeople.org/groups/cockpit/logs/pull-3148-2c8112b1-rhel-7-x86_64/log.html

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-docker", line 126, in testBasic
    self.assertEqual(set(info[0]["HostConfig"]["Links"]),
TypeError: 'NoneType' object is not iterable
```
http://fedorapeople.org/groups/cockpit/logs/pull-3018-ec77ab43-rhel-7-x86_64/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-docker", line 126, in testBasic
    self.assertEqual(set(info[0]["HostConfig"]["Links"]),
TypeError: 'NoneType' object is not iterable
```
http://stefw.fedorapeople.org/logs/pull-3313-bdd3931c-rhel-7/log.html
