### ISSUE TITLE
unknown internal metric disk.dev.total_bytes'

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3101]
This is a message that sometimes happen during shutdown:

```
# testBasic (check_shutdown_restart.TestShutdownRestart)
#
> transport closed: disconnected
> health check failed
> transport closed, dropped message:  
{"command":"open","channel":"1","payload":"null","host":"localhost"}
> transport closed, dropped message:  
{"command":"logout","disconnect":true}
> Error during WebSocket handshake: location mismatch: ws://10.111.112.103:9090/cockpit/socket != ws://10.111.112.103:9090/
Unexpected journal message '(null): unknown internal metric disk.dev.total_bytes'
Warning: Permanently added '10.111.112.103' (ECDSA) to the list of known hosts.
Journal database copied to TestShutdownRestart-testBasic-10.111.112.103-FAIL.journal
Journal extracted to TestShutdownRestart-testBasic-10.111.112.103-FAIL.log
Wrote TestShutdownRestart-testBasic-FAIL.png
Warning: Permanently added '10.111.112.103' (ECDSA) to the list of known hosts.
Journal database copied to TestShutdownRestart-testBasic-10.111.112.103-FAIL.journal
Journal extracted to TestShutdownRestart-testBasic-10.111.112.103-FAIL.log
not ok 57 testBasic (check_shutdown_restart.TestShutdownRestart)
Traceback (most recent call last):
  File "check-shutdown-restart", line 54, in testBasic
    self.check_journal_messages()
  File "/build/cockpit/test/testlib.py", line 631, in check_journal_messages
    raise Error("There were unexpected journal messages")
Error: There were unexpected journal messages
```

**Comment by stefwalter** [comment]
More cases of this here: http://files.cockpit-project.org/logs/pull-3068-0c94ef09-fedora-23-x86_64/log

```
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"3"}
Unexpected journal message '(null): unknown internal metric kernel.all.cpu.nice'
Unexpected journal message '(null): unknown internal metric mem.util.used'
Unexpected journal message '(null): unknown internal metric network.interface.total.bytes'
Unexpected journal message '(null): unknown internal metric disk.dev.total_bytes'
Warning: Permanently added '10.111.112.103' (ECDSA) to the list of known hosts.
```

**Comment by stefwalter** [comment]
I think I know what this is.
