### ISSUE TITLE
check-multi-machine-key: #dashboard-hosts a img ==  server-error.png

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3159]

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine-key", line 120, in testBasic
    b.wait_attr("#dashboard-hosts a[data-address='%s'] img" % m2.address, 'src', '../shell/images/server-error.png')
  File "testlib.py", line 233, in wait_attr
    return self.wait_js_func('ph_has_attr', selector, attr, val)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 674, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 697, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://files.cockpit-project.org/logs/pull-3138-8a7666b1-fedora-23-x86_64/log.html

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine-key", line 120, in testBasic
    b.wait_attr("#dashboard-hosts a[data-address='%s'] img" % m2.address, 'src', '../shell/images/server-error.png')
  File "testlib.py", line 233, in wait_attr
    return self.wait_js_func('ph_has_attr', selector, attr, val)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 674, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 697, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine-key", line 120, in testBasic
    b.wait_attr("#dashboard-hosts a[data-address='%s'] img" % m2.address, 'src', '../shell/images/server-error.png')
  File "testlib.py", line 233, in wait_attr
    return self.wait_js_func('ph_has_attr', selector, attr, val)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 674, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 697, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://mvo.fedorapeople.org/logs/test-42907727-fedora-testing-x86_64/log.html

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine-key", line 120, in testBasic
    b.wait_attr("#dashboard-hosts a[data-address='%s'] img" % m2.address, 'src', '../shell/images/server-error.png')
  File "testlib.py", line 233, in wait_attr
    return self.wait_js_func('ph_has_attr', selector, attr, val)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 674, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 697, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://mvo.fedorapeople.org/logs/test-e405d722-fedora-testing-x86_64/log.html

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine-key", line 120, in testBasic
    b.wait_attr("#dashboard-hosts a[data-address='%s'] img" % m2.address, 'src', '../shell/images/server-error.png')
  File "testlib.py", line 233, in wait_attr
    return self.wait_js_func('ph_has_attr', selector, attr, val)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 674, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 697, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://mvo.fedorapeople.org/logs/test-9382dad5-fedora-testing-x86_64/log.html

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine-key", line 120, in testBasic
    b.wait_attr("#dashboard-hosts a[data-address='%s'] img" % m2.address, 'src', '../shell/images/server-error.png')
  File "testlib.py", line 232, in wait_attr
    return self.wait_js_func('ph_has_attr', selector, attr, val)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 673, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 696, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://files.cockpit-project.org/logs/pull-3186-83323a22-fedora-23-x86_64/log.html
