### ISSUE TITLE
Fedora: RAID does not sync up in test-storage-mdraid

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3265]
There's a failure in test-storage-mdraid where the RAID does not sync up:

```
# ----------------------------------------------------------------------
# testRaid (check_storage_mdraid.TestStorage)
#
Wrote TestStorage-testRaid-FAIL.png
Warning: Permanently added '10.111.116.125' (ECDSA) to the list of known hosts.

Journal database copied to TestStorage-testRaid-10.111.116.125-FAIL.journal
Journal extracted to TestStorage-testRaid-10.111.116.125-FAIL.log
not ok 56 testRaid (check_storage_mdraid.TestStorage)
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "/build/cockpit/test/testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/testlib.py", line 678, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/testlib.py", line 701, in _invoke
    raise Error(res['error'])
Error: timeout
Error: /dev/md127: unrecognised disk label
Model: Linux Software RAID Array (md)
Disk /dev/md127: 103MB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 

NAME    MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda       8:0    0   50M  0 disk  
└─md127   9:127  0   98M  0 raid5 
sdb       8:16   0   50M  0 disk  
└─md127   9:127  0   98M  0 raid5 
sdc       8:32   0   50M  0 disk  
└─md127   9:127  0   98M  0 raid5 
sdd       8:48   0   50M  0 disk  
sr0      11:0    1  366K  0 rom   
vda     252:0    0    8G  0 disk  
├─vda1  252:1    0  500M  0 part  /boot
├─vda2  252:2    0  615M  0 part  [SWAP]
└─vda3  252:3    0  6.9G  0 part  /
```

**Comment by stefwalter** [comment]
http://files.cockpit-project.org/logs/pull-3262-aaf524fb-fedora-23/log.html

**Comment by stefwalter** [comment]
![teststorage-testraid-fail](https://cloud.githubusercontent.com/assets/795070/11529856/1702d08c-98f0-11e5-8caa-d77b196ff1b7.png)

**Comment by mvollmer** [comment]
From a distance, this as if storaged got out of sync with reality.  Maybe https://bugzilla.redhat.com/show_bug.cgi?id=1282814 is relevant.

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 678, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 701, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://files.cockpit-project.org/logs/pull-3272-f55a9f68-fedora-23/log.html

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3119-e07c74c1-fedora-22/log.html

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 678, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 701, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3202-6841e29d-fedora-22/log.html

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3202-4e899b66-fedora-22/log.html

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3324-f78c1ea0-fedora-22/log.html

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 716, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 739, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 104, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 44, in wait_states
    })""", states)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 649, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 672, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 667, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 690, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 668, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 691, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by mvollmer** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 668, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 691, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 658, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 681, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 660, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 683, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 208, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 658, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 681, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-03-24T17:23:15.204294 | revision 04e339863fe7cc1de24164317ac6ef4dee4f3fb3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4084-04e33986-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-03-24T17:23:15.204294 | revision 04e339863fe7cc1de24164317ac6ef4dee4f3fb3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4084-04e33986-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/debian-unstable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-04-12T12:37:08.688358 | revision 39ea21c5a7951d8344a85b4aa9181a79bacd8f73, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4190-39ea21c5-verify-debian-unstable/log.html)
Times recorded: 1
Latest occurrences:

- 2016-04-12T12:37:08.688358 | revision 39ea21c5a7951d8344a85b4aa9181a79bacd8f73, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4190-39ea21c5-verify-debian-unstable/log.html)

**Comment by cockpituous** [comment]
verify/fedora-23
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 660, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 683, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-06-01T22:25:32.289299 | revision 141236f207ce00c55f0334067286f8eef1ec575c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4521-141236f2-verify-fedora-23/log.html)
Times recorded: 1
Latest occurrences:

- 2016-06-01T22:25:32.289299 | revision 141236f207ce00c55f0334067286f8eef1ec575c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4521-141236f2-verify-fedora-23/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 684, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 707, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-08-12T16:17:38.431051 | revision 5c0c38073de728395e9e8c654ae5f65fd817b305, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4854-5c0c3807-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-12T16:17:38.431051 | revision 5c0c38073de728395e9e8c654ae5f65fd817b305, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4854-5c0c3807-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 684, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 707, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-08-12T16:27:36.756877 | revision 5c0c38073de728395e9e8c654ae5f65fd817b305, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4854-5c0c3807-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-12T16:27:36.756877 | revision 5c0c38073de728395e9e8c654ae5f65fd817b305, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4854-5c0c3807-verify-centos-7/log.html)

**Comment by mvollmer** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-10-06T16:59:13.813691
Times recorded: 1
Latest occurrences:

- 2016-10-06T16:59:13.813691

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mdraid", line 105, in testRaid
    "QEMU QEMU HARDDISK (DISK3)": "In Sync" })
  File "check-storage-mdraid", line 45, in wait_states
    })""", states)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 688, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 711, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-10-11T16:37:32.691522 | revision dc7d383493a305d9530701445491d76a7dface35, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5149-dc7d3834-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-11T16:37:32.691522 | revision dc7d383493a305d9530701445491d76a7dface35, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5149-dc7d3834-verify-fedora-testing/log.html)

**Comment by mvollmer** [comment]
Looks like this has fixed itself.
