### ISSUE TITLE
Fedora Atomic does not persist journal from first boot

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3306]
Fedora Atomic 22 does not seem to persist the journal. This causes test failures in test-journal and makes the Logs view far less useful than it should be.

**Comment by stefwalter** [comment]
CC @cgwalters

**Comment by stefwalter** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1289902

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 203, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 108, in wait_log_lines
    })""", expected)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://stefw.fedorapeople.org/logs/pull-3308-c90b8172-fedora-atomic/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 203, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 108, in wait_log_lines
    })""", expected)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://stefw.fedorapeople.org/logs/pull-3308-3e8ba97c-fedora-atomic/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 203, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 108, in wait_log_lines
    })""", expected)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://stefw.fedorapeople.org/logs/pull-3308-18221f7e-fedora-atomic/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 203, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 108, in wait_log_lines
    })""", expected)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://stefw.fedorapeople.org/logs/pull-3313-bdd3931c-fedora-atomic/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 203, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 108, in wait_log_lines
    })""", expected)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://stefw.fedorapeople.org/logs/pull-3279-86d71690-fedora-atomic/log.html

**Comment by stefwalter** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1265295

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 203, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 108, in wait_log_lines
    })""", expected)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3330-0c5c2e4c-fedora-atomic/log.html

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 203, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 108, in wait_log_lines
    })""", expected)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 687, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 710, in _invoke
    raise Error(res['error'])
Error: timeout
```
http://fedorapeople.org/groups/cockpit/logs/pull-3340-498816e0-fedora-atomic/log.html

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 211, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 715, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 738, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 713, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 736, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 713, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 736, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 716, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 739, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 716, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 739, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 716, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 739, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 716, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 739, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 716, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 739, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 714, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 737, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 723, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 746, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 222, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 726, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 749, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 208, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 644, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 667, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 216, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 105, in wait_log_lines
    })""", expected)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-journal", line 215, in testBasic
    [ "check-journal", "BEFORE BOOT", "" ]
  File "check-journal", line 104, in wait_log_lines
    })""", expected)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```
