### ISSUE TITLE
Debian build failure: Attempt to unlock esprima@*, which hasn't been locked

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3387]
Debian build failed like this: https://fedorapeople.org/groups/cockpit/logs/pull-3359-4935dd19-debian-unstable/

```
I: using fakeroot in build.
I: Current time: Mon Dec 21 11:54:18 EST 2015
I: pbuilder-time-stamp: 1450716858
I: Building the build Environment
I: extracting base tarball [/var/cache/pbuilder/base.tgz]
I: copying local configuration
I: mounting /proc filesystem
I: mounting /run/shm filesystem
I: mounting /dev/pts filesystem
I: policy-rc.d already exists
I: Obtaining the cached apt archive contents
I: Installing the build-deps
Reading package lists...
Building dependency tree...
Reading state information...
fakeroot is already the newest version (1.20.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
I: Copying back the cached apt archive contents
I: Copying source file
I: copying [cockpit_0.dsc]
I: copying [./cockpit_0.tar.gz]
I: Extracting source
dpkg-source: warning: extracting unsigned source package (cockpit_0.dsc)
dpkg-source: info: extracting cockpit in cockpit-0
dpkg-source: info: unpacking cockpit_0.tar.gz
I: Building the package
I: Running cd /build/*/ && env PATH="/usr/sbin:/usr/bin:/sbin:/bin" HOME="/nonexistent" dpkg-buildpackage -us -uc -rfakeroot
dpkg-buildpackage: source package cockpit
dpkg-buildpackage: source version 0
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by Cockpit <cockpit@cockpit-project.org>
 dpkg-source --before-build cockpit-0
dpkg-buildpackage: host architecture amd64
 fakeroot debian/rules clean
dh clean --with autoreconf
   dh_testdir
   dh_auto_clean
   dh_autoreconf_clean
   dh_clean
 dpkg-source -b cockpit-0
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building cockpit in cockpit_0.tar.xz
dpkg-source: info: building cockpit in cockpit_0.dsc
 debian/rules build
dh build --with autoreconf
   dh_testdir
   debian/rules override_dh_autoreconf
make[1]: Entering directory '/build/cockpit-0'
NOCONFIGURE=t dh_autoreconf ./autogen.sh
+ dirname ./autogen.sh
+ srcdir=.
+ test -z .
+ PKG_NAME=Cockpit
+ test -f ./src/ws/cockpit.service.in
+ pwd
+ olddir=/build/cockpit-0
+ cd .
+ npm install
npm ERR! Error: Attempt to unlock po2json@*, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:34:29
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /build/cockpit-0
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! Error: Attempt to unlock stdio@*, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/lib/nodejs/lockfile.js:161:38
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /build/cockpit-0
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! Error: Attempt to unlock uglify-js@*, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/lib/nodejs/lockfile.js:161:38
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /build/cockpit-0
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! Error: Attempt to unlock uglifycss@*, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/lib/nodejs/lockfile.js:161:38
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /build/cockpit-0
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! Error: Attempt to unlock html-minifier@0.7.2, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/lib/nodejs/lockfile.js:161:38
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /build/cockpit-0
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! Error: Attempt to unlock esprima@*, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/lib/nodejs/lockfile.js:161:38
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /build/cockpit-0
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! Error: Attempt to unlock bower@*, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/lib/nodejs/lockfile.js:161:38
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /build/cockpit-0
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /build/cockpit-0/npm-debug.log
npm ERR! not ok code 0
dh_autoreconf: ./autogen.sh returned exit code 1
debian/rules:9: recipe for target 'override_dh_autoreconf' failed
make[1]: *** [override_dh_autoreconf] Error 2
make[1]: Leaving directory '/build/cockpit-0'
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Failed autobuilding of package
I: unmounting dev/pts filesystem
I: unmounting run/shm filesystem
I: unmounting proc filesystem
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build/5617 and its subdirectories
```

**Comment by mvollmer** [comment]
I don't think this is happening anymore, right?
