### ISSUE TITLE
Kubernetes logs stay empty on Fedora 22

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3645]
The shell works, but nothing shows up in the "Logs" tab.

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 182, in testDashboard
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 182, in testDashboard
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 648, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 671, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
I think that kubernetes is broken on Fedora 22 ... and there's no decent reaction from upstream. I would suggest "expiring" this and just not having the logs show up on Fedora 22, what do you think?

**Comment by mvollmer** [comment]
> I think that kubernetes is broken on Fedora 22 ... and there's no decent reaction from upstream. I would suggest "expiring" this and just not having the logs show up on Fedora 22, what do you think?

Yes, I think we don't need to fix this in any way.  This just caused me a bit of confusion when testing the automatic image updates, and made me think for a moment that something had regressed.

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 182, in testDashboard
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 649, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 672, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 240, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 667, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 690, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 198, in testDashboard
    self.check_logs(b)
  File "kubelib.py", line 72, in check_logs
    b.wait_in_text(".listing-panel pre.logs", "HelloMessage.")
  File "testlib.py", line 240, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 667, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 690, in _invoke
    raise Error(res['error'])
Error: timeout
```
