### ISSUE TITLE
avc: denied { append } for pid=1835 comm="rhsmcertd-worke"

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3703]
This appears in the logs on rhel-atomic sometimes:
```
 type=1400 audit(1454848791.816:4): avc: denied { append } for pid=1833 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=25411401 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1305467

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 95, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 492, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 605, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1455554709.162:4): avc:  denied  { append } for  pid=1909 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=25411401 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 95, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 492, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 607, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1455726711.727:4): avc:  denied  { append } for  pid=1837 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=25411401 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 95, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 492, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 607, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1455914302.467:4): avc:  denied  { append } for  pid=1830 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=25411400 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 95, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 492, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 607, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1456403623.625:4): avc:  denied  { append } for  pid=1980 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 95, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 492, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 607, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1456797664.296:4): avc:  denied  { append } for  pid=1977 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 95, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 492, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 607, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1456831823.935:4): avc:  denied  { append } for  pid=1973 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 620, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1456938553.652:4): avc:  denied  { append } for  pid=1921 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 620, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1456958068.745:4): avc:  denied  { append } for  pid=1923 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 623, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457336487.516:4): avc:  denied  { append } for  pid=1914 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 623, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457354923.940:4): avc:  denied  { append } for  pid=1922 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 623, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457356351.146:4): avc:  denied  { append } for  pid=1921 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 623, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457425580.366:4): avc:  denied  { append } for  pid=2280 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 624, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457438118.273:4): avc:  denied  { append } for  pid=2282 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 624, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457445291.195:4): avc:  denied  { append } for  pid=1909 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 624, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457514218.406:4): avc:  denied  { append } for  pid=1913 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 624, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457535493.725:4): avc:  denied  { append } for  pid=2451 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "check-multi-machine", line 127, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 624, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1457696877.196:4): avc:  denied  { append } for  pid=1921 comm="rhsmcertd-worke" name="rhsm.log" dev="vda3" ino=26076393 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```
