### ISSUE TITLE
Internal metrics causes segfault

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#3812]
This was reported on IRC, centos 7, cockpit 0.93. 

No idea why /proc/diskstats is missing but we should probably recover a little more gracefully here.

```
feb 23 16:09:17  cockpit-ws[16163]: 1: added channel 1:2!13 to socket
feb 23 16:09:17  cockpit-bridge[17332]: error loading contents /proc/diskstats: Failed to open file '/proc/diskstats': No such file or directory
feb 23 16:09:17  cockpit-bridge[17332]: #0  0x00007f151a1daca9 in waitpid () at /lib64/libpthread.so.0
feb 23 16:09:17  cockpit-bridge[17332]: #1  0x00007f151b78e254 in cockpit_test_signal_backtrace ()
feb 23 16:09:17  cockpit-bridge[17332]: #2  0x00007f1519e40670 in <signal handler called> () at /lib64/libc.so.6
feb 23 16:09:17  cockpit-bridge[17332]: #3  0x00007f151ac9d4d7 in g_slice_alloc () at /lib64/libglib-2.0.so.0
feb 23 16:09:17  cockpit-bridge[17332]: #4  0x00007f151aa1baeb in json_array_new () at /lib64/libjson-glib-1.0.so.0
feb 23 16:09:17  cockpit-bridge[17332]: #5  0x00007f151b772176 in cockpit_internal_metrics_tick ()
feb 23 16:09:17  cockpit-bridge[17332]: #6  0x00007f151b77634e in on_timeout_tick ()
feb 23 16:09:17  cockpit-bridge[17332]: #7  0x00007f151b77293f in cockpit_internal_metrics_prepare ()
feb 23 16:09:17  cockpit-bridge[17332]: #8  0x00007f151b780767 in on_idle_prepare ()
feb 23 16:09:17  cockpit-bridge[17332]: #9  0x00007f151ac817aa in g_main_context_dispatch ()
feb 23 16:09:17  cockpit-bridge[17332]: #10 0x00007f151ac81af8 in g_main_context_iterate.isra.24 ()
feb 23 16:09:17  cockpit-bridge[17332]: #11 0x00007f151ac81bac in g_main_context_iteration ()
feb 23 16:09:17  cockpit-bridge[17332]: #12 0x00007f151b76a404 in main ()
```

**Comment by petervo** [comment]
This was on a VPS which i guess disabled access to /proc/diskstats.
