### ISSUE TITLE
test: knownIssue

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#4048]
playground to reduce clobbering

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:14:36.974195
Latest occurrences:

- 2016-03-21T12:14:36.974195

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:16:01.724261
Latest occurrences:

- 2016-03-21T12:16:01.724261

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:35:45.768765
Latest occurrences:

- 2016-03-21T12:35:45.768765

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:38:38.383541
Latest occurrences:

- 2016-03-21T12:38:38.383541

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:45:08.790085
Latest occurrences:

- 2016-03-21T12:45:08.790085

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:46:46.166953
Latest occurrences:

- 2016-03-21T12:46:46.166953

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:50:08.677895
Latest occurrences:

- 2016-03-21T12:50:08.677895

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T12:53:33.546813
Latest occurrences:

- 2016-03-21T12:53:33.546813

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T13:11:33.237224
Times recorded: 1
Latest occurrences:

- 2016-03-21T13:11:33.237224

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
different error info
```
First occurrence: 2016-03-21T13:14:11.510523
Times recorded: 1
Latest occurrences:

- 2016-03-21T13:14:11.510523

**Comment by dperpeet** [comment]
625f738e7e4b481f69591ae87bd30ad49bf52931
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T16:37:01.925001
Times recorded: 1
Latest occurrences:

- 2016-03-21T16:37:01.925001

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T16:43:33.618024 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931
Times recorded: 1
Latest occurrences:

- 2016-03-21T16:43:33.618024 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T16:45:30.162296 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931
Times recorded: 1
Latest occurrences:

- 2016-03-21T16:45:30.162296 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931

**Comment by dperpeet** [comment]
fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T16:58:20.275476 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931
Times recorded: 1
Latest occurrences:

- 2016-03-21T16:58:20.275476 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931

**Comment by dperpeet** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
traceback
	line2
	line3
```
First occurrence: 2016-03-21T17:19:31.222655 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931, [logs](http://files.cockpit-project.org/logs/pull-4049-625f738e-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-03-21T17:19:31.222655 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931, [logs](http://files.cockpit-project.org/logs/pull-4049-625f738e-verify-fedora-24/log.html)

**Comment by dperpeet** [comment]
This was only to test 890a67e4fb4c2e1fe2691b5a303ecda7f37f8185

**Comment by dperpeet** [comment]
verify/fedora-23
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 504, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 625, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1458743165.535:268): avc:  denied  { read } for  pid=1298 comm="ssh-transport-c" name="unix" dev="proc" ino=4026532021 scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=file permissive=0
```
First occurrence: 2016-03-24T11:07:25.579370 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931
Times recorded: 1
Latest occurrences:

- 2016-03-24T11:07:25.579370 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931

**Comment by dperpeet** [comment]
verify/fedora-23
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 504, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 625, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1458743165.535:268): avc:  denied  { read } for  pid=1298 comm="ssh-transport-c" name="unix" dev="proc" ino=4026532021 scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=file permissive=0
```
First occurrence: 2016-03-24T11:12:31.368544 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931
Times recorded: 1
Latest occurrences:

- 2016-03-24T11:12:31.368544 | revision 625f738e7e4b481f69591ae87bd30ad49bf52931
