### ISSUE TITLE
TestStorage testLvm fails waiting for 'Erasing'

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4055]
This bug happens regularly in the tests:

```
 WARNING: Sum of all thin volume sizes (100.00 MiB) exceeds the size of thin pool TEST1/pool and the size of whole volume group (48.00 MiB)!
```

```
Traceback (most recent call last):
  File "./verify/check-storage-lvm2", line 185, in testLvm
    b.wait_in_text("#jobs", "Erasing")
  File "/build/cockpit/test/common/testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-lvm2", line 185, in testLvm
    b.wait_in_text("#jobs", "Erasing")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-03-21T20:58:35.686222 | revision 6c89c56913c5e8e084401a7085758a77f6838118, [logs](http://files.cockpit-project.org/logs/pull-4051-6c89c569-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-03-21T20:58:35.686222 | revision 6c89c56913c5e8e084401a7085758a77f6838118, [logs](http://files.cockpit-project.org/logs/pull-4051-6c89c569-verify-fedora-24/log.html)
