### ISSUE TITLE
Storaged before 2.5 can't make maximum thin pools

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#4107]
Storaged before 2.5 interprets the size for a new thin pool as the size for the data part of the pool.  Additional space will be used for the metadata part and maybe other things.  This was not intended when designing the API, but overlooked.  Instead, the given size should be taken as the total size to take out of the volume group.

The consequence is that accepting the default of the "Create Thin Pool" dialog will not work with storaged before 2.5: it will always lead to a "not enough space" error.

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-lvm2", line 166, in testLvm
    values = { "name": "pool" })
  File "storagelib.py", line 139, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 124, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-03-30T07:50:21.875764 | revision e4041503dfbc1e711246fbdc43271d001f7080f7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-3876-e4041503-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-03-30T07:50:21.875764 | revision e4041503dfbc1e711246fbdc43271d001f7080f7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-3876-e4041503-verify-rhel-7/log.html)

**Comment by mvollmer** [comment]
verify/fedora-23
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-lvm2", line 168, in testLvm
    "name": "pool" })
  File "storagelib.py", line 136, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 121, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-04-20T14:24:52.084935
Times recorded: 1
Latest occurrences:

- 2016-04-20T14:24:52.084935

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-lvm2", line 168, in testLvm
    "name": "pool" })
  File "storagelib.py", line 136, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 121, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-04-20T12:07:22.593799 | revision c2a46802a8deaa8601abf6de769ad204010161da, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4258-c2a46802-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2016-04-20T12:07:22.593799 | revision c2a46802a8deaa8601abf6de769ad204010161da, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4258-c2a46802-verify-fedora-testing/log.html)
