### ISSUE TITLE
Atomic: rpm-ostree daemon: Regression with CachedUpdate property updates

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#4738]
https://github.com/projectatomic/rpm-ostree/issues/392

**Comment by mvollmer** [comment]
verify/rhel-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-ostree", line 163, in testOstree
    b.wait_present('table.listing-ct tbody:nth-child(3) i.fa-circle')
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 665, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 688, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-14T13:31:46.249687 | revision 2d086fa5dd726efc4746254605017fd49aecbaa7, [logs](http://mvo.fedorapeople.org/logs/pull-2d086fa5-verify-rhel-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-14T13:31:46.249687 | revision 2d086fa5dd726efc4746254605017fd49aecbaa7, [logs](http://mvo.fedorapeople.org/logs/pull-2d086fa5-verify-rhel-atomic/log.html)

**Comment by mvollmer** [comment]
verify/fedora-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-ostree", line 163, in testOstree
    b.wait_present('table.listing-ct tbody:nth-child(3) i.fa-circle')
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 665, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 688, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-14T16:27:05.182026 | revision 2d086fa5dd726efc4746254605017fd49aecbaa7, [logs](http://mvo.fedorapeople.org/logs/pull-2d086fa5-verify-fedora-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-14T16:27:05.182026 | revision 2d086fa5dd726efc4746254605017fd49aecbaa7, [logs](http://mvo.fedorapeople.org/logs/pull-2d086fa5-verify-fedora-atomic/log.html)

**Comment by petervo** [comment]
verify/centos-continuous-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-ostree", line 165, in testOstree
    b.wait_present('table.listing-ct tbody:nth-child(3) i.fa-circle')
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 686, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 709, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-20T14:27:57.016961 | revision d632c5b0b2bee8aa5bc67b5c7733f4dad54b3530, [logs](None)
Times recorded: 1
Latest occurrences:

- 2016-07-20T14:27:57.016961 | revision d632c5b0b2bee8aa5bc67b5c7733f4dad54b3530, [logs](None)

**Comment by petervo** [comment]
verify/continuous-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-ostree", line 165, in testOstree
    b.wait_present('table.listing-ct tbody:nth-child(3) i.fa-circle')
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 686, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 709, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-21T07:05:50.943919
Times recorded: 1
Latest occurrences:

- 2016-07-21T07:05:50.943919
