### ISSUE TITLE
Fedora: Old Fedora 22 version of Cockpit fails in o.client.lookup

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5127]
We see this failure in TestMultiOS against Fedora 22. It seems like a failure in the Fedora 22 version of Cockpit. The code in question is the old dbus-json1 code.

```
Page error: TypeError: null is not an object (evaluating 'o.client.lookup')
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/shell/shell.js 51 c
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 71 dispatch
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 71 handle
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 71 trigger
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 71 
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 70 each
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 70 each
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 71 trigger
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/shell/shell.js 11 _state_change
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/shell/shell.js 11 _handle_seed
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/shell/shell.js 11 
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 71 dispatch
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 71 handle
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 64 i
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 64 c
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 64 P
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 64 onmessage
http://10.111.124.155:9090/cockpit/$044bc7a0875465d09f87bf7f1910f63dd22827eb/base1/bundle.js 64 t
```

**Comment by cockpituous** [comment]
verify/debian-unstable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-multi-os", line 177, in testFedora22
    self.checkStock()
  File "check-multi-os", line 153, in checkStock
    dev_b.wait_present("iframe.container-frame[name='cockpit1:%s/shell/shell'][src$='#/accounts']" % stock_m.address)
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 688, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 711, in _invoke
    raise Error(res['error'])
Error: TypeError: null is not an object (evaluating 'o.client.lookup')
```
First occurrence: 2016-10-11T13:36:14.131548 | revision 16d14f44a8b96cf7cb8fea0723904798508012e2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5045-16d14f44-verify-debian-unstable/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-11T13:36:14.131548 | revision 16d14f44a8b96cf7cb8fea0723904798508012e2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5045-16d14f44-verify-debian-unstable/log.html)

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-multi-os", line 177, in testFedora22
    self.checkStock()
  File "check-multi-os", line 153, in checkStock
    dev_b.wait_present("iframe.container-frame[name='cockpit1:%s/shell/shell'][src$='#/accounts']" % stock_m.address)
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 688, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 711, in _invoke
    raise Error(res['error'])
Error: TypeError: null is not an object (evaluating 'o.client.lookup')
```
First occurrence: 2016-10-17T12:14:50.084833 | revision 87b0cf93b08560f9bc23b13c0e5f8d21af8fe306, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5168-87b0cf93-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-17T12:14:50.084833 | revision 87b0cf93b08560f9bc23b13c0e5f8d21af8fe306, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5168-87b0cf93-verify-centos-7/log.html)

**Comment by cockpituous** [comment]
verify/fedora-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-multi-os", line 177, in testFedora22
    self.checkStock()
  File "check-multi-os", line 153, in checkStock
    dev_b.wait_present("iframe.container-frame[name='cockpit1:%s/shell/shell'][src$='#/accounts']" % stock_m.address)
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 688, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 711, in _invoke
    raise Error(res['error'])
Error: TypeError: null is not an object (evaluating 'o.client.lookup')
```
First occurrence: 2016-10-18T16:53:19.451929 | revision e0ab5b7161f803e8ea8d16178218e8c666a370c6, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5175-e0ab5b71-verify-fedora-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-18T16:53:19.451929 | revision e0ab5b7161f803e8ea8d16178218e8c666a370c6, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5175-e0ab5b71-verify-fedora-atomic/log.html)
