### ISSUE TITLE
Debian: storaged crashes in poll_with_variant()

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5399]
storaged-project/storaged#109

Should be fixed by above storaged pull request.

```
#0  poll_with_variant (pid=6255, info=0x0, error=0x1873b30, user_data=0x0)
    at udiskslinuxvolumegroupobject.c:633
#1  0x00007fbdd25b175f in variant_reader_watch_child (pid=6255, 
    status=<optimized out>, user_data=0x19a14a0) at udiskslvm2daemonutil.c:285
#2  0x00007fbde3ecd0a4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbde3ed06aa in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fbde3ed0a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fbde3ed0d82 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x0000000000414747 in main (argc=<optimized out>, argv=<optimized out>)
    at main.c:180
```

**Comment by cockpituous** [comment]
verify/debian-unstable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-lvm2", line 155, in testLvm
    self.dialog({ "size": 30 })
  File "storagelib.py", line 151, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 136, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 223, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 714, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 737, in _invoke
    raise Error(res['error'])
Error: timeout
Message recipient disconnected from message bus without replying
```
First occurrence: 2016-11-17T07:08:21.882377 | revision 0cd744b41e6f5befd25c14a3d4f34af49eab7c91, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5417-0cd744b4-verify-debian-unstable/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-17T07:08:21.882377 | revision 0cd744b41e6f5befd25c14a3d4f34af49eab7c91, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5417-0cd744b4-verify-debian-unstable/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-lvm2", line 155, in testLvm
    self.dialog({ "size": 30 })
  File "storagelib.py", line 245, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 230, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 736, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 762, in _invoke
    raise Error(res['error'])
Error: timeout
Message recipient disconnected from message bus without replying
```
First occurrence: 2017-03-15T22:47:21.149718 | revision 28e290de5e69aeed4e4c5d7cf0e8f85ddfc78db3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6111-28e290de-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2017-03-15T22:47:21.149718 | revision 28e290de5e69aeed4e4c5d7cf0e8f85ddfc78db3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6111-28e290de-verify-debian-testing/log.html)

**Comment by martinpitt** [comment]
This happens very rarely (just once, four months ago), so this gets dropped in #7193 .
