### ISSUE TITLE
CentOS 7: NetworkManager crash assertion devices/nm-device.c:8954

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5662]
https://bugzilla.redhat.com/show_bug.cgi?id=1404148

NetworkManager crashes on CentOS 7

```
Jan 03 03:29:06 localhost.localdomain NetworkManager[495]: NetworkManager:ERROR:devices/nm-device.c:8954:<unknown-fcn>: assertion failed: (<dropped>)
```

**Comment by stefwalter** [comment]
```
#0  0x00007f91a346a1d7 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f91a346b8c8 in __GI_abort () at abort.c:90
#2  0x00007f91a3c7e2a5 in g_assertion_message (
    domain=domain@entry=0x7f91a6f936e3 "NetworkManager", 
    file=file@entry=0x7f91a6f8e85e "devices/nm-device.c", 
    line=line@entry=8954, func=func@entry=0x7f91a6f8a851 "<unknown-fcn>", 
    message=message@entry=0x7f91a74ceeb0 "assertion failed: (<dropped>)")
    at gtestutils.c:2429
#3  0x00007f91a3c7e33a in g_assertion_message_expr (
    domain=domain@entry=0x7f91a6f936e3 "NetworkManager", 
    file=file@entry=0x7f91a6f8e85e "devices/nm-device.c", 
    line=line@entry=8954, func=func@entry=0x7f91a6f8a851 "<unknown-fcn>", 
    expr=expr@entry=0x7f91a6f8a847 "<dropped>") at gtestutils.c:2444
#4  0x00007f91a6e2d2bb in nm_device_start_ip_check (self=0x7f91a74ecb10)
    at devices/nm-device.c:8954
#5  0x00007f91a6ea33f4 in _cb_info_callback (error=0x0, info=0x7f91a7491750)
    at nm-firewall-manager.c:187
#6  _cb_info_complete_normal (info=0x7f91a7491750, error=0x0)
    at nm-firewall-manager.c:198
#7  0x00007f91a6ea37a7 in _handle_dbus (proxy=<optimized out>, 
    result=<optimized out>, user_data=0x7f91a7491750)
    at nm-firewall-manager.c:261
```

**Comment by stefwalter** [comment]
```
# testBasic (check_networking.TestNetworking)
#
52:54:00:9e:00:F2 -> ens6
52:54:00:9e:00:F2 -> ens6
> Successfully loaded SELinux database in 3.199ms, size on heap is 315K.
calling: info

> Successfully loaded SELinux database in 3.087ms, size on heap is 315K.
calling: info

> Successfully loaded SELinux database in 1.905ms, size on heap is 315K.
calling: info

> Successfully loaded SELinux database in 4.952ms, size on heap is 315K.
calling: info

> Invalid prefix or netmask 255.255.0.8
> connection ens6 cannot change the UUID from 239b3e45-2af8-44e5-94aa-0d840cfdc817 to c54770e7-02b4-439b-9d1a-513cc134eb3e
> Successfully loaded SELinux database in 4.135ms, size on heap is 315K.
calling: info

Wrote TestNetworking-testBasic-FAIL.png
Journal extracted to TestNetworking-testBasic-10.111.121.252-FAIL.log
Core dumps downloaded to TestNetworking-testBasic-10.111.121.252-FAIL.core
not ok 67 testBasic (check_networking.TestNetworking) duration: 94s
Traceback (most recent call last):
  File "./verify/check-networking", line 129, in testBasic
    b.wait_popdown("network-ip-settings-dialog")
  File "/build/cockpit/test/common/testlib.py", line 272, in wait_popdown
    self.wait_not_visible('#' + id)
  File "/build/cockpit/test/common/testlib.py", line 244, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 724, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 747, in _invoke
    raise Error(res['error'])
Error: timeout
connection ens6 cannot change the UUID from 239b3e45-2af8-44e5-94aa-0d840cfdc817 to c54770e7-02b4-439b-9d1a-513cc134eb3e
Successfully loaded SELinux database in 4.135ms, size on heap is 315K.
calling: info

```

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-networking", line 129, in testBasic
    b.wait_popdown("network-ip-settings-dialog")
  File "testlib.py", line 272, in wait_popdown
    self.wait_not_visible('#' + id)
  File "testlib.py", line 244, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 724, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 747, in _invoke
    raise Error(res['error'])
Error: timeout
Successfully loaded SELinux database in 11.076ms, size on heap is 315K.
calling: info

connection ens6 cannot change the UUID from a18b1239-a986-4225-a140-bb70ab3da0a4 to c0287afb-533b-446b-a8df-737deaa6f9ea
```
First occurrence: 2017-01-03T11:39:32.178903 | revision 4281ac4a4cc13e5bbba634a352108b654888584c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5663-4281ac4a-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-03T11:39:32.178903 | revision 4281ac4a4cc13e5bbba634a352108b654888584c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5663-4281ac4a-verify-centos-7/log.html)
