### ISSUE TITLE
Fedora 25: NetworkManager crash assertion devices/nm-device.c:9015

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5671]
https://bugzilla.redhat.com/show_bug.cgi?id=1409896

NetworkManager crashes due to an assertion failure.

```
Jan 03 13:45:07 localhost.localdomain NetworkManager[845]: NetworkManager:ERROR:devices/nm-device.c:9015:<unknown-fcn>: assertion failed: (<dropped>)
```

**Comment by stefwalter** [comment]
Example failure:

```
# testBasic (check_networking.TestNetworking)
#
52:54:00:9e:00:F2 -> ens6
52:54:00:9e:00:F2 -> ens6
> Invalid prefix or netmask 255.255.0.8
> No such interface 'org.freedesktop.NetworkManager.Settings.Connection' on object at path /org/freedesktop/NetworkManager/Settings/4
> No such interface 'org.freedesktop.NetworkManager.Settings.Connection' on object at path /org/freedesktop/NetworkManager/Settings/4
> No such interface 'org.freedesktop.NetworkManager.Settings.Connection' on object at path /org/freedesktop/NetworkManager/Settings/4
> No such interface 'org.freedesktop.NetworkManager.Settings.Connection' on object at path /org/freedesktop/NetworkManager/Settings/4
52:54:00:9e:00:F8 -> ens7
52:54:00:9e:00:F8 -> ens7
Unexpected journal message 'org.freedesktop.NetworkManager: couldn't introspect /org/freedesktop/systemd1/unit/systemd_2dcoredump_2esocket: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying'
Journal extracted to TestNetworking-testBasic-10.111.122.77-FAIL.log
Wrote TestNetworking-testBasic-FAIL.png
Journal extracted to TestNetworking-testBasic-10.111.122.77-FAIL.log
not ok 101 testBasic (check_networking.TestNetworking) duration: 38s
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 538, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 679, in check_journal_messages
    raise Error(first)
Error: org.freedesktop.NetworkManager: couldn't introspect /org/freedesktop/systemd1/unit/systemd_2dcoredump_2esocket: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 538, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 679, in check_journal_messages
    raise Error(first)
Error: org.freedesktop.NetworkManager: couldn't introspect /org/freedesktop/systemd1/unit/systemd_2dcoredump_2esocket: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```
First occurrence: 2017-01-06T22:13:54.022921 | revision a12a038fe45d2610d566748736b0494f6ce03d62, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5670-a12a038f-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-06T22:13:54.022921 | revision a12a038fe45d2610d566748736b0494f6ce03d62, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5670-a12a038f-verify-fedora-25/log.html)
