### ISSUE TITLE
Debian: udisksd assertion crash in udev_device_get_syspath()

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5673]
https://github.com/storaged-project/storaged/issues/168

```
# testMounting (check_storage_mounting.TestStorage)
#
> Message recipient disconnected from message bus without replying
Wrote TestStorage-testMounting-FAIL.png
Journal extracted to TestStorage-testMounting-10.111.112.68-FAIL.log
Core dumps downloaded to TestStorage-testMounting-10.111.112.68-FAIL.core
not ok 14 testMounting (check_storage_mounting.TestStorage) duration: 101s
Traceback (most recent call last):
  File "./verify/check-storage-mounting", line 65, in testMounting
    "mount_point": mount_point_foo })
  File "/build/cockpit/test/verify/storagelib.py", line 245, in dialog
    self.dialog_wait_close()
  File "/build/cockpit/test/verify/storagelib.py", line 230, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/common/testlib.py", line 223, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 724, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 747, in _invoke
    raise Error(res['error'])
Error: timeout
Message recipient disconnected from message bus without replying
```

**Comment by stefwalter** [comment]
Backtrace: 

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007f9e2701b40a in __GI_abort () at abort.c:89
#2  0x00007f9e28cba7f2 in log_assert_failed (text=<optimized out>, 
    file=<optimized out>, line=<optimized out>, func=<optimized out>)
    at ../src/basic/log.c:795
#3  0x00007f9e28cc0d3f in sd_device_get_syspath (device=<optimized out>, 
    ret=0x7f9e2491c340) at ../src/libsystemd/sd-device/sd-device.c:682
#4  0x00007f9e28cb2216 in udev_device_get_syspath (udev_device=<optimized out>)
    at ../src/libudev/libudev-device.c:607
#5  0x000000000041ab8d in udisks_linux_block_object_trigger_uevent (
    object=0x7f9e18005a20) at udiskslinuxblockobject.c:902
#6  0x00000000004209cf in udisks_linux_block_handle_format (block=0x1684380, 
    invocation=0x168c2a0, type=0x7f9e1800ebf0 "ext4", options=0x1693d00, 
    complete=complete@entry=0x41b3c0 <handle_format_complete>, 
    complete_user_data=complete_user_data@entry=0x7f9e2491c660)
    at udiskslinuxblock.c:2936
#7  0x000000000042182c in handle_format (block=<optimized out>, 
    invocation=<optimized out>, type=<optimized out>, options=<optimized out>)
    at udiskslinuxblock.c:3318
#8  0x00007f9e259f7038 in ffi_call_unix64 ()
   from /usr/lib/x86_64-linux-gnu/libffi.so.6
#9  0x00007f9e259f6a9a in ffi_call ()
   from /usr/lib/x86_64-linux-gnu/libffi.so.6
---Type <return> to continue, or q <return> to quit---
#10 0x00007f9e278c67ae in g_cclosure_marshal_generic ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f9e278c5f75 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f9e278d837d in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007f9e278dfd31 in g_signal_emitv ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007f9e27ed0939 in ?? () from /usr/lib/x86_64-linux-gnu/libudisks2.so.0
#15 0x00007f9e27bdc44e in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007f9e27b93cbd in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007f9e27614d3e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f9e27614345 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f9e2738c464 in start_thread (arg=0x7f9e2491d700)
    at pthread_create.c:333
#20 0x00007f9e270cf9df in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

**Comment by martinpitt** [comment]
This has never matched in practice (perhaps because of the fixed line number in the override?), and that test succeeds on debian-stable and testing. The override gets dropped in #7193.
