### ISSUE TITLE
storage: luks test failure on centos-7

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#5917]
original failure log: https://fedorapeople.org/groups/cockpit/logs/pull-5905-1f8bb7fe-verify-centos-7/log.html#83

```
# testLuks (check_storage_luks.TestStorage)
#
> Using older 'storaged' API: org.storaged.Storaged
Wrote TestStorage-testLuks-FAIL.png
Journal extracted to TestStorage-testLuks-10.111.123.137-FAIL.log
not ok 83 testLuks (check_storage_luks.TestStorage) duration: 87s
```
```python
Traceback (most recent call last):
  File "./verify/check-storage-luks", line 62, in testLuks
    assert m.execute("cat /etc/crypttab | logger -s 2>&1 | grep 'UUID='") != ""
  File "/build/cockpit/test/common/testvm.py", line 412, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'cat /etc/crypttab | logger -s 2>&1 | grep 'UUID='' returned non-zero exit status 1
```
![teststorage-testluks-fail](https://cloud.githubusercontent.com/assets/8711649/23159781/631e642e-f824-11e6-9723-bef0cf1ee404.png)

**Comment by mvollmer** [comment]
Our flake detection / known issue machinery should take care of test failures, so I close this.
