### ISSUE TITLE
Fedora: storaged asserts and crashes in handle_format()

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5998]
https://bugzilla.redhat.com/show_bug.cgi?id=1427832

```
> Message recipient disconnected from message bus without replying
not ok 109 testFormatTypes (check_storage_format.TestStorage) duration: 77s
Traceback (most recent call last):
  File "./verify/check-storage-format", line 77, in testFormatTypes
    check_type("ntfs")
  File "./verify/check-storage-format", line 70, in check_type
    self.dialog({ "type": type })
  File "/build/cockpit/test/verify/storagelib.py", line 245, in dialog
    self.dialog_wait_close()
  File "/build/cockpit/test/verify/storagelib.py", line 230, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/common/testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 717, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 743, in _invoke
    raise Error(res['error'])
Error: timeout
Message recipient disconnected from message bus without replying
Wrote TestStorage-testFormatTypes-FAIL.png
Journal extracted to TestStorage-testFormatTypes-10.111.114.72-FAIL.log
Core dumps downloaded to TestStorage-testFormatTypes-10.111.114.72-FAIL.core
```

```
                                                              Stack trace of thread 1309:
                                                              #0  0x00007f92277cd91f raise (libc.so.6)
                                                              #1  0x00007f92277cf51a abort (libc.so.6)
                                                              #2  0x00007f92296a1e85 log_assert_failed (/usr/lib64/libudev.so.1.6.5)
                                                              #3  0x00007f92296a377f sd_device_get_syspath (/usr/lib64/libudev.so.1.6.5)
                                                              #4  0x00007f9229697066 udev_device_get_syspath (/usr/lib64/libudev.so.1.6.5)
                                                              #5  0x000056038d966e4d udisks_linux_block_object_trigger_uevent (udisksd)
                                                              #6  0x000056038d96cbc3 udisks_linux_block_handle_format (udisksd)
                                                              #7  0x000056038d96db6c handle_format (udisksd)
                                                              #8  0x00007f9225427c58 ffi_call_unix64 (libffi.so.6)
                                                              #9  0x00007f92254276ba ffi_call (libffi.so.6)
                                                              #10 0x00007f922809ec1e g_cclosure_marshal_generic (libgobject-2.0.so.0)
                                                              #11 0x00007f922809e3e5 g_closure_invoke (libgobject-2.0.so.0)
                                                              #12 0x00007f92280b082d signal_emit_unlocked_R (libgobject-2.0.so.0)
                                                              #13 0x00007f92280b8241 g_signal_emitv (libgobject-2.0.so.0)
                                                              #14 0x00007f92286a5f59 _udisks_block_skeleton_handle_method_call (libudisks2.so.0)
                                                              #15 0x00007f92283b29ae dispatch_in_thread_func (libgio-2.0.so.0)
                                                              #16 0x00007f922836a18d g_task_thread_pool_thread (libgio-2.0.so.0)
                                                              #17 0x00007f9227dee58e g_thread_pool_thread_proxy (libglib-2.0.so.0)
                                                              #18 0x00007f9227dedb93 g_thread_proxy (libglib-2.0.so.0)
                                                              #19 0x00007f9227b656ca start_thread (libpthread.so.0)
                                                              #20 0x00007f922789ff7f __clone (libc.so.6)
```

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-format", line 74, in testFormatTypes
    check_type("ext4")
  File "check-storage-format", line 70, in check_type
    self.dialog({ "type": type })
  File "storagelib.py", line 245, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 230, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 738, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 764, in _invoke
    raise Error(res['error'])
Error: timeout
Message recipient disconnected from message bus without replying
```
First occurrence: 2017-03-17T13:24:35.155118 | revision de7ecc3456a5de27a9e534aabda3cb635cd90265, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6139-de7ecc34-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-03-17T13:24:35.155118 | revision de7ecc3456a5de27a9e534aabda3cb635cd90265, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6139-de7ecc34-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-format", line 75, in testFormatTypes
    check_type("vfat")
  File "check-storage-format", line 70, in check_type
    self.dialog({ "type": type })
  File "storagelib.py", line 245, in dialog
    self.dialog_wait_close()
  File "storagelib.py", line 230, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "testlib.py", line 221, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 740, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 766, in _invoke
    raise Error(res['error'])
Error: timeout
Message recipient disconnected from message bus without replying
```
First occurrence: 2017-04-07T23:38:02.728414 | revision 18a08333b7ae3349e621fdb68e81ecf0cfdbe629, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6302-18a08333-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2017-04-07T23:38:02.728414 | revision 18a08333b7ae3349e621fdb68e81ecf0cfdbe629, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6302-18a08333-verify-fedora-testing/log.html)
