### ISSUE TITLE
Show available admin accounts on the login page.

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#60]
With avatar.

**Comment by stefwalter** [comment]
This goes against the security that people expect from a server. Lets close this.

**Comment by cockpituous** [comment]
verify/ubuntu-1804
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDosParts (check_storage_msdos.TestStorage)
#

DevTools listening on ws://127.0.0.1:9306/devtools/browser/264f0114-dac1-456d-bfb6-c759b951d0a2
[1001/132029.741933:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/132029.745096:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/132029.751005:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestStorage-testDosParts-ubuntu-1804-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorage-testDosParts-ubuntu-1804-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorage-testDosParts-ubuntu-1804-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorage-testDosParts-ubuntu-1804-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-msdos", line 80, in testDosParts
    self.content_row_wait_in_col(3, 1, "xfs File System")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 93, in content_row_wait_in_col
    self.retry(None, lambda: self.browser.is_present(col) and val in self.browser.text(col), None)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 68, in retry
    self.browser.wait(step)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 331, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

not ok 210 testDosParts (check_storage_msdos.TestStorage) # duration: 122s
```
First occurrence: 2019-10-01T13:21:57.952501 | revision 74fdcfa1a895652e34cf5571915fb3c987be2e0b
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:21:57.952501 | revision 74fdcfa1a895652e34cf5571915fb3c987be2e0b
