### ISSUE TITLE
RHEL, CentOS: kubernetes selfLink is missing a slash

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#6059]
https://bugzilla.redhat.com/show_bug.cgi?id=1430427

**Comment by mvollmer** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "kubelib.py", line 541, in testNodes
    b.wait_not_present("modal-dialog")
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 729, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 755, in _invoke
    raise Error(res['error'])
Error: timeout
the server could not find the requested resource
```
First occurrence: 2017-03-09T09:42:15.100475
Times recorded: 1
Latest occurrences:

- 2017-03-09T09:42:15.100475

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "kubelib.py", line 541, in testNodes
    b.wait_not_present("modal-dialog")
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 729, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 755, in _invoke
    raise Error(res['error'])
Error: timeout
the server could not find the requested resource
```
First occurrence: 2017-03-13T08:03:03.959875 | revision 663e7750f8d8172f325cb9ccec98fe2bf5894c6e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6083-663e7750-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-03-13T08:03:03.959875 | revision 663e7750f8d8172f325cb9ccec98fe2bf5894c6e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6083-663e7750-verify-centos-7/log.html)
