### ISSUE TITLE
Fedora: lsblk -sl has unexpected output ordering 

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#6331]
https://bugzilla.redhat.com/show_bug.cgi?id=1441175

**Comment by mvollmer** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 184, in testDevmapper
    b.wait_not_in_text("#storage-drives", "DISK1")
  File "testlib.py", line 248, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 740, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 766, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-04-12T11:07:47.928414
Times recorded: 1
Latest occurrences:

- 2017-04-12T11:07:47.928414

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-docker-storage", line 198, in testDevmapper
    b.wait_not_in_text("#storage-drives", "DISK1")
  File "/build/cockpit/test/common/testlib.py", line 255, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 219, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 774, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 800, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-06-19T16:52:38.805654 | revision 9b5b21bf67af7e21098b16d4e97761f31378a0cd, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7002-20170619-163131-9b5b21bf-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-06-19T16:52:38.805654 | revision 9b5b21bf67af7e21098b16d4e97761f31378a0cd, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7002-20170619-163131-9b5b21bf-verify-fedora-26/log.html)
