### ISSUE TITLE
Fedora: setroubleshootd API is broken:  AttributeError: module 'seobject' has no attribute 'boolean_desc'

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#6332]
https://bugzilla.redhat.com/show_bug.cgi?id=1441638

**Comment by mvollmer** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-setroubleshoot", line 75, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "testlib.py", line 218, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 740, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 766, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-04-12T15:06:10.343204
Times recorded: 1
Latest occurrences:

- 2017-04-12T15:06:10.343204

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 118, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 225, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 219, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 761, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 787, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-06-25T17:39:31.682972 | revision 9a554961e91bde8acf65098fbbf7243532e81108, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7109-20170625-173030-9a554961-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-06-25T17:39:31.682972 | revision 9a554961e91bde8acf65098fbbf7243532e81108, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7109-20170625-173030-9a554961-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 118, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-07-18T20:40:17.109088 | revision 78d349287bd92bbfddd6ee86298ecc0d62dbfc01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7319-20170718-203232-78d34928-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T20:40:17.109088 | revision 78d349287bd92bbfddd6ee86298ecc0d62dbfc01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7319-20170718-203232-78d34928-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 118, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-07-20T11:48:34.315170 | revision 509a38a90f2215e3752b01864c73a5e5e24fe063, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7114-20170720-103939-509a38a9-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-20T11:48:34.315170 | revision 509a38a90f2215e3752b01864c73a5e5e24fe063, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7114-20170720-103939-509a38a9-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 118, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-07-24T13:08:35.729540 | revision 5c68fd4494401feddeef99a4fd3b1b36ccae5cbc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7350-20170724-124444-5c68fd44-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-24T13:08:35.729540 | revision 5c68fd4494401feddeef99a4fd3b1b36ccae5cbc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7350-20170724-124444-5c68fd44-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 118, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-07-26T20:52:10.325462 | revision 653bb55deccd0b7ec2c49775d3103a52f768970d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7379-20170726-202525-653bb55d-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-26T20:52:10.325462 | revision 653bb55deccd0b7ec2c49775d3103a52f768970d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7379-20170726-202525-653bb55d-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 118, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-07-30T14:00:40.116160 | revision f8e83bc7891cae38dc1145738a36f10376cfe475, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7402-20170730-134949-f8e83bc7-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-30T14:00:40.116160 | revision f8e83bc7891cae38dc1145738a36f10376cfe475, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7402-20170730-134949-f8e83bc7-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 118, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-08-01T14:42:00.343669 | revision e315af9a31ce3049e202d0d2128c287969886fc7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7426-20170801-143333-e315af9a-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-01T14:42:00.343669 | revision e315af9a31ce3049e202d0d2128c287969886fc7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7426-20170801-143333-e315af9a-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-08-03T19:56:54.680406 | revision fe1cfd5dd1a12477b1b2f036c12e11453b7eb142, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7437-20170803-194848-fe1cfd5d-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-03T19:56:54.680406 | revision fe1cfd5dd1a12477b1b2f036c12e11453b7eb142, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7437-20170803-194848-fe1cfd5d-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-08-09T10:38:53.184908 | revision bb3ae91a2e99de2e32f12a277f755b48ceac75ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7470-20170809-102727-bb3ae91a-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-09T10:38:53.184908 | revision bb3ae91a2e99de2e32f12a277f755b48ceac75ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7470-20170809-102727-bb3ae91a-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-08-15T05:17:31.081192 | revision a22cfe28e5297ec762d2c3791363f794b3b7f6d3, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20170815-050505-a22cfe28-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-15T05:17:31.081192 | revision a22cfe28e5297ec762d2c3791363f794b3b7f6d3, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20170815-050505-a22cfe28-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-08-21T16:06:17.556024 | revision e49d709087b7bb34072fa0a0901b269408338573, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7478-20170821-155454-e49d7090-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-21T16:06:17.556024 | revision e49d709087b7bb34072fa0a0901b269408338573, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7478-20170821-155454-e49d7090-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 825, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 851, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-08-28T19:05:23.817510 | revision 5e79d0e5f68efc34db21436384017ab26551c92c, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20170828-185353-5e79d0e5-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-28T19:05:23.817510 | revision 5e79d0e5f68efc34db21436384017ab26551c92c, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20170828-185353-5e79d0e5-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 825, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 851, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-09-01T19:58:25.512148 | revision 91add5b79f062c70c3d07f6ba6b17708b1745169, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20170901-193636-91add5b7-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-09-01T19:58:25.512148 | revision 91add5b79f062c70c3d07f6ba6b17708b1745169, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20170901-193636-91add5b7-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 825, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 851, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-09-07T02:27:28.445314 | revision 2835150124e4e1c4b9cf3da61792b5a0e832e770, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7607-20170907-020606-28351501-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2017-09-07T02:27:28.445314 | revision 2835150124e4e1c4b9cf3da61792b5a0e832e770, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7607-20170907-020606-28351501-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 825, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 851, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-09-07T05:47:54.571891 | revision 793db6903b53e4cd02f27b6d2599235c102758cb
Times recorded: 1
Latest occurrences:

- 2017-09-07T05:47:54.571891 | revision 793db6903b53e4cd02f27b6d2599235c102758cb

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 120, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 230, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 825, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 851, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-09-13T02:08:59.779456 | revision c247b3e9f17c4cf02e0d1bfc3ee2bbbecdefe985, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7662-20170913-015858-c247b3e9-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-09-13T02:08:59.779456 | revision c247b3e9f17c4cf02e0d1bfc3ee2bbbecdefe985, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7662-20170913-015858-c247b3e9-verify-fedora-26/log.html)
