### ISSUE TITLE
RHEL: Candlepin subscription-manager version mismatch error

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#6384]
There is a regression with the latest subscription-manager when using our existing candlepin image, leading to an error from the subscription-manager cli.

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1445387

```
> unrecognized subscription-manager failure output:  subscription-manager exited with code 70 sequence item 0: expected string, NoneType found
Registering to: 10.111.117.60:8443/candlepin
> Error: sequence item 0: expected string, NoneType found
Registering to: 10.111.117.60:8443/candlepin
not ok 1 testRegister (check_subscriptions.TestSubscriptions) duration: 105s
```
```python
Traceback (most recent call last):
  File "./verify/check-subscriptions", line 126, in testRegister
    b.wait_in_text("body", "Invalid credentials")
  File "/build/cockpit/test/common/testlib.py", line 245, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 741, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 767, in _invoke
    raise Error(res['error'])
Error: timeout
unrecognized subscription-manager failure output:  subscription-manager exited with code 70 sequence item 0: expected string, NoneType found
```
![testsubscriptions-testregister-fail](https://cloud.githubusercontent.com/assets/8711649/25375440/f784b138-29a0-11e7-9ab5-534470e8cc88.png)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-subscriptions", line 126, in testRegister
    b.wait_in_text("body", "Invalid credentials")
  File "testlib.py", line 245, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 741, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 767, in _invoke
    raise Error(res['error'])
Error: timeout
unrecognized subscription-manager failure output:  subscription-manager exited with code 70 sequence item 0: expected string, NoneType found
Registering to: 10.111.114.24:8443/candlepin
Error: sequence item 0: expected string, NoneType found
Registering to: 10.111.114.24:8443/candlepin
```
First occurrence: 2017-04-25T08:42:23.969148 | revision 12250f6d2b69fa7a882928f5635df367c94af2b9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-12250f6d-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-04-25T08:42:23.969148 | revision 12250f6d2b69fa7a882928f5635df367c94af2b9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-12250f6d-verify-rhel-7/log.html)

**Comment by dperpeet** [comment]
fixed and verified
