### ISSUE TITLE
Fedora: dockerd-current crashes with double-free

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#6432]
https://bugzilla.redhat.com/show_bug.cgi?id=1447557

```
Traceback (most recent call last):
  File "./verify/check-docker", line *, in testBasic
    b.wait_visible("#container-details")
*
Error: timeout
```

```
Traceback (most recent call last):
  File "./verify/check-docker", line *, in testBasic
    b.wait_visible("#container-details-start")
*
Error: timeout
```

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 168, in testBasic
    b.wait_visible("#container-details-start")
  File "testlib.py", line 227, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 741, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 767, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-05-03T17:02:39.388264 | revision db760c7a738bdf84ad7a26a52e6c5a705065c3bb, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6431-db760c7a-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-05-03T17:02:39.388264 | revision db760c7a738bdf84ad7a26a52e6c5a705065c3bb, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6431-db760c7a-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7.4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 167, in testBasic
    b.wait_visible("#container-details-start")
  File "testlib.py", line 227, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 745, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 771, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-05-16T15:41:05.797069 | revision 29e647acbbf36030a59035cf6663e019cd5c0944, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-29e647ac-verify-rhel-7.4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-05-16T15:41:05.797069 | revision 29e647acbbf36030a59035cf6663e019cd5c0944, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-29e647ac-verify-rhel-7.4/log.html)
