### ISSUE TITLE
debian-testing: apparmor denial: libvirt qemu cannot read `/proc/*/cmdline`

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#6690]
https://launchpad.net/bugs/1693115
https://bugs.debian.org/878203

**Comment by martinpitt** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 544, in tearDown
    self.check_journal_messages()
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 706, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1495610398.860:14): apparmor="DENIED" operation="open" profile="libvirt-85ba2ed4-b077-4e61-ab6b-5d22f3fd039d" name="/proc/1197/cmdline" pid=6058 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
```
First occurrence: 2017-05-24T09:20:15.248036
Times recorded: 1
Latest occurrences:

- 2017-05-24T09:20:15.248036

**Comment by martinpitt** [comment]
Turns out it was fixed very recently already: https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1680384

So this just requires an image rebuild.

**Comment by martinpitt** [comment]
This bug now hit Debian testing:
http://209.132.184.41/logs/pull-8219-20171206-214646-d2e9e141-verify-debian-testing/log.html#2

**Comment by martinpitt** [comment]
Added Debian bug ref to description.

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDelete (check_machines.TestMachines)
#
Warning: Permanently added '[127.0.0.2]:2701' (ECDSA) to the list of known hosts.
Started /usr/bin/chromium-browser (pid 64504) on port 9686
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9686/devtools/browser/b7b71468-3b73-4a5c-a28c-3e629951857e
[1207/092043.606311:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 64601: Permission denied (13)
[1207/092043.853288:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 64627: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 401 (Authentication failed)","timestamp":1512638445804.08,"url":"http://127.0.0.2:9591/cockpit/login","networkRequestId":"64627.8"}
Unexpected journal message 'audit: type=1400 audit(1512638448.632:50): apparmor="DENIED" operation="open" profile="libvirt-ac4ac3f4-3509-4d91-80a3-6b1699175bb7" name="/proc/527/cmdline" pid=843 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0'
Journal extracted to TestMachines-testDelete-debian-testing-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 655, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 789, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1512638448.632:50): apparmor="DENIED" operation="open" profile="libvirt-ac4ac3f4-3509-4d91-80a3-6b1699175bb7" name="/proc/527/cmdline" pid=843 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0

not ok 123 testDelete (check_machines.TestMachines) # duration: 23s
Wrote screenshot to TestMachines-testDelete-debian-testing-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMachines-testDelete-debian-testing-127.0.0.2-2701-FAIL.html
Journal extracted to TestMachines-testDelete-debian-testing-127.0.0.2-2701-FAIL.log
Killing browser (pid 64504)
```
First occurrence: 2017-12-07T09:20:51.254695 | revision 14220eb0d583e4978fe3b11de9634e405342ab55, [logs](http://209.132.184.41/logs/pull-8069-20171207-090808-14220eb0-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2017-12-07T09:20:51.254695 | revision 14220eb0d583e4978fe3b11de9634e405342ab55, [logs](http://209.132.184.41/logs/pull-8069-20171207-090808-14220eb0-verify-debian-testing/log.html)

**Comment by martinpitt** [comment]
This has not yet been fixed in Debian, at least https://bugs.debian.org/878203 is still open. So let's keep this for now.
