### ISSUE TITLE
Styling of journal entrys in Storage

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#68]
Andreas: The styling of the journal entrys in Storage (and other places) needs a bit of visual styling, as the list-within-list doesn't look proper right now.

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtSegv (check_journal.TestJournal)
#

DevTools listening on ws://127.0.0.1:9854/devtools/browser/2749931a-a1c5-4915-be66-cc720c57d344
[1001/133859.122468:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/133859.124600:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/133859.128287:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
bash: line 1:  4691 Segmentation fault      (core dumped) python3 -c 'import os; os.kill(os.getpid(), 11)'
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestJournal-testAbrtSegv-fedora-31-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestJournal-testAbrtSegv-fedora-31-127.0.0.2-2601-FAIL.html
Wrote JS log to TestJournal-testAbrtSegv-fedora-31-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestJournal-testAbrtSegv-fedora-31-127.0.0.2-2601-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestJournal-testAbrtSegv-fedora-31-127.0.0.2-2601-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-journal", line 395, in testAbrtSegv
    b.wait_visible(sel)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 357, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 348, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 342, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 339, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in os_kill')")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":7,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1569937144206.1802, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '1000043123.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


not ok 48 testAbrtSegv (check_journal.TestJournal) # duration: 98s
```
First occurrence: 2019-10-01T13:40:11.681040 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:40:11.681040 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtDelete (check_journal.TestJournal)
#

DevTools listening on ws://127.0.0.1:10184/devtools/browser/515896b7-ca85-4bf2-bd98-2bc32c08264d
[1001/133925.301724:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/133925.304382:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/133925.308001:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
bash: line 1:  3801 Segmentation fault      (core dumped) python3 -c 'import os; os.kill(os.getpid(), 11)'
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestJournal-testAbrtDelete-fedora-31-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestJournal-testAbrtDelete-fedora-31-127.0.0.2-2201-FAIL.html
Wrote JS log to TestJournal-testAbrtDelete-fedora-31-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestJournal-testAbrtDelete-fedora-31-127.0.0.2-2201-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestJournal-testAbrtDelete-fedora-31-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-journal", line 433, in testAbrtDelete
    b.click(sel)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 214, in click
    self.mouse(selector + ":not([disabled])", "click", 0, 0, 0)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 210, in mouse
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 357, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 348, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 342, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 339, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in os_kill'):not([disabled])")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":7,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1569937167326.036, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000043504.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


not ok 46 testAbrtDelete (check_journal.TestJournal) # duration: 94s
```
First occurrence: 2019-10-01T13:40:33.520131 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:40:33.520131 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtSegv (check_journal.TestJournal)
#

DevTools listening on ws://127.0.0.1:9939/devtools/browser/2333e5a7-10a9-4ddc-8968-b5b734b1b67d
[1001/135203.591008:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/135203.605551:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/135203.616125:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
bash: line 1:  7060 Segmentation fault      (core dumped) python3 -c 'import os; os.kill(os.getpid(), 11)'
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Tabs)
> warning: Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TabContent, Uncontrolled(Tabs)
Wrote screenshot to TestJournal-testAbrtSegv-fedora-30-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestJournal-testAbrtSegv-fedora-30-127.0.0.2-2901-FAIL.html
Wrote JS log to TestJournal-testAbrtSegv-fedora-30-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestJournal-testAbrtSegv-fedora-30-127.0.0.2-2901-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestJournal-testAbrtSegv-fedora-30-127.0.0.2-2901-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-journal", line 395, in testAbrtSegv
    b.wait_visible(sel)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 357, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 348, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 342, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 339, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in os_kill')")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":7,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1569937928360.043, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '1000042680.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Tabs)
warning: Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TabContent, Uncontrolled(Tabs)

not ok 48 testAbrtSegv (check_journal.TestJournal) # duration: 144s
```
First occurrence: 2019-10-01T13:53:25.850153 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:53:25.850153 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtDelete (check_journal.TestJournal)
#

DevTools listening on ws://127.0.0.1:9710/devtools/browser/3502803e-5aae-44d6-b39b-4e1429b62393
[1001/135229.824172:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/135229.837550:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/135229.854478:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
bash: line 1:  7266 Segmentation fault      (core dumped) python3 -c 'import os; os.kill(os.getpid(), 11)'
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Tabs)
> warning: Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TabContent, Uncontrolled(Tabs)
Wrote screenshot to TestJournal-testAbrtDelete-fedora-30-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestJournal-testAbrtDelete-fedora-30-127.0.0.2-2201-FAIL.html
Wrote JS log to TestJournal-testAbrtDelete-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestJournal-testAbrtDelete-fedora-30-127.0.0.2-2201-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestJournal-testAbrtDelete-fedora-30-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-journal", line 433, in testAbrtDelete
    b.click(sel)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 214, in click
    self.mouse(selector + ":not([disabled])", "click", 0, 0, 0)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 210, in mouse
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 357, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 348, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 342, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 339, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in os_kill'):not([disabled])")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":7,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1569937955583.57, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '1000043014.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Tabs)
warning: Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TabContent, Uncontrolled(Tabs)

not ok 46 testAbrtDelete (check_journal.TestJournal) # duration: 132s
```
First occurrence: 2019-10-01T13:53:57.293241 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:53:57.293241 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
