### ISSUE TITLE
Use libssh instead of sshpass + ssh.

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#69]
To improve error reporting, host key handling, etc.

**Comment by cockpituous** [comment]
verify/ubuntu-1804
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSnapshots (check_storage_lvm2.TestStorage)
#

DevTools listening on ws://127.0.0.1:10163/devtools/browser/eab802e4-8f01-4ee4-b913-be910ed519ea
[1001/132304.543939:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/132304.548499:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/132304.553232:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

  WARNING: Sum of all thin volume sizes (100.00 MiB) exceeds the size of thin pool TEST/pool (20.00 MiB).
  WARNING: Sum of all thin volume sizes (100.00 MiB) exceeds the size of thin pools (20.00 MiB).
  WARNING: Sum of all thin volume sizes (100.00 MiB) exceeds the size of thin pools (20.00 MiB).
Wrote screenshot to TestStorage-testSnapshots-ubuntu-1804-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestStorage-testSnapshots-ubuntu-1804-127.0.0.2-2801-FAIL.html
Wrote JS log to TestStorage-testSnapshots-ubuntu-1804-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestStorage-testSnapshots-ubuntu-1804-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-lvm2", line 291, in testSnapshots
    self.content_row_wait_in_col(3, 2, "mysnapshot")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 93, in content_row_wait_in_col
    self.retry(None, lambda: self.browser.is_present(col) and val in self.browser.text(col), None)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 68, in retry
    self.browser.wait(step)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 331, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

not ok 204 testSnapshots (check_storage_lvm2.TestStorage) # duration: 128s
```
First occurrence: 2019-10-01T13:24:36.662265 | revision 74fdcfa1a895652e34cf5571915fb3c987be2e0b
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:24:36.662265 | revision 74fdcfa1a895652e34cf5571915fb3c987be2e0b
