### ISSUE TITLE
check-openshift TestRegistry.testImages does not work with new OpenShift image

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7452]
Temporary known issue for PR #7401. This is fixed in #7400, using this to decouple these PRs.

We haven't really run the openshift tests for months due to the selfLink issue, so this will be much better already.
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-openshift", line 450, in testImages
    b.click("tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle")
  File "/build/cockpit/test/common/testlib.py", line 169, in click
    self.call_js_func('ph_click', selector, force)
  File "/build/cockpit/test/common/testlib.py", line 154, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle not found
```

**Comment by martinpitt** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "test/verify/check-openshift", line 450, in testImages
    b.click("tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle")
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 169, in click
    self.call_js_func('ph_click', selector, force)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 154, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle not found
```
First occurrence: 2017-08-04T08:29:55.768141
Times recorded: 1
Latest occurrences:

- 2017-08-04T08:29:55.768141

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-openshift", line 450, in testImages
    b.click("tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle")
  File "/build/cockpit/test/common/testlib.py", line 169, in click
    self.call_js_func('ph_click', selector, force)
  File "/build/cockpit/test/common/testlib.py", line 154, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle not found
```
First occurrence: 2017-08-04T07:10:23.213157 | revision a685ed9eebcab6d6fe0da81e296fb21f64c3de01
Times recorded: 1
Latest occurrences:

- 2017-08-04T07:10:23.213157 | revision a685ed9eebcab6d6fe0da81e296fb21f64c3de01

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-openshift", line 450, in testImages
    b.click("tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle")
  File "/build/cockpit/test/common/testlib.py", line 169, in click
    self.call_js_func('ph_click', selector, force)
  File "/build/cockpit/test/common/testlib.py", line 154, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle not found
```
First occurrence: 2017-08-04T07:23:48.889244 | revision a685ed9eebcab6d6fe0da81e296fb21f64c3de01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7401-20170804-065454-a685ed9e-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-04T07:23:48.889244 | revision a685ed9eebcab6d6fe0da81e296fb21f64c3de01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7401-20170804-065454-a685ed9e-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-openshift", line 450, in testImages
    b.click("tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle")
  File "/build/cockpit/test/common/testlib.py", line 169, in click
    self.call_js_func('ph_click', selector, force)
  File "/build/cockpit/test/common/testlib.py", line 154, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: tbody[data-id='marmalade/busybee:0.x'] tr td.listing-ct-toggle not found
```
First occurrence: 2017-08-04T07:30:40.429119 | revision a685ed9eebcab6d6fe0da81e296fb21f64c3de01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7401-20170804-065151-a685ed9e-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-04T07:30:40.429119 | revision a685ed9eebcab6d6fe0da81e296fb21f64c3de01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7401-20170804-065151-a685ed9e-verify-rhel-7/log.html)
