### ISSUE TITLE
Setroubleshoot doesn't seem to be able to suggest any fixes

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#7638]
I can't seem to generate an error that sealert is able to suggest a fix for. I opened

https://github.com/fedora-selinux/setroubleshoot/issues/65

But for now let's make this a known issue.

**Comment by cockpituous** [comment]
verify/fedora-27
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "./verify/check-setroubleshoot", line 131, in testTroubleshootAlerts
    b.wait_in_text(panel_selector, "you can run restorecon")
  File "/home/pvolpe/code/cockpit/test/common/testlib.py", line 257, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/pvolpe/code/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/pvolpe/code/cockpit/test/common/testlib.py", line 825, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/home/pvolpe/code/cockpit/test/common/testlib.py", line 851, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-09-09T12:39:17.858930
Times recorded: 1
Latest occurrences:

- 2017-09-09T12:39:17.858930

**Comment by petervo** [comment]
Thanks to @bachradsusi for explaining to me why this is the way it is. I'll figure out a different way to test.
