### ISSUE TITLE
Resource graphs on server page stop scrolling frequently

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#79]
Resource graphs on server page stop scrolling frequently

**Comment by stefwalter** [comment]
No longer happens.

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_kdump.TestKdump)
#
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.

DevTools listening on ws://127.0.0.1:9953/devtools/browser/b437222d-eea6-4e1d-8203-01f656bdd14a
[1001/133820.270030:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/133820.303215:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/133820.309972:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: transport closed: disconnected
Unexpected journal messages:
audit: type=1400 audit(1569937306.576:500): avc:  denied  { write } for  pid=15714 comm="NetworkManager" path="/var/tmp/dracut.nUvFKh/systemd-cat" dev="dm-0" ino=395402 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.log
Wrote screenshot to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 789, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 967, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1569937306.576:500): avc:  denied  { write } for  pid=15714 comm="NetworkManager" path="/var/tmp/dracut.nUvFKh/systemd-cat" dev="dm-0" ino=395402 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0

not ok 53 testBasic (check_kdump.TestKdump) # duration: 356s
```
First occurrence: 2019-10-01T13:43:47.748851 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:43:47.748851 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
