### ISSUE TITLE
semanage broken on RHEL 7.5: policydb version 31 does not match my version range 15-30

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7904]
This is the known issue for https://bugzilla.redhat.com/show_bug.cgi?id=1500888, which affects `test/verify/check-connection TestConnection.testSocketPort` and two tests in `check-multi-machine`:

```
ERROR: policydb version 31 does not match my version range 15-30
ERROR: Unable to open policy //etc/selinux/targeted/policy/policy.31.
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 32, in <module>
    import seobject
  File "/usr/lib64/python2.7/site-packages/seobject/__init__.py", line 36, in <module>
    import sepolicy
  File "/usr/lib64/python2.7/site-packages/sepolicy/__init__.py", line 913, in <module>
    raise e
ValueError: Failed to read //etc/selinux/targeted/policy/policy.31 policy file
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 800, in testTroubleshooting
    m1.execute("! selinuxenabled || semanage port -a -t ssh_port_t -p tcp 2222")
  File "/build/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command '! selinuxenabled || semanage port -a -t ssh_port_t -p tcp 2222' returned non-zero exit status 1
```

**Comment by martinpitt** [comment]
verify/rhel-7-5
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSocketPort (__main__.TestConnection)
#
Warning: Permanently added '[127.0.0.2]:2201' (ECDSA) to the list of known hosts.
ERROR: policydb version 31 does not match my version range 15-30
ERROR: Unable to open policy //etc/selinux/targeted/policy/policy.31.
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 32, in <module>
    import seobject
  File "/usr/lib64/python2.7/site-packages/seobject/__init__.py", line 36, in <module>
    import sepolicy
  File "/usr/lib64/python2.7/site-packages/sepolicy/__init__.py", line 913, in <module>
    raise e
ValueError: Failed to read //etc/selinux/targeted/policy/policy.31 policy file
Traceback (most recent call last):
  File "test/verify/check-connection", line 172, in testSocketPort
    m.execute('! selinuxenabled || semanage port -m -t websm_port_t -p tcp 443')
  File "/home/martin/upstream/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command '! selinuxenabled || semanage port -m -t websm_port_t -p tcp 443' returned non-zero exit status 1

not ok 1 testSocketPort (__main__.TestConnection) # duration: 15s
Journal extracted to TestConnection-testSocketPort-rhel-7-5-127.0.0.2-2201-FAIL.log
```
First occurrence: 2017-10-18T10:13:20.952262
Times recorded: 1
Latest occurrences:

- 2017-10-18T10:13:20.952262

**Comment by cockpituous** [comment]
verify/rhel-7-5
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTroubleshootAlerts (check_setroubleshoot.TestSelinux)
#
Warning: Permanently added '[127.0.0.2]:2401' (ECDSA) to the list of known hosts.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 64, in testTroubleshootAlerts
    b.wait_in_text("body", "No SELinux alerts.")
  File "/build/cockpit/test/common/testlib.py", line 257, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 825, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 851, in _invoke
    raise Error(res['error'])
Error: timeout


not ok 71 testTroubleshootAlerts (check_setroubleshoot.TestSelinux) # duration: 81s
Wrote TestSelinux-testTroubleshootAlerts-rhel-7-5-127.0.0.2-2401-FAIL.png
Wrote TestSelinux-testTroubleshootAlerts-rhel-7-5-127.0.0.2-2401-FAIL.html
Journal extracted to TestSelinux-testTroubleshootAlerts-rhel-7-5-127.0.0.2-2401-FAIL.log
```
First occurrence: 2017-10-18T17:28:58.713591 | revision abbc7920e62dccdbd849b34e0179bdfd178fee2f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7887-20171018-171616-abbc7920-verify-rhel-7-5/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-18T17:28:58.713591 | revision abbc7920e62dccdbd849b34e0179bdfd178fee2f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7887-20171018-171616-abbc7920-verify-rhel-7-5/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-5
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTroubleshooting (check_multi_machine.TestMultiMachine)
#
Warning: Permanently added '[127.0.0.2]:2301' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2303' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2302' (ECDSA) to the list of known hosts.
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"kernel.all.cpu.nice","units":"millisec","derive":"rate"},{"name":"kernel.all.cpu.user","units":"millisec","derive":"rate"},{"name":"kernel.all.cpu.sys","units":"millisec","derive":"rate"}],"host":"localhost","timestamp":-4749,"limit":1,"command":"open","channel":"1:2!10","group":"cockpit1:localhost/dashboard"}
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"kernel.all.cpu.nice","units":"millisec","derive":"rate"},{"name":"kernel.all.cpu.user","units":"millisec","derive":"rate"},{"name":"kernel.all.cpu.sys","units":"millisec","derive":"rate"}],"host":"10.111.113.2","timestamp":-301749,"limit":300,"command":"open","channel":"1:2!11","group":"cockpit1:localhost/dashboard"}
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"mem.util.used","units":"bytes"}],"host":"localhost","timestamp":-4750,"limit":1,"command":"open","channel":"1:2!12","group":"cockpit1:localhost/dashboard"}
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"mem.util.used","units":"bytes"}],"host":"10.111.113.2","timestamp":-301750,"limit":300,"command":"open","channel":"1:2!13","group":"cockpit1:localhost/dashboard"}
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"network.interface.total.bytes","units":"bytes","derive":"rate"}],"omit-instances":["lo"],"host":"localhost","timestamp":-4750,"limit":1,"command":"open","channel":"1:2!14","group":"cockpit1:localhost/dashboard"}
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"network.interface.total.bytes","units":"bytes","derive":"rate"}],"omit-instances":["lo"],"host":"10.111.113.2","timestamp":-301750,"limit":300,"command":"open","channel":"1:2!15","group":"cockpit1:localhost/dashboard"}
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"disk.dev.total_bytes","units":"bytes","derive":"rate"}],"host":"localhost","timestamp":-4751,"limit":1,"command":"open","channel":"1:2!16","group":"cockpit1:localhost/dashboard"}
> transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"disk.dev.total_bytes","units":"bytes","derive":"rate"}],"host":"10.111.113.2","timestamp":-301751,"limit":300,"command":"open","channel":"1:2!17","group":"cockpit1:localhost/dashboard"}
> cat: *.pub: No such file or directory

> failed to list keys in home directory: cat: *.pub: No such file or directory
> Login failed
> cat: *.pub: No such file or directory

> failed to list keys in home directory: cat: *.pub: No such file or directory
> Login failed
ERROR: policydb version 31 does not match my version range 15-30
ERROR: Unable to open policy //etc/selinux/targeted/policy/policy.31.
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 32, in <module>
    import seobject
  File "/usr/lib64/python2.7/site-packages/seobject/__init__.py", line 36, in <module>
    import sepolicy
  File "/usr/lib64/python2.7/site-packages/sepolicy/__init__.py", line 913, in <module>
    raise e
ValueError: Failed to read //etc/selinux/targeted/policy/policy.31 policy file
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 800, in testTroubleshooting
    m1.execute("! selinuxenabled || semanage port -a -t ssh_port_t -p tcp 2222")
  File "/build/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command '! selinuxenabled || semanage port -a -t ssh_port_t -p tcp 2222' returned non-zero exit status 1

not ok 13 testTroubleshooting (check_multi_machine.TestMultiMachine) # duration: 75s
Wrote TestMultiMachine-testTroubleshooting-rhel-7-5-127.0.0.2-2301-FAIL.png
Wrote TestMultiMachine-testTroubleshooting-rhel-7-5-127.0.0.2-2301-FAIL.html
Wrote TestMultiMachine-testTroubleshooting-rhel-7-5-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMultiMachine-testTroubleshooting-rhel-7-5-127.0.0.2-2301-FAIL.log
Journal extracted to TestMultiMachine-testTroubleshooting-rhel-7-5-127.0.0.2-2303-FAIL.log
Journal extracted to TestMultiMachine-testTroubleshooting-rhel-7-5-127.0.0.2-2302-FAIL.log
```
First occurrence: 2017-10-19T10:50:49.301252 | revision 978a72d8f69e888ffacd364413dd170985cafdb0, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7887-20171019-102222-978a72d8-verify-rhel-7-5/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-19T10:50:49.301252 | revision 978a72d8f69e888ffacd364413dd170985cafdb0, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7887-20171019-102222-978a72d8-verify-rhel-7-5/log.html)
