### ISSUE TITLE
ubuntu 17.10: hotplugging virtio disk fails

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7977]
Downstream bug: https://launchpad.net/bugs/1726804 . Fix is already in artful-proposed, so our next image rebuild in a few days should pick it up.

This makes `test/verify/check-machines -stv TestMachines.testDisks` fail:
```
error: internal error: unable to execute QEMU command 'device_add': Property 'virtio-blk-device.drive' can't find value 'drive-virtio-disk2'
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 374, in testDisks
    m.execute("virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc") # attach to the virtio bus instead of ide
  File "/build/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc' returned non-zero exit status 1
```

**Comment by martinpitt** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDisks (__main__.TestMachines)
#
Warning: Permanently added '[127.0.0.2]:2201' (ECDSA) to the list of known hosts.
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8): No such file or directory
Libvirt version does not support disk statistics
error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Property 'virtio-blk-device.drive' can't find value 'drive-virtio-disk2'
Traceback (most recent call last):
  File "test/verify/check-machines", line 374, in testDisks
    m.execute("virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc") # attach to the virtio bus instead of ide
  File "/home/martin/upstream/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc' returned non-zero exit status 1

not ok 1 testDisks (__main__.TestMachines) # duration: 88s
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2201-FAIL.png
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2201-FAIL.html
Journal extracted to TestMachines-testDisks-ubuntu-stable-127.0.0.2-2201-FAIL.log
```
First occurrence: 2017-10-26T23:39:15.056908
Times recorded: 1
Latest occurrences:

- 2017-10-26T23:39:15.056908

**Comment by cockpituous** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDisks (check_machines.TestMachines)
#
Warning: Permanently added '[127.0.0.2]:2801' (ECDSA) to the list of known hosts.
Libvirt version does not support disk statistics
error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Property 'virtio-blk-device.drive' can't find value 'drive-virtio-disk2'
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 374, in testDisks
    m.execute("virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc") # attach to the virtio bus instead of ide
  File "/build/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc' returned non-zero exit status 1

not ok 163 testDisks (check_machines.TestMachines) # duration: 97s
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2801-FAIL.png
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2801-FAIL.html
Journal extracted to TestMachines-testDisks-ubuntu-stable-127.0.0.2-2801-FAIL.log
```
First occurrence: 2017-10-28T00:02:25.778211 | revision 3127ce8186cd4fb1f4423fa7fc87b7a536c23a17, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7959-20171027-235353-3127ce81-verify-ubuntu-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-28T00:02:25.778211 | revision 3127ce8186cd4fb1f4423fa7fc87b7a536c23a17, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7959-20171027-235353-3127ce81-verify-ubuntu-stable/log.html)

**Comment by cockpituous** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDisks (check_machines.TestMachines)
#
Warning: Permanently added '[127.0.0.2]:2201' (ECDSA) to the list of known hosts.
Libvirt version does not support disk statistics
error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Property 'virtio-blk-device.drive' can't find value 'drive-virtio-disk2'
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 374, in testDisks
    m.execute("virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc") # attach to the virtio bus instead of ide
  File "/build/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc' returned non-zero exit status 1

not ok 3 testDisks (check_machines.TestMachines) # duration: 124s
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2201-FAIL.png
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2201-FAIL.html
Journal extracted to TestMachines-testDisks-ubuntu-stable-127.0.0.2-2201-FAIL.log
```
First occurrence: 2017-10-31T05:45:00.439717 | revision adcbdd3ac1aa663a75fd9dc15278c783fe571f5f, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20171031-051818-adcbdd3a-verify-ubuntu-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-31T05:45:00.439717 | revision adcbdd3ac1aa663a75fd9dc15278c783fe571f5f, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20171031-051818-adcbdd3a-verify-ubuntu-stable/log.html)

**Comment by cockpituous** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDisks (check_machines.TestMachines)
#
Warning: Permanently added '[127.0.0.2]:2801' (ECDSA) to the list of known hosts.
Libvirt version does not support disk statistics
error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Property 'virtio-blk-device.drive' can't find value 'drive-virtio-disk2'
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 374, in testDisks
    m.execute("virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc") # attach to the virtio bus instead of ide
  File "/build/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc' returned non-zero exit status 1

not ok 3 testDisks (check_machines.TestMachines) # duration: 162s
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2801-FAIL.png
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2801-FAIL.html
Journal extracted to TestMachines-testDisks-ubuntu-stable-127.0.0.2-2801-FAIL.log
```
First occurrence: 2017-11-02T09:11:36.923321 | revision dcc130ea8332efd19d0c68918bb8f1cb4b26375c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7972-20171102-083737-dcc130ea-verify-ubuntu-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2017-11-02T09:11:36.923321 | revision dcc130ea8332efd19d0c68918bb8f1cb4b26375c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7972-20171102-083737-dcc130ea-verify-ubuntu-stable/log.html)

**Comment by cockpituous** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDisks (check_machines.TestMachines)
#
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Libvirt version does not support disk statistics
error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Property 'virtio-blk-device.drive' can't find value 'drive-virtio-disk2'
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 374, in testDisks
    m.execute("virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc") # attach to the virtio bus instead of ide
  File "/build/cockpit/test/common/testvm.py", line 468, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'virsh attach-disk subVmTest1 /var/lib/libvirt/images/image3.img vdc' returned non-zero exit status 1

not ok 3 testDisks (check_machines.TestMachines) # duration: 89s
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2601-FAIL.png
Wrote TestMachines-testDisks-ubuntu-stable-127.0.0.2-2601-FAIL.html
Journal extracted to TestMachines-testDisks-ubuntu-stable-127.0.0.2-2601-FAIL.log
```
First occurrence: 2017-11-03T17:01:03.694266 | revision fa7a9a23a999ebb2962b47574c8eaaa5f9968004, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7580-20171103-164242-fa7a9a23-verify-ubuntu-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2017-11-03T17:01:03.694266 | revision fa7a9a23a999ebb2962b47574c8eaaa5f9968004, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7580-20171103-164242-fa7a9a23-verify-ubuntu-stable/log.html)
