### ISSUE TITLE
Make sure that all resources are loaded upfront

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#80]
The webapp is supposed to be delivered by the server and then run independently. This means that we should load all resources that it might need, such as images.

For example, the (multi-server) dashboard puts a (ugly) "retry" icon on the page when a connection to a server is lost. However, it might be that this icon can't be loaded anymore when connectivity to the management server is gone completely.

**Comment by stefwalter** [comment]
@andreasn We should instead do this by avoiding use of images, and use them from the fonts instead.

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNegotiate (check_realms.TestKerberos)
#
++ seq 1 20
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ break
+ realm join -vU admin cockpit.lan
+ echo foobarfoo
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2019-09-17 13:59:51
    Valid Until: 2039-09-17 13:59:51

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful
This program will set up FreeIPA client.
Version 4.8.1


Using default chrony configuration.
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * Successfully enrolled machine in realm
++ seq 1 20
+ for x in $(seq 1 20)
+ KRB5_TRACE=/dev/stderr
+ kinit -f admin@COCKPIT.LAN
+ echo foobarfoo
[8129] 1569936101.87497: Getting initial credentials for admin@COCKPIT.LAN
[8129] 1569936101.87499: Sending unauthenticated request
[8129] 1569936101.87500: Sending request (180 bytes) to COCKPIT.LAN
[8129] 1569936101.87501: Initiating TCP connection to stream 10.111.112.100:88
[8129] 1569936101.87502: Sending TCP request to stream 10.111.112.100:88
[8129] 1569936101.87503: Received answer (524 bytes) from stream 10.111.112.100:88
[8129] 1569936101.87504: Terminating TCP connection to stream 10.111.112.100:88
[8129] 1569936101.87505: Response was from master KDC
[8129] 1569936101.87506: Received error from KDC: -1765328359/Additional pre-authentication required
[8129] 1569936101.87509: Preauthenticating using KDC method data
[8129] 1569936101.87510: Processing preauth types: PA-PK-AS-REQ (16), PA-PK-AS-REP_OLD (15), PA-PK-AS-REQ_OLD (14), PA-FX-FAST (136), PA-ETYPE-INFO2 (19), PA-PKINIT-KX (147), PA-SPAKE (151), PA-ENC-TIMESTAMP (2), PA_AS_FRESHNESS (150), PA-FX-COOKIE (133)
[8129] 1569936101.87511: Selected etype info: etype aes256-cts, salt "l:K,,[Lz]sB#.N*/", params ""
[8129] 1569936101.87512: Received cookie: MIT1\x00\x00\x00\x01\xcf\xd1\xda\xab\x0b,j\xb8d\xa4"\xa92\xbf\x84 \xd50\xe3`$q\xc6\xf3\xf7^\x051\x09BW\xe0r\xc0\x13\x97@1%|5\xb3\xaa.\x15\xb5\\xd7\xf8f\x87\x05\xe1\x82\xcf\xdf\xf5y\xe7\xe9\x83\x1f\x05lYh8\x0b\x85\x97K\x9b\xef\x82}B\x85_\xbe\xb0\xec\xe4@\xe4\x1e\x0b\xdb\xca\x08\xef&\xfe@q$%\xdb\xb5^\x0crD=\xd6\xc8m\xaf\x0a\x0f\x15@\xcd\xe0\x09\xf6\x94/\xf2]\xba=\xf9\xb0WL\xfd}\xee\xe5\xae
[8129] 1569936101.87513: SPAKE challenge received with group 1, pubkey 8779E105CAF365CDFEEFBC6BCD098B197DA86AEDBC857598B29974DC9D82A086
[8129] 1569936101.87514: SPAKE key generated with pubkey 1A5351ED9DF7028D164089F22346AC0C7600BA86DE7C0ABE8C1DF013AAAE8378
[8129] 1569936101.87515: SPAKE algorithm result: 9C89390CB5F1737F4DB7E64752CC2AEC2C795601DBC50306358639F7788FC201
[8129] 1569936101.87516: SPAKE final transcript hash: 19708CBDDB08ED3BB81645E6E5B87329C017F7000A59E7884A7C34866164C9F7
[8129] 1569936101.87517: Sending SPAKE response
[8129] 1569936101.87518: Preauth module spake (151) (real) returned: 0/Success
[8129] 1569936101.87519: Produced preauth for next request: PA-FX-COOKIE (133), PA-SPAKE (151)
[8129] 1569936101.87520: Sending request (439 bytes) to COCKPIT.LAN
[8129] 1569936101.87521: Initiating TCP connection to stream 10.111.112.100:88
[8129] 1569936101.87522: Sending TCP request to stream 10.111.112.100:88
[8129] 1569936101.87523: Received answer (724 bytes) from stream 10.111.112.100:88
[8129] 1569936101.87524: Terminating TCP connection to stream 10.111.112.100:88
[8129] 1569936101.87525: Response was from master KDC
[8129] 1569936101.87526: Processing preauth types: PA-ETYPE-INFO2 (19)
[8129] 1569936101.87527: Selected etype info: etype aes256-cts, salt "l:K,,[Lz]sB#.N*/", params ""
[8129] 1569936101.87528: Produced preauth for next request: (empty)
[8129] 1569936101.87529: AS key determined by preauth: aes256-cts/E3D6
[8129] 1569936101.87530: Decrypted AS reply; session key is: aes256-cts/6FEB
[8129] 1569936101.87531: FAST negotiation: available
[8129] 1569936101.87532: Initializing KCM:0 with default princ admin@COCKPIT.LAN
[8129] 1569936101.87533: Storing admin@COCKPIT.LAN -> krbtgt/COCKPIT.LAN@COCKPIT.LAN in KCM:0
[8129] 1569936101.87534: Storing config in KCM:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: fast_avail: yes
[8129] 1569936101.87535: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/fast_avail/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KCM:0
[8129] 1569936101.87536: Storing config in KCM:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: pa_type: 151
[8129] 1569936101.87537: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/pa_type/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KCM:0
+ break
+ grep -iq '^C\.utf'
+ locale -a
+ loc=C.UTF-8
+ type ipa
+ LC_ALL=C.UTF-8
+ ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN
+ ipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab
+ sed -i '/^sudoers:/ s/files sss/sss files/' /etc/nsswitch.conf
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin
+ break
+ getent passwd admin
+ chown -R admin /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin x0.cockpit.lan true
+ break

DevTools listening on ws://127.0.0.1:10195/devtools/browser/3de9c577-375a-473e-a427-96c6a0344f59
[1001/132155.820437:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1001/132155.822734:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1001/132155.826570:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Login failed
> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

Wrote screenshot to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2901-FAIL.html
Wrote JS log to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestKerberos-testNegotiate-fedora-31-127.0.0.2-2901-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2902-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-realms", line 517, in testNegotiate
    b.wait_popdown('troubleshoot-dialog')
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 420, in wait_popdown
    self.wait_not_visible('#' + id)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 385, in wait_not_visible
    self.wait_js_func('!ph_is_visible', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 342, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 339, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 175, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_visible("#troubleshoot-dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 226, 'columnNumber': 9, 'scriptId': '11', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '11', 'url': '', 'lineNumber': 225, 'columnNumber': 8}, {'functionName': '', 'scriptId': '11', 'url': '', 'lineNumber': 237, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:238:24', 'objectId': '{"injectedScriptId":2,"id":1}'}}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Login failed
warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-31&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

warning: Error opening directory '/home/admin/.ssh': No such file or directory
warning: --: line 25: cd: /home/admin/.ssh: No such file or directory


not ok 165 testNegotiate (check_realms.TestKerberos) # duration: 206s
```
First occurrence: 2019-10-01T13:23:07.603744 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
Times recorded: 1
Latest occurrences:

- 2019-10-01T13:23:07.603744 | revision ea7c9dd8599fae8aca8fa43c450848de6f803280
