### ISSUE TITLE
bots fail to upload images

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8022]
We currently have a [ton of failed image updates](https://github.com/cockpit-project/cockpit/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Abot) like #8000 that fail on uploading:
```
Saving...
Uploading...
Traceback (most recent call last):
  File "/build/cockpit/bots/image-create", line 220, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/build/cockpit/bots/image-upload', 'fedora-27']' returned non-zero exit status 7
# Task: image-refresh fedora-27
# Host: cockpit-tasks-jrpmt
```

There is no useful error message, so it doesn't immediately look like a token issue. It could be due to verifymachine{4,5} being down, but aren't these supposed to pick one of the ~ 30 running cockpit/image OpenShift pods?

**Comment by martinpitt** [comment]
There is an error message, it's just at an odd place in the logs. Examples:
```
curl: (7) Failed to connect to cockpit-tests port 8493: No route to host
image-upload: unable to upload image: https://209.132.184.69:8493/
```
All public images have exactly the same "cockpit-tests" name and IP, so there doesn't seem to be any round-robin/randomization going on. I. e. this is just image-upload's default store.

This IP is instance-69.cloud.fedoraproject.org, so indeed due to verifymachine*.

**Comment by martinpitt** [comment]
As none of our other cockpit-* machines are accessible from the public internet (only through the Red Hat  VPN), I am hesitant to change the default upload/download store to cockpit-11. @stefwalter, who can be contacted about reviving the two verifymachines? Despite the same name, https://cloud.fedoraproject.org is something else (cloud images, not cloud service).
