### ISSUE TITLE
bots get stuck on rebase failure, need to fail the test

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8223]
We have 40 bots running, and yet there are only three active ones:
```
❱❱❱ bots/tests-scan -vd
pull-8220   verify/debian-stable      174eb49    Testing in progress [cockpit-tasks-w5lts]
pull-8222   verify/debian-testing     9382be1    Testing in progress [cockpit-tasks-vlgg4]
pull-8220   verify/fedora-27          174eb49    Testing in progress [cockpit-tasks-bdlj7]
pull-7911   verify/ubuntu-stable      c74c226    9
pull-7911   verify/rhel-7-5           c74c226    9
pull-7911   verify/rhel-7             c74c226    9
pull-7911   verify/fedora-atomic      c74c226    9
pull-7911   verify/fedora-27          c74c226    9
pull-7911   verify/centos-7           c74c226    9
pull-7911   selenium/explorer         c74c226    9
pull-7911   selenium/chrome           c74c226    9
pull-8193   verify/ubuntu-stable      f99ce30    9
pull-8193   verify/ubuntu-1604        f99ce30    9
pull-8193   verify/fedora-i386        f99ce30    9
pull-8193   verify/fedora-atomic      f99ce30    9
pull-8193   verify/fedora-27          f99ce30    9
pull-8193   verify/debian-testing     f99ce30    9
pull-8193   selenium/firefox          f99ce30    9
pull-8193   selenium/explorer         f99ce30    9
pull-8193   container/kubernetes      f99ce30    9
```

I did a few spot checks on the others, and they all seem to get stuck in a loop:
```
HEAD is now at f99ce306... bots: Port bots to python3

+ TEST_NAME=pull-8193-20171206-224141

+ TEST_REVISION=f99ce306b73acc9b5fb471cdc322a3d289605dc5

+ bots/tests-invoke --rebase=master selenium/chrome pull/8193/head

From https://github.com/cockpit-project/cockpit

 * branch              refs/pull/8193/head -> FETCH_HEAD

From https://github.com/cockpit-project/cockpit

 * branch              master     -> FETCH_HEAD

 * branch              master     -> FETCH_HEAD

http://209.132.184.41/logs/pull-8193-20171206-224141-f99ce306-selenium-chrome/

First, rewinding head to replay your work on top of it...

Applying: containers: Fix out of tree builds for i386 unit-tests container

Applying: bots: Port bots to python3

error: Failed to merge in the changes.

Using index info to reconstruct a base tree...

M	bots/issue-scan

M	bots/task/__init__.py

M	bots/tests-invoke

M	bots/tests-scan

Falling back to patching base and 3-way merge...

Auto-merging bots/tests-scan

Auto-merging bots/tests-invoke

CONFLICT (content): Merge conflict in bots/tests-invoke

Auto-merging bots/task/__init__.py

CONFLICT (content): Merge conflict in bots/task/__init__.py

Auto-merging bots/issue-scan

Patch failed at 0002 bots: Port bots to python3

The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".

If you prefer to skip this patch, run "git rebase --skip" instead.

To check out the original branch and stop rebasing, run "git rebase --abort".

Testing f99ce306b73acc9b5fb471cdc322a3d289605dc5 for pull-8193-20171206-224141 with selenium/chrome on cockpit-tasks-0d1d2...

Rebasing onto origin/master ...

Traceback (most recent call last):

  File "bots/tests-invoke", line 169, in rebase

    subprocess.check_call([ "git", "rebase", origin_base ])

  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['git', 'rebase', 'origin/master']' returned non-zero exit status 128.

{"github": {"token": "", "requests": [{"method": "POST", "resource": "/repos/cockpit-project/cockpit/statuses/f99ce306b73acc9b5fb471cdc322a3d289605dc5", "data": {"state": "pending", "context": "selenium/chrome", "description": "Testing in progress [cockpit-tasks-0d1d2]", "target_url": ":link"}}], "watches": [{"resource": "/repos/cockpit-project/cockpit/commits/f99ce306b73acc9b5fb471cdc322a3d289605dc5/status", "result": {"statuses": [{"context": "selenium/chrome", "description": "Testing in progress [cockpit-tasks-0d1d2]", "target_url": ":link"}]}}]}, "revision": "f99ce306b73acc9b5fb471cdc322a3d289605dc5", "link": "log.html", "extras": ["https://raw.githubusercontent.com/cockpit-project/cockpit/master/bots/task/log.html"], "onaborted": {"github": {"token": "", "requests": [{"method": "POST", "resource": "/repos/cockpit-project/cockpit/statuses/f99ce306b73acc9b5fb471cdc322a3d289605dc5", "data": {"state": "error", "context": "selenium/chrome", "description": "Aborted without status", "target_url": ":link"}}]}}, "base": "dfec04b61a43961104e1a2547d3300e6731b1893"}

tests-invoke: Rebase failed

++ shuf -i 60-600 -n 1
+ sleep 524
```
But then they don't send a "failed" status message to github, so the test status stays at "Rebase". This causes an eternal retry loop and starving all other tests from running.

**Comment by martinpitt** [comment]
I'm staring at bots/tests-invoke and I can't immediately see the error. In `def rebase()` we are supposed to handle this with
```python
                subprocess.check_call([ "git", "rebase", origin_base ])
        except subprocess.CalledProcessError:
            subprocess.call([ "git", "rebase", "--abort" ])
            traceback.print_exc()
            return "Rebase failed"
````
and then `run()` propagates that string error so that `stop_publishing()` should see it. But quite obvioulsy the return value is `None` so that `stop_publishing()` does
```python
        elif ret is None:
            message = "Rebased"
            mark_respawn()
```
which is exactly the status of #8193. As the output does show `tests-invoke: Rebase failed`, the `except:` apparently works, and the traceback is from `print_exc()`.

**Comment by martinpitt** [comment]
Actually, there is no proof yet that this affects master - it could be that there's something wrong in the Python 3 port in #8193 only, and since today the bots always use the code from PRs. This means that any error introduced in a PR can DoS our bots now (but that's hard to avoid, and after all testing the bots in PRs is a great advantage). I don't see anything wrong with the changed tests-invoke code in that PR, though.

**Comment by martinpitt** [comment]
This could have something to do with `CONFLICT (content): Merge conflict in bots/tests-invoke` and trying to run the py2 code through py3? Although I'd expect a massively different exception in that case (e. g. `basestring` isn't even defined in py3)

**Comment by martinpitt** [comment]
#8226 removes the `mark_respawn()` logic, which should fix this issue.

**Comment by martinpitt** [comment]
Closing this as it was only a fallout from the Python3 port, and now the bots run into different trouble. Let's debug in #8226.
