### ISSUE TITLE
check-openshift TestOpenshift.testNodeNavigation is flaky

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8364]
This test fails rather often on our infrastructure. This reproduces locally (with a loop) too:
```
-> wait: ph_is_visible("#machine-troubleshoot")
<- {u'type': u'undefined'}
-> ph_click("#machine-troubleshoot",false)
<- {u'type': u'string', u'value': u'#machine-troubleshoot is not visible'}
Traceback (most recent call last):
  File "/home/martin/upstream/cockpit/test/verify/kubelib.py", line 793, in testNodeNavigation
    b.click('#machine-troubleshoot')
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 202, in click
    self.call_js_func('ph_click', selector, force)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 187, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 173, in eval_js
    self.raise_cdp_exception("eval_js", code, result["exceptionDetails"])
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: eval_js(ph_click("#machine-troubleshoot",false)): #machine-troubleshoot is not visible
```

So this is a little  odd, as we explicitly do the `wait_visible()` before clicking. However, in my current failure the screenshot looks like this:

![testopenshift-testnodenavigation-rhel-7-5-127 0 0 2-2201-fail](https://user-images.githubusercontent.com/200109/34599967-89225678-f1f5-11e7-9619-ba61b2457eca.png)

i. e. it appears like the  troubleshoot button was visible for a bit, and then goes back to being hidden? The dumped HTML agrees:
```html
            <div class="curtains-ct blank-slate-pf" hidden="" style="display: block;">
              <div class="blank-slate-pf-icon">
                <div class="spinner spinner-lg" hidden="" style="display: block;"></div>
                <i class="fa fa-exclamation-circle" style="display: none;"></i>
              </div>
              <h1>Connecting to the machine</h1>
              <p></p>
              <div class="blank-slate-pf-main-action">
                <button id="machine-reconnect" class="btn btn-primary btn-lg" style="display: none;">Reconnect</button>
                <button id="machine-troubleshoot" class="btn btn-primary btn-lg" style="display: none;">Troubleshoot</button>
              </div>
            </div>
```

**Comment by martinpitt** [comment]
Waiting for the spinner to go away first seems to help:
```diff
         b.switch_to_top()
+        # the troubleshoot button by itself shows/hides multiple times, wait for "Connecting.." to disappear first
+        b.wait_not_visible(".curtains-ct .spinner")
         b.wait_visible("#machine-troubleshoot")
```
I've been running this in two parallel
```
while TEST_OS=rhel-7-5 test/verify/check-openshift TestOpenshift.testNodeNavigation -tv; do sleep 1; done
```
loops, and it seems stable now. I'll post this as a PR.
