### ISSUE TITLE
SSH sessions are in a private "mnt" namespace

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8389]
Upstream bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886811

When `check-storage-mounting` executes `umount` via SSH, this does not affect the UDisks2 daemon anymore.

```
Traceback (most recent call last):
  File "./test/verify/check-storage-mounting", line 118, in testMounting
    b.wait_not_in_text("#storage_mounts", mount_point_bar)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 302, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 266, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 263, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 166, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_in_text("#storage_mounts","/run/bar")): condition did not become true
```

**Comment by mvollmer** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMounting (__main__.TestStorage)
#
Warning: Permanently added '[127.0.0.2]:2201' (ECDSA) to the list of known hosts.
Started /usr/bin/chromium-browser (pid 10215) on port 9447

DevTools listening on ws://127.0.0.1:9447/devtools/browser/cf87c6f7-5f3d-449e-85d3-b0a5bf2e3cc5
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 401 (Authentication failed)","timestamp":1515581453758.95,"url":"http://127.0.0.2:9091/cockpit/login","networkRequestId":"10270.8"}
Traceback (most recent call last):
  File "./test/verify/check-storage-mounting", line 118, in testMounting
    b.wait_not_in_text("#storage_mounts", mount_point_bar)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 302, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 266, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 263, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 166, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_in_text("#storage_mounts","/run/bar")): condition did not become true

not ok 1 testMounting (__main__.TestStorage) # duration: 74s
Wrote screenshot to TestStorage-testMounting-debian-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testMounting-debian-testing-127.0.0.2-2201-FAIL.html
Journal extracted to TestStorage-testMounting-debian-testing-127.0.0.2-2201-FAIL.log
Killing browser (pid 10215)
```
First occurrence: 2018-01-10T12:52:01.392553
Times recorded: 1
Latest occurrences:

- 2018-01-10T12:52:01.392553

**Comment by martinpitt** [comment]
This was a regression in systemd 236, and got fixed upstream in https://github.com/systemd/systemd/pull/7763 .

**Comment by mvollmer** [comment]
> This was a regression in systemd 236, and got fixed upstream in systemd/systemd#7763 .

Cool, thanks for digging this out.

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUsed (check_storage_used.TestStorage)
#
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Started /usr/bin/chromium-browser (pid 627768) on port 9339
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9339/devtools/browser/07417e73-538a-4e0d-a9c1-0184c08671ab
[0112/003328.426828:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 627909: Permission denied (13)
[0112/003329.550616:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 628027: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 401 (Authentication failed)","timestamp":1515717210009.79,"url":"http://127.0.0.2:9391/cockpit/login","networkRequestId":"628027.8"}
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-used", line 48, in testUsed
    self.content_tab_wait_in_info(2, 1, "Mounted At", "/mnt")
  File "/build/cockpit/test/verify/storagelib.py", line 162, in content_tab_wait_in_info
    self.retry(setup, check, teardown)
  File "/build/cockpit/test/verify/storagelib.py", line 69, in retry
    self.browser.wait(step)
  File "/build/cockpit/test/common/testlib.py", line 247, in wait
    val = predicate()
  File "/build/cockpit/test/verify/storagelib.py", line 63, in step
    if check():
  File "/build/cockpit/test/verify/storagelib.py", line 142, in check
    if not b.is_present(row + ".open"):
  File "/build/cockpit/test/common/testlib.py", line 265, in is_present
    return self.call_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 185, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 169, in eval_js
    silent=False, awaitPromise=True, returnByValue=True, no_trace=no_trace)
  File "/build/cockpit/test/common/cdp.py", line 85, in invoke
    res = self.command(cmd)
  File "/build/cockpit/test/common/cdp.py", line 97, in command
    line = self._driver.stdout.readline()
  File "/build/cockpit/test/common/testlib.py", line 242, in alarm_handler
    raise Error('timed out waiting for predicate to become true')
Error: timed out waiting for predicate to become true

not ok 84 testUsed (check_storage_used.TestStorage) # duration: 89s
Wrote screenshot to TestStorage-testUsed-debian-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorage-testUsed-debian-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorage-testUsed-debian-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorage-testUsed-debian-testing-127.0.0.2-2501-FAIL.log
Killing browser (pid 627768)
```
First occurrence: 2018-01-12T00:34:43.546814 | revision cceab54ec3f701c295160063d3c0b00fc6e66700, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8314-20180112-002222-cceab54e-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-01-12T00:34:43.546814 | revision cceab54ec3f701c295160063d3c0b00fc6e66700, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8314-20180112-002222-cceab54e-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMounting (check_storage_mounting.TestStorage)
#
Warning: Permanently added '[127.0.0.2]:2401' (ECDSA) to the list of known hosts.
Started /usr/bin/chromium-browser (pid 628880) on port 9426
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9426/devtools/browser/49137221-3baf-49d6-818e-3a1835ffadbd
[0112/003351.743062:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 628952: Permission denied (13)
[0112/003352.797053:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 628980: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 401 (Authentication failed)","timestamp":1515717233129.01,"url":"http://127.0.0.2:9291/cockpit/login","networkRequestId":"628980.8"}
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-mounting", line 118, in testMounting
    b.wait_not_in_text("#storage_mounts", mount_point_bar)
  File "/build/cockpit/test/common/testlib.py", line 298, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 262, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 259, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 165, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_in_text("#storage_mounts","/run/bar")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9291/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'628980.8', u'timestamp': 1515717233129.01}

not ok 76 testMounting (check_storage_mounting.TestStorage) # duration: 85s
Wrote screenshot to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.log
Killing browser (pid 628880)
```
First occurrence: 2018-01-12T00:35:02.627191 | revision cceab54ec3f701c295160063d3c0b00fc6e66700, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8314-20180112-002222-cceab54e-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-01-12T00:35:02.627191 | revision cceab54ec3f701c295160063d3c0b00fc6e66700, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8314-20180112-002222-cceab54e-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUsed (check_storage_used.TestStorage)
#
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Started /usr/bin/chromium-browser (pid 308045) on port 9879

DevTools listening on ws://127.0.0.1:9879/devtools/browser/403829b1-bcb6-40b1-a4a4-9a0e98cad396
[0112/122205.922493:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 308191: Permission denied (13)
[0112/122206.875126:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 308344: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 401 (Authentication failed)","timestamp":1515759727198.69,"url":"http://127.0.0.2:9491/cockpit/login","networkRequestId":"308344.8"}
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-used", line 48, in testUsed
    self.content_tab_wait_in_info(2, 1, "Mounted At", "/mnt")
  File "/build/cockpit/test/verify/storagelib.py", line 162, in content_tab_wait_in_info
    self.retry(setup, check, teardown)
  File "/build/cockpit/test/verify/storagelib.py", line 69, in retry
    self.browser.wait(step)
  File "/build/cockpit/test/common/testlib.py", line 247, in wait
    val = predicate()
  File "/build/cockpit/test/verify/storagelib.py", line 63, in step
    if check():
  File "/build/cockpit/test/verify/storagelib.py", line 142, in check
    if not b.is_present(row + ".open"):
  File "/build/cockpit/test/common/testlib.py", line 265, in is_present
    return self.call_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 185, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 169, in eval_js
    silent=False, awaitPromise=True, returnByValue=True, no_trace=no_trace)
  File "/build/cockpit/test/common/cdp.py", line 85, in invoke
    res = self.command(cmd)
  File "/build/cockpit/test/common/cdp.py", line 97, in command
    line = self._driver.stdout.readline()
  File "/build/cockpit/test/common/testlib.py", line 242, in alarm_handler
    raise Error('timed out waiting for predicate to become true')
Error: timed out waiting for predicate to become true

not ok 88 testUsed (check_storage_used.TestStorage) # duration: 90s
Screenshot not available
Wrote HTML dump to TestStorage-testUsed-debian-testing-127.0.0.2-2601-FAIL.html
Wrote JS log to TestStorage-testUsed-debian-testing-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestStorage-testUsed-debian-testing-127.0.0.2-2601-FAIL.log
Killing browser (pid 308045)
```
First occurrence: 2018-01-12T12:23:19.791734 | revision 3c202d9ed1349f55dcd0b503138485d13f565c9f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8410-20180112-121111-3c202d9e-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-01-12T12:23:19.791734 | revision 3c202d9ed1349f55dcd0b503138485d13f565c9f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8410-20180112-121111-3c202d9e-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMounting (check_storage_mounting.TestStorage)
#
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Started /usr/bin/chromium-browser (pid 309050) on port 9809

DevTools listening on ws://127.0.0.1:9809/devtools/browser/94e161f7-cd00-47c9-b355-33c2335d521d
[0112/122226.633988:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 309121: Permission denied (13)
[0112/122227.722061:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 309195: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 401 (Authentication failed)","timestamp":1515759748207.43,"url":"http://127.0.0.2:9391/cockpit/login","networkRequestId":"309195.8"}
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-mounting", line 118, in testMounting
    b.wait_not_in_text("#storage_mounts", mount_point_bar)
  File "/build/cockpit/test/common/testlib.py", line 298, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 262, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 259, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 165, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_in_text("#storage_mounts","/run/bar")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9391/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'309195.8', u'timestamp': 1515759748207.43}

not ok 78 testMounting (check_storage_mounting.TestStorage) # duration: 85s
Wrote screenshot to TestStorage-testMounting-debian-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorage-testMounting-debian-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorage-testMounting-debian-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorage-testMounting-debian-testing-127.0.0.2-2501-FAIL.log
Killing browser (pid 309050)
```
First occurrence: 2018-01-12T12:23:38.315913 | revision 3c202d9ed1349f55dcd0b503138485d13f565c9f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8410-20180112-121111-3c202d9e-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-01-12T12:23:38.315913 | revision 3c202d9ed1349f55dcd0b503138485d13f565c9f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8410-20180112-121111-3c202d9e-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMounting (check_storage_mounting.TestStorage)
#

DevTools listening on ws://127.0.0.1:10200/devtools/browser/2fe45664-cdc5-4447-9640-dba21ce71a4a
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-mounting", line 118, in testMounting
    b.wait_not_in_text("#storage_mounts", mount_point_bar)
  File "/build/cockpit/test/common/testlib.py", line 300, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 264, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 261, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_in_text("#storage_mounts","/run/bar")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9291/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'15559.8', u'timestamp': 1516114954184.55}

not ok 16 testMounting (check_storage_mounting.TestStorage) # duration: 88s
Wrote screenshot to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testMounting-debian-testing-127.0.0.2-2401-FAIL.log
```
First occurrence: 2018-01-16T15:03:46.605176 | revision 1cff05fccc67f288fa1d187119b992c0de795858, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8414-20180116-134343-1cff05fc-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-01-16T15:03:46.605176 | revision 1cff05fccc67f288fa1d187119b992c0de795858, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8414-20180116-134343-1cff05fc-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUsed (check_storage_used.TestStorage)
#

DevTools listening on ws://127.0.0.1:9774/devtools/browser/8aa692bb-017b-49b5-a1a7-ffa7ce0afee4
[0117/111157.039827:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 2888: Permission denied (13)
[0117/111157.955051:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 2933: Permission denied (13)
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-used", line 48, in testUsed
    self.content_tab_wait_in_info(2, 1, "Mounted At", "/mnt")
  File "/build/cockpit/test/verify/storagelib.py", line 162, in content_tab_wait_in_info
    self.retry(setup, check, teardown)
  File "/build/cockpit/test/verify/storagelib.py", line 69, in retry
    self.browser.wait(step)
  File "/build/cockpit/test/common/testlib.py", line 249, in wait
    val = predicate()
  File "/build/cockpit/test/verify/storagelib.py", line 63, in step
    if check():
  File "/build/cockpit/test/verify/storagelib.py", line 156, in check
    if not b.is_present(cell):
  File "/build/cockpit/test/common/testlib.py", line 267, in is_present
    return self.call_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 187, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 171, in eval_js
    silent=False, awaitPromise=True, returnByValue=True, no_trace=no_trace)
  File "/build/cockpit/test/common/cdp.py", line 84, in invoke
    res = self.command(cmd)
  File "/build/cockpit/test/common/cdp.py", line 96, in command
    line = self._driver.stdout.readline()
  File "/build/cockpit/test/common/testlib.py", line 244, in alarm_handler
    raise Error('timed out waiting for predicate to become true')
Error: timed out waiting for predicate to become true

not ok 107 testUsed (check_storage_used.TestStorage) # duration: 87s
Screenshot not available
Wrote HTML dump to TestStorage-testUsed-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorage-testUsed-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testUsed-debian-testing-127.0.0.2-2301-FAIL.log
```
First occurrence: 2018-01-17T11:13:11.602558 | revision 5af93c4982658b63b208ec1ed076290c05577523, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8433-20180117-110303-5af93c49-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-01-17T11:13:11.602558 | revision 5af93c4982658b63b208ec1ed076290c05577523, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8433-20180117-110303-5af93c49-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMounting (check_storage_mounting.TestStorage)
#

DevTools listening on ws://127.0.0.1:9431/devtools/browser/1d05665a-b577-498b-a4db-99726d0689dd
[0117/111223.417161:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 4097: Permission denied (13)
[0117/111224.413958:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 4144: Permission denied (13)
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-mounting", line 118, in testMounting
    b.wait_not_in_text("#storage_mounts", mount_point_bar)
  File "/build/cockpit/test/common/testlib.py", line 300, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 264, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 261, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_in_text("#storage_mounts","/run/bar")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9091/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'4144.8', u'timestamp': 1516187544818.43}

not ok 97 testMounting (check_storage_mounting.TestStorage) # duration: 82s
Wrote screenshot to TestStorage-testMounting-debian-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testMounting-debian-testing-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testMounting-debian-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testMounting-debian-testing-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-01-17T11:13:32.244241 | revision 5af93c4982658b63b208ec1ed076290c05577523, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8433-20180117-110303-5af93c49-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-01-17T11:13:32.244241 | revision 5af93c4982658b63b208ec1ed076290c05577523, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8433-20180117-110303-5af93c49-verify-debian-testing/log.html)
