### ISSUE TITLE
naughty overrides are broken due to github comment flooding

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8417]
https://fedorapeople.org/groups/cockpit/logs/pull-8403-20180111-150909-000c71fe-verify-fedora-i386/log.html failed left and right because naughty overrides  don't get taken into account any more. This is due to
```
❱❱❱ cat /tmp/out | bots/tests-policy  verify/fedora-i386
issues/7636/comments
{"message":"Commenting is disabled on issues with more than 2500 comments","documentation_url":"https://developer.github.com/v3/issues/comments/#create-a-comment"}
Traceback (most recent call last):
  File "bots/tests-policy", line 369, in <module>
    sys.exit(main())
  File "bots/tests-policy", line 80, in main
    post_github(api, number, output, image)
  File "bots/tests-policy", line 366, in post_github
    update_known_issue(api, number, trace, link, context)
  File "bots/tests-policy", line 331, in update_known_issue
    return api.post("issues/{0}/comments".format(number), data)
  File "/home/martin/upstream/cockpit/bots/task/github.py", line 249, in post
    raise Exception("GitHub API problem: {0}".format(response['reason'] or status))
Exception: GitHub API problem: Forbidden
```

It works in offline mode:
```
❱❱❱ cat /tmp/out | bots/tests-policy -o verify/fedora-i386
# testBond (check_networking_bond.TestNetworking)
[...]
Error: audit: type=1400 audit(1515684651.950:146): avc:  denied  { map } for  pid=1075 comm="hostname" path="/usr/bin/hostname" dev="vda4" ino=161820 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:hostname_exec_t:s0 tclass=file permissive=0

ok 9 testBond (check_networking_bond.TestNetworking) # duration: 39s # SKIP Known issue #7636
```

Indeed we flood known issues way too much. For this particular issue the damage is done, and  we should file a new known issue and retire the old one. But we also need to prevent this from happening again.

How about checking the date of the last comment, and only add a new one if it is older than one or two weeks? That way we can still track if a known issue is still current, but don't flood it with each and every single  failure?

**Comment by martinpitt** [comment]
Better approach: tests-policy has code `# try to find an existing comment to update`, which makes more sense. Apparently this is broken, thus it generates new comments all the time.

**Comment by martinpitt** [comment]
One aspect is that #7635 and #7636 affect pretty much every test, thus there is the whole combinatorial explosion of #tests x #os for searching for comments to update.

**Comment by martinpitt** [comment]
Another change is that in September the errors only included the traceback, while now they include the entire test output. That changes very often (e. g. between Phantom and Chrome, or with eliminating `Warning: Permanently added '[127.0.0.2]:2401' (ECDSA) to the list of known hosts.`, thus each small variation adds the whole #tests x #os multitude of variants again.

**Comment by martinpitt** [comment]
I now have a fixed tests-policy which is much more robust. In order to test it properly, and to stop PRs from failing due to this issue, I am cleaning up issue #7636, #7635, and #6901 by removing all but the last 100 comments:

```py
        if api and api.available:
            comments = issue_comments(api, 7636)
            for c in comments[:-100]:
                id = c['id']
                response = api.request("DELETE", "issues/comments/" + str(id))
                if response['status'] == 204:
                    print("deleted", id)
                else:
                    print(response)
                    sys.exit(1)
```
