### ISSUE TITLE
test-policy: fresh failure is detected as a flake

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8584]
PR #8529 (fedora-26 image refresh) originally [failed](https://fedorapeople.org/groups/cockpit/logs/pull-8529-20180207-100000-5dd443cb-verify-fedora-26/log.html#104) on a test that got introduced very recently in PR #8201, but wasn't tested on fedora-26 previously. But both the neural network and the clustering detected it as a flake:
```
# testResizeNtfs (check_storage_resize.TestStorage)
#
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9427/devtools/browser/6bf46a3a-f837-4340-bf77-ee1c705f08b5
[0207/102253.920943:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 107865: Permission denied (13)
[0207/102254.913767:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 107909: Permission denied (13)
> warning: Error resizing logical volume: Command-line `lvresize "TEST"/"vol" -L 419430400b -r' exited with non-zero exit status 5:
stdout: `fsck from util-linux 2.30.2
'
stderr: `  Filesystem check failed.
'
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-resize", line 108, in testResizeNtfs
    can_grow=True, grow_needs_unmount=True)
  File "/build/cockpit/bots/../test/verify/check-storage-resize", line 67, in checkResize
    self.dialog_wait_close()
  File "/build/cockpit/test/verify/storagelib.py", line 262, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 258, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 255, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 166, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_is_present("#dialog")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9791/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'107909.8', u'timestamp': 1517998977247.36}
warning: Error resizing logical volume: Command-line `lvresize "TEST"/"vol" -L 419430400b -r' exited with non-zero exit status 5:
stdout: `fsck from util-linux 2.30.2
'
stderr: `  Filesystem check failed.
'

not ok 104 testResizeNtfs (check_storage_resize.TestStorage) # duration: 123s
Wrote screenshot to TestStorage-testResizeNtfs-fedora-26-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestStorage-testResizeNtfs-fedora-26-127.0.0.2-2901-FAIL.html
Wrote JS log to TestStorage-testResizeNtfs-fedora-26-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testResizeNtfs-fedora-26-127.0.0.2-2901-FAIL.log


# Flake probability: 53.1% (neural network)

# Flake likely 96.7% (clustering)
```

**Comment by stefwalter** [comment]
Investigation has shown that this registered as part of the 332 cluster here. Two things to note:

 * This is marginally related (same test)
 * But the cluster is not big enough (only 3 items) to reliably consider this a valid result.

This needs further work. Thanks for highlighting it.

**Comment by martinpitt** [comment]
Some correct instances for comparison, in case that 's useful at all: In PR #8739 I added three new tests, which all failed the first time on [Fedora-27](https://fedorapeople.org/groups/cockpit/logs/pull-8739-20180301-112323-46004200-verify-fedora-27/log.html) and some other OSes. As the logs might go away at some point, copying the failures here:
```
# testBaseImage (check_bots_api.TestImageCustomize)
#
8e16854b-dc7a-40da-9a76-2da5e4ecf8ae
+ ! test -f /run/nologin && cat /proc/sys/kernel/random/boot_id
+ echo hello > /var/custom-test
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-bots-api", line 36, in tearDown
    os.unlink(f)
OSError: [Errno 2] No such file or directory: 'test/images/custom-fedora-27.qcow2'

not ok 140 testBaseImage (check_bots_api.TestImageCustomize) # duration: 45s


# Flake probability: 61.4% (neural network)

# Flake unlikely 70.0% (clustering)
/usr/lib64/python3.6/site-packages/sklearn/externals/six.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```

```
# testCustomDir (check_bots_api.TestImageCustomize)
#
43ae0529-4cd0-4973-b2ab-4d0166f9f876
+ ! test -f /run/nologin && cat /proc/sys/kernel/random/boot_id
+ echo hello > /var/custom-test
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-bots-api", line 36, in tearDown
    os.unlink(f)
OSError: [Errno 2] No such file or directory: 'test/images/custom-fedora-27'

not ok 141 testCustomDir (check_bots_api.TestImageCustomize) # duration: 47s


# Flake probability: 61.4% (neural network)

# Flake unlikely 70.0% (clustering)
```

So the neural nework leans towards "flake", but clustering is correctly leaning towards "no flake".
