### ISSUE TITLE
Tests often fail with `timed out waiting for page load` in login_and_go

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8605]
Recently, our tests became a lot more unstable than usual, and often fail like this:
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-system-info", line 183, in testBasic
    self.login_and_go("/system")
  File "/build/cockpit/test/common/testlib.py", line 669, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized)
  File "/build/cockpit/test/common/testlib.py", line 396, in login_and_go
    self.open(href)
  File "/build/cockpit/test/common/testlib.py", line 122, in open
    self.expect_load()
  File "/build/cockpit/test/common/testlib.py", line 136, in expect_load
    })' % (self.cdp.timeout * 1000))
  File "/build/cockpit/test/common/cdp.py", line 109, in command
    raise RuntimeError(res["error"])
RuntimeError: timed out waiting for page load
```

This happens across all tests and OSes. The screenshot just shows the login page with no user/password filled, and there is no error in the journal or in the logs (like a browser error).

Recent example: https://fedorapeople.org/groups/cockpit/logs/pull-8603-20180213-070808-e9e6e6c8-verify-fedora-i386/log.html#111

Timing-wise this could coincide with updating the [cockpit/tests](https://hub.docker.com/r/cockpit/tests/tags/) container 5 days ago, which likely hauled in a new chromium version.

**Comment by martinpitt** [comment]
I ran a build and test in our container locally, in a loop, and wasn't able to reproduce this. Trying #8606 to debug it on our infra.

**Comment by martinpitt** [comment]
This happens with verbosity, tracing, and disabled test parellelism as well; example  [one](https://fedorapeople.org/groups/cockpit/logs/pull-8606-20180213-094343-216636a3-verify-fedora-atomic/log.html#140), [two](https://fedorapeople.org/groups/cockpit/logs/pull-8606-20180213-094141-216636a3-verify-rhel-7-5/log.html#176), [three](https://fedorapeople.org/groups/cockpit/logs/pull-8606-20180213-094040-216636a3-verify-debian-stable/log.html#69).

In all three cases this happens after a logout; I haven't (so far) seen a case that fails on the initial login.
```
-> ph_click("#go-logout",false)
<- {u'type': u'undefined'}
-> expect_load
CDP: executionContextDestroyed 9
CDP: executionContextDestroyed 10
CDP: executionContextDestroyed 8
CDP: frameNavigated {"frame":{"id":"(86FC3618305306312F9A3D78CBA22B85)","loaderId":"53222.10","url":"http://127.0.0.2:9091/playground/test","securityOrigin":"http://127.0.0.2:9091","mimeType":"text/html"}}
CDP: executionContextCreated {"context":{"id":11,"origin":"http://127.0.0.2:9091","name":"","auxData":{"isDefault":true,"frameId":"(86FC3618305306312F9A3D78CBA22B85)"}}}
<- expect_load done
+ [ some commands to mangle the VM for a new test scenario ]
+ systemctl start cockpit.socket
-> switch to frame None
-> Page.navigate({"url": "http://127.0.0.2:9091/playground/test"})
CDP: executionContextDestroyed 11
CDP: frameNavigated {"frame":{"id":"(86FC3618305306312F9A3D78CBA22B85)","loaderId":"53222.11","url":"http://127.0.0.2:9091/playground/test","securityOrigin":"http://127.0.0.2:9091","mimeType":"text/html"}}
CDP: executionContextCreated {"context":{"id":12,"origin":"http://127.0.0.2:9091","name":"","auxData":{"isDefault":true,"frameId":"(86FC3618305306312F9A3D78CBA22B85)"}}}
<- {u'frameId': u'(86FC3618305306312F9A3D78CBA22B85)'}
-> expect_load
<- raise timed out waiting for page load
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-reauthorize", line 120, in testSudo
    self.login_and_go("/playground/test", authorized=False)
  File "/build/cockpit/test/common/testlib.py", line 669, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized)
  File "/build/cockpit/test/common/testlib.py", line 396, in login_and_go
    self.open(href)
  File "/build/cockpit/test/common/testlib.py", line 122, in open
    self.expect_load()
  File "/build/cockpit/test/common/testlib.py", line 136, in expect_load
    })' % (self.cdp.timeout * 1000))
  File "/build/cockpit/test/common/cdp.py", line 109, in command
    raise RuntimeError(res["error"])
RuntimeError: timed out waiting for page load
```

In all three examples the frame ID is identical to the previous one, and most importantly, the `executionContextCreated` signal that belongs to the `Page.navigate()` seems to fire *before* calling `expect_load()`, so that the latter never sees it and thus the `Page.loadEventFired` event times out. This would be the race condition.

On the other hand, when running the test locally, I see exactly the same order (no events between `expect_load` and `expect_load_done`), so this could also just be bad interleaving between the Python test process and cdp-driver.js.

**Comment by martinpitt** [comment]
This becomes quite easy to reproduce locally with this change:
```diff
--- a/test/common/testlib.py
+++ b/test/common/testlib.py
@@ -119,6 +119,7 @@ class Browser:
             self.cdp.invoke("Network.setCookie", **cookie)
         self.switch_to_top()
         self.cdp.invoke("Page.navigate", url=href)
+        time.sleep(0.1)
         self.expect_load()
 
     def reload(self, ignore_cache=False):
```
Indeed the slightest delay makes the `expect_load()` miss the `Page.loadEventFired()`. In retrospect this looks like an error: There should be no need to expect a page load right after a `Page.navigate()`. I pushed this to #8606, let's hear the bots' opinion about my reasoning.

**Comment by martinpitt** [comment]
So the previous reasoning was wrong after all, we really do need to wait for `Page.loadEventFired()`, otherwise the page load isn't complete yet (e. g. `#login` was not yet visible). I now updated #8606 to listen for that event in a non-racy way.
