### ISSUE TITLE
rpm-ostreed: GetCachedRebaseRpmDiff regression

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8622]
See https://github.com/projectatomic/rpm-ostree/issues/1250

**Comment by mvollmer** [comment]
verify/continuous-atomic
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRemoteManagement (__main__.OstreeCase)
#

DevTools listening on ws://127.0.0.1:9480/devtools/browser/2a23ffea-29c4-40c8-a9d9-745edef989c2
> log: P  centos-atomic-host-4313fbe5c6292d2709b73aee4f60905ecfd3a559c1809cf533990745035cfa61.0 
> log: P  centos-atomic-host-e5e1d67af13843af97dec2774a00cb7ddf5857a413b1f2664b01b294eecf3585.0 
> warning: error: [7] Couldn't connect to server

ls: cannot access /sysroot/ostree/repo/zremote-test1.trustedkeys.gpg: No such file or directory
> log: P  centos-atomic-host-4313fbe5c6292d2709b73aee4f60905ecfd3a559c1809cf533990745035cfa61.0 
> log: P  centos-atomic-host-e5e1d67af13843af97dec2774a00cb7ddf5857a413b1f2664b01b294eecf3585.0 
> warning: error: GPG: Unable to export keys: GPGME: No data

> warning: error: GPG: Unable to export keys: GPGME: No data
> log: CHECK zremote-test1 zremote-branch1 zremote-test1:zremote-branch1
> log: CACHED 
Traceback (most recent call last):
  File "./test/verify/check-ostree", line 614, in testRemoteManagement
    b.wait_text('table.listing-ct tbody:nth-child(3) div.listing-ct-head h3', name + " zremote-branch1.1")
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 298, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 259, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 256, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(ph_text_is("table.listing-ct tbody:nth-child(3) div.listing-ct-head h3","centos-atomic-host zremote-branch1.1")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9091/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'8391.8', u'timestamp': 1518685787993.14}
log: P  centos-atomic-host-4313fbe5c6292d2709b73aee4f60905ecfd3a559c1809cf533990745035cfa61.0 
log: P  centos-atomic-host-e5e1d67af13843af97dec2774a00cb7ddf5857a413b1f2664b01b294eecf3585.0 
warning: error: [7] Couldn't connect to server

log: P  centos-atomic-host-4313fbe5c6292d2709b73aee4f60905ecfd3a559c1809cf533990745035cfa61.0 
log: P  centos-atomic-host-e5e1d67af13843af97dec2774a00cb7ddf5857a413b1f2664b01b294eecf3585.0 
warning: error: GPG: Unable to export keys: GPGME: No data

warning: error: GPG: Unable to export keys: GPGME: No data
log: CHECK zremote-test1 zremote-branch1 zremote-test1:zremote-branch1
log: CACHED 

not ok 1 testRemoteManagement (__main__.OstreeCase) # duration: 183s
Wrote screenshot to OstreeCase-testRemoteManagement-continuous-atomic-127.0.0.2-2201-FAIL.png
Wrote HTML dump to OstreeCase-testRemoteManagement-continuous-atomic-127.0.0.2-2201-FAIL.html
Wrote JS log to OstreeCase-testRemoteManagement-continuous-atomic-127.0.0.2-2201-FAIL.js.log
Journal extracted to OstreeCase-testRemoteManagement-continuous-atomic-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-02-15T11:12:15.179708
Times recorded: 1
Latest occurrences:

- 2018-02-15T11:12:15.179708
