### ISSUE TITLE
rpm-ostreed: CachedUpdate is missing signature information

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8623]
https://github.com/projectatomic/rpm-ostree/issues/1254

**Comment by mvollmer** [comment]
verify/continuous-atomic
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOstree (__main__.OstreeRestartCase)
#

DevTools listening on ws://127.0.0.1:9472/devtools/browser/5c17560b-3c3b-407f-8370-95039cf53177
> warning: error: [7] Couldn't connect to server

> log: SIG DownloadUpdateRpmDiff Finished [false,"[7] Couldn't connect to server"]
> log: SIG DownloadUpdateRpmDiff SignatureProgress [[{"t":"(bbbbbsxxsssss)","v":[false,false,false,false,true,"EE15015654780CBD",1518687657,0,"RSA","SHA1","[unknown name]","[unknown email]",""]}],"8c2d993329fdd656f044747c27ba2cc7b476ebcaded632dcad75b973d740f8e2"]
> log: SIG DownloadUpdateRpmDiff Finished [false,"Commit 8c2d993329fdd656f044747c27ba2cc7b476ebcaded632dcad75b973d740f8e2: GPG signatures found, but none are in trusted keyring"]
> log: SIG DownloadUpdateRpmDiff SignatureProgress [[{"t":"(bbbbbsxxsssss)","v":[false,false,false,false,true,"EE15015654780CBD",1518692449,0,"RSA","SHA1","[unknown name]","[unknown email]",""]}],"4629f45af3d8bd09c0a75a629d7446e4d6bd072d8125e04ff5b23c77ceb892d3"]
> log: SIG DownloadUpdateRpmDiff Finished [false,"Commit 4629f45af3d8bd09c0a75a629d7446e4d6bd072d8125e04ff5b23c77ceb892d3: GPG signatures found, but none are in trusted keyring"]
> log: SIG DownloadUpdateRpmDiff SignatureProgress [[{"t":"(bbbbbsxxsssss)","v":[true,false,false,false,false,"95A8BA1754D0E95E2B3A98A7EE15015654780CBD",1518692449,0,"RSA","SHA1","Cockpit Tester","do-not-reply@cockpit-project.org","95A8BA1754D0E95E2B3A98A7EE15015654780CBD"]}],"4629f45af3d8bd09c0a75a629d7446e4d6bd072d8125e04ff5b23c77ceb892d3"]
> log: SIG DownloadUpdateRpmDiff Message ["6 metadata, 10 content objects fetched; 9662 KiB transferred in 1 seconds"]
> log: SIG DownloadUpdateRpmDiff ProgressEnd []
> log: SIG DownloadUpdateRpmDiff Finished [true,""]
Traceback (most recent call last):
  File "./test/verify/check-ostree", line 256, in testOstree
    self.check_sig (b, "table.listing-ct tbody:nth-child(3)")
  File "./test/verify/check-ostree", line 142, in check_sig
    b.wait_in_text("{0} div.signatures".format(sel), KEY_ID)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 292, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 259, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 256, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(ph_in_text("table.listing-ct tbody:nth-child(3) div.signatures","95A8BA1754D0E95E2B3A98A7EE15015654780CBD")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9091/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'29219.8', u'timestamp': 1518692386426.17}
warning: error: [7] Couldn't connect to server

log: SIG DownloadUpdateRpmDiff Finished [false,"[7] Couldn't connect to server"]
log: SIG DownloadUpdateRpmDiff SignatureProgress [[{"t":"(bbbbbsxxsssss)","v":[false,false,false,false,true,"EE15015654780CBD",1518687657,0,"RSA","SHA1","[unknown name]","[unknown email]",""]}],"8c2d993329fdd656f044747c27ba2cc7b476ebcaded632dcad75b973d740f8e2"]
log: SIG DownloadUpdateRpmDiff Finished [false,"Commit 8c2d993329fdd656f044747c27ba2cc7b476ebcaded632dcad75b973d740f8e2: GPG signatures found, but none are in trusted keyring"]
log: SIG DownloadUpdateRpmDiff SignatureProgress [[{"t":"(bbbbbsxxsssss)","v":[false,false,false,false,true,"EE15015654780CBD",1518692449,0,"RSA","SHA1","[unknown name]","[unknown email]",""]}],"4629f45af3d8bd09c0a75a629d7446e4d6bd072d8125e04ff5b23c77ceb892d3"]
log: SIG DownloadUpdateRpmDiff Finished [false,"Commit 4629f45af3d8bd09c0a75a629d7446e4d6bd072d8125e04ff5b23c77ceb892d3: GPG signatures found, but none are in trusted keyring"]
log: SIG DownloadUpdateRpmDiff SignatureProgress [[{"t":"(bbbbbsxxsssss)","v":[true,false,false,false,false,"95A8BA1754D0E95E2B3A98A7EE15015654780CBD",1518692449,0,"RSA","SHA1","Cockpit Tester","do-not-reply@cockpit-project.org","95A8BA1754D0E95E2B3A98A7EE15015654780CBD"]}],"4629f45af3d8bd09c0a75a629d7446e4d6bd072d8125e04ff5b23c77ceb892d3"]
log: SIG DownloadUpdateRpmDiff Message ["6 metadata, 10 content objects fetched; 9662 KiB transferred in 1 seconds"]
log: SIG DownloadUpdateRpmDiff ProgressEnd []
log: SIG DownloadUpdateRpmDiff Finished [true,""]

not ok 1 testOstree (__main__.OstreeRestartCase) # duration: 165s
Wrote screenshot to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.png
Wrote HTML dump to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.html
Wrote JS log to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.js.log
Journal extracted to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-02-15T13:01:55.987519
Times recorded: 1
Latest occurrences:

- 2018-02-15T13:01:55.987519
