### ISSUE TITLE
rpm-ostreed: GetCachedUpdateRpmDiff gives wrong information

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8709]
https://github.com/projectatomic/rpm-ostree/issues/1272

**Comment by mvollmer** [comment]
verify/continuous-atomic
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOstree (__main__.OstreeRestartCase)
#

DevTools listening on ws://127.0.0.1:9275/devtools/browser/b944f2f1-21e1-4732-b533-2e9dc2ec874f
> log: 
> warning: error: [7] Couldn't connect to server

> log: 
Traceback (most recent call last):
  File "./test/verify/check-ostree", line 244, in testOstree
    self.check_change_counts(b, "table.listing-ct tbody:nth-child(3)")
  File "./test/verify/check-ostree", line 135, in check_change_counts
    "1 package")
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 299, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 260, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 257, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 168, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(ph_text_is("table.listing-ct tbody:nth-child(3) dd.adds","1 package")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9091/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'15217.8', u'timestamp': 1519654057933.5}
log: 
warning: error: [7] Couldn't connect to server

log: 

not ok 1 testOstree (__main__.OstreeRestartCase) # duration: 171s
Wrote screenshot to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.png
Wrote HTML dump to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.html
Wrote JS log to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.js.log
Journal extracted to OstreeRestartCase-testOstree-continuous-atomic-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-02-26T16:09:51.923175
Times recorded: 1
Latest occurrences:

- 2018-02-26T16:09:51.923175
