### ISSUE TITLE
check-openshift TestRegistryPrerelease.testImages fails against OpenShift 3.9

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8745]
One of the two regressions in #8740 which is probably an API change/regression:
```
$ test/verify/check-openshift TestRegistryPrerelease.testImages -tv
[...]
-> wait: ph_in_text("tbody[data-id='marmalade/juggs:2.9'] .listing-ct-panel","Juggs Image")
<- {u'type': u'undefined'}
-> wait: ph_in_text("tbody[data-id='marmalade/juggs:2.9'] registry-image-body","This is a test description of an image. It can be as long as a paragraph, featuring a nice brogrammer sales pitch.")
<- {u'type': u'undefined'}
-> wait: ph_in_text("tbody[data-id='marmalade/juggs:2.9'] registry-image-body","http://hipsum.co")
<- {u'type': u'undefined'}
-> ph_click("tbody[data-id='marmalade/juggs:2.9'] .listing-ct-head li:last-child a",false)
<- {u'type': u'undefined'}
-> wait: ph_is_present("tbody[data-id='marmalade/juggs:2.9'] registry-image-meta")
<- {u'type': u'undefined'}
-> wait: ph_in_text("tbody[data-id='marmalade/juggs:2.9'] registry-image-meta","build-date=2016-03-04")
<- {u'type': u'undefined'}
-> ph_go("#/images")
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-I4l5F4Kq75Yvla5XX3FqfoQO1206LqJ8p8rtQPyLwm4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1519922665694.27,"url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":3039,"stackTrace":{"callFrames":[{"functionName":"html","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":3039,"columnNumber":23},{"functionName":"JQLite.(anonymous function)","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":3086,"columnNumber":9},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":8064,"columnNumber":26},{"functionName":"processQueue","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":13403,"columnNumber":27},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":13419,"columnNumber":27},{"functionName":"$eval","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":14655,"columnNumber":28},{"functionName":"$digest","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":14471,"columnNumber":31},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":11589,"columnNumber":43},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":5242,"columnNumber":7},{"functionName":"forEach","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":411,"columnNumber":20},{"functionName":"fireUrlChange","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":5241,"columnNumber":5},{"functionName":"cacheStateAndFireUrlChange","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":5209,"columnNumber":5},{"functionName":"eventHandler","scriptId":"42","url":"http://127.0.0.2:9291/cockpit/$079199cd95039535fa6e24fcd2de10c18e97847f/kubernetes/registry.js","lineNumber":3132,"columnNumber":21},{"functionName":"ph_go","scriptId":"20","url":"","lineNumber":167,"columnNumber":29},{"functionName":"","scriptId":"131","url":"","lineNumber":0,"columnNumber":0}]}}
<- {u'type': u'undefined'}
-> wait: ph_is_present("tbody[data-id='marmalade/juggs']")
<- {u'type': u'undefined'}
-> wait: ph_in_text("tbody[data-id='marmalade/juggs'] tr","and 1 other")
<- {u'type': u'undefined'}
-> wait: ph_is_present("tbody[data-id='marmalade/juggs'] tr td a.registry-image-tag:contains('latest')")
<- {u'type': u'string', u'value': u'condition did not become true'}
Traceback (most recent call last):
  File "/home/martin/upstream/c2/test/verify/kubelib.py", line 1002, in testImages
    b.wait_present("tbody[data-id='marmalade/juggs'] tr td a.registry-image-tag:contains('latest')")
  File "/home/martin/upstream/c2/test/common/testlib.py", line 270, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 264, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/c2/test/common/testlib.py", line 261, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 169, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(ph_is_present("tbody[data-id='marmalade/juggs'] tr td a.registry-image-tag:contains('latest')")): condition did not become true

```

Example: https://fedorapeople.org/groups/cockpit/logs/pull-8740-20180301-133333-f8bb64f9-verify-fedora-27/log.html#150

I'm handling these as expected failures for now, so that we can land the new image and avoid other regressions.

**Comment by martinpitt** [comment]
It appears this is only a sorting problem. With current openshift 3.7 image it looks like this, and "2.5" is behind "and 1 other":

![3 7](https://user-images.githubusercontent.com/200109/37096141-06f21302-2218-11e8-8980-5d8b4a393059.png)

While on the prerelease the "latest" tag is hidden behind "and 1 other":

![prerelease](https://user-images.githubusercontent.com/200109/37096183-1db4221a-2218-11e8-9786-9bef97f708f3.png)

**Comment by martinpitt** [comment]
The streams and their tags are queried in pkg/kubernetes/scripts/images.js `allStreams()`, which corresponds directly to:

```
❱❱❱ oc -n marmalade get imagestreams -o json|grep tag
                "tags": [
                        "tag": "0.x"
                        "tag": "latest"
                "tags": [
                        "tag": "2.11"
                        "tag": "2.5"
                        "tag": "2.8"
                        "tag": "2.9"
                        "tag": "latest"
                "tags": [
                        "tag": "latest"
```
(the second block is for juggs, the others are other images).  On 3.7 it looks like this:

```
❱❱❱ oc -n marmalade get imagestreams -o json|grep tag
                "tags": [
                        "tag": "latest"
                        "tag": "0.x"
                "tags": [
                        "tag": "latest"
                        "tag": "2.11"
                        "tag": "2.9"
                        "tag": "2.8"
                        "tag": "2.5"
                "tags": [
                        "tag": "latest"
```
which again corresponds to the screenshot above.

The tag list is *meant* to be sorted by tag name (https://github.com/cockpit-project/registry-image-widgets/blob/master/views/imagestream-listing.html#L27) but apparently this doesn't work.

A tag in the JSON just looks like this (same in 3.7 and 3.9):
```json
                "tags": [
                    {
                        "items": [
                            {
                                "created": "2018-02-15T23:26:06Z",
                                "dockerImageReference": "172.30.29.205:5000/marmalade/juggs@sha256:ceca6bfda
158357db6c37798070637f39211c9d367b773b1cb33c65ba1c14625",
                                "generation": 1,
                                "image": "sha256:ceca6bfda158357db6c37798070637f39211c9d367b773b1cb33c65ba1c
14625"
                            }
                        ],
                        "tag": "latest"
                    }
            ]
```
So https://github.com/cockpit-project/registry-image-widgets/blob/master/images.js#L116  seems to expect a `"name"` attribute of a tag, which doesn't exist. Or I could read this all wrong - e. g. I have not the slightest idea where `imagestream.spec` comes from, this isn't defined anywhere in registry-image-widgets.
