### ISSUE TITLE
Fedora 28: SELinux denies port binding to rpcbind.service

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8871]
```
[root@m2 ~]# systemctl status rpcbind.service
● rpcbind.service - RPC Bind
   Loaded: loaded (/usr/lib/systemd/system/rpcbind.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-03-22 05:53:09 EDT; 2min 38s ago
[...]
Mär 22 05:53:09 m2.cockpit.lan systemd[1]: Starting RPC Bind...
Mär 22 05:53:09 m2.cockpit.lan rpcbind[1446]: rpcbind: svc_tli_create: could not bind to anonymous port
```

SELinux denial:
```
audit: type=1400 audit(1521712389.010:254): avc:  denied  { name_bind } for  pid=1446 comm="rpcbind" src=63890 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0
```

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1559324

**Comment by cockpituous** [comment]
verify/fedora-28
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsClient (check_storage_nfs.TestStorage)
#

DevTools listening on ws://127.0.0.1:10179/devtools/browser/d87df2ff-dd0e-49cd-9bbd-1edb66dc63db
[0322/102440.386027:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 110211: Permission denied (13)
[0322/102441.000098:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 110245: Permission denied (13)
> warning: clnt_create: RPC: Unknown host

> warning: 
> warning: clnt_create: RPC: Unknown host

> warning: 
Unexpected journal message 'audit: type=1400 audit(1521714285.775:290): avc:  denied  { name_bind } for  pid=1622 comm="rpcbind" src=64050 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0'
Wrote JS log to TestStorage-testNfsClient-fedora-28-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorage-testNfsClient-fedora-28-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 669, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 814, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1521714285.775:290): avc:  denied  { name_bind } for  pid=1622 comm="rpcbind" src=64050 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 113 testNfsClient (check_storage_nfs.TestStorage) # duration: 33s
Wrote screenshot to TestStorage-testNfsClient-fedora-28-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorage-testNfsClient-fedora-28-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorage-testNfsClient-fedora-28-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorage-testNfsClient-fedora-28-127.0.0.2-2501-FAIL.log
```
First occurrence: 2018-03-22T10:24:53.259757 | revision 1fb7e667065f5b843a44b76aaa2995762915f05e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8848-20180322-100808-1fb7e667-verify-fedora-28/log.html)
Times recorded: 1
Latest occurrences:

- 2018-03-22T10:24:53.259757 | revision 1fb7e667065f5b843a44b76aaa2995762915f05e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8848-20180322-100808-1fb7e667-verify-fedora-28/log.html)

**Comment by cockpituous** [comment]
verify/fedora-27
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsClient (check_storage_nfs.TestStorage)
#
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:10209/devtools/browser/f8dfc3c0-3fd9-4811-b64f-44ca59fa361c
[0406/155122.955861:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 23894: Permission denied (13)
[0406/155124.000356:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 23929: Permission denied (13)
> warning: clnt_create: RPC: Unknown host

> warning: 
> warning: clnt_create: RPC: Unknown host

> warning: 
Unexpected journal message 'audit: type=1400 audit(1523029889.530:294): avc:  denied  { name_bind } for  pid=1818 comm="rpcbind" src=62252 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0'
Wrote JS log to TestStorage-testNfsClient-fedora-27-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testNfsClient-fedora-27-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 669, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 821, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1523029889.530:294): avc:  denied  { name_bind } for  pid=1818 comm="rpcbind" src=62252 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 145 testNfsClient (check_storage_nfs.TestStorage) # duration: 34s
Wrote screenshot to TestStorage-testNfsClient-fedora-27-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorage-testNfsClient-fedora-27-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorage-testNfsClient-fedora-27-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testNfsClient-fedora-27-127.0.0.2-2401-FAIL.log
```
First occurrence: 2018-04-06T15:51:46.584876 | revision ada04b5ef1fdf33d7aa39c7969d55b881728ab56, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8947-20180406-153636-ada04b5e-verify-fedora-27/log.html)
Times recorded: 1
Latest occurrences:

- 2018-04-06T15:51:46.584876 | revision ada04b5ef1fdf33d7aa39c7969d55b881728ab56, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8947-20180406-153636-ada04b5e-verify-fedora-27/log.html)

**Comment by cockpituous** [comment]
verify/fedora-28
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsListExports (check_storage_nfs.TestStorage)
#

DevTools listening on ws://127.0.0.1:9683/devtools/browser/3150285a-8116-4d64-bf5c-4b4e3c567f28
[0417/100137.031924:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 26943: Permission denied (13)
[0417/100138.009744:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 26994: Permission denied (13)
> warning: clnt_create: RPC: Unknown host

> warning: 
Unexpected journal message 'audit: type=1400 audit(1523959302.943:292): avc:  denied  { name_bind } for  pid=1881 comm="rpcbind" src=64755 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0'
Wrote JS log to TestStorage-testNfsListExports-fedora-28-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorage-testNfsListExports-fedora-28-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 817, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1523959302.943:292): avc:  denied  { name_bind } for  pid=1881 comm="rpcbind" src=64755 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 132 testNfsListExports (check_storage_nfs.TestStorage) # duration: 31s
Wrote screenshot to TestStorage-testNfsListExports-fedora-28-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorage-testNfsListExports-fedora-28-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorage-testNfsListExports-fedora-28-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorage-testNfsListExports-fedora-28-127.0.0.2-2701-FAIL.log
```
First occurrence: 2018-04-17T10:01:48.005667 | revision 8518cd777f7e5f588ae79952f8da90b8787a90ed, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8956-20180417-094343-8518cd77-verify-fedora-28/log.html)
Times recorded: 1
Latest occurrences:

- 2018-04-17T10:01:48.005667 | revision 8518cd777f7e5f588ae79952f8da90b8787a90ed, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8956-20180417-094343-8518cd77-verify-fedora-28/log.html)

**Comment by cockpituous** [comment]
verify/fedora-28
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsBusy (check_storage_nfs.TestStorage)
#

DevTools listening on ws://127.0.0.1:9875/devtools/browser/1c2583e9-5a88-420c-b968-d95028a5dee9
[0417/100142.266090:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 27110: Permission denied (13)
[0417/100143.278038:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 27182: Permission denied (13)
> warning: clnt_create: RPC: Unknown host

> warning: 
> warning: umount.nfs4: /mounts/foo: device is busy

Connection to 127.0.0.2 closed by remote host.
Unexpected journal message 'audit: type=1400 audit(1523959308.308:294): avc:  denied  { name_bind } for  pid=1834 comm="rpcbind" src=62333 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0'
Wrote JS log to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 817, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1523959308.308:294): avc:  denied  { name_bind } for  pid=1834 comm="rpcbind" src=62333 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 130 testNfsBusy (check_storage_nfs.TestStorage) # duration: 33s
Wrote screenshot to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2601-FAIL.html
Wrote JS log to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2601-FAIL.log
```
First occurrence: 2018-04-17T10:01:53.629906 | revision 8518cd777f7e5f588ae79952f8da90b8787a90ed, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8956-20180417-094343-8518cd77-verify-fedora-28/log.html)
Times recorded: 1
Latest occurrences:

- 2018-04-17T10:01:53.629906 | revision 8518cd777f7e5f588ae79952f8da90b8787a90ed, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8956-20180417-094343-8518cd77-verify-fedora-28/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsListExports (check_storage_nfs.TestStorage)
#

DevTools listening on ws://127.0.0.1:9306/devtools/browser/99ae6dd1-183b-4bc5-8699-0399202692dd
[0601/201030.116579:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 179385: Permission denied (13)
[0601/201030.944961:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 179451: Permission denied (13)
> warning: clnt_create: RPC: Unknown host

> warning: 
Unexpected journal message 'audit: type=1400 audit(1527883836.368:296): avc:  denied  { name_bind } for  pid=1892 comm="rpcbind" src=63362 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0'
Wrote JS log to TestStorage-testNfsListExports-fedora-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorage-testNfsListExports-fedora-testing-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1527883836.368:296): avc:  denied  { name_bind } for  pid=1892 comm="rpcbind" src=63362 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 153 testNfsListExports (check_storage_nfs.TestStorage) # duration: 30s
Wrote screenshot to TestStorage-testNfsListExports-fedora-testing-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorage-testNfsListExports-fedora-testing-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorage-testNfsListExports-fedora-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorage-testNfsListExports-fedora-testing-127.0.0.2-2701-FAIL.log
```
First occurrence: 2018-06-01T20:10:39.612203 | revision 534a28e6d7add4ce0ca1738fd6f5c8194247ee01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9267-20180601-195454-534a28e6-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-01T20:10:39.612203 | revision 534a28e6d7add4ce0ca1738fd6f5c8194247ee01, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9267-20180601-195454-534a28e6-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-28
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsBusy (check_storage_nfs.TestStorage)
#
[0605/222215.662344:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9744/devtools/browser/8dc55b1c-583c-4fbb-9e4a-95bf032f7a02
[0605/222215.687893:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 333496: Permission denied (13)
[0605/222216.411680:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0605/222216.413776:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0605/222216.414881:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /usr/lib64/chromium-browser/content_gpu.service
[0605/222216.616209:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 333540: Permission denied (13)
[0605/222216.993755:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0605/222216.996208:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0605/222216.996918:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /usr/lib64/chromium-browser/content_gpu.service
[0605/222217.579178:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0605/222217.581240:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0605/222217.582105:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /usr/lib64/chromium-browser/content_gpu.service
[0605/222218.226037:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0605/222218.228063:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0605/222218.228832:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /usr/lib64/chromium-browser/content_gpu.service
> warning: clnt_create: RPC: Unknown host

> warning: 
> warning: umount.nfs4: /mounts/foo: device is busy

Connection to 127.0.0.2 closed by remote host.
Unexpected journal message 'audit: type=1400 audit(1528237342.091:295): avc:  denied  { name_bind } for  pid=1886 comm="rpcbind" src=63869 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0'
Wrote JS log to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528237342.091:295): avc:  denied  { name_bind } for  pid=1886 comm="rpcbind" src=63869 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 156 testNfsBusy (check_storage_nfs.TestStorage) # duration: 31s
Wrote screenshot to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2901-FAIL.html
Wrote JS log to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testNfsBusy-fedora-28-127.0.0.2-2901-FAIL.log
```
First occurrence: 2018-06-05T22:22:26.232001 | revision 86f4f087efed07cd803e51ccbeb661eb32562c7f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9304-20180605-220505-86f4f087-verify-fedora-28/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-05T22:22:26.232001 | revision 86f4f087efed07cd803e51ccbeb661eb32562c7f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9304-20180605-220505-86f4f087-verify-fedora-28/log.html)

**Comment by martinpitt** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFormatTooSmall (__main__.TestStorage)
#
[0724/100736.136408:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9815/devtools/browser/127b0c21-1e6b-448e-bb5f-4290ddf9276f
> warning: Error creating file system: Command-line `mkfs.xfs -N -f -L ""  "/dev/sda"' exited with non-zero exit status 1: agsize (1280 blocks) too small, need at least 4096 blocks
Usage: mkfs.xfs
/* blocksize */		[-b size=num]
/* metadata */		[-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1]
/* data subvol */	[-d agcount=n,agsize=n,file,name=xxx,size=num,
			    (sunit=value,swidth=value|su=num,sw=num|noalign),
			    sectsize=num
/* force overwrite */	[-f]
/* inode size */	[-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2,
			    projid32bit=0|1,sparse=0|1]
/* no discard */	[-K]
/* log subvol */	[-l agnum=n,internal,size=num,logdev=xxx,version=n
			    sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */		[-L label (maximum 12 characters)]
/* naming */		[-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */	[-N]
/* prototype file */	[-p fname]
/* quiet */		[-q]
/* realtime subvol */	[-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */	[-s size=num]
/* version */		[-V]
			devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).

Unexpected journal messages:
audit: type=1400 audit(1532419648.775:80): avc:  denied  { name_bind } for  pid=648 comm="rpcbind" src=63183 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0
Wrote JS log to TestStorage-testFormatTooSmall-rhel-x-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testFormatTooSmall-rhel-x-127.0.0.2-2201-FAIL.log
Wrote screenshot to TestStorage-testFormatTooSmall-rhel-x-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testFormatTooSmall-rhel-x-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testFormatTooSmall-rhel-x-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testFormatTooSmall-rhel-x-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 853, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1532419648.775:80): avc:  denied  { name_bind } for  pid=648 comm="rpcbind" src=63183 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 1 testFormatTooSmall (__main__.TestStorage) # duration: 79s
```
First occurrence: 2018-07-24T10:08:42.417476
Times recorded: 1
Latest occurrences:

- 2018-07-24T10:08:42.417476

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testImageNames (check_kubernetes_openshift.TestRegistry)
#
[1112/110741.919552:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10004/devtools/browser/c0af7826-c4ac-483f-a07a-da7f0cb40659
[1112/110741.922623:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 187653: Permission denied (13)
[1112/110742.428653:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 187854: Permission denied (13)
Flag --value has been deprecated, Use -p, --param instead.
Flag --value has been deprecated, Use -p, --param instead.
Flag --value has been deprecated, Use -p, --param instead.
Flag --value has been deprecated, Use -p, --param instead.
[1112/111006.170337:ERROR:cert_verify_proc_nss.cc(977)] CERT_PKIXVerifyCert for 127.0.0.2 failed err=-8172
CDP: Security.certificateError {"eventId":1,"errorType":"ERR_CERT_AUTHORITY_INVALID","requestURL":"https://127.0.0.2:9144/oauth/authorize?client_id=cockpit-oauth-client&response_type=token&redirect_uri=http%3A%2F%2F127.0.0.2%3A30701%2Fregistry"}; action: continue
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:30701\". Either the 'unsafe-inline' keyword, a hash ('sha256-I4l5F4Kq75Yvla5XX3FqfoQO1206LqJ8p8rtQPyLwm4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1542021007835.37,"url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":3011,"stackTrace":{"callFrames":[{"functionName":"html","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":3011,"columnNumber":23},{"functionName":"JQLite.(anonymous function)","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":3058,"columnNumber":9},{"functionName":"","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":8036,"columnNumber":26},{"functionName":"processQueue","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":13375,"columnNumber":27},{"functionName":"","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":13391,"columnNumber":27},{"functionName":"$eval","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":14627,"columnNumber":28},{"functionName":"$digest","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":14443,"columnNumber":31},{"functionName":"$apply","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":14732,"columnNumber":24},{"functionName":"","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":11512,"columnNumber":24},{"functionName":"eventHandler","scriptId":"35","url":"http://127.0.0.2:30701/cockpit/@localhost/registry/registry.js","lineNumber":3104,"columnNumber":21},{"functionName":"ph_mouse_event","scriptId":"15","url":"","lineNumber":107,"columnNumber":12},{"functionName":"ph_click","scriptId":"15","url":"","lineNumber":125,"columnNumber":4},{"functionName":"","scriptId":"43","url":"","lineNumber":0,"columnNumber":0}]}}
Unexpected journal messages:
audit: type=1400 audit(1542020855.693:71): avc:  denied  { name_bind } for  pid=415 comm="rpcbind" src=65338 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=1
Wrote JS log to TestRegistry-testImageNames-FAIL.js.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 694, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 875, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1542020855.693:71): avc:  denied  { name_bind } for  pid=415 comm="rpcbind" src=65338 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=1

not ok 15 testImageNames (check_kubernetes_openshift.TestRegistry) # duration: 164s
Wrote screenshot to TestRegistry-testImageNames-FAIL.png
Wrote HTML dump to TestRegistry-testImageNames-FAIL.html
Wrote JS log to TestRegistry-testImageNames-FAIL.js.log
```
First occurrence: 2018-11-12T11:10:12.123695 | revision b3644626cd507a467cbced2de1338f303d01644e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10553-20181112-110101-b3644626-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-11-12T11:10:12.123695 | revision b3644626cd507a467cbced2de1338f303d01644e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10553-20181112-110101-b3644626-verify-fedora-29/log.html)
