### ISSUE TITLE
systemd 238 regression: check-system-info TestSystemInfo.testTime causes timedated crash

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8880]
This test case currently fails on RHEL 8 nightlies and on debian-testing:
```
# testTime (check_system_info.TestSystemInfo)
> warning: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-system-info", line 223, in testTime
    b.wait_popdown("system_information_change_systime")
[...]
Error: timeout
not ok 91 testTime (check_system_info.TestSystemInfo) # duration: 85s
```
because the daemon crashes:

![testsysteminfo-testtime-rhel-8-127 0 0 2-2201-fail](https://user-images.githubusercontent.com/200109/37826955-c2838022-2e95-11e8-9302-99b94e9a8cbe.png)

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1559830

**Comment by martinpitt** [comment]
verify/rhel-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTime (__main__.TestSystemInfo)
#

DevTools listening on ws://127.0.0.1:9948/devtools/browser/f9bcc007-2e1b-46e0-8ff4-399e1bb85c34
> warning: Message recipient disconnected from message bus without replying
> warning: Checking for available updates failed: not-found
Traceback (most recent call last):
  File "test/verify/check-system-info", line 223, in testTime
    b.wait_popdown("system_information_change_systime")
  File "/home/martin/upstream/c3/test/common/testlib.py", line 322, in wait_popdown
    self.wait_not_visible('#' + id)
  File "/home/martin/upstream/c3/test/common/testlib.py", line 294, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "/home/martin/upstream/c3/test/common/testlib.py", line 264, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/c3/test/common/testlib.py", line 261, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/c3/test/common/testlib.py", line 166, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_is_visible("#system_information_change_systime")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9091/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'23009.8', u'timestamp': 1521804664882.19}
warning: Message recipient disconnected from message bus without replying
warning: Checking for available updates failed: not-found

not ok 1 testTime (__main__.TestSystemInfo) # duration: 76s
Wrote screenshot to TestSystemInfo-testTime-rhel-8-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSystemInfo-testTime-rhel-8-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSystemInfo-testTime-rhel-8-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-rhel-8-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-03-23T12:32:08.601435
Times recorded: 1
Latest occurrences:

- 2018-03-23T12:32:08.601435

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_journal.TestJournal)
#
Failed to set ntp: Message recipient disconnected from message bus without replying
Failed to set time: Automatic time synchronization is enabled
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-journal", line 99, in testBasic
    m.execute("timedatectl set-ntp off; timedatectl set-time 2038-01-01")
  File "/build/cockpit/bots/machine/testvm.py", line 488, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'timedatectl set-ntp off; timedatectl set-time 2038-01-01' returned non-zero exit status 1

not ok 196 testBasic (check_journal.TestJournal) # duration: 15s
Journal extracted to TestJournal-testBasic-debian-testing-127.0.0.2-2501-FAIL.log
```
First occurrence: 2018-03-29T07:49:59.838647 | revision d48c8047c06fcef116179f9e66c9aab69cebd511, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8775-20180329-074040-d48c8047-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-03-29T07:49:59.838647 | revision d48c8047c06fcef116179f9e66c9aab69cebd511, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8775-20180329-074040-d48c8047-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Failed to set ntp: Message recipient disconnected from message bus without replying
Failed to set time: Automatic time synchronization is enabled
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 240, in testCreateTimer
    m.execute("timedatectl set-ntp off; timedatectl set-time '2020-01-01 15:30:00'")
  File "/build/cockpit/bots/machine/testvm.py", line 488, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'timedatectl set-ntp off; timedatectl set-time '2020-01-01 15:30:00'' returned non-zero exit status 1

not ok 62 testCreateTimer (check_services.TestServices) # duration: 70s
Journal extracted to TestServices-testCreateTimer-debian-testing-127.0.0.2-2801-FAIL.log
```
First occurrence: 2018-03-29T15:59:39.508345 | revision d48c8047c06fcef116179f9e66c9aab69cebd511, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8775-20180329-154545-d48c8047-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-03-29T15:59:39.508345 | revision d48c8047c06fcef116179f9e66c9aab69cebd511, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8775-20180329-154545-d48c8047-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/rhel-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Failed to set ntp: Message recipient disconnected from message bus without replying
Failed to set time: Automatic time synchronization is enabled
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 240, in testCreateTimer
    m.execute("timedatectl set-ntp off; timedatectl set-time '2020-01-01 15:30:00'")
  File "/build/cockpit/bots/machine/testvm.py", line 488, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'timedatectl set-ntp off; timedatectl set-time '2020-01-01 15:30:00'' returned non-zero exit status 1

not ok 119 testCreateTimer (check_services.TestServices) # duration: 14s
Journal extracted to TestServices-testCreateTimer-rhel-8-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-04-05T01:06:42.805968 | revision dec17db1914a508b234605c2239435656476377d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8946-20180405-004747-dec17db1-verify-rhel-8/log.html)
Times recorded: 1
Latest occurrences:

- 2018-04-05T01:06:42.805968 | revision dec17db1914a508b234605c2239435656476377d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8946-20180405-004747-dec17db1-verify-rhel-8/log.html)
