### ISSUE TITLE
system 238 regression: logind sessions stuck in "closing" state after daemon-reload

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8903]
Reported downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1560885

This causes `test/verify/check-session TestSession.testBasic` to fail:
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-session", line 52, in testBasic
    wait_session(False)
  File "/build/cockpit/bots/../test/verify/check-session", line 41, in wait_session
    wait(cond)
  File "/build/cockpit/test/common/testlib.py", line 1279, in wait
    raise Error(msg or "Condition did not become true.")
Error: Condition did not become true.
```

**Comment by martinpitt** [comment]
verify/rhel-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestSession)
#

DevTools listening on ws://127.0.0.1:9930/devtools/browser/55497500-bdc1-4bc3-97ed-9e2fa2ca4a03
Traceback (most recent call last):
  File "test/verify/check-session", line 52, in testBasic
    wait_session(False)
  File "test/verify/check-session", line 41, in wait_session
    wait(cond)
  File "/home/martin/upstream/c3/test/common/testlib.py", line 1279, in wait
    raise Error(msg or "Condition did not become true.")
Error: Condition did not become true.

not ok 1 testBasic (__main__.TestSession) # duration: 81s
Wrote screenshot to TestSession-testBasic-rhel-8-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSession-testBasic-rhel-8-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSession-testBasic-rhel-8-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSession-testBasic-rhel-8-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-03-27T10:28:22.652343
Times recorded: 1
Latest occurrences:

- 2018-03-27T10:28:22.652343

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_session.TestSession)
#

DevTools listening on ws://127.0.0.1:9734/devtools/browser/7bb828e6-4ca1-4f49-a488-dd92cb10a859
[0329/075505.506373:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 25671: Permission denied (13)
[0329/075506.500164:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 25702: Permission denied (13)
> log: transport closed, dropped message:  1:1!1
{"type":"s","call":["/user","org.freedesktop.DBus.Properties","GetAll",["cockpit.User"]],"id":"2"}
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-session", line 52, in testBasic
    wait_session(False)
  File "/build/cockpit/bots/../test/verify/check-session", line 41, in wait_session
    wait(cond)
  File "/build/cockpit/test/common/testlib.py", line 1274, in wait
    raise Error(msg or "Condition did not become true.")
Error: Condition did not become true.

not ok 96 testBasic (check_session.TestSession) # duration: 79s
Wrote screenshot to TestSession-testBasic-debian-testing-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestSession-testBasic-debian-testing-127.0.0.2-2701-FAIL.html
Wrote JS log to TestSession-testBasic-debian-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestSession-testBasic-debian-testing-127.0.0.2-2701-FAIL.log
```
First occurrence: 2018-03-29T07:56:11.148208 | revision d48c8047c06fcef116179f9e66c9aab69cebd511, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8775-20180329-074040-d48c8047-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-03-29T07:56:11.148208 | revision d48c8047c06fcef116179f9e66c9aab69cebd511, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8775-20180329-074040-d48c8047-verify-debian-testing/log.html)
