### ISSUE TITLE
ubuntu-testing known issue: apparmor failure on libvirtd signal sending

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#9036]
We're seeing failures like this:

Error: audit: type=1400 audit(1524574945.952:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1199 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

on the latest update of ubuntu-testing.

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (check_machines.TestMachines)
#
ls: cannot access '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_NESTED': No such file or directory
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9257/devtools/browser/90dd4166-b08d-4460-98d4-063585f68af6
[0424/141438.821077:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 235050: Permission denied (13)
[0424/141439.809339:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 235087: Permission denied (13)
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable libvirtd
Removed /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Removed /etc/systemd/system/sockets.target.wants/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable libvirtd
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket -> /lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket -> /lib/systemd/system/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Unexpected journal message 'audit: type=1400 audit(1524579292.728:39): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1185 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1524579302.876:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1512 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 817, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1524579292.728:39): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1185 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 165 testLibvirt (check_machines.TestMachines) # duration: 57s
Wrote screenshot to TestMachines-testLibvirt-debian-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestMachines-testLibvirt-debian-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2901-FAIL.log
```
First occurrence: 2018-04-24T14:15:20.993949 | revision 475c87f27775e0b9961cfa274eccaa3096ce9a87, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9007-20180424-140404-475c87f2-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-04-24T14:15:20.993949 | revision 475c87f27775e0b9961cfa274eccaa3096ce9a87, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9007-20180424-140404-475c87f2-verify-debian-testing/log.html)

**Comment by allisonkarlitskaya** [comment]
This looks like a dup of #8467?  How did we forget this so quickly?

**Comment by allisonkarlitskaya** [comment]
Different signal kill vs hup, but otherwise exactly the same story...

**Comment by martinpitt** [comment]
@allisonkarlitskaya : So I suppose you can refer to the corresponding old Debian bug when filing the new one? It seems a bit weird to me that the AppArmor profile would restrict the allowed signal, instead of simply "send signals or not", but I haven't checked. It could also be that this is a regression in 4.2.

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (check_machines.TestMachines)
#
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9397/devtools/browser/99e6dbd7-7148-4765-9dea-2e08391bdc84
[0528/084247.518393:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 418650: Permission denied (13)
[0528/084248.532869:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 418818: Permission denied (13)
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable libvirtd
Removed /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Removed /etc/systemd/system/sockets.target.wants/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable libvirtd
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket -> /lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket -> /lib/systemd/system/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Unexpected journal message 'audit: type=1400 audit(1527496979.896:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1202 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1527496989.816:41): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1285 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1527496979.896:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1202 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 206 testLibvirt (check_machines.TestMachines) # duration: 60s
Wrote screenshot to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.html
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.log
```
First occurrence: 2018-05-28T08:43:24.016488 | revision fc1f8030f27962034fc341a3eb5390824fcc9288, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9185-20180528-083232-fc1f8030-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-05-28T08:43:24.016488 | revision fc1f8030f27962034fc341a3eb5390824fcc9288, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9185-20180528-083232-fc1f8030-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (check_machines.TestMachines)
#

DevTools listening on ws://127.0.0.1:10201/devtools/browser/747f5ce0-6a55-4cbc-9e42-f97e2ff0d696
[0530/092010.681206:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 475586: Permission denied (13)
[0530/092011.670426:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 475611: Permission denied (13)
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable libvirtd
Removed /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Removed /etc/systemd/system/sockets.target.wants/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable libvirtd
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket -> /lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket -> /lib/systemd/system/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Unexpected journal message 'audit: type=1400 audit(1527672025.484:38): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1258 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1527672035.600:39): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=3384 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1527672025.484:38): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1258 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 138 testLibvirt (check_machines.TestMachines) # duration: 58s
Wrote screenshot to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.html
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2801-FAIL.log
```
First occurrence: 2018-05-30T09:20:49.206841 | revision 35edd9c45b9197bd5b94e335c9a502c2d148c3a8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9140-20180530-090707-35edd9c4-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-05-30T09:20:49.206841 | revision 35edd9c45b9197bd5b94e335c9a502c2d148c3a8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9140-20180530-090707-35edd9c4-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (check_machines.TestMachines)
#
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9609/devtools/browser/6dc742aa-bfa0-4b8d-8a39-a70c3eba8a05
[0601/074017.997285:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 565600: Permission denied (13)
[0601/074018.998049:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 565632: Permission denied (13)
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable libvirtd
Removed /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Removed /etc/systemd/system/sockets.target.wants/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable libvirtd
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket -> /lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket -> /lib/systemd/system/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Unexpected journal message 'audit: type=1400 audit(1527838830.592:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1238 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1527838840.852:41): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=2156 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1527838830.592:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1238 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 103 testLibvirt (check_machines.TestMachines) # duration: 54s
Wrote screenshot to TestMachines-testLibvirt-debian-testing-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMachines-testLibvirt-debian-testing-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2701-FAIL.log
```
First occurrence: 2018-06-01T07:41:14.108105 | revision c5a81545351b9a0b739348c810589105db13b641, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8968-20180601-072626-c5a81545-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-01T07:41:14.108105 | revision c5a81545351b9a0b739348c810589105db13b641, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8968-20180601-072626-c5a81545-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (check_machines.TestMachines)
#
ls: cannot access '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_NESTED': No such file or directory

DevTools listening on ws://127.0.0.1:9903/devtools/browser/b0db85f6-f961-4e09-a55d-3ab4eeeaafd9
[0604/114632.238485:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 130558: Permission denied (13)
[0604/114633.313775:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 130624: Permission denied (13)
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable libvirtd
Removed /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Removed /etc/systemd/system/sockets.target.wants/virtlogd.socket.
> warning: error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory

> warning: spawn 'virsh' process returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to connect to the hypervisor\nerror: Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory"}", data: """"
> warning: dominfo() exception: 'error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory', data: '', output: ''
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable libvirtd
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket -> /lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket -> /lib/systemd/system/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Unexpected journal message 'audit: type=1400 audit(1528112808.788:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1297 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1528112819.904:41): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=3319 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528112808.788:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1297 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 182 testLibvirt (check_machines.TestMachines) # duration: 61s
Wrote screenshot to TestMachines-testLibvirt-debian-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestMachines-testLibvirt-debian-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2401-FAIL.log
```
First occurrence: 2018-06-04T11:47:34.918158 | revision bb9142033d5de7083257bb513843caacb42649da
Times recorded: 1
Latest occurrences:

- 2018-06-04T11:47:34.918158 | revision bb9142033d5de7083257bb513843caacb42649da

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_machines.TestMachines)
#
ls: cannot access '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_NESTED': No such file or directory
[0606/025750.369649:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9489/devtools/browser/34919fbd-a81f-4b75-adb9-078a4ed81c88
[0606/025750.463100:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 20886: Permission denied (13)
[0606/025751.702938:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 20967: Permission denied (13)
[0606/025753.037980:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/025753.132789:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0606/025754.239390:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/025754.244773:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0606/025755.170158:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/025755.175199:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0606/025756.271358:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/025756.277531:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
> warning: error: Failed to get memory statistics for domain subVmTest1
error: Requested operation is not valid: domain is not running

> info: The 'virsh' command failed, as expected: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to get memory statistics for domain subVmTest1\nerror: Requested operation is not valid: domain is not running"}", data: """"
> warning: Unable to parse event, ignoring: events received: 8
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
> warning: error: Domain is already active

Unexpected journal message 'audit: type=1400 audit(1528254015.212:58): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=7105 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testBasic-debian-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachines-testBasic-debian-testing-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528254015.212:58): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=7105 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 179 testBasic (check_machines.TestMachines) # duration: 187s
Wrote screenshot to TestMachines-testBasic-debian-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMachines-testBasic-debian-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMachines-testBasic-debian-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachines-testBasic-debian-testing-127.0.0.2-2501-FAIL.log
```
First occurrence: 2018-06-06T03:00:30.665283 | revision 979b8d2a05b705b921dc6dab5b3aecbc38a16ef8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9166-20180606-024343-979b8d2a-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-06T03:00:30.665283 | revision 979b8d2a05b705b921dc6dab5b3aecbc38a16ef8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9166-20180606-024343-979b8d2a-verify-debian-testing/log.html)

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (check_machines.TestMachines)
#
ls: cannot access '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_NESTED': No such file or directory
[0606/160234.498609:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9373/devtools/browser/a096593f-c687-467d-8cd2-1ec96cf9cf99
[0606/160234.533742:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 964761: Permission denied (13)
[0606/160235.344777:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/160235.346955:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0606/160235.555248:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 964878: Permission denied (13)
[0606/160235.951633:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/160235.954239:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0606/160236.691265:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/160236.693668:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0606/160237.364612:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0606/160237.367372:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable libvirtd
Removed /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Removed /etc/systemd/system/sockets.target.wants/virtlogd.socket.
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
> warning: Unable to parse event, ignoring: events received: 0
> warning: Unable to parse event, ignoring: error: internal error: client socket is closed
> warning: Unable to parse event, ignoring: 
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable libvirtd
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket -> /lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket -> /lib/systemd/system/virtlogd.socket.
Unexpected journal message 'audit: type=1400 audit(1528300969.176:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1276 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1528300979.356:41): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=2981 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528300969.176:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1276 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 196 testLibvirt (check_machines.TestMachines) # duration: 59s
Wrote screenshot to TestMachines-testLibvirt-debian-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMachines-testLibvirt-debian-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2501-FAIL.log
```
First occurrence: 2018-06-06T16:03:15.430714 | revision 338e3470425245bcb60056fc1a255f5959bd1e55, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9324-20180606-154848-338e3470-verify-debian-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-06T16:03:15.430714 | revision 338e3470425245bcb60056fc1a255f5959bd1e55, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9324-20180606-154848-338e3470-verify-debian-testing/log.html)
