### ISSUE TITLE
cluster learning crashes: AttributeError: 'Cluster' object has no attribute 'merged'

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9085]
Seen in [this log](https://fedorapeople.org/groups/cockpit/logs/pull-9083-20180502-114242-bd7d68de-verify-rhel-8/log.html#31):
```
# testBond (check_networking_bond.TestNetworking)
#
NAME             UUID                                  TYPE      DEVICE 
System eth0      5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
static-52:54:01  32f2a6b0-ccf9-46c3-bfc1-5476bf6155b1  ethernet  eth1   
virbr0           2badc1f1-8add-4bcb-bf16-4f1c39fe1f31  bridge    virbr0 
System eth1      9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
enp0s2           99dd3ddc-3515-4852-a358-26ed25f32a82  ethernet  --     


DevTools listening on ws://127.0.0.1:9732/devtools/browser/94167709-1099-455c-9e89-f24e277736f8
[0502/120346.132946:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 221166: Permission denied (13)
[0502/120347.070342:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 221200: Permission denied (13)
52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
52:54:01:00:00:04 -> eth3
52:54:01:00:00:04 -> eth3
Unexpected journal message '/usr/libexec/cockpit-pcp: bridge was killed: 11'
Wrote JS log to TestNetworking-testBond-rhel-8-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestNetworking-testBond-rhel-8-127.0.0.2-2401-FAIL.log
Journal extracted to TestNetworking-testBond-fedora-26-127.0.0.2-2402-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 819, in check_journal_messages
    raise Error(first)
Error: /usr/libexec/cockpit-pcp: bridge was killed: 11

not ok 31 testBond (check_networking_bond.TestNetworking) # duration: 35s
Wrote screenshot to TestNetworking-testBond-rhel-8-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestNetworking-testBond-rhel-8-127.0.0.2-2401-FAIL.html
Wrote JS log to TestNetworking-testBond-rhel-8-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestNetworking-testBond-rhel-8-127.0.0.2-2401-FAIL.log
Journal extracted to TestNetworking-testBond-fedora-26-127.0.0.2-2402-FAIL.log

/usr/lib64/python3.6/site-packages/sklearn/externals/six.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/build/cockpit/bots/tests-policy", line 382, in <module>
    sys.exit(main())
  File "/build/cockpit/bots/tests-policy", line 98, in main
    output = guessFlake(output, context)
  File "/build/cockpit/bots/tests-policy", line 178, in guessFlake
    analysis = cluster.analyze()
  File "/build/cockpit/bots/learn/cluster.py", line 114, in analyze
    merged = (float(self.merged) / float(total))
AttributeError: 'Cluster' object has no attribute 'merged'

```

**Comment by stefwalter** [comment]
Fixed in #9079
