### ISSUE TITLE
SELinux denies chronyd access to its socket

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9328]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1584757

Messages in tests:
```
Traceback (most recent call last):
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528354884.409:308): avc:  denied  { sendto } for  pid=1914 comm="chronyd" path="/run/chrony/chronyc.1919.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:realmd_t:s0 tclass=unix_dgram_socket permissive=0

```

**Comment by martinpitt** [comment]
verify/fedora-28
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpaUnqualifiedUsers (__main__.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2018-05-25 08:18:46
    Valid Until: 2038-05-25 08:18:46

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
New SSSD config will be created
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
trying https://f0.cockpit.lan/ipa/json
[try 1]: Forwarding 'schema' to json server 'https://f0.cockpit.lan/ipa/json'
trying https://f0.cockpit.lan/ipa/session/json
[try 1]: Forwarding 'ping' to json server 'https://f0.cockpit.lan/ipa/session/json'
[try 1]: Forwarding 'ca_is_enabled' to json server 'https://f0.cockpit.lan/ipa/session/json'
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
[try 1]: Forwarding 'host_mod' to json server 'https://f0.cockpit.lan/ipa/session/json'
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.

Using default chrony configuration.
Client configuration complete.
The ipa-client-install command was successful
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/bin/authselect select sssd with-mkhomedir --force && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
Created symlink /etc/systemd/system/multi-user.target.wants/oddjobd.service ? /usr/lib/systemd/system/oddjobd.service.
 * Successfully enrolled machine in realm

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: [0607/095925.284416:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10064/devtools/browser/e7eeb519-77fe-4bde-aaa9-2ee3b05b08c2
> warning: Shutdown scheduled for Thu 2018-06-07 03:59:31 EDT, use 'shutdown -c' to cancel.

> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1528358371306.55,"url":"http://127.0.0.2:9091/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"20044.28"}
Connection to 127.0.0.2 closed by remote host.
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"3"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
Unexpected journal message 'audit: type=1400 audit(1528358319.692:314): avc:  denied  { sendto } for  pid=1850 comm="chronyd" path="/run/chrony/chronyc.1855.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:realmd_t:s0 tclass=unix_dgram_socket permissive=0'
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2201-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528358319.692:314): avc:  denied  { sendto } for  pid=1850 comm="chronyd" path="/run/chrony/chronyc.1855.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:realmd_t:s0 tclass=unix_dgram_socket permissive=0

not ok 3 testIpaUnqualifiedUsers (__main__.TestRealms) # duration: 128s
Wrote screenshot to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2201-FAIL.html
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2201-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2202-FAIL.log
```
First occurrence: 2018-06-07T09:59:48.515357
Times recorded: 1
Latest occurrences:

- 2018-06-07T09:59:48.515357

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNegotiate (check_realms.TestKerberos)
#
++ seq 1 20
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ break
+ echo foobarfoo
+ realm join -vU admin cockpit.lan
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2018-05-25 08:18:46
    Valid Until: 2038-05-25 08:18:46

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
New SSSD config will be created
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
trying https://f0.cockpit.lan/ipa/json
[try 1]: Forwarding 'schema' to json server 'https://f0.cockpit.lan/ipa/json'
trying https://f0.cockpit.lan/ipa/session/json
[try 1]: Forwarding 'ping' to json server 'https://f0.cockpit.lan/ipa/session/json'
[try 1]: Forwarding 'ca_is_enabled' to json server 'https://f0.cockpit.lan/ipa/session/json'
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
[try 1]: Forwarding 'host_mod' to json server 'https://f0.cockpit.lan/ipa/session/json'
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful

Using default chrony configuration.
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/bin/authselect select sssd with-mkhomedir --force && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
Created symlink /etc/systemd/system/multi-user.target.wants/oddjobd.service ? /usr/lib/systemd/system/oddjobd.service.
 * Successfully enrolled machine in realm
++ seq 1 20
+ for x in $(seq 1 20)
+ KRB5_TRACE=/dev/stderr
+ kinit -f admin@COCKPIT.LAN
+ echo foobarfoo
[2109] 1528823730.878316: Getting initial credentials for admin@COCKPIT.LAN
[2109] 1528823730.878318: Sending unauthenticated request
[2109] 1528823730.878319: Sending request (183 bytes) to COCKPIT.LAN
[2109] 1528823730.878320: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[2109] 1528823730.878321: No URI records found
[2109] 1528823730.878322: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[2109] 1528823730.878323: SRV answer: 0 100 88 "f0.cockpit.lan."
[2109] 1528823730.878324: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[2109] 1528823730.878325: SRV answer: 0 100 88 "f0.cockpit.lan."
[2109] 1528823730.878326: Resolving hostname f0.cockpit.lan.
[2109] 1528823730.878327: Resolving hostname f0.cockpit.lan.
[2109] 1528823730.878328: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[2109] 1528823730.878329: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[2109] 1528823730.878330: Initiating TCP connection to stream 172.27.0.15:88
[2109] 1528823730.878331: Terminating TCP connection to stream 172.27.0.15:88
[2109] 1528823730.878332: Initiating TCP connection to stream 10.111.112.100:88
[2109] 1528823730.878333: Sending TCP request to stream 10.111.112.100:88
[2109] 1528823730.878334: Received answer (524 bytes) from stream 10.111.112.100:88
[2109] 1528823730.878335: Terminating TCP connection to stream 10.111.112.100:88
[2109] 1528823730.878336: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[2109] 1528823730.878337: No URI records found
[2109] 1528823730.878338: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[2109] 1528823730.878339: SRV answer: 0 100 88 "f0.cockpit.lan."
[2109] 1528823730.878340: Response was from master KDC
[2109] 1528823730.878341: Received error from KDC: -1765328359/Additional pre-authentication required
[2109] 1528823730.878344: Preauthenticating using KDC method data
[2109] 1528823730.878345: Processing preauth types: PA-PK-AS-REQ (16), PA-PK-AS-REP_OLD (15), PA-PK-AS-REQ_OLD (14), PA-FX-FAST (136), PA-ETYPE-INFO2 (19), PA-PKINIT-KX (147), PA-SPAKE (151), PA-ENC-TIMESTAMP (2), PA_AS_FRESHNESS (150), PA-FX-COOKIE (133)
[2109] 1528823730.878346: Selected etype info: etype aes256-cts, salt "4Gc$s Ukh"@F4?D:", params ""
[2109] 1528823730.878347: Received cookie: MIT1\x00\x00\x00\x01\x14\x9d=w\xab\xc3\xc5P%\xd0\x05\xc5\xfc\x86\xcb2 \"\xdf\x81\xaeR\x0fA\x8e_7t\xd8\xd5\xec\xb5\xe2hN\xdfw\x06hP\x8aT\xb3JF\xc9f\x0e\xfd\x96\xd4\xd0)\x99=\xe0\xef\x1ai\xc5~\xd1\xb5P\xe2\xf3\x9d\\x81(\x107\x9f\x0c^\xe8\xda\x1b\x88\x93U\xba\xc7\xbe+i\x13#\xd9EC\xe2Q\xf0\x8dL\xc9\x1e%\xfb\xc3]\xb09@\x97\x13\x18\xf3\xe2+4\xe3_\xcf\x9e\xc1\x8a\xa2\xcaQ\xc5\xc3\x84?\x11\x0b'\xd0
[2109] 1528823730.878348: SPAKE challenge received with group 1, pubkey B8D6072FF5C55EEDC0ECC5B1915664A3E207F1D91355A7E05EDBDE8BC429B7A4
[2109] 1528823730.878349: SPAKE key generated with pubkey FB7E21252378C857855D576433A7A46811E8F8EAB4F8FFADB9603B7BEE04BA49
[2109] 1528823730.878350: SPAKE algorithm result: 9CA4AF55E2F6D9FB89E14CCEDE3F2FA070CFCBDE043AB98F079F51CE68475D10
[2109] 1528823730.878351: SPAKE final transcript hash: 2D433666BD52EF0D2162BFD3D1AFD74F6AEFC3761DFDB828A709E0F9E8BF32DB
[2109] 1528823730.878352: Sending SPAKE response
[2109] 1528823730.878353: Preauth module spake (151) (real) returned: 0/Success
[2109] 1528823730.878354: Produced preauth for next request: PA-FX-COOKIE (133), PA-SPAKE (151)
[2109] 1528823730.878355: Sending request (442 bytes) to COCKPIT.LAN
[2109] 1528823730.878356: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[2109] 1528823730.878357: No URI records found
[2109] 1528823730.878358: Sending DNS SRV query for _kerberos._udp.COCKPIT.LAN.
[2109] 1528823730.878359: SRV answer: 0 100 88 "f0.cockpit.lan."
[2109] 1528823730.878360: Sending DNS SRV query for _kerberos._tcp.COCKPIT.LAN.
[2109] 1528823730.878361: SRV answer: 0 100 88 "f0.cockpit.lan."
[2109] 1528823730.878362: Resolving hostname f0.cockpit.lan.
[2109] 1528823730.878363: Resolving hostname f0.cockpit.lan.
[2109] 1528823730.878364: Initiating TCP connection to stream fec0::5054:ff:fe12:3456:88
[2109] 1528823730.878365: Terminating TCP connection to stream fec0::5054:ff:fe12:3456:88
[2109] 1528823730.878366: Initiating TCP connection to stream 172.27.0.15:88
[2109] 1528823730.878367: Terminating TCP connection to stream 172.27.0.15:88
[2109] 1528823730.878368: Initiating TCP connection to stream 10.111.112.100:88
[2109] 1528823730.878369: Sending TCP request to stream 10.111.112.100:88
[2109] 1528823730.878370: Received answer (724 bytes) from stream 10.111.112.100:88
[2109] 1528823730.878371: Terminating TCP connection to stream 10.111.112.100:88
[2109] 1528823730.878372: Sending DNS URI query for _kerberos.COCKPIT.LAN.
[2109] 1528823730.878373: No URI records found
[2109] 1528823730.878374: Sending DNS SRV query for _kerberos-master._tcp.COCKPIT.LAN.
[2109] 1528823730.878375: SRV answer: 0 100 88 "f0.cockpit.lan."
[2109] 1528823730.878376: Response was from master KDC
[2109] 1528823730.878377: Processing preauth types: PA-ETYPE-INFO2 (19)
[2109] 1528823730.878378: Selected etype info: etype aes256-cts, salt "4Gc$s Ukh"@F4?D:", params ""
[2109] 1528823730.878379: Produced preauth for next request: (empty)
[2109] 1528823730.878380: AS key determined by preauth: aes256-cts/4A6D
[2109] 1528823730.878381: Decrypted AS reply; session key is: aes256-cts/93B3
[2109] 1528823730.878382: FAST negotiation: available
[2109] 1528823730.878383: Initializing KEYRING:persistent:0:0 with default princ admin@COCKPIT.LAN
[2109] 1528823730.878384: Storing admin@COCKPIT.LAN -> krbtgt/COCKPIT.LAN@COCKPIT.LAN in KEYRING:persistent:0:0
[2109] 1528823730.878385: Storing config in KEYRING:persistent:0:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: fast_avail: yes
[2109] 1528823730.878386: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/fast_avail/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KEYRING:persistent:0:0
[2109] 1528823730.878387: Storing config in KEYRING:persistent:0:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: pa_type: 151
[2109] 1528823730.878388: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/pa_type/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KEYRING:persistent:0:0
+ break
+ type ipa
+ LC_ALL=C.UTF-8
+ ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN
+ ipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Warning: Permanently added 'x0.cockpit.lan' (ECDSA) to the list of known hosts.
Connection closed by UNKNOWN port 65535
+ sleep 1
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 2
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 3
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 4
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 5
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 6
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 7
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 8
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 9
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 10
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 11
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 12
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
Connection closed by UNKNOWN port 65535
+ sleep 13
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
[0612/171711.434593:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9387/devtools/browser/fd3b7959-f8b5-4574-bd13-ded13558faad
[0612/171711.466662:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 734282: Permission denied (13)
[0612/171712.443384:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 734348: Permission denied (13)
> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: line 25: cd: /home/admin/.ssh: No such file or directory

Unexpected journal message 'audit: type=1400 audit(1528823689.918:302): avc:  denied  { sendto } for  pid=1920 comm="chronyd" path="/run/chrony/chronyc.1925.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:realmd_t:s0 tclass=unix_dgram_socket permissive=0'
Unexpected journal message 'audit: type=1400 audit(1528823690.929:303): avc:  denied  { sendto } for  pid=1920 comm="chronyd" path="/run/chrony/chronyc.1925.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:realmd_t:s0 tclass=unix_dgram_socket permissive=0'
Journal extracted to TestKerberos-testNegotiate-fedora-testing-127.0.0.2-2301-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528823689.918:302): avc:  denied  { sendto } for  pid=1920 comm="chronyd" path="/run/chrony/chronyc.1925.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:realmd_t:s0 tclass=unix_dgram_socket permissive=0

not ok 92 testNegotiate (check_realms.TestKerberos) # duration: 181s
Journal extracted to TestKerberos-testNegotiate-fedora-testing-127.0.0.2-2301-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2302-FAIL.log
```
First occurrence: 2018-06-12T17:17:22.118841 | revision 6d4f0c01b45331462c1073ea1bcd13289aaf15a3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9267-20180612-164141-6d4f0c01-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-12T17:17:22.118841 | revision 6d4f0c01b45331462c1073ea1bcd13289aaf15a3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9267-20180612-164141-6d4f0c01-verify-fedora-testing/log.html)

**Comment by guillermocol** [comment]
Hello, 
I was trying to install also freeipa in Debian 10 and I have got the same error as above for the ntp configuration. Is anything we can do to correct this error?

These are the ntp servers and ntp pool selected:
NTP server:	0.uk.pool.ntp.org
NTP server:	1.uk.pool.ntp.org
NTP server:	2.uk.pool.ntp.org
NTP server:	3.uk.pool.ntp.org
NTP pool:	uk.pool.ntp.org

Continue to configure the system with these values? [no]: yes

The following operations may take some minutes to complete.
Please wait until the prompt is returned.

** Final Error during Installation
Synchronizing time
Configuration of chrony was changed by installer.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Warning: IPA was unable to sync time with chrony!
         Time synchronization is required for IPA to work correctly

**Comment by martinpitt** [comment]
@guillermocol : This sounds like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968428 . Either way this is a bug in Debian's freeipa package.
