### ISSUE TITLE
rhel-8: Unexpected selinux tang messages 

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#9333]
(Similar to #9233, but on rhel-8 so let's keep those separate)

https://bugzilla.redhat.com/show_bug.cgi?id=1588516

```
audit: type=1400 audit(1528376687.827:317): avc:  denied  { read } for  pid=1 comm="systemd" name="tang" dev="dm-0" ino=25361236 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tangd_db_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1528376687.856:319): avc:  denied  { getattr } for  pid=4896 comm="tangd" path="socket:[34857]" dev="sockfs" ino=34857 scontext=system_u:system_r:tangd_t:s0 tcontext=system_u:system_r:tangd_t:s0 tclass=tcp_socket permissive=1
```

**Comment by cockpituous** [comment]
verify/rhel-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClevisTang (check_storage_luks.TestStorage)
#
Failed to reset failed state of unit tangd-update.service: Unit tangd-update.service not loaded.
[0607/145948.609180:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9331/devtools/browser/77e0059f-5641-4f33-a26e-2e227545753d
[0607/145948.656229:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 206330: Permission denied (13)
[0607/145949.432919:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0607/145949.436961:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0607/145949.642759:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 206458: Permission denied (13)
[0607/145950.213248:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0607/145950.215505:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0607/145950.216628:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /usr/lib64/chromium-browser/content_gpu.service
[0607/145950.855531:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0607/145950.857666:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0607/145950.858817:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /usr/lib64/chromium-browser/content_gpu.service
[0607/145951.646813:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0607/145951.649704:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Checking for available updates failed: not-found
> warning: Checking for available updates failed: not-found
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Checking for available updates failed: not-found
> warning: Checking for available updates failed: not-found
> warning: Error communicating with the server!
Traceback (most recent call last):
  File "<stdin>", line 159, in <module>
  File "<stdin>", line 131, in check_key
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['clevis', 'decrypt']' returned non-zero exit status 1.

> log: Error communicating with the server!
Traceback (most recent call last):
  File "<stdin>", line 159, in <module>
  File "<stdin>", line 131, in check_key
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['clevis', 'decrypt']' returned non-zero exit status 1.
Unexpected journal message 'audit: type=1400 audit(1528383653.377:318): avc:  denied  { read } for  pid=1 comm="systemd" name="tang" dev="dm-0" ino=25361236 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tangd_db_t:s0 tclass=dir permissive=0'
Unexpected journal message 'audit: type=1400 audit(1528383653.425:320): avc:  denied  { getattr } for  pid=4893 comm="tangd" path="socket:[34767]" dev="sockfs" ino=34767 scontext=system_u:system_r:tangd_t:s0 tcontext=system_u:system_r:tangd_t:s0 tclass=tcp_socket permissive=1'
Wrote JS log to TestStorage-testClevisTang-rhel-8-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testClevisTang-rhel-8-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528383653.377:318): avc:  denied  { read } for  pid=1 comm="systemd" name="tang" dev="dm-0" ino=25361236 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tangd_db_t:s0 tclass=dir permissive=0

not ok 227 testClevisTang (check_storage_luks.TestStorage) # duration: 106s
Wrote screenshot to TestStorage-testClevisTang-rhel-8-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorage-testClevisTang-rhel-8-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorage-testClevisTang-rhel-8-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testClevisTang-rhel-8-127.0.0.2-2301-FAIL.log
```
First occurrence: 2018-06-07T15:01:10.260825 | revision 38d010006560074388dd7cfdb13744bc29bcaf5f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9329-20180607-144949-38d01000-verify-rhel-8/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-07T15:01:10.260825 | revision 38d010006560074388dd7cfdb13744bc29bcaf5f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9329-20180607-144949-38d01000-verify-rhel-8/log.html)

**Comment by cockpituous** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClevisTang (check_storage_luks.TestStorage)
#
Failed to reset failed state of unit tangd-update.service: Unit tangd-update.service not loaded.
[0612/085732.877990:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9814/devtools/browser/d201eda4-1a42-4713-a4c0-725589e6670b
[0612/085732.906141:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 130852: Permission denied (13)
[0612/085733.913540:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 130960: Permission denied (13)
> log: PackageKit went away from D-Bus
> warning: Checking for available updates failed: not-found
> warning: Checking for available updates failed: not-found
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Checking for available updates failed: not-found
> warning: Checking for available updates failed: not-found
> warning: Error communicating with the server!
Traceback (most recent call last):
  File "<stdin>", line 159, in <module>
  File "<stdin>", line 131, in check_key
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['clevis', 'decrypt']' returned non-zero exit status 1.

> log: Error communicating with the server!
Traceback (most recent call last):
  File "<stdin>", line 159, in <module>
  File "<stdin>", line 131, in check_key
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['clevis', 'decrypt']' returned non-zero exit status 1.
Unexpected journal message 'audit: type=1400 audit(1528793916.818:331): avc:  denied  { read } for  pid=1 comm="systemd" name="tang" dev="dm-0" ino=25361236 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tangd_db_t:s0 tclass=dir permissive=0'
Unexpected journal message 'audit: type=1400 audit(1528793916.857:332): avc:  denied  { getattr } for  pid=4931 comm="tangd" path="socket:[34942]" dev="sockfs" ino=34942 scontext=system_u:system_r:tangd_t:s0 tcontext=system_u:system_r:tangd_t:s0 tclass=tcp_socket permissive=1'
Unexpected journal message 'audit: type=1400 audit(1528793931.097:406): avc:  denied  { read } for  pid=1 comm="systemd" name="tang" dev="dm-0" ino=25361236 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tangd_db_t:s0 tclass=dir permissive=0'
Wrote JS log to TestStorage-testClevisTang-rhel-x-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testClevisTang-rhel-x-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 822, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1528793916.818:331): avc:  denied  { read } for  pid=1 comm="systemd" name="tang" dev="dm-0" ino=25361236 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tangd_db_t:s0 tclass=dir permissive=0

not ok 226 testClevisTang (check_storage_luks.TestStorage) # duration: 115s
Wrote screenshot to TestStorage-testClevisTang-rhel-x-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorage-testClevisTang-rhel-x-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorage-testClevisTang-rhel-x-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testClevisTang-rhel-x-127.0.0.2-2301-FAIL.log
```
First occurrence: 2018-06-12T08:58:54.255444 | revision 51017ca7db688f4ba394f051973ef49e7ad5c694, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9361-20180612-084646-51017ca7-verify-rhel-x/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-12T08:58:54.255444 | revision 51017ca7db688f4ba394f051973ef49e7ad5c694, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9361-20180612-084646-51017ca7-verify-rhel-x/log.html)
