### ISSUE TITLE
SELinux denies chronyd to read drift file

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9449]
Tests fail like this:
```
# testNotSupported (check_realms.TestRealms)

Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 823, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1529522975.001:4): avc:  denied  { read } for  pid=498 comm="chronyd" name="drift" dev="vda3" ino=13112955 scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=file
```

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1593449

**Comment by martinpitt** [comment]
Example: https://fedorapeople.org/groups/cockpit/logs/pull-9443-20180620-180303-19a2aa07-verify-rhel-7/log.html#133

**Comment by martinpitt** [comment]
This happens rarely and was sheer luck, but the bug hasn't been fixed yet. So let's keep the naughty issue open for now.

**Comment by martinpitt** [comment]
Still not fixed upstream.
