### ISSUE TITLE
SELinux denies post{master,conf} reading resolv.conf

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9450]
Test failure:
```
Unexpected journal message 'type=1400 audit(1529522308.239:4): avc:  denied  { read } for  pid=891 comm="postfix" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.437:5): avc:  denied  { read } for  pid=932 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.550:6): avc:  denied  { read } for  pid=958 comm="master" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.704:7): avc:  denied  { read } for  pid=972 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.891:8): avc:  denied  { read } for  pid=1014 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.994:9): avc:  denied  { read } for  pid=1061 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.086:10): avc:  denied  { read } for  pid=1087 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.195:11): avc:  denied  { read } for  pid=1126 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.337:12): avc:  denied  { read } for  pid=1151 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.461:13): avc:  denied  { read } for  pid=1182 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.566:14): avc:  denied  { read } for  pid=1203 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.663:15): avc:  denied  { read } for  pid=1238 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.772:16): avc:  denied  { read } for  pid=1258 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.908:17): avc:  denied  { read } for  pid=1268 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522310.008:18): avc:  denied  { read } for  pid=1279 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Wrote JS log to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.log
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 823, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1529522308.239:4): avc:  denied  { read } for  pid=891 comm="postfix" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file
```

Seen on https://fedorapeople.org/groups/cockpit/logs/pull-9443-20180620-190909-19a2aa07-verify-centos-7/log.html#231

I will report this to RHEL once we get a log that it actually happens on RHEL 7.5 too, not just on CentOS. Otherwise I will report it directly to CentOS.

**Comment by martinpitt** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
# testBasic (check_kdump.TestKdump)
#
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
Created symlink from /etc/systemd/system/multi-user.target.wants/kdump.service to /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code. See "systemctl status kdump.service" and "journalctl -xe" for details.
[0620/191638.746167:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9476/devtools/browser/03c236ac-8c63-4b8c-a122-bc03102ff4c4
[0620/191638.769326:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 114985: Permission denied (13)
[0620/191639.696945:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 115102: Permission denied (13)
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-3.10.0-862.3.2.el7.x86_64
Found initrd image: /boot/initramfs-3.10.0-862.3.2.el7.x86_64.img
Found linux image: /boot/vmlinuz-3.10.0-862.el7.x86_64
Found initrd image: /boot/initramfs-3.10.0-862.el7.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-fee965724a3d31b0a8470d53dd5fdf87
Found initrd image: /boot/initramfs-0-rescue-fee965724a3d31b0a8470d53dd5fdf87.img
Found linux image: /boot/vmlinuz-0-rescue-c2b5013e25f5437b95745cc9b1f64382
Found initrd image: /boot/initramfs-0-rescue-c2b5013e25f5437b95745cc9b1f64382.img
done
Connection to 127.0.0.2 closed by remote host.
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1529522209342.53,"url":"http://127.0.0.2:9091/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"115102.28"}
ssh_exchange_identification: read: Connection reset by peer
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"9"}
> log: transport closed, dropped message:  1:1!5
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"10"}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_CONNECTION_RESET","timestamp":1529522311551.98,"url":"http://127.0.0.2:9091/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"115102.134"}
Connection to 127.0.0.2 closed by remote host.
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
Unexpected journal message 'type=1400 audit(1529522308.239:4): avc:  denied  { read } for  pid=891 comm="postfix" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.437:5): avc:  denied  { read } for  pid=932 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.550:6): avc:  denied  { read } for  pid=958 comm="master" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.704:7): avc:  denied  { read } for  pid=972 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.891:8): avc:  denied  { read } for  pid=1014 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522308.994:9): avc:  denied  { read } for  pid=1061 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.086:10): avc:  denied  { read } for  pid=1087 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.195:11): avc:  denied  { read } for  pid=1126 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.337:12): avc:  denied  { read } for  pid=1151 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.461:13): avc:  denied  { read } for  pid=1182 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.566:14): avc:  denied  { read } for  pid=1203 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.663:15): avc:  denied  { read } for  pid=1238 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.772:16): avc:  denied  { read } for  pid=1258 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522309.908:17): avc:  denied  { read } for  pid=1268 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Unexpected journal message 'type=1400 audit(1529522310.008:18): avc:  denied  { read } for  pid=1279 comm="postconf" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file'
Wrote JS log to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.log
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 823, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1529522308.239:4): avc:  denied  { read } for  pid=891 comm="postfix" name="resolv.conf" dev="vda4" ino=5667184 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file

not ok 231 testBasic (check_kdump.TestKdump) # duration: 141s
Wrote screenshot to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.html
Wrote JS log to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestKdump-testBasic-centos-7-127.0.0.2-2201-FAIL.log
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
```
First occurrence: 2018-06-20T23:12:44.044753
Times recorded: 1
Latest occurrences:

- 2018-06-20T23:12:44.044753

**Comment by martinpitt** [comment]
I want to give this one more round to verify it's really fixed now.
