### ISSUE TITLE
RHEL: firewalld triggers an selinux-policy error loading nft modules

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#9462]
https://bugzilla.redhat.com/show_bug.cgi?id=1593687

Example:

```
Error: audit: type=1400 audit(1529580634.564:324): avc:  denied  { module_request } for  pid=3272 comm="nft" kmod="nfnetlink-subsys-10" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
```

A failure here: https://fedorapeople.org/groups/cockpit/logs/pull-9429-20180621-110808-8372eedf-verify-rhel-x/log.html#53

**Comment by stefwalter** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# testTeamActive (check_networking_team.TestNetworking)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       627fb4a2-0567-4723-9c09-9da749051d3d  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
enp0s2       5c00d3b8-f66b-424e-a3dd-4ee4af6f1af3  ethernet  --     

[0621/113022.556073:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9575/devtools/browser/cb094540-baae-41a8-8163-ea59a92b544e
[0621/113022.616874:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 922594: Permission denied (13)
[0621/113023.555760:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 922663: Permission denied (13)
52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
Unexpected journal message 'audit: type=1400 audit(1529580634.564:324): avc:  denied  { module_request } for  pid=3272 comm="nft" kmod="nfnetlink-subsys-10" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0'
Unexpected journal message 'audit: type=1400 audit(1529580634.564:325): avc:  denied  { module_request } for  pid=3272 comm="nft" kmod="nfnetlink-subsys-10" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0'
Unexpected journal message 'audit: type=1400 audit(1529580634.564:326): avc:  denied  { module_request } for  pid=3272 comm="nft" kmod="nfnetlink-subsys-10" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0'
Unexpected journal message 'audit: type=1400 audit(1529580634.598:327): avc:  denied  { module_request } for  pid=3272 comm="nft" kmod="nfnetlink-subsys-10" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0'
Wrote JS log to TestNetworking-testTeamActive-rhel-x-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestNetworking-testTeamActive-rhel-x-127.0.0.2-2301-FAIL.log
Journal extracted to TestNetworking-testTeamActive-fedora-28-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 823, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1529580634.564:324): avc:  denied  { module_request } for  pid=3272 comm="nft" kmod="nfnetlink-subsys-10" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0

not ok 53 testTeamActive (check_networking_team.TestNetworking) # duration: 45s
Wrote screenshot to TestNetworking-testTeamActive-rhel-x-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestNetworking-testTeamActive-rhel-x-127.0.0.2-2301-FAIL.html
Wrote JS log to TestNetworking-testTeamActive-rhel-x-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestNetworking-testTeamActive-rhel-x-127.0.0.2-2301-FAIL.log
Journal extracted to TestNetworking-testTeamActive-fedora-28-127.0.0.2-2302-FAIL.log
```
First occurrence: 2018-06-21T13:56:48.007036
Times recorded: 1
Latest occurrences:

- 2018-06-21T13:56:48.007036

**Comment by stefwalter** [comment]
Duplicate of #9261
