### ISSUE TITLE
Ubuntu: libvirtd crashes in pci_get_strings

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#9486]
libvirtd crashes routinely in pci_get_strings on Ubuntu stable.

https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/746064

**Comment by cockpituous** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMtu (check_networking_mtu.TestNetworking)
#
NAME                UUID                                  TYPE      DEVICE 
Wired connection 1  cc94f4e1-a94e-342e-87eb-e06312d0a7c7  ethernet  eth1   

[0626/090527.191939:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:9844/devtools/browser/6a772684-7e0f-4111-bc6c-48117aff9c3d
[0626/090527.240486:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 121813: Permission denied (13)
[0626/090528.268266:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 121850: Permission denied (13)
52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
Process 565 (libvirtd) of user 0 dumped core.

Stack trace of thread 711:
#0  0x00007f9aec10ee93 n/a (libpciaccess.so.0)
#1  0x00007f9aec10ef92 n/a (libpciaccess.so.0)
#2  0x00007f9aec10f073 pci_get_strings (libpciaccess.so.0)
#3  0x00007f9aec31eaa1 n/a (libvirt_driver_nodedev.so)
#4  0x00007f9aec320320 n/a (libvirt_driver_nodedev.so)
#5  0x00007f9b1d5b9ad2 n/a (libvirt.so.0)
#6  0x00007f9b1cc636db start_thread (libpthread.so.0)
#7  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 600:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 601:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 602:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 603:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 604:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 605:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba778 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 606:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba778 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 607:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba778 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 608:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba778 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 609:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba778 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 656:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 657:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 658:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 659:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 660:
#0  0x00007f9b1cc699f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f9b1d5b9d06 virCondWait (libvirt.so.0)
#2  0x00007f9b1d5ba843 n/a (libvirt.so.0)
#3  0x00007f9b1d5b9aa8 n/a (libvirt.so.0)
#4  0x00007f9b1cc636db start_thread (libpthread.so.0)
#5  0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 661:
#0  0x00007f9b1c97fbf9 __GI___poll (libc.so.6)
#1  0x00007f9b1d54f803 n/a (libvirt.so.0)
#2  0x00007f9b1d5539ff virCommandRun (libvirt.so.0)
#3  0x00007f9b1d56c546 n/a (libvirt.so.0)
#4  0x00007f9b1d56c8df n/a (libvirt.so.0)
#5  0x00007f9b1d56caaf n/a (libvirt.so.0)
#6  0x00007f9b1cc6b827 __pthread_once_slow (libpthread.so.0)
#7  0x00007f9b1d56c4d7 n/a (libvirt.so.0)
#8  0x00007f9b1d56d2a9 virFirewallNew (libvirt.so.0)
#9  0x00007f9adef0a512 n/a (libvirt_driver_nwfilter.so)
#10 0x00007f9adeeff79d virNWFilterTechDriversInit (libvirt_driver_nwfilter.so)
#11 0x00007f9adeefe5ad n/a (libvirt_driver_nwfilter.so)
#12 0x00007f9b1d663db5 virStateInitialize (libvirt.so.0)
#13 0x0000561b167b6beb n/a (libvirtd)
#14 0x00007f9b1d5b9ad2 n/a (libvirt.so.0)
#15 0x00007f9b1cc636db start_thread (libpthread.so.0)
#16 0x00007f9b1c98c88f __clone (libc.so.6)

Stack trace of thread 565:
#0  0x00007f9b1cc700e0 __errno_location (libpthread.so.0)
#1  0x00007f9b1d5426cc virFree (libvirt.so.0)
#2  0x00007f9b1d581586 virLogVMessage (libvirt.so.0)
#3  0x00007f9b1d581b6b virLogMessage (libvirt.so.0)
#4  0x00007f9b1d5625ab virEventPollRunOnce (libvirt.so.0)
#5  0x00007f9b1d561331 virEventRunDefaultImpl (libvirt.so.0)
#6  0x00007f9b1d6d9f35 virNetDaemonRun (libvirt.so.0)
#7  0x0000561b167b52ca n/a (libvirtd)
#8  0x00007f9b1c88cb97 __libc_start_main (libc.so.6)
#9  0x0000561b167b688a n/a (libvirtd)

Stack trace of thread 729:
#0  0x00007f9b1c97af44 __libc_openat64 (libc.so.6)
#1  0x00007f9b19942086 n/a (libudev.so.1)
#2  0x00007f9b19948fd3 n/a (libudev.so.1)
#3  0x00007f9b19949511 n/a (libudev.so.1)
#4  0x00007f9b199507c2 udev_device_new_from_syspath (libudev.so.1)
#5  0x00007f9aec31fef6 n/a (libvirt_driver_nodedev.so)
#6  0x00007f9b1d5b9ad2 n/a (libvirt.so.0)
#7  0x00007f9b1cc636db start_thread (libpthread.so.0)
#8  0x00007f9b1c98c88f __clone (libc.so.6)

Wrote JS log to TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.log
Journal extracted to TestNetworking-testMtu-fedora-28-127.0.0.2-2902-FAIL.log
Core dumps downloaded to /build/cockpit/TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 832, in check_journal_messages
    raise Error(first)
Error: Process 565 (libvirtd) of user 0 dumped core.

not ok 87 testMtu (check_networking_mtu.TestNetworking) # duration: 44s
Wrote screenshot to TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.html
Wrote JS log to TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.log
Journal extracted to TestNetworking-testMtu-fedora-28-127.0.0.2-2902-FAIL.log
Core dumps downloaded to /build/cockpit/TestNetworking-testMtu-ubuntu-stable-127.0.0.2-2901-FAIL.core
```
First occurrence: 2018-06-26T09:05:44.308390 | revision 37ea2d28b6e6144cb764cb42ad04567e484dc3cc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9482-20180626-084444-37ea2d28-verify-ubuntu-stable/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-26T09:05:44.308390 | revision 37ea2d28b6e6144cb764cb42ad04567e484dc3cc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9482-20180626-084444-37ea2d28-verify-ubuntu-stable/log.html)

**Comment by cockpituous** [comment]
verify/ubuntu-1804
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSocket (check_connection.TestConnection)
#
Unexpected journal messages:
Process 569 (libvirtd) of user 0 dumped core.
Stack trace of thread 708:
#0  0x00007f4990a9a836 _int_realloc (libc.so.6)
#1  0x00007f4990a9df9b __GI___libc_realloc (libc.so.6)
#2  0x00007f4960318dbc n/a (libpciaccess.so.0)
#3  0x00007f4960318f92 n/a (libpciaccess.so.0)
#4  0x00007f4960319073 pci_get_strings (libpciaccess.so.0)
#5  0x00007f4960528aa1 n/a (libvirt_driver_nodedev.so)
#6  0x00007f496052a320 n/a (libvirt_driver_nodedev.so)
#7  0x00007f4991753932 n/a (libvirt.so.0)
#8  0x00007f4990dfd6db start_thread (libpthread.so.0)
#9  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 596:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 597:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 598:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 599:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 600:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 601:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917545d8 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 602:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917545d8 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 603:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917545d8 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 604:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917545d8 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 605:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917545d8 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 654:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 655:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 656:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 657:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 658:
#0  0x00007f4990e039f3 futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4991753b66 virCondWait (libvirt.so.0)
#2  0x00007f49917546a3 n/a (libvirt.so.0)
#3  0x00007f4991753908 n/a (libvirt.so.0)
#4  0x00007f4990dfd6db start_thread (libpthread.so.0)
#5  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 659:
#0  0x00007f4990b19bf9 __GI___poll (libc.so.6)
#1  0x00007f49916e9853 n/a (libvirt.so.0)
#2  0x00007f49916eda4f virCommandRun (libvirt.so.0)
#3  0x00007f4991706596 n/a (libvirt.so.0)
#4  0x00007f499170692f n/a (libvirt.so.0)
#5  0x00007f4991706aff n/a (libvirt.so.0)
#6  0x00007f4990e05827 __pthread_once_slow (libpthread.so.0)
#7  0x00007f4991706527 n/a (libvirt.so.0)
#8  0x00007f49917072f9 virFirewallNew (libvirt.so.0)
#9  0x00007f4953114512 n/a (libvirt_driver_nwfilter.so)
#10 0x00007f495310979d virNWFilterTechDriversInit (libvirt_driver_nwfilter.so)
#11 0x00007f49531085ad n/a (libvirt_driver_nwfilter.so)
#12 0x00007f49917fdc15 virStateInitialize (libvirt.so.0)
#13 0x0000557a13d9dbeb n/a (libvirtd)
#14 0x00007f4991753932 n/a (libvirt.so.0)
#15 0x00007f4990dfd6db start_thread (libpthread.so.0)
#16 0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 728:
#0  0x00007f4990b356d9 __lll_unlock_wake_private (libc.so.6)
#1  0x00007f4990a9dfc8 __GI___libc_realloc (libc.so.6)
#2  0x00007f4960318dbc n/a (libpciaccess.so.0)
#3  0x00007f4960318f92 n/a (libpciaccess.so.0)
#4  0x00007f4960319073 pci_get_strings (libpciaccess.so.0)
#5  0x00007f4960528aa1 n/a (libvirt_driver_nodedev.so)
#6  0x00007f4960529f06 n/a (libvirt_driver_nodedev.so)
#7  0x00007f4991753932 n/a (libvirt.so.0)
#8  0x00007f4990dfd6db start_thread (libpthread.so.0)
#9  0x00007f4990b2688f __clone (libc.so.6)
Stack trace of thread 569:
#0  0x00007f499171a3d9 n/a (libvirt.so.0)
#1  0x00007f499171b37e virLogVMessage (libvirt.so.0)
#2  0x00007f499171b99b virLogMessage (libvirt.so.0)
#3  0x00007f49916fb624 n/a (libvirt.so.0)
#4  0x00007f49916fc4fe virEventPollRunOnce (libvirt.so.0)
#5  0x00007f49916fb381 virEventRunDefaultImpl (libvirt.so.0)
#6  0x00007f4991873d95 virNetDaemonRun (libvirt.so.0)
#7  0x0000557a13d9c2ca n/a (libvirtd)
#8  0x00007f4990a26b97 __libc_start_main (libc.so.6)
#9  0x0000557a13d9d88a n/a (libvirtd)
Journal extracted to TestConnection-testSocket-ubuntu-1804-127.0.0.2-2201-FAIL.log
Core dumps downloaded to /build/cockpit/TestConnection-testSocket-ubuntu-1804-127.0.0.2-2201-FAIL.core
Journal extracted to TestConnection-testSocket-ubuntu-1804-127.0.0.2-2201-FAIL.log
Core dumps downloaded to /build/cockpit/TestConnection-testSocket-ubuntu-1804-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 692, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 871, in check_journal_messages
    raise Error(first)
testlib.Error: Process 569 (libvirtd) of user 0 dumped core.

not ok 221 testSocket (check_connection.TestConnection) # duration: 20s
```
First occurrence: 2018-10-23T13:59:50.587242 | revision c27d586c667276d03e056c5447df0cb1b3b8febf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10409-20181023-135151-c27d586c-verify-ubuntu-1804/log.html)
Times recorded: 1
Latest occurrences:

- 2018-10-23T13:59:50.587242 | revision c27d586c667276d03e056c5447df0cb1b3b8febf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10409-20181023-135151-c27d586c-verify-ubuntu-1804/log.html)
