### ISSUE TITLE
Ubuntu: nsupdate asserts in dns_name_clone

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#9487]
The nsupdate command asserts routinely in isc_assertion_failed.

https://launchpad.net/bugs/1778641

```
Process 8276 (nsupdate) of user 0 dumped core.

Stack trace of thread 8279:
#0  0x00007f5c584f5428 __GI_raise (libc.so.6)
#1  0x00007f5c584f702a __GI_abort (libc.so.6)
#2  0x00007f5c5889ce7f isc_assertion_failed (libisc.so.160)
#3  0x00007f5c59281895 dns_name_clone (libdns.so.162)
#4  0x0000561cdd7b16be n/a (nsupdate)
#5  0x0000561cdd7b319b n/a (nsupdate)
#6  0x0000561cdd7b46d2 n/a (nsupdate)
#7  0x00007f5c588c1360 n/a (libisc.so.160)
#8  0x00007f5c582aa6ba start_thread (libpthread.so.0)
#9  0x00007f5c585c741d __clone (libc.so.6)
```

**Comment by martinpitt** [comment]
This was fixed two months ago in ubuntu-1604 already; is that really the right bug?

**Comment by cockpituous** [comment]
verify/ubuntu-1604
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNegotiate (check_realms.TestKerberos)
#
+ seq 1 20
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ break
+ realm join -vU admin cockpit.lan
+ echo foobarfoo
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Unconditionally checking packages
 * Resolving required packages
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time with KDC...
Attempting to sync time using ntpd.  Will timeout after 15 seconds
Unable to sync time with NTP server, assuming the time is in sync. Please check that 123 UDP port is opened.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  Fri May 25 08:18:46 2018 UTC
    Valid Until: Tue May 25 08:18:46 2038 UTC

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
New SSSD config will be created
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
trying https://f0.cockpit.lan/ipa/json
Forwarding 'ping' to json server 'https://f0.cockpit.lan/ipa/json'
Forwarding 'ca_is_enabled' to json server 'https://f0.cockpit.lan/ipa/json'
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Failed to update DNS records.
Missing A/AAAA record(s) for host x0.cockpit.lan: 10.111.113.1.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_dsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Forwarding 'host_mod' to json server 'https://f0.cockpit.lan/ipa/json'
Could not update DNS SSHFP records.
SSSD enabled
Configured /etc/openldap/ldap.conf
No SRV records of NTP servers found. IPA server address will be used
NTP enabled
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.

 * /usr/sbin/update-rc.d sssd enable
update-rc.d: error: cannot find a LSB script for sssd
 * /usr/sbin/service sssd restart
 * Successfully enrolled machine in realm
+ seq 1 20
+ KRB5_TRACE=/dev/stderr kinit -f admin@COCKPIT.LAN
+ echo foobarfoo
[8364] 1529823069.469391: Getting initial credentials for admin@COCKPIT.LAN
[8364] 1529823069.469776: Sending request (164 bytes) to COCKPIT.LAN
[8364] 1529823069.470209: Initiating TCP connection to stream 10.111.112.100:88
[8364] 1529823069.471477: Sending TCP request to stream 10.111.112.100:88
[8364] 1529823069.481223: Received answer (492 bytes) from stream 10.111.112.100:88
[8364] 1529823069.481642: Terminating TCP connection to stream 10.111.112.100:88
[8364] 1529823069.482154: Response was from master KDC
[8364] 1529823069.482486: Received error from KDC: -1765328359/Additional pre-authentication required
[8364] 1529823069.482857: Processing preauth types: 16, 15, 14, 136, 19, 147, 151, 2, 133
[8364] 1529823069.482885: Selected etype info: etype aes256-cts, salt "4Gc$s Ukh"@F4?D:", params ""
[8364] 1529823069.482929: Received cookie: MIT1\x00\x00\x00\x01%3\xd4\xda\xc8T\xfd\xed\xe1Aj\xd9>\x0c4\xe0QO\x7f\xe0v\xdb\xc7\xf8\xfd\xd1\xff\x126\xba\x92\xc8\x9d4X\xb4\x09\x05\\x85\x15\xc8\x838\x19X\x15\x15#\xba\xac\x1f\x800!\xc4\xea\xad\xf6\xc5\x0b\xe5a\xa5;\xe3\x1en\x9f\xc9p\xa0\x88\xa5\x0f\xcf\xdf\xeb\xbeD}\x8eA\x88o^\xdb\x8br\x1d\xfc\xbenV\xd2\xdd\x7f\x89eX\xb1\xc8\x90\x068\x9c\x9b\x07b\xb2aV\x9aB\x0b\x09us'\x9e72\x85]6\xb1!\x8eW;
[8364] 1529823069.515322: AS key obtained for encrypted timestamp: aes256-cts/A782
[8364] 1529823069.515899: Encrypted timestamp (for 1529823068.469405): plain 301AA011180F32303138303632343036353130385AA105020307299D, encrypted 52AD834AAFEFBBF75CCFD7E98DDE71B59F20ACDDF393204F2625BD524FB7A535ED36D8C110BF4A8EBB59444EC4B583A5E9D7695FF2B57D6C
[8364] 1529823069.520324: Preauth module encrypted_timestamp (2) (real) returned: 0/Success
[8364] 1529823069.520682: Produced preauth for next request: 133, 2
[8364] 1529823069.520895: Sending request (399 bytes) to COCKPIT.LAN
[8364] 1529823069.521159: Initiating TCP connection to stream 10.111.112.100:88
[8364] 1529823069.522071: Sending TCP request to stream 10.111.112.100:88
[8364] 1529823069.525948: Received answer (724 bytes) from stream 10.111.112.100:88
[8364] 1529823069.526161: Terminating TCP connection to stream 10.111.112.100:88
[8364] 1529823069.526489: Response was from master KDC
[8364] 1529823069.526712: Processing preauth types: 19
[8364] 1529823069.526911: Selected etype info: etype aes256-cts, salt "4Gc$s Ukh"@F4?D:", params ""
[8364] 1529823069.527116: Produced preauth for next request: (empty)
[8364] 1529823069.527362: AS key determined by preauth: aes256-cts/A782
[8364] 1529823069.527410: Decrypted AS reply; session key is: aes256-cts/78D3
[8364] 1529823069.527422: FAST negotiation: available
[8364] 1529823069.527433: Initializing KEYRING:persistent:0:0 with default princ admin@COCKPIT.LAN
[8364] 1529823069.527739: Storing admin@COCKPIT.LAN -> krbtgt/COCKPIT.LAN@COCKPIT.LAN in KEYRING:persistent:0:0
[8364] 1529823069.528480: Storing config in KEYRING:persistent:0:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: fast_avail: yes
[8364] 1529823069.528516: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/fast_avail/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KEYRING:persistent:0:0
[8364] 1529823069.528926: Storing config in KEYRING:persistent:0:0 for krbtgt/COCKPIT.LAN@COCKPIT.LAN: pa_type: 2
[8364] 1529823069.528946: Storing admin@COCKPIT.LAN -> krb5_ccache_conf_data/pa_type/krbtgt\/COCKPIT.LAN\@COCKPIT.LAN@X-CACHECONF: in KEYRING:persistent:0:0
+ break
+ type ipa
+ curl --insecure -s --negotiate -u : https://f0.cockpit.lan/ipa/json --header Referer: https://f0.cockpit.lan/ipa --header Content-Type: application/json --header Accept: application/json --data {"params": [["HTTP/x0.cockpit.lan@COCKPIT.LAN"], {"raw": false, "all": false, "version": "2.101", "force": true, "no_members": false, "ipakrbokasdelegate": true}], "method": "service_add", "id": 0}
+ ipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab
Failed to parse result: Failed to decode GetKeytab Control.

Retrying with pre-4.0 keytab retrieval method...
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab
+ seq 1 60
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
+ seq 1 60
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
[0624/065114.782619:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10120/devtools/browser/ef7387c9-1b8e-4a92-a567-7eb7d3261e9e
[0624/065114.842672:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 58480: Permission denied (13)
[0624/065115.876786:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 58528: Permission denied (13)
> warning: Error opening directory '/home/admin/.ssh': No such file or directory
> warning: --: 26: cd: can't cd to /home/admin/.ssh

Process 8230 (nsupdate) of user 0 dumped core.

Stack trace of thread 8233:
#0  0x00007f587a039428 __GI_raise (libc.so.6)
#1  0x00007f587a03b02a __GI_abort (libc.so.6)
#2  0x00007f587a3e0e7f isc_assertion_failed (libisc.so.160)
#3  0x00007f587adc5895 dns_name_clone (libdns.so.162)
#4  0x0000564b4d3006be n/a (nsupdate)
#5  0x0000564b4d30219b n/a (nsupdate)
#6  0x0000564b4d3036d2 n/a (nsupdate)
#7  0x00007f587a405360 n/a (libisc.so.160)
#8  0x00007f5879dee6ba start_thread (libpthread.so.0)
#9  0x00007f587a10b41d __clone (libc.so.6)

Stack trace of thread 8230:
#0  0x00007f587a039826 __GI___sigsuspend (libc.so.6)
#1  0x00007f587a40d8c9 isc__app_ctxrun (libisc.so.160)
#2  0x00007f587a40e37b isc_app_run (libisc.so.160)
#3  0x0000564b4d2fe97f n/a (nsupdate)
#4  0x00007f587a024830 __libc_start_main (libc.so.6)
#5  0x0000564b4d2fecb9 n/a (nsupdate)

Stack trace of thread 8231:
#0  0x00007f587a10ba13 epoll_wait (libc.so.6)
#1  0x00007f587a417bae n/a (libisc.so.160)
#2  0x00007f5879dee6ba start_thread (libpthread.so.0)
#3  0x00007f587a10b41d __clone (libc.so.6)

Stack trace of thread 8232:
#0  0x00007f5879df4360 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f587a40a73a n/a (libisc.so.160)
#2  0x00007f5879dee6ba start_thread (libpthread.so.0)
#3  0x00007f587a10b41d __clone (libc.so.6)

Journal extracted to TestKerberos-testNegotiate-ubuntu-1604-127.0.0.2-2601-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2602-FAIL.log
scp: /var/lib/systemd/coredump/.#core.nsupdate.0.b1e0f9ab82594a70b94df0beeac86888.8367.1529823069000000000000.xz20ee230995a70e3f: No such file or directory
scp: /var/lib/systemd/coredump/.#core.nsupdate.0.b1e0f9ab82594a70b94df0beeac86888.8279.1529823067000000000000.xz5058f4384d036b7d: No such file or directory
scp: /var/lib/systemd/coredump/.#core.nsupdate.0.b1e0f9ab82594a70b94df0beeac86888.8367.1529823069000000000000a1874651992f39b0: No such file or directory
Core dumps downloaded to /build/cockpit/TestKerberos-testNegotiate-ubuntu-1604-127.0.0.2-2601-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 832, in check_journal_messages
    raise Error(first)
Error: Process 8230 (nsupdate) of user 0 dumped core.

not ok 127 testNegotiate (check_realms.TestKerberos) # duration: 84s
Journal extracted to TestKerberos-testNegotiate-ubuntu-1604-127.0.0.2-2601-FAIL.log
Journal extracted to TestKerberos-testNegotiate-ipa-127.0.0.2-2602-FAIL.log
Core dumps downloaded to /build/cockpit/TestKerberos-testNegotiate-ubuntu-1604-127.0.0.2-2601-FAIL.core
```
First occurrence: 2018-06-24T06:51:28.416997 | revision 0c5cf4dc07e579e0dc63f7bc3bacd177003ed207, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9482-20180624-063333-0c5cf4dc-verify-ubuntu-1604/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-24T06:51:28.416997 | revision 0c5cf4dc07e579e0dc63f7bc3bacd177003ed207, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9482-20180624-063333-0c5cf4dc-verify-ubuntu-1604/log.html)

**Comment by cockpituous** [comment]
verify/ubuntu-1604
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
[0624/065109.710688:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9951/devtools/browser/2e7a8456-d465-4479-a508-d83b5f06a457
[0624/065109.747619:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 58183: Permission denied (13)
[0624/065110.795323:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 58235: Permission denied (13)
klist: Credentials cache keyring 'persistent:0:0' not found
klist: Credentials cache keyring 'persistent:1001:1001' not found
> log: Failed to clean up SPN from /etc/cockpit/krb5.keytab: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
> log: Failed to join domain: cockpit.lan: Already running another action
Process 8275 (nsupdate) of user 0 dumped core.

Stack trace of thread 8278:
#0  0x00007f4767355428 __GI_raise (libc.so.6)
#1  0x00007f476735702a __GI_abort (libc.so.6)
#2  0x00007f47676fce7f isc_assertion_failed (libisc.so.160)
#3  0x00007f47680e1895 dns_name_clone (libdns.so.162)
#4  0x000055d2040f46be n/a (nsupdate)
#5  0x000055d2040f619b n/a (nsupdate)
#6  0x000055d2040f76d2 n/a (nsupdate)
#7  0x00007f4767721360 n/a (libisc.so.160)
#8  0x00007f476710a6ba start_thread (libpthread.so.0)
#9  0x00007f476742741d __clone (libc.so.6)

Stack trace of thread 8275:
#0  0x00007f4767355826 __GI___sigsuspend (libc.so.6)
#1  0x00007f47677298c9 isc__app_ctxrun (libisc.so.160)
#2  0x00007f476772a37b isc_app_run (libisc.so.160)
#3  0x000055d2040f297f n/a (nsupdate)
#4  0x00007f4767340830 __libc_start_main (libc.so.6)
#5  0x000055d2040f2cb9 n/a (nsupdate)

Stack trace of thread 8276:
#0  0x00007f4767427a13 epoll_wait (libc.so.6)
#1  0x00007f4767733bae n/a (libisc.so.160)
#2  0x00007f476710a6ba start_thread (libpthread.so.0)
#3  0x00007f476742741d __clone (libc.so.6)

Stack trace of thread 8277:
#0  0x00007f4767110360 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f476772673a n/a (libisc.so.160)
#2  0x00007f476710a6ba start_thread (libpthread.so.0)
#3  0x00007f476742741d __clone (libc.so.6)

Process 8284 (nsupdate) of user 0 dumped core.

Stack trace of thread 8287:
#0  0x00007f24a49b0428 __GI_raise (libc.so.6)
#1  0x00007f24a49b202a __GI_abort (libc.so.6)
#2  0x00007f24a4d57e7f isc_assertion_failed (libisc.so.160)
#3  0x00007f24a573c895 dns_name_clone (libdns.so.162)
#4  0x00005626946266be n/a (nsupdate)
#5  0x000056269462819b n/a (nsupdate)
#6  0x00005626946296d2 n/a (nsupdate)
#7  0x00007f24a4d7c360 n/a (libisc.so.160)
#8  0x00007f24a47656ba start_thread (libpthread.so.0)
#9  0x00007f24a4a8241d __clone (libc.so.6)

Stack trace of thread 8284:
#0  0x00007f24a49b0826 __GI___sigsuspend (libc.so.6)
#1  0x00007f24a4d848c9 isc__app_ctxrun (libisc.so.160)
#2  0x00007f24a4d8537b isc_app_run (libisc.so.160)
#3  0x000056269462497f n/a (nsupdate)
#4  0x00007f24a499b830 __libc_start_main (libc.so.6)
#5  0x0000562694624cb9 n/a (nsupdate)

Stack trace of thread 8285:
#0  0x00007f24a4a82a13 epoll_wait (libc.so.6)
#1  0x00007f24a4d8ebae n/a (libisc.so.160)
#2  0x00007f24a47656ba start_thread (libpthread.so.0)
#3  0x00007f24a4a8241d __clone (libc.so.6)

Stack trace of thread 8286:
#0  0x00007f24a476b360 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f24a4d8173a n/a (libisc.so.160)
#2  0x00007f24a47656ba start_thread (libpthread.so.0)
#3  0x00007f24a4a8241d __clone (libc.so.6)

Process 8414 (nsupdate) of user 0 dumped core.

Stack trace of thread 8420:
#0  0x00007f528cab7428 __GI_raise (libc.so.6)
#1  0x00007f528cab902a __GI_abort (libc.so.6)
#2  0x00007f528ce5ee7f isc_assertion_failed (libisc.so.160)
#3  0x00007f528d843895 dns_name_clone (libdns.so.162)
#4  0x00005614ac04a6be n/a (nsupdate)
#5  0x00005614ac04c19b n/a (nsupdate)
#6  0x00005614ac04d6d2 n/a (nsupdate)
#7  0x00007f528ce83360 n/a (libisc.so.160)
#8  0x00007f528c86c6ba start_thread (libpthread.so.0)
#9  0x00007f528cb8941d __clone (libc.so.6)

Stack trace of thread 8414:
#0  0x00007f528cab7826 __GI___sigsuspend (libc.so.6)
#1  0x00007f528ce8b8c9 isc__app_ctxrun (libisc.so.160)
#2  0x00007f528ce8c37b isc_app_run (libisc.so.160)
#3  0x00005614ac04897f n/a (nsupdate)
#4  0x00007f528caa2830 __libc_start_main (libc.so.6)
#5  0x00005614ac048cb9 n/a (nsupdate)

Stack trace of thread 8418:
#0  0x00007f528cb89a13 epoll_wait (libc.so.6)
#1  0x00007f528ce95bae n/a (libisc.so.160)
#2  0x00007f528c86c6ba start_thread (libpthread.so.0)
#3  0x00007f528cb8941d __clone (libc.so.6)

Stack trace of thread 8419:
#0  0x00007f528c872360 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f528ce8873a n/a (libisc.so.160)
#2  0x00007f528c86c6ba start_thread (libpthread.so.0)
#3  0x00007f528cb8941d __clone (libc.so.6)

Process 8310 (nsupdate) of user 0 dumped core.

Stack trace of thread 8313:
#0  0x00007f5116a43428 __GI_raise (libc.so.6)
#1  0x00007f5116a4502a __GI_abort (libc.so.6)
#2  0x00007f5116deae7f isc_assertion_failed (libisc.so.160)
#3  0x00007f51177cf895 dns_name_clone (libdns.so.162)
#4  0x000055a7b38f66be n/a (nsupdate)
#5  0x000055a7b38f819b n/a (nsupdate)
#6  0x000055a7b38f96d2 n/a (nsupdate)
#7  0x00007f5116e0f360 n/a (libisc.so.160)
#8  0x00007f51167f86ba start_thread (libpthread.so.0)
#9  0x00007f5116b1541d __clone (libc.so.6)

Stack trace of thread 8310:
#0  0x00007f5116a43826 __GI___sigsuspend (libc.so.6)
#1  0x00007f5116e178c9 isc__app_ctxrun (libisc.so.160)
#2  0x00007f5116e1837b isc_app_run (libisc.so.160)
#3  0x000055a7b38f497f n/a (nsupdate)
#4  0x00007f5116a2e830 __libc_start_main (libc.so.6)
#5  0x000055a7b38f4cb9 n/a (nsupdate)

Stack trace of thread 8311:
#0  0x00007f5116b15a13 epoll_wait (libc.so.6)
#1  0x00007f5116e21bae n/a (libisc.so.160)
#2  0x00007f51167f86ba start_thread (libpthread.so.0)
#3  0x00007f5116b1541d __clone (libc.so.6)

Stack trace of thread 8312:
#0  0x00007f51167fe360 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f5116e1473a n/a (libisc.so.160)
#2  0x00007f51167f86ba start_thread (libpthread.so.0)
#3  0x00007f5116b1541d __clone (libc.so.6)

Wrote JS log to TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2902-FAIL.log
Core dumps downloaded to /build/cockpit/TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 832, in check_journal_messages
    raise Error(first)
Error: Process 8275 (nsupdate) of user 0 dumped core.

not ok 128 testIpa (check_realms.TestRealms) # duration: 131s
Wrote screenshot to TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.html
Wrote JS log to TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2902-FAIL.log
Core dumps downloaded to /build/cockpit/TestRealms-testIpa-ubuntu-1604-127.0.0.2-2901-FAIL.core
```
First occurrence: 2018-06-24T06:52:13.474473 | revision 0c5cf4dc07e579e0dc63f7bc3bacd177003ed207, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9482-20180624-063333-0c5cf4dc-verify-ubuntu-1604/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-24T06:52:13.474473 | revision 0c5cf4dc07e579e0dc63f7bc3bacd177003ed207, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9482-20180624-063333-0c5cf4dc-verify-ubuntu-1604/log.html)

**Comment by stefwalter** [comment]
> This was fixed two months ago in ubuntu-1604 already; is that really the right bug?

@martinpitt Maybe not the right bug, is there a better one? It's pretty crappy that nsupdate crashes so much.

**Comment by martinpitt** [comment]
@stefwalter: There is no existing bug report for it, but I did find one on errors.ubuntu.com. I created https://launchpad.net/bugs/1778641 for it and updated the description here.

**Comment by martinpitt** [comment]
obsolete
