### ISSUE TITLE
Fedora 28: SELinux prevents rpc.gssd from getattr

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#9505]
https://bugzilla.redhat.com/show_bug.cgi?id=1575234

Failure looks like this:

```
Error: audit: type=1400 audit(1529972895.393:87): avc:  denied  { getattr } for  pid=584 comm="gssproxy" path="/usr/sbin/rpc.gssd" dev="dm-0" ino=10308307 scontext=system_u:system_r:gssproxy_t:s0 tcontext=system_u:object_r:gssd_exec_t:s0 tclass=file permissive=0
```

**Comment by stefwalter** [comment]
verify/fedora-28
Ooops, it happened again<hr>
```
# testIpaUnqualifiedUsers (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2018-06-24 09:02:23
    Valid Until: 2038-06-24 09:02:23

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
New SSSD config will be created
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
trying https://f0.cockpit.lan/ipa/json
[try 1]: Forwarding 'schema' to json server 'https://f0.cockpit.lan/ipa/json'
trying https://f0.cockpit.lan/ipa/session/json
[try 1]: Forwarding 'ping' to json server 'https://f0.cockpit.lan/ipa/session/json'
[try 1]: Forwarding 'ca_is_enabled' to json server 'https://f0.cockpit.lan/ipa/session/json'
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
[try 1]: Forwarding 'host_mod' to json server 'https://f0.cockpit.lan/ipa/session/json'
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Unable to find 'admin' user with 'getent passwd admin@cockpit.lan'!
Unable to reliably detect configuration. Check NSS setup manually.
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful

Using default chrony configuration.
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/bin/authselect select sssd with-mkhomedir --force && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
Created symlink /etc/systemd/system/multi-user.target.wants/oddjobd.service ? /usr/lib/systemd/system/oddjobd.service.
 * Successfully enrolled machine in realm

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: [0626/002727.067461:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9988/devtools/browser/a1e4e85a-6a0e-44ac-9ba7-d3f3b67a1b6a
[0626/002727.160585:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 66072: Permission denied (13)
[0626/002728.352306:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 66134: Permission denied (13)
> warning: Shutdown scheduled for Mon 2018-06-25 20:27:41 EDT, use 'shutdown -c' to cancel.

> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1529972863547.67,"url":"http://127.0.0.2:9191/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"66134.28"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"9"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"10"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"11"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"12"}
Unexpected journal message 'audit: type=1400 audit(1529972895.393:87): avc:  denied  { getattr } for  pid=584 comm="gssproxy" path="/usr/sbin/rpc.gssd" dev="dm-0" ino=10308307 scontext=system_u:system_r:gssproxy_t:s0 tcontext=system_u:object_r:gssd_exec_t:s0 tclass=file permissive=0'
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2301-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 828, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1529972895.393:87): avc:  denied  { getattr } for  pid=584 comm="gssproxy" path="/usr/sbin/rpc.gssd" dev="dm-0" ino=10308307 scontext=system_u:system_r:gssproxy_t:s0 tcontext=system_u:object_r:gssd_exec_t:s0 tclass=file permissive=0

not ok 135 testIpaUnqualifiedUsers (check_realms.TestRealms) # duration: 251s
Wrote screenshot to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2301-FAIL.html
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-28-127.0.0.2-2301-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2302-FAIL.log


# Flake probability: 0.271 (clustering)
```
First occurrence: 2018-06-26T07:40:41.564926
Times recorded: 1
Latest occurrences:

- 2018-06-26T07:40:41.564926

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpaUnqualifiedUsers (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2018-06-24 09:02:23
    Valid Until: 2038-06-24 09:02:23

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
New SSSD config will be created
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
trying https://f0.cockpit.lan/ipa/json
[try 1]: Forwarding 'schema' to json server 'https://f0.cockpit.lan/ipa/json'
trying https://f0.cockpit.lan/ipa/session/json
[try 1]: Forwarding 'ping' to json server 'https://f0.cockpit.lan/ipa/session/json'
[try 1]: Forwarding 'ca_is_enabled' to json server 'https://f0.cockpit.lan/ipa/session/json'
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
[try 1]: Forwarding 'host_mod' to json server 'https://f0.cockpit.lan/ipa/session/json'
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful

Using default chrony configuration.
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/bin/authselect select sssd with-mkhomedir --force && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
Created symlink /etc/systemd/system/multi-user.target.wants/oddjobd.service ? /usr/lib/systemd/system/oddjobd.service.
 * Successfully enrolled machine in realm
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: [0626/173430.082312:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9809/devtools/browser/0eb9a569-0cd3-40b1-a8e2-be82d7acf676
[0626/173430.114450:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 61821: Permission denied (13)
[0626/173430.542676:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 61857: Permission denied (13)
> warning: Shutdown scheduled for Tue 2018-06-26 13:34:34 EDT, use 'shutdown -c' to cancel.

> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1530034475181.78,"url":"http://127.0.0.2:9391/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"61857.28"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"3"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
Unexpected journal message 'audit: type=1400 audit(1530034483.695:83): avc:  denied  { getattr } for  pid=583 comm="gssproxy" path="/usr/sbin/rpc.gssd" dev="dm-0" ino=9439070 scontext=system_u:system_r:gssproxy_t:s0 tcontext=system_u:object_r:gssd_exec_t:s0 tclass=file permissive=0'
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-testing-127.0.0.2-2501-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2502-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 828, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1530034483.695:83): avc:  denied  { getattr } for  pid=583 comm="gssproxy" path="/usr/sbin/rpc.gssd" dev="dm-0" ino=9439070 scontext=system_u:system_r:gssproxy_t:s0 tcontext=system_u:object_r:gssd_exec_t:s0 tclass=file permissive=0

not ok 112 testIpaUnqualifiedUsers (check_realms.TestRealms) # duration: 182s
Wrote screenshot to TestRealms-testIpaUnqualifiedUsers-fedora-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestRealms-testIpaUnqualifiedUsers-fedora-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-testing-127.0.0.2-2501-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2502-FAIL.log
```
First occurrence: 2018-06-26T17:34:54.193087 | revision 3cdf437dbb120cfbbb7c3643dcbb342a29fd5381, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9490-20180626-171212-3cdf437d-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-26T17:34:54.193087 | revision 3cdf437dbb120cfbbb7c3643dcbb342a29fd5381, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9490-20180626-171212-3cdf437d-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpaUnqualifiedUsers (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2018-06-24 09:02:23
    Valid Until: 2038-06-24 09:02:23

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
New SSSD config will be created
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
trying https://f0.cockpit.lan/ipa/json
[try 1]: Forwarding 'schema' to json server 'https://f0.cockpit.lan/ipa/json'
trying https://f0.cockpit.lan/ipa/session/json
[try 1]: Forwarding 'ping' to json server 'https://f0.cockpit.lan/ipa/session/json'
[try 1]: Forwarding 'ca_is_enabled' to json server 'https://f0.cockpit.lan/ipa/session/json'
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
[try 1]: Forwarding 'host_mod' to json server 'https://f0.cockpit.lan/ipa/session/json'
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Unable to find 'admin' user with 'getent passwd admin@cockpit.lan'!
Unable to reliably detect configuration. Check NSS setup manually.
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful

Using default chrony configuration.
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/bin/authselect select sssd with-mkhomedir --force && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
Created symlink /etc/systemd/system/multi-user.target.wants/oddjobd.service ? /usr/lib/systemd/system/oddjobd.service.
 * Successfully enrolled machine in realm

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: [0725/105458.519409:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10198/devtools/browser/10cc6c3b-48dc-45be-8f17-c52784365be6
[0725/105458.619568:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 29912: Permission denied (13)
[0725/105458.871587:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 29938: Permission denied (13)
> warning: Shutdown scheduled for Wed 2018-07-25 06:55:08 EDT, use 'shutdown -c' to cancel.

> warning: transport closed: disconnected
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"3"}
ssh_exchange_identification: Connection closed by remote host
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1532516110739.45,"url":"http://127.0.0.2:9191/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"29938.28"}
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: read: Connection reset by peer
ssh_exchange_identification: Connection closed by remote host
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"9"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"10"}
Unexpected journal messages:
audit: type=1400 audit(1532516129.415:82): avc:  denied  { getattr } for  pid=418 comm="gssproxy" path="/usr/sbin/rpc.gssd" dev="vda4" ino=4702232 scontext=system_u:system_r:gssproxy_t:s0 tcontext=system_u:object_r:gssd_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-i386-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-i386-127.0.0.2-2301-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2302-FAIL.log
Wrote screenshot to TestRealms-testIpaUnqualifiedUsers-fedora-i386-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestRealms-testIpaUnqualifiedUsers-fedora-i386-127.0.0.2-2301-FAIL.html
Wrote JS log to TestRealms-testIpaUnqualifiedUsers-fedora-i386-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-fedora-i386-127.0.0.2-2301-FAIL.log
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 853, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1532516129.415:82): avc:  denied  { getattr } for  pid=418 comm="gssproxy" path="/usr/sbin/rpc.gssd" dev="vda4" ino=4702232 scontext=system_u:system_r:gssproxy_t:s0 tcontext=system_u:object_r:gssd_exec_t:s0 tclass=file permissive=0

not ok 237 testIpaUnqualifiedUsers (check_realms.TestRealms) # duration: 236s
```
First occurrence: 2018-07-25T10:55:51.216284 | revision 8e749b05939ce6a73c618153edf5ae385cad1c65, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9728-20180725-104141-8e749b05-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2018-07-25T10:55:51.216284 | revision 8e749b05939ce6a73c618153edf5ae385cad1c65, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9728-20180725-104141-8e749b05-verify-fedora-i386/log.html)
