### ISSUE TITLE
SELinux denied { map } comm="mdadm" path="/usr/sbin/mdadm"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9507]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1595100

Example: https://fedorapeople.org/groups/cockpit/logs/pull-9502-20180626-054848-8d62c140-verify-fedora-27/log.html#166

**Comment by cockpituous** [comment]
verify/fedora-27
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNotRemovingDisks (check_storage_mdraid.TestStorage)
#
[0626/073452.422507:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9743/devtools/browser/9c4514e6-bc98-4732-8819-591b6e8e527e
[0626/073452.480007:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 75327: Permission denied (13)
[0626/073453.693227:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 75363: Permission denied (13)
Error: /dev/md127: unrecognised disk label
Model: Linux Software RAID Array (md)
Disk /dev/md127: 51.4MB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 

NAME            MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda               8:0    0   50M  0 disk  
sdb               8:16   0   50M  0 disk  
`-md127           9:127  0   49M  0 raid5 
sdc               8:32   0   50M  0 disk  
sr0              11:0    1  366K  0 rom   
vda             252:0    0   12G  0 disk  
|-vda1          252:1    0    1G  0 part  /boot
`-vda2          252:2    0   11G  0 part  
  |-fedora-root 253:0    0  9.8G  0 lvm   /
  `-fedora-swap 253:1    0  1.2G  0 lvm   [SWAP]

Unexpected journal message 'audit: type=1400 audit(1529998509.625:287): avc:  denied  { map } for  pid=6676 comm="mdadm" path="/usr/sbin/mdadm" dev="dm-0" ino=10256363 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0'
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-27-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-27-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-mdraid", line 35, in tearDown
    MachineCase.tearDown(self)
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 828, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1529998509.625:287): avc:  denied  { map } for  pid=6676 comm="mdadm" path="/usr/sbin/mdadm" dev="dm-0" ino=10256363 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0

not ok 160 testNotRemovingDisks (check_storage_mdraid.TestStorage) # duration: 45s
Wrote screenshot to TestStorage-testNotRemovingDisks-fedora-27-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestStorage-testNotRemovingDisks-fedora-27-127.0.0.2-2901-FAIL.html
Wrote JS log to TestStorage-testNotRemovingDisks-fedora-27-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testNotRemovingDisks-fedora-27-127.0.0.2-2901-FAIL.log
```
First occurrence: 2018-06-26T07:35:14.882117 | revision 5064159ada544d68e1a71bd405fb62ccc9ccd414, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9502-20180626-071818-5064159a-verify-fedora-27/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-26T07:35:14.882117 | revision 5064159ada544d68e1a71bd405fb62ccc9ccd414, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9502-20180626-071818-5064159a-verify-fedora-27/log.html)

**Comment by cockpituous** [comment]
verify/fedora-27
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRaid (check_storage_mdraid.TestStorage)
#
[0626/073444.587995:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9629/devtools/browser/1f61d3db-966c-4108-9d6b-3b82e3b3f44f
[0626/073444.624026:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 75194: Permission denied (13)
[0626/073445.657176:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 75231: Permission denied (13)
Error: Could not stat device /dev/md127 - No such file or directory.

NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda               8:0    0   50M  0 disk 
sdb               8:16   0   50M  0 disk 
sdc               8:32   0   50M  0 disk 
sdd               8:48   0   50M  0 disk 
sr0              11:0    1  366K  0 rom  
vda             252:0    0   12G  0 disk 
|-vda1          252:1    0    1G  0 part /boot
`-vda2          252:2    0   11G  0 part 
  |-fedora-root 253:0    0  9.8G  0 lvm  /
  `-fedora-swap 253:1    0  1.2G  0 lvm  [SWAP]

Unexpected journal message 'audit: type=1400 audit(1529998503.960:291): avc:  denied  { map } for  pid=6758 comm="mdadm" path="/usr/sbin/mdadm" dev="dm-0" ino=10256363 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0'
Wrote JS log to TestStorage-testRaid-fedora-27-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-27-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-mdraid", line 35, in tearDown
    MachineCase.tearDown(self)
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 828, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1529998503.960:291): avc:  denied  { map } for  pid=6758 comm="mdadm" path="/usr/sbin/mdadm" dev="dm-0" ino=10256363 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0

not ok 161 testRaid (check_storage_mdraid.TestStorage) # duration: 60s
Wrote screenshot to TestStorage-testRaid-fedora-27-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorage-testRaid-fedora-27-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorage-testRaid-fedora-27-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-27-127.0.0.2-2501-FAIL.log
```
First occurrence: 2018-06-26T07:35:20.827589 | revision 5064159ada544d68e1a71bd405fb62ccc9ccd414, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9502-20180626-071818-5064159a-verify-fedora-27/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-26T07:35:20.827589 | revision 5064159ada544d68e1a71bd405fb62ccc9ccd414, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9502-20180626-071818-5064159a-verify-fedora-27/log.html)

**Comment by cockpituous** [comment]
verify/fedora-27
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testHiddenRaid (check_storage_hidden.TestStorage)
#
[0626/073550.002107:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9539/devtools/browser/a043fc93-3d08-451c-9738-76d65e7cf832
[0626/073550.049698:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 76443: Permission denied (13)
[0626/073551.121267:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 76477: Permission denied (13)
Unexpected journal message 'audit: type=1400 audit(1529998564.873:288): avc:  denied  { map } for  pid=6689 comm="mdadm" path="/usr/sbin/mdadm" dev="dm-0" ino=10256363 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0'
Wrote JS log to TestStorage-testHiddenRaid-fedora-27-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testHiddenRaid-fedora-27-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 828, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1529998564.873:288): avc:  denied  { map } for  pid=6689 comm="mdadm" path="/usr/sbin/mdadm" dev="dm-0" ino=10256363 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0

not ok 152 testHiddenRaid (check_storage_hidden.TestStorage) # duration: 45s
Wrote screenshot to TestStorage-testHiddenRaid-fedora-27-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorage-testHiddenRaid-fedora-27-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorage-testHiddenRaid-fedora-27-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testHiddenRaid-fedora-27-127.0.0.2-2401-FAIL.log
```
First occurrence: 2018-06-26T07:36:11.148618 | revision 5064159ada544d68e1a71bd405fb62ccc9ccd414, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9502-20180626-071818-5064159a-verify-fedora-27/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-26T07:36:11.148618 | revision 5064159ada544d68e1a71bd405fb62ccc9ccd414, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9502-20180626-071818-5064159a-verify-fedora-27/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRaid (check_storage_mdraid.TestStorage)
#
[0626/112012.175430:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9713/devtools/browser/ab0addbc-bfb7-4759-a267-b352b4d93cd5
[0626/112012.323357:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 152891: Permission denied (13)
[0626/112013.776413:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 152928: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
Error: Could not stat device /dev/md127 - No such file or directory.

NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   50M  0 disk 
sdb      8:16   0   50M  0 disk 
sdc      8:32   0   50M  0 disk 
sdd      8:48   0   50M  0 disk 
sr0     11:0    1  366K  0 rom  
vda    252:0    0    8G  0 disk 
|-vda1 252:1    0    1M  0 part 
|-vda2 252:2    0    1G  0 part /boot
|-vda3 252:3    0  615M  0 part [SWAP]
`-vda4 252:4    0  6.4G  0 part /

Unexpected journal message 'audit: type=1400 audit(1530012106.693:316): avc:  denied  { map } for  pid=6987 comm="mdadm" path="/usr/sbin/mdadm" dev="vda4" ino=4903763 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0'
Unexpected journal message 'audit: type=1400 audit(1530012106.883:318): avc:  denied  { map } for  pid=6991 comm="mdadm" path="/usr/sbin/mdadm" dev="vda4" ino=4903763 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0'
Unexpected journal message 'audit: type=1400 audit(1530012107.023:320): avc:  denied  { map } for  pid=6993 comm="mdadm" path="/usr/sbin/mdadm" dev="vda4" ino=4903763 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0'
Wrote JS log to TestStorage-testRaid-fedora-i386-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-i386-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-mdraid", line 35, in tearDown
    MachineCase.tearDown(self)
  File "/build/cockpit/test/common/testlib.py", line 670, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 828, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1530012106.693:316): avc:  denied  { map } for  pid=6987 comm="mdadm" path="/usr/sbin/mdadm" dev="vda4" ino=4903763 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:mdadm_exec_t:s0 tclass=file permissive=0

not ok 167 testRaid (check_storage_mdraid.TestStorage) # duration: 191s
Wrote screenshot to TestStorage-testRaid-fedora-i386-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestStorage-testRaid-fedora-i386-127.0.0.2-2901-FAIL.html
Wrote JS log to TestStorage-testRaid-fedora-i386-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testRaid-fedora-i386-127.0.0.2-2901-FAIL.log
```
First occurrence: 2018-06-26T11:22:20.225124 | revision 21486f86b61832898f6099e827eb5365c3f908ab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9512-20180626-103434-21486f86-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2018-06-26T11:22:20.225124 | revision 21486f86b61832898f6099e827eb5365c3f908ab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9512-20180626-103434-21486f86-verify-fedora-i386/log.html)
