### ISSUE TITLE
 avc: denied { map } for comm="local" path="/usr/libexec/postfix/local

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9592]
```
type=1400 audit(1530740634.282:4): avc:  denied  { map } for  pid=1717 comm="local" path="/usr/libexec/postfix/local" dev="dm-0" ino=25529702 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:postfix_local_exec_t:s0 tclass=file permissive=0
```

This is just background noise, we don't do anything with postfix/email in our tests.

Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1598388

**Comment by cockpituous** [comment]
verify/rhel-7-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFailure (check_docker.TestDocker)
#
[0705/144623.200211:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9524/devtools/browser/56ae38b9-e7d1-44bd-9dbc-cdef965bf451
[0705/144623.233702:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 45261: Permission denied (13)
[0705/144623.459014:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 45289: Permission denied (13)
> warning: 
Unexpected journal messages:
type=1400 audit(1530801994.189:4): avc:  denied  { map } for  pid=1928 comm="local" path="/usr/libexec/postfix/local" dev="dm-0" ino=25543974 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:postfix_local_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestDocker-testFailure-rhel-7-6-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestDocker-testFailure-rhel-7-6-127.0.0.2-2401-FAIL.log
Wrote screenshot to TestDocker-testFailure-rhel-7-6-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestDocker-testFailure-rhel-7-6-127.0.0.2-2401-FAIL.html
Wrote JS log to TestDocker-testFailure-rhel-7-6-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestDocker-testFailure-rhel-7-6-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 847, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1530801994.189:4): avc:  denied  { map } for  pid=1928 comm="local" path="/usr/libexec/postfix/local" dev="dm-0" ino=25543974 scontext=system_u:system_r:postfix_master_t:s0 tcontext=system_u:object_r:postfix_local_exec_t:s0 tclass=file permissive=0

not ok 204 testFailure (check_docker.TestDocker) # duration: 72s
```
First occurrence: 2018-07-05T14:48:18.492513 | revision c381afa878f25f87966298dd949ffc70abc91c41, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9580-20180705-143333-c381afa8-verify-rhel-7-6/log.html)
Times recorded: 1
Latest occurrences:

- 2018-07-05T14:48:18.492513 | revision c381afa878f25f87966298dd949ffc70abc91c41, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9580-20180705-143333-c381afa8-verify-rhel-7-6/log.html)
