### ISSUE TITLE
udisks regression: Format() fails with 'bd_fs_wipe' called, but not implemented

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9595]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1598430

**Comment by martinpitt** [comment]
verify/rhel-7-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFormatTypes (__main__.TestStorage)
#
[0705/144734.358714:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10004/devtools/browser/63a187d4-a08d-4357-bcf8-e5330b0faee2
> warning: Error wiping device: The function 'bd_fs_wipe' called, but not implemented!
Wrote screenshot to TestStorage-testFormatTypes-rhel-7-6-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testFormatTypes-rhel-7-6-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testFormatTypes-rhel-7-6-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testFormatTypes-rhel-7-6-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-format", line 80, in testFormatTypes
    check_type("xfs")
  File "test/verify/check-storage-format", line 70, in check_type
    self.dialog({ "type": type })
  File "/home/martin/upstream/c3/test/verify/storagelib.py", line 295, in dialog
    self.dialog_wait_close()
  File "/home/martin/upstream/c3/test/verify/storagelib.py", line 273, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/martin/upstream/c3/test/common/testlib.py", line 279, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/home/martin/upstream/c3/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/c3/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/c3/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1530794855361.43, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '23323.8'}
warning: Error wiping device: The function 'bd_fs_wipe' called, but not implemented!

not ok 1 testFormatTypes (__main__.TestStorage) # duration: 86s
```
First occurrence: 2018-07-05T14:48:41.791125
Times recorded: 1
Latest occurrences:

- 2018-07-05T14:48:41.791125
