### ISSUE TITLE
SELinux denies "map" to dnsmasq for NetworkManager

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9598]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1598506
```
type=1400 audit(1530804601.908:4): avc:  denied  { map } for  pid=3052 comm="dnsmasq" path="/usr/sbin/dnsmasq" dev="dm-0" ino=714988 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:dnsmasq_exec_t:s0 tclass=file permissive=0
```

**Comment by martinpitt** [comment]
verify/rhel-7-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (__main__.TestNetworking)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       2df915df-2684-4cc7-b4a9-2e6b5511d8d4  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
[0705/181039.150061:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9983/devtools/browser/d9a8fa94-bd7a-4c95-8b54-68abf4c65bac

(process:2125): GLib-GIO-WARNING **: 12:10:44.635: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP4Config/7 but no object proxy exists

(process:2125): GLib-GIO-WARNING **: 12:10:44.636: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP6Config/8 but no object proxy exists

(process:2125): GLib-GIO-WARNING **: 12:10:44.636: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/ActiveConnection/5 but no object proxy exists
Unexpected journal messages:
type=1400 audit(1530807045.221:4): avc:  denied  { map } for  pid=2246 comm="dnsmasq" path="/usr/sbin/dnsmasq" dev="dm-0" ino=714988 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:dnsmasq_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestNetworking-testOtherSettings-rhel-7-6-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-7-6-127.0.0.2-2301-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-28-127.0.0.2-2302-FAIL.log
Wrote screenshot to TestNetworking-testOtherSettings-rhel-7-6-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-rhel-7-6-127.0.0.2-2301-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-rhel-7-6-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-7-6-127.0.0.2-2301-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-28-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "/home/martin/upstream/c3/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/home/martin/upstream/c3/test/common/testlib.py", line 847, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1530807045.221:4): avc:  denied  { map } for  pid=2246 comm="dnsmasq" path="/usr/sbin/dnsmasq" dev="dm-0" ino=714988 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:dnsmasq_exec_t:s0 tclass=file permissive=0

not ok 1 testOtherSettings (__main__.TestNetworking) # duration: 36s
```
First occurrence: 2018-07-05T18:10:48.843943
Times recorded: 1
Latest occurrences:

- 2018-07-05T18:10:48.843943

**Comment by cockpituous** [comment]
verify/rhel-8-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (check_networking_settings.TestNetworking)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       2c6d8e5d-db54-4601-8bca-9ee18ff9bd79  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         890048f1-2eaa-4cd0-a110-0fc97e62e77c  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
[0401/142337.345182:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10133/devtools/browser/e8906c54-ed70-4909-8350-42a82aac492d
[0401/142337.349021:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 126067: Permission denied (13)
[0401/142337.360740:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0401/142337.362184:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0401/142337.502941:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 126096: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
audit: type=1400 audit(1554128622.140:4): avc:  denied  { write } for  pid=2413 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=17078427 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0
Wrote JS log to TestNetworking-testOtherSettings-rhel-8-1-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-8-1-127.0.0.2-2501-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-29-127.0.0.2-2502-FAIL.log
Wrote screenshot to TestNetworking-testOtherSettings-rhel-8-1-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-rhel-8-1-127.0.0.2-2501-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-rhel-8-1-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-8-1-127.0.0.2-2501-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-29-127.0.0.2-2502-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 778, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 977, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1554128622.140:4): avc:  denied  { write } for  pid=2413 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=17078427 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0

not ok 97 testOtherSettings (check_networking_settings.TestNetworking) # duration: 38s
```
First occurrence: 2019-04-01T14:23:47.859353 | revision cc74197c3a8554f2e6cb0f4c0e9ad6c804fb0dae, [logs](https://209.132.184.41:8493/logs/pull-11506-20190401-140404-cc74197c-verify-rhel-8-1/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-01T14:23:47.859353 | revision cc74197c3a8554f2e6cb0f4c0e9ad6c804fb0dae, [logs](https://209.132.184.41:8493/logs/pull-11506-20190401-140404-cc74197c-verify-rhel-8-1/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (check_networking_settings.TestNetworking)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       45d715d5-679e-4ae8-95da-4e629170a6cf  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
[0408/103218.788302:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10050/devtools/browser/98b4f550-db2a-4877-ae35-82e8a683c261
[0408/103218.791891:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 47356: Permission denied (13)
[0408/103218.803774:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0408/103218.805729:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0408/103218.957885:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 47387: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


(process:2020): GLib-GIO-WARNING **: 06:32:26.308: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/DHCP4Config/3 but no object proxy exists

(process:2020): GLib-GIO-WARNING **: 06:32:26.383: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP4Config/6 but no object proxy exists

(process:2020): GLib-GIO-WARNING **: 06:32:26.383: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP6Config/8 but no object proxy exists

(process:2020): GLib-GIO-WARNING **: 06:32:26.383: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/ActiveConnection/5 but no object proxy exists
Unexpected journal messages:
type=1400 audit(1554719547.032:4): avc:  denied  { search } for  pid=2231 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=25516457 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0
Wrote JS log to TestNetworking-testOtherSettings-rhel-7-7-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-7-7-127.0.0.2-2801-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-29-127.0.0.2-2802-FAIL.log
Wrote screenshot to TestNetworking-testOtherSettings-rhel-7-7-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-rhel-7-7-127.0.0.2-2801-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-rhel-7-7-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-7-7-127.0.0.2-2801-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-29-127.0.0.2-2802-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 776, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 958, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1554719547.032:4): avc:  denied  { search } for  pid=2231 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=25516457 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0

not ok 139 testOtherSettings (check_networking_settings.TestNetworking) # duration: 47s
```
First occurrence: 2019-04-08T10:32:32.277937 | revision 49fb29b91c2cc51235e8dc384c0b0ff9407504b0, [logs](https://209.132.184.41:8493/logs/pull-11532-20190408-094949-49fb29b9-verify-rhel-7-7/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-08T10:32:32.277937 | revision 49fb29b91c2cc51235e8dc384c0b0ff9407504b0, [logs](https://209.132.184.41:8493/logs/pull-11532-20190408-094949-49fb29b9-verify-rhel-7-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-8-0-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (check_networking_settings.TestNetworking)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       920a08da-65bf-436d-b623-48647a010ee3  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         4d3da0fa-005e-4c99-b9c4-285dffe09a44  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
[0429/075856.452521:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9751/devtools/browser/7ee6cfbf-8030-4ef5-bc95-e69386dcc555
[0429/075856.456801:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 32751: Permission denied (13)
[0429/075856.467937:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0429/075856.469496:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0429/075856.628686:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 32787: Permission denied (13)

(process:2184): GLib-GIO-WARNING **: 03:59:00.761: gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/DHCP4Config/3 but no object proxy exists
Unexpected journal messages:
audit: type=1400 audit(1556524741.821:4): avc:  denied  { write } for  pid=2375 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=194996 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0
Wrote JS log to TestNetworking-testOtherSettings-rhel-8-0-distropkg-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-8-0-distropkg-127.0.0.2-2201-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-29-127.0.0.2-2202-FAIL.log
Wrote screenshot to TestNetworking-testOtherSettings-rhel-8-0-distropkg-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-rhel-8-0-distropkg-127.0.0.2-2201-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-rhel-8-0-distropkg-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-8-0-distropkg-127.0.0.2-2201-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-29-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 959, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1556524741.821:4): avc:  denied  { write } for  pid=2375 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=194996 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0

not ok 89 testOtherSettings (check_networking_settings.TestNetworking) # duration: 41s
```
First occurrence: 2019-04-29T07:59:10.162839 | revision e553f6ee3c63e3c45d3070d981e75ee72b38eab3, [logs](https://209.132.184.41:8493/logs/pull-11695-20190429-073737-e553f6ee-verify-rhel-8-0-distropkg/log.html)
Times recorded: 1
Latest occurrences:

- 2019-04-29T07:59:10.162839 | revision e553f6ee3c63e3c45d3070d981e75ee72b38eab3, [logs](https://209.132.184.41:8493/logs/pull-11695-20190429-073737-e553f6ee-verify-rhel-8-0-distropkg/log.html)

**Comment by cockpituous** [comment]
verify/rhel-atomic
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (check_networking_settings.TestNetworking)
#
NAME                UUID                                  TYPE      DEVICE 
Wired connection 1  78db9fb7-0d65-3843-8901-16f624128d44  ethernet  eth1   
System eth0         5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2

DevTools listening on ws://127.0.0.1:10185/devtools/browser/592c7bd9-8151-41e4-8952-166a2d37e2d1
[0906/071313.968328:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0906/071313.970257:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[0906/071313.972654:WARNING:gpu_process_host.cc(1205)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: PackageKit went away from D-Bus
> warning: Checking for available updates failed: not-found
> log: PackageKit went away from D-Bus
Unexpected journal messages:
type=1400 audit(1567753999.496:5): avc:  denied  { search } for  pid=2669 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=73 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0
Wrote JS log to TestNetworking-testOtherSettings-rhel-atomic-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-atomic-127.0.0.2-2701-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-30-127.0.0.2-2702-FAIL.log
Wrote screenshot to TestNetworking-testOtherSettings-rhel-atomic-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-rhel-atomic-127.0.0.2-2701-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-rhel-atomic-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-rhel-atomic-127.0.0.2-2701-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-30-127.0.0.2-2702-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/cockpit/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1567753999.496:5): avc:  denied  { search } for  pid=2669 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=73 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0

not ok 42 testOtherSettings (check_networking_settings.TestNetworking) # duration: 89s
```
First occurrence: 2019-09-06T07:13:24.269220 | revision 22fa337058fcf7c8175598c256ab2827ddc3550b
Times recorded: 1
Latest occurrences:

- 2019-09-06T07:13:24.269220 | revision 22fa337058fcf7c8175598c256ab2827ddc3550b
