### ISSUE TITLE
SETroubleshoot page does not work on rhel-x

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9721]
`test/verify/check-setroubleshoot TestSelinux.testTroubleshootAlerts` currently fails:
```
Traceback (most recent call last):
  File "test/verify/check-setroubleshoot", line 76, in testTroubleshootAlerts
    b.wait_present(row_selector)
*
testlib.Error: timeout
wait_js_cond(ph_is_present("tbody:contains('ls from read access on the directory')")): condition did not become true
```
I see the synthetic `httpd_t` violation in audit.log, but the Cockpit page says "no SELinux alerts". This requires some more in-depth debugging.

The rhel-x image refresh has been blocked for several months, so let's use known issues for the remaining few regressions to *finally* get a current image again.

**Comment by cockpituous** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTroubleshootAlerts (check_setroubleshoot.TestSelinux)
#
[0724/151514.982953:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9671/devtools/browser/c47cd6f9-b7d5-49d6-93ab-4fecebc9a13e
[0724/151515.056749:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 257551: Permission denied (13)
[0724/151515.227927:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 257616: Permission denied (13)
> log: PackageKit went away from D-Bus
> warning: Checking for available updates failed: not-found
> warning: Checking for available updates failed: not-found
./ls: cannot open directory '/home/admin': Permission denied
Wrote screenshot to TestSelinux-testTroubleshootAlerts-rhel-x-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSelinux-testTroubleshootAlerts-rhel-x-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSelinux-testTroubleshootAlerts-rhel-x-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSelinux-testTroubleshootAlerts-rhel-x-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-setroubleshoot", line 76, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "/build/cockpit/test/common/testlib.py", line 276, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("tbody:contains('ls from read access on the directory')")): condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1532445315814.56, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '257616.8'}
log: PackageKit went away from D-Bus
warning: Checking for available updates failed: not-found
warning: Checking for available updates failed: not-found

not ok 186 testTroubleshootAlerts (check_setroubleshoot.TestSelinux) # duration: 91s
```
First occurrence: 2018-07-24T15:16:23.803120 | revision a0182fa3e736ad13cd940ebe0160e762b142cd0e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9475-20180724-150000-a0182fa3-verify-rhel-x/log.html)
Times recorded: 1
Latest occurrences:

- 2018-07-24T15:16:23.803120 | revision a0182fa3e736ad13cd940ebe0160e762b142cd0e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9475-20180724-150000-a0182fa3-verify-rhel-x/log.html)
