### ISSUE TITLE
 iptables: Bad rule (does a matching rule exist in that chain?)

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9722]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1607929

Failure:
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-networking-firewall", line 66, in testNetworkingPage
    b.wait_in_text("#networking-firewall-summary", "{} Active Rule".format(len(active_rules)))
*
testlib.Error: timeout
wait_js_cond(ph_in_text("#networking-firewall-summary","3 Active Rule")): condition did not become true
```

**Comment by martinpitt** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNetworkingPage (__main__.TestFirewall)
#
[1108/084142.472891:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9431/devtools/browser/23306ca4-697d-45dd-9461-6653ef7aa177
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
Wrote screenshot to TestFirewall-testNetworkingPage-debian-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestFirewall-testNetworkingPage-debian-testing-127.0.0.2-2201-FAIL.html
Wrote JS log to TestFirewall-testNetworkingPage-debian-testing-127.0.0.2-2201-FAIL.js.log
Traceback (most recent call last):
  File "test/verify/check-networking-firewall", line 69, in testNetworkingPage
    m.execute("systemctl stop firewalld")
  File "/home/martin/upstream/c2/bots/machine/testvm.py", line 489, in execute
    ret = select.select(rset, wset, [], 10)
  File "/home/martin/upstream/c2/bots/machine/testvm.py", line 110, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'systemctl stop firewalld'

not ok 1 testNetworkingPage (__main__.TestFirewall) # duration: 269s
```
First occurrence: 2018-11-08T08:45:58.740993
Times recorded: 1
Latest occurrences:

- 2018-11-08T08:45:58.740993

**Comment by cockpituous** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNetworkingPage (check_networking_firewall.TestFirewall)
#
[1203/142752.561932:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10065/devtools/browser/5859cd8c-fbef-4058-97de-ddbb586afa51
[1203/142752.566299:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 354238: Permission denied (13)
[1203/142752.727492:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 354267: Permission denied (13)
Wrote screenshot to TestFirewall-testNetworkingPage-rhel-8-0-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestFirewall-testNetworkingPage-rhel-8-0-127.0.0.2-2501-FAIL.html
Wrote JS log to TestFirewall-testNetworkingPage-rhel-8-0-127.0.0.2-2501-FAIL.js.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-networking-firewall", line 68, in testNetworkingPage
    m.execute("systemctl stop firewalld")
  File "/build/cockpit/bots/machine/machine_core/ssh_connection.py", line 317, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/bots/machine/machine_core/timeout.py", line 43, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'systemctl stop firewalld'

not ok 73 testNetworkingPage (check_networking_firewall.TestFirewall) # duration: 292s
```
First occurrence: 2018-12-03T14:32:18.146626 | revision 32b57a585ceeca590fb72c5e9998eb014cb5a8cf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10740-20181203-140707-32b57a58-verify-rhel-8-0/log.html)
Times recorded: 1
Latest occurrences:

- 2018-12-03T14:32:18.146626 | revision 32b57a585ceeca590fb72c5e9998eb014cb5a8cf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10740-20181203-140707-32b57a58-verify-rhel-8-0/log.html)
