### ISSUE TITLE
sssd 2.0 breaks Kerberos authentication with KCM cache

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9900]
This gets exposed by the check-realms tests on rhel-x.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1622026

**Comment by cockpituous** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpaUnqualifiedUsers (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Performing LDAP DSE lookup on: 172.27.0.15
 ! Can't contact LDAP server
 * Performing LDAP DSE lookup on: fec0::5054:ff:fe12:3456
 ! Can't contact LDAP server
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2018-06-24 09:02:23
    Valid Until: 2038-06-24 09:02:23

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
WARNING: The configuration pre-client installation is not managed by authselect and cannot be backed up. Uninstallation may not be able to revert to the original state.
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config
Configuring cockpit.lan as NIS domain.
This program will set up FreeIPA client.
Version 4.7.0


Using default chrony configuration.
Client configuration complete.
The ipa-client-install command was successful
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/bin/authselect select sssd with-mkhomedir --force && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
Backup stored at /var/lib/authselect/backups/2018-08-24-08-59-13.TKpwkJ
Profile "sssd" was selected.
The following nsswitch maps are overwritten by the profile:
- passwd
- group
- netgroup
- automount
- services

Make sure that SSSD service is configured and enabled. See SSSD documentation for more information.
 
- with-mkhomedir is selected, make sure oddjobd service is enabled
  - systemctl enable oddjobd.service
  - systemctl start oddjobd.service
 * Successfully enrolled machine in realm
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
id: cannot find name for group ID 573400000

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: Sorry, try again.
[sudo] password for admin: 
sudo: 1 incorrect password attempt
Journal extracted to TestRealms-testIpaUnqualifiedUsers-ipa-127.0.0.2-2602-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-realms", line 273, in testIpaUnqualifiedUsers
    timeout=300)
  File "/build/cockpit/bots/machine/testvm.py", line 481, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/bots/machine/testvm.py", line 110, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'while ! su - -c "echo foobarfoo | sudo -S true" admin; do sleep 5; done'

not ok 237 testIpaUnqualifiedUsers (check_realms.TestRealms) # duration: 422s
```
First occurrence: 2018-08-24T09:04:17.468164 | revision 3fcf8785dd31662513bb7399b807ee1e921e4905, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9894-20180824-085050-3fcf8785-verify-rhel-x/log.html)
Times recorded: 1
Latest occurrences:

- 2018-08-24T09:04:17.468164 | revision 3fcf8785dd31662513bb7399b807ee1e921e4905, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9894-20180824-085050-3fcf8785-verify-rhel-x/log.html)
