### ISSUE TITLE
 cockpit-ssh crashes on a FIPS 140-2 compliant system

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9918]
Cockpit dashboard fails with "Cockpit is not installed" when attempting to connect to a remote system, when the dashboard is being run on a FIPS 140-2 compliant system. This hits an assertion in OpenSSL:

    OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!

We use MD5 for the key fingerprint.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1585191

libssh 0.8.2 will provide support for SHA256 fingerprints, as soon as that is available, we should switch to that.

This causes a new `testFIPS` test case to fail.

**Comment by cockpituous** [comment]
verify/rhel-7-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (check_multi_machine.TestMultiMachine)
#
ssh_exchange_identification: read: Connection reset by peer
[0827/132846.373980:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10048/devtools/browser/0b3b9ebb-e319-4765-b88c-dd1ab1975d8d
[0827/132846.454358:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 30498: Permission denied (13)
[0827/132846.643885:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 30531: Permission denied (13)
Wrote screenshot to TestMultiMachine-testFIPS-rhel-7-6-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestMultiMachine-testFIPS-rhel-7-6-127.0.0.2-2801-FAIL.html
Wrote JS log to TestMultiMachine-testFIPS-rhel-7-6-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-6-127.0.0.2-2801-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-6-127.0.0.2-2802-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-6-127.0.0.2-2803-FAIL.log
Core dumps downloaded to /build/cockpit/TestMultiMachine-testFIPS-rhel-7-6-127.0.0.2-2801-FAIL.core
[0100/000000.411386:ERROR:broker_posix.cc(39)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 457, in testFIPS
    add_machine(b, "10.111.113.2")
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 82, in add_machine
    start_machine_troubleshoot(b, new=True, known_host=known_host)
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 71, in start_machine_troubleshoot
    b.wait_in_text('#troubleshoot-dialog', "Fingerprint")
  File "/build/cockpit/test/common/testlib.py", line 303, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#troubleshoot-dialog","Fingerprint")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 189, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 188, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 200, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:201:24)', 'objectId': '{"injectedScriptId":3,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1535376527416.35, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '30531.8'}

not ok 236 testFIPS (check_multi_machine.TestMultiMachine) # duration: 192s
```
First occurrence: 2018-08-27T13:29:53.309295 | revision 3beaf1275de2d5095dfc0a580f848e5b52d058ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9901-20180827-131919-3beaf127-verify-rhel-7-6/log.html)
Times recorded: 1
Latest occurrences:

- 2018-08-27T13:29:53.309295 | revision 3beaf1275de2d5095dfc0a580f848e5b52d058ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9901-20180827-131919-3beaf127-verify-rhel-7-6/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-5-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (check_multi_machine.TestMultiMachine)
#
ssh_exchange_identification: read: Connection reset by peer
ssh_exchange_identification: read: Connection reset by peer
ssh_exchange_identification: read: Connection reset by peer
[0827/133341.258975:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9609/devtools/browser/b609b23f-13da-400b-9427-8d557d9b5bfc
[0827/133341.313771:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 29736: Permission denied (13)
[0827/133341.491542:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 29765: Permission denied (13)
Wrote screenshot to TestMultiMachine-testFIPS-rhel-7-5-distropkg-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMultiMachine-testFIPS-rhel-7-5-distropkg-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMultiMachine-testFIPS-rhel-7-5-distropkg-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-5-distropkg-127.0.0.2-2701-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-5-distropkg-127.0.0.2-2702-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-5-distropkg-127.0.0.2-2703-FAIL.log
Core dumps downloaded to /build/cockpit/TestMultiMachine-testFIPS-rhel-7-5-distropkg-127.0.0.2-2701-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 457, in testFIPS
    add_machine(b, "10.111.113.2")
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 82, in add_machine
    start_machine_troubleshoot(b, new=True, known_host=known_host)
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 71, in start_machine_troubleshoot
    b.wait_in_text('#troubleshoot-dialog', "Fingerprint")
  File "/build/cockpit/test/common/testlib.py", line 303, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#troubleshoot-dialog","Fingerprint")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 189, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 188, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 200, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:201:24)', 'objectId': '{"injectedScriptId":3,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1535376822989.76, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '29765.8'}

not ok 236 testFIPS (check_multi_machine.TestMultiMachine) # duration: 165s
```
First occurrence: 2018-08-27T13:34:49.217568 | revision 3beaf1275de2d5095dfc0a580f848e5b52d058ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9901-20180827-132424-3beaf127-verify-rhel-7-5-distropkg/log.html)
Times recorded: 1
Latest occurrences:

- 2018-08-27T13:34:49.217568 | revision 3beaf1275de2d5095dfc0a580f848e5b52d058ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9901-20180827-132424-3beaf127-verify-rhel-7-5-distropkg/log.html)

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (check_multi_machine.TestMultiMachine)
#
[0827/133656.341755:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10038/devtools/browser/4485e77a-73aa-4739-aae9-fcf2766246fc
[0827/133656.410247:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 266720: Permission denied (13)
[0827/133656.634634:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 266748: Permission denied (13)
Wrote screenshot to TestMultiMachine-testFIPS-centos-7-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestMultiMachine-testFIPS-centos-7-127.0.0.2-2801-FAIL.html
Wrote JS log to TestMultiMachine-testFIPS-centos-7-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMultiMachine-testFIPS-centos-7-127.0.0.2-2801-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-centos-7-127.0.0.2-2802-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-centos-7-127.0.0.2-2803-FAIL.log
Core dumps downloaded to /build/cockpit/TestMultiMachine-testFIPS-centos-7-127.0.0.2-2801-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 457, in testFIPS
    add_machine(b, "10.111.113.2")
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 82, in add_machine
    start_machine_troubleshoot(b, new=True, known_host=known_host)
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 71, in start_machine_troubleshoot
    b.wait_in_text('#troubleshoot-dialog', "Fingerprint")
  File "/build/cockpit/test/common/testlib.py", line 303, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#troubleshoot-dialog","Fingerprint")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 189, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 188, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 200, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:201:24)', 'objectId': '{"injectedScriptId":3,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1535377017413.15, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '266748.8'}

not ok 236 testFIPS (check_multi_machine.TestMultiMachine) # duration: 196s
```
First occurrence: 2018-08-27T13:38:03.391623 | revision 3beaf1275de2d5095dfc0a580f848e5b52d058ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9901-20180827-132626-3beaf127-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2018-08-27T13:38:03.391623 | revision 3beaf1275de2d5095dfc0a580f848e5b52d058ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9901-20180827-132626-3beaf127-verify-centos-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-5
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (check_multi_machine.TestMultiMachine)
#
ssh_exchange_identification: read: Connection reset by peer
[0904/071559.412912:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9486/devtools/browser/2782236c-0cd5-4bcc-861d-3506abb538ec
[0904/071559.442585:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 62382: Permission denied (13)
[0904/071559.584590:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 62407: Permission denied (13)
Wrote screenshot to TestMultiMachine-testFIPS-rhel-7-5-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMultiMachine-testFIPS-rhel-7-5-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMultiMachine-testFIPS-rhel-7-5-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-5-127.0.0.2-2301-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-5-127.0.0.2-2302-FAIL.log
Journal extracted to TestMultiMachine-testFIPS-rhel-7-5-127.0.0.2-2303-FAIL.log
Core dumps downloaded to /build/cockpit/TestMultiMachine-testFIPS-rhel-7-5-127.0.0.2-2301-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 457, in testFIPS
    add_machine(b, "10.111.113.2")
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 82, in add_machine
    start_machine_troubleshoot(b, new=True, known_host=known_host)
  File "/build/cockpit/bots/../test/verify/check-multi-machine", line 71, in start_machine_troubleshoot
    b.wait_in_text('#troubleshoot-dialog', "Fingerprint")
  File "/build/cockpit/test/common/testlib.py", line 308, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 275, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 272, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#troubleshoot-dialog","Fingerprint")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":3,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1536045360447.13, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '62407.8'}

not ok 79 testFIPS (check_multi_machine.TestMultiMachine) # duration: 135s
```
First occurrence: 2018-09-04T07:17:47.856513 | revision 7d921975dc0a10b36875dcd45580533c5ae8e31d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9954-20180904-064141-7d921975-verify-rhel-7-5/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-04T07:17:47.856513 | revision 7d921975dc0a10b36875dcd45580533c5ae8e31d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9954-20180904-064141-7d921975-verify-rhel-7-5/log.html)
