### ISSUE TITLE
testRegister (check_subscriptions.TestSubscriptions) started failing on rhel-atomic

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9936]
This test case started to fail on several PRs now:
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-subscriptions", line 120, in testRegister
    b.wait_present(register_button_sel)
  File "/build/cockpit/test/common/testlib.py", line 280, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 274, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 271, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("button.btn-primary:contains('Register')"))
```
![screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-9831-20180829-123030-0687daf0-verify-rhel-atomic/TestSubscriptions-testRegister-rhel-atomic-127.0.0.2-2801-FAIL.png)

Examples:
 - https://fedorapeople.org/groups/cockpit/logs/pull-9831-20180829-123030-0687daf0-verify-rhel-atomic/log.html#207
 - https://fedorapeople.org/groups/cockpit/logs/pull-9933-20180829-130303-022ab0d1-verify-rhel-atomic/log.html#234

This seems to have happened out of the blue -- maybe there's some expiry on the candlepin image?

**Comment by mvollmer** [comment]
The error:

```
2018-08-31 07:00:40,432 [INFO] rhsmd:3150:MainThread @rhsmd:279 - rhsmd started
2018-08-31 07:00:40,463 [INFO] rhsmd:3150:MainThread @connection.py:868 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=True
2018-08-31 07:00:40,465 [ERROR] rhsmd:3150:MainThread @cache.py:181 - Error updating system data on the server
2018-08-31 07:00:40,465 [ERROR] rhsmd:3150:MainThread @cache.py:182 - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/subscription_manager/cache.py", line 173, in update_check
    self._sync_with_server(uep, consumer_uuid)
  File "/usr/lib64/python2.7/site-packages/subscription_manager/cache.py", line 523, in _sync_with_server
    content_tags=self.tags)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 1048, in updateConsumer
    ret = self.conn.request_put(method, params)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 699, in request_put
    return self._request("PUT", method, params, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 716, in _request
    info=info, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 555, in _request
    conn.request(request_type, handler, body=body, headers=final_headers)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1251, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 824, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
```

**Comment by martinpitt** [comment]
That error makes sense, as your test VMs have no network access. But this should always have been the case.. The image was last refreshed on Aug 25 in #9898, and the test worked there. The candlepin image hasn't changed in ages. So the only changing thing I can think of is time, some hardcoded expiry somewhere?

**Comment by mvollmer** [comment]
The current `rhel-atomic` image is still subscribed, while the `rhel-7-5` image is not.  I guess that is the fundamental issue.

`rhel-atomic.setup` tries to run `subscription-manager unregister`, but seems to have failed.

**Comment by mvollmer** [comment]
Unsubscribing an Atomic image can not work since all changes to /etc after a `atomic host upgrade` will be lost on next boot.
