### ISSUE TITLE
 SELinux denials for dogtag-ipa-rene when starting certmonger.service

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9970]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1624930

```
# systemctl start certmonger.service

audit: type=1400 audit(1535987990.579:11): avc:  denied  { map } for  pid=4486 comm="dogtag-ipa-rene" path=2F72756E2F6666694E7968326F63202864656C6574656429 dev="tmpfs" ino=42056 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1535987990.579:12): avc:  denied  { write } for  pid=4486 comm="dogtag-ipa-rene" name="/" dev="configfs" ino=11939 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:configfs_t:s0 tclass=dir permissive=0
[...]
```

**Comment by cockpituous** [comment]
verify/rhel-x
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_sosreport.TestSOS)
#
[0903/170311.854530:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9746/devtools/browser/d26d7c32-93ea-4264-890f-804a9f16a471
[0903/170311.904937:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 117432: Permission denied (13)
[0903/170312.073026:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 117486: Permission denied (13)
Unexpected journal messages:
audit: type=1400 audit(1535994260.920:4): avc:  denied  { map } for  pid=4524 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F666669583075584D6C202864656C6574656429 dev="tmpfs" ino=41936 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1535994260.920:5): avc:  denied  { map } for  pid=4524 comm="dogtag-ipa-rene" path=2F746D702F6666696377694F6F73202864656C6574656429 dev="dm-0" ino=8686837 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1535994260.920:6): avc:  denied  { map } for  pid=4524 comm="dogtag-ipa-rene" path=2F7661722F746D702F6666694A6465483079202864656C6574656429 dev="dm-0" ino=8686837 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1535994260.920:7): avc:  denied  { write } for  pid=4524 comm="dogtag-ipa-rene" name="/" dev="tmpfs" ino=10652 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1535994260.920:8): avc:  denied  { map } for  pid=4524 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F66666978364775654D202864656C6574656429 dev="tmpfs" ino=41937 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1535994260.920:9): avc:  denied  { write } for  pid=4524 comm="dogtag-ipa-rene" name="/" dev="devtmpfs" ino=3 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:device_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1535994260.920:10): avc:  denied  { write } for  pid=4524 comm="dogtag-ipa-rene" name="/" dev="tmpfs" ino=10652 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1535994260.920:11): avc:  denied  { map } for  pid=4524 comm="dogtag-ipa-rene" path=2F72756E2F666669554248705153202864656C6574656429 dev="tmpfs" ino=41938 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1535994260.920:12): avc:  denied  { write } for  pid=4524 comm="dogtag-ipa-rene" name="/" dev="configfs" ino=11827 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:configfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1535994260.920:13): avc:  denied  { write } for  pid=4524 comm="dogtag-ipa-rene" name="/" dev="dm-0" ino=128 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:root_t:s0 tclass=dir permissive=0
Wrote JS log to TestSOS-testBasic-rhel-x-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSOS-testBasic-rhel-x-127.0.0.2-2601-FAIL.log
Wrote screenshot to TestSOS-testBasic-rhel-x-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestSOS-testBasic-rhel-x-127.0.0.2-2601-FAIL.html
Wrote JS log to TestSOS-testBasic-rhel-x-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSOS-testBasic-rhel-x-127.0.0.2-2601-FAIL.log
[0100/000000.564808:ERROR:broker_posix.cc(102)] Error sending sync broker message: Broken pipe (32)
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 686, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 859, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1535994260.920:4): avc:  denied  { map } for  pid=4524 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F666669583075584D6C202864656C6574656429 dev="tmpfs" ino=41936 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0

not ok 228 testBasic (check_sosreport.TestSOS) # duration: 314s
```
First occurrence: 2018-09-03T17:07:57.647084 | revision cd35b6a4335122b3d8d59ec6c7bc97d6037513e8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9968-20180903-165555-cd35b6a4-verify-rhel-x/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-03T17:07:57.647084 | revision cd35b6a4335122b3d8d59ec6c7bc97d6037513e8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9968-20180903-165555-cd35b6a4-verify-rhel-x/log.html)

**Comment by martinpitt** [comment]
This is happening on latest images again, reopening.

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
[1211/144629.106824:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10059/devtools/browser/9cbafbd5-c0b6-4113-a4b4-42e3eb62da62
[1211/144629.110549:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 131372: Permission denied (13)
[1211/144629.122542:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1211/144629.124024:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[1211/144629.284455:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 131405: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: > warning: Removing principal HTTP/x0.cockpit.lan@COCKPIT.LAN

> log: Failed to join domain: cockpit.lan: Already running another action
Unexpected journal messages:
audit: type=1400 audit(1544539635.475:354): avc:  denied  { execute } for  pid=2045 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F666669514778644654202864656C6574656429 dev="tmpfs" ino=37167 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539635.482:355): avc:  denied  { execute } for  pid=2045 comm="dogtag-ipa-rene" path=2F746D702F6666697154314E5535202864656C6574656429 dev="tmpfs" ino=37168 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539635.482:356): avc:  denied  { execute } for  pid=2045 comm="dogtag-ipa-rene" path=2F7661722F746D702F666669567437706169202864656C6574656429 dev="dm-0" ino=8649561 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539635.482:357): avc:  denied  { write } for  pid=2045 comm="dogtag-ipa-rene" name="/" dev="tmpfs" ino=11633 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1544539640.526:389): avc:  denied  { execute } for  pid=2073 comm="certmonger" path=2F72756E2F636572746D6F6E6765722F666669753339314163202864656C6574656429 dev="tmpfs" ino=37190 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539640.536:390): avc:  denied  { execute } for  pid=2073 comm="certmonger" path=2F746D702F66666944356A453342202864656C6574656429 dev="tmpfs" ino=37191 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539640.536:391): avc:  denied  { execute } for  pid=2073 comm="certmonger" path=2F7661722F746D702F6666697A7A44687731202864656C6574656429 dev="dm-0" ino=8649561 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539640.536:392): avc:  denied  { write } for  pid=2073 comm="certmonger" name="/" dev="tmpfs" ino=11633 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1544539685.606:702): avc:  denied  { execute } for  pid=2932 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F6666694D434E506161202864656C6574656429 dev="tmpfs" ino=46493 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539685.633:703): avc:  denied  { execute } for  pid=2932 comm="dogtag-ipa-rene" path=2F746D702F666669776456637674202864656C6574656429 dev="tmpfs" ino=46494 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544539685.633:704): avc:  denied  { execute } for  pid=2932 comm="dogtag-ipa-rene" path=2F7661722F746D702F66666939373342504D202864656C6574656429 dev="dm-0" ino=8541314 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
Wrote JS log to TestRealms-testIpa-fedora-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-testing-127.0.0.2-2701-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2702-FAIL.log
Wrote screenshot to TestRealms-testIpa-fedora-testing-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-testing-127.0.0.2-2701-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-testing-127.0.0.2-2701-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2702-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 737, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 912, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1544539635.475:354): avc:  denied  { execute } for  pid=2045 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F666669514778644654202864656C6574656429 dev="tmpfs" ino=37167 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0

not ok 198 testIpa (check_realms.TestRealms) # duration: 222s
```
First occurrence: 2018-12-11T14:48:30.015359 | revision eb655f3e68c2e30a254daa45b109c71f0b70fe4c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10775-20181211-143030-eb655f3e-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2018-12-11T14:48:30.015359 | revision eb655f3e68c2e30a254daa45b109c71f0b70fe4c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10775-20181211-143030-eb655f3e-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_sosreport.TestSOS)
#
[1213/145504.545570:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9684/devtools/browser/351c27e0-31f8-47ee-a520-08a51f2687ab
[1213/145504.549543:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 145587: Permission denied (13)
[1213/145504.561319:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1213/145504.563030:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[1213/145504.760252:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 145622: Permission denied (13)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Unexpected journal messages:
audit: type=1400 audit(1544712978.292:580): avc:  denied  { write } for  pid=4409 comm="dogtag-ipa-rene" name="/" dev="debugfs" ino=1 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:debugfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1544712978.292:581): avc:  denied  { write } for  pid=4409 comm="dogtag-ipa-rene" name="/" dev="hugetlbfs" ino=18816 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:hugetlbfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1544712978.292:582): avc:  denied  { execute } for  pid=4409 comm="dogtag-ipa-rene" path=2F746D702F666669574842447239202864656C6574656429 dev="tmpfs" ino=40084 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
Wrote JS log to TestSOS-testBasic-fedora-29-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSOS-testBasic-fedora-29-127.0.0.2-2501-FAIL.log
Wrote screenshot to TestSOS-testBasic-fedora-29-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestSOS-testBasic-fedora-29-127.0.0.2-2501-FAIL.html
Wrote JS log to TestSOS-testBasic-fedora-29-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSOS-testBasic-fedora-29-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 737, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 916, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1544712978.292:580): avc:  denied  { write } for  pid=4409 comm="dogtag-ipa-rene" name="/" dev="debugfs" ino=1 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:debugfs_t:s0 tclass=dir permissive=0

not ok 146 testBasic (check_sosreport.TestSOS) # duration: 147s
```
First occurrence: 2018-12-13T14:57:12.663655 | revision d3d9579e4f4a9cf13f5a9a30029acd4a7080effc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10814-20181213-143434-d3d9579e-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-12-13T14:57:12.663655 | revision d3d9579e4f4a9cf13f5a9a30029acd4a7080effc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10814-20181213-143434-d3d9579e-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
kinit: Cannot contact any KDC for realm 'COCKPIT.LAN' while getting initial credentials
ipa: ERROR: cannot connect to 'https://f0.cockpit.lan/ipa/json': [Errno 111] Connection refused
[1214/040711.605413:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9861/devtools/browser/c62dd91c-221c-41ec-bfc4-0a3b20e092b4
[1214/040711.609504:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 31934: Permission denied (13)
[1214/040711.626004:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1214/040711.627667:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[1214/040711.780580:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 31968: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: > warning: Removing principal HTTP/x0.cockpit.lan@COCKPIT.LAN

> log: Failed to join domain: cockpit.lan: Already running another action
Unexpected journal messages:
audit: type=1400 audit(1544760483.228:348): avc:  denied  { execute } for  pid=1929 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F666669355834784833202864656C6574656429 dev="tmpfs" ino=36487 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760483.239:349): avc:  denied  { execute } for  pid=1929 comm="dogtag-ipa-rene" path=2F746D702F6666694A7865433945202864656C6574656429 dev="tmpfs" ino=36488 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760483.239:350): avc:  denied  { execute } for  pid=1929 comm="dogtag-ipa-rene" path=2F7661722F746D702F66666943594E514267202864656C6574656429 dev="vda4" ino=4405860 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760488.295:383): avc:  denied  { execute } for  pid=1956 comm="certmonger" path=2F72756E2F636572746D6F6E6765722F66666948786479746B202864656C6574656429 dev="tmpfs" ino=36510 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760488.304:384): avc:  denied  { execute } for  pid=1956 comm="certmonger" path=2F746D702F66666950584A573537202864656C6574656429 dev="tmpfs" ino=36511 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760488.305:385): avc:  denied  { execute } for  pid=1956 comm="certmonger" path=2F7661722F746D702F6666695A46726D4956202864656C6574656429 dev="vda4" ino=4405860 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760488.305:386): avc:  denied  { write } for  pid=1956 comm="certmonger" name="/" dev="tmpfs" ino=11712 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1544760528.833:696): avc:  denied  { execute } for  pid=2810 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F666669674144614276202864656C6574656429 dev="tmpfs" ino=45737 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760528.840:697): avc:  denied  { execute } for  pid=2810 comm="dogtag-ipa-rene" path=2F746D702F66666977546B517953202864656C6574656429 dev="tmpfs" ino=45738 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
audit: type=1400 audit(1544760528.840:698): avc:  denied  { execute } for  pid=2810 comm="dogtag-ipa-rene" path=2F7661722F746D702F6666694F6352777766202864656C6574656429 dev="vda4" ino=4398211 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_tmp_t:s0 tclass=file permissive=0
Wrote JS log to TestRealms-testIpa-fedora-i386-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-i386-127.0.0.2-2601-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2602-FAIL.log
Wrote screenshot to TestRealms-testIpa-fedora-i386-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestRealms-testIpa-fedora-i386-127.0.0.2-2601-FAIL.html
Wrote JS log to TestRealms-testIpa-fedora-i386-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestRealms-testIpa-fedora-i386-127.0.0.2-2601-FAIL.log
Journal extracted to TestRealms-testIpa-ipa-127.0.0.2-2602-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 737, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 916, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1544760483.228:348): avc:  denied  { execute } for  pid=1929 comm="dogtag-ipa-rene" path=2F72756E2F636572746D6F6E6765722F666669355834784833202864656C6574656429 dev="tmpfs" ino=36487 scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:certmonger_var_run_t:s0 tclass=file permissive=0

not ok 193 testIpa (check_realms.TestRealms) # duration: 189s
```
First occurrence: 2018-12-14T04:09:13.845364 | revision 8167a25c80d11a3a804d5ff84b5304532a9edf83, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10828-20181214-035555-8167a25c-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2018-12-14T04:09:13.845364 | revision 8167a25c80d11a3a804d5ff84b5304532a9edf83, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10828-20181214-035555-8167a25c-verify-fedora-i386/log.html)
