### ISSUE TITLE
Kdump service crash on fedora-29

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#9993]
https://bugzilla.redhat.com/show_bug.cgi?id=1619122 causes test/verify/check-kdump to fail when the service is started.

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_kdump.TestKdump)
#
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.
[0905/153558.735224:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9422/devtools/browser/dfd38fc3-5908-4cd0-ae3a-6c6fc3a36d14
[0905/153558.787419:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 347256: Permission denied (13)
[0905/153558.969223:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 347283: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.18.5-300.fc29.x86_64
Found initrd image: /boot/initramfs-4.18.5-300.fc29.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-6892f1259a614015b5b3e9c99f357afe
Found initrd image: /boot/initramfs-0-rescue-6892f1259a614015b5b3e9c99f357afe.img
done
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1536161771332.37,"url":"http://127.0.0.2:9791/cockpit/static/fonts/OpenSans-Light-webfont.woff","networkRequestId":"347283.28"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
ssh_exchange_identification: read: Connection reset by peer
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: read: Connection reset by peer
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
> log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"9"}
> warning: Failed to query RHEL subscription status: 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestKdump-testBasic-fedora-29-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-29-127.0.0.2-2901-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-29-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-29-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kdump", line 99, in testBasic
    self.browser.wait_in_text("#app", "Service is running")
  File "/build/cockpit/test/common/testlib.py", line 303, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#app","Service is running")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 189, 'columnNumber': 9, 'scriptId': '50', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '50', 'url': '', 'lineNumber': 188, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '50', 'url': '', 'lineNumber': 200, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:201:24)', 'objectId': '{"injectedScriptId":9,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1536161759321.78, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '347283.8'}
warning: Failed to query RHEL subscription status: 
warning: transport closed: disconnected
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: net::ERR_EMPTY_RESPONSE', 'timestamp': 1536161771332.37, 'url': 'http://127.0.0.2:9791/cockpit/static/fonts/OpenSans-Light-webfont.woff', 'networkRequestId': '347283.28'}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"4"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"5"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"6"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"7"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"8"}
log: transport closed, dropped message:  1:1!6
{"call":["/org/freedesktop/timedate1","org.freedesktop.DBus.Properties","Get",["org.freedesktop.timedate1","NTPSynchronized"]],"id":"9"}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1536161799354.59, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '347283.114'}
warning: Failed to query RHEL subscription status: 
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 36 testBasic (check_kdump.TestKdump) # duration: 188s
```
First occurrence: 2018-09-05T15:38:45.091978 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T15:38:45.091978 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
