### ISSUE TITLE
timesyncd fails to start on fedora-29

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#9994]
https://bugzilla.redhat.com/show_bug.cgi?id=1559286 causes check-system-info to fail when starting systemd-timesyncd.

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTimeServers (check_system_info.TestSystemInfo)
#
Removed /etc/systemd/system/dbus-org.freedesktop.timedate1.service.
Removed /etc/systemd/system/systemd-timedated.service.
[0905/145904.172406:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9502/devtools/browser/bd846579-f0bb-4528-86c4-efca2b5a35ac
[0905/145904.234453:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303745: Permission denied (13)
[0905/145904.414060:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303812: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-29-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-system-info", line 308, in testTimeServers
    b.wait_visible("#systime-ntp-servers")
  File "/build/cockpit/test/common/testlib.py", line 285, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_visible("#systime-ntp-servers")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 189, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 188, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 200, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:201:24)', 'objectId': '{"injectedScriptId":4,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1536159544800.65, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '303812.8'}
warning: Failed to query RHEL subscription status: 
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 238 testTimeServers (check_system_info.TestSystemInfo) # duration: 94s
```
First occurrence: 2018-09-05T15:00:15.381758 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T15:00:15.381758 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-i386
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTimeServers (check_system_info.TestSystemInfo)
#
Removed /etc/systemd/system/dbus-org.freedesktop.timedate1.service.
Removed /etc/systemd/system/systemd-timedated.service.
[1122/080933.667565:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9785/devtools/browser/ba5ee461-dba5-462d-942d-4cb98e0e6f53
[1122/080933.671615:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 36433: Permission denied (13)
[1122/080933.844882:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 36458: Permission denied (13)
> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2701-FAIL.html
Wrote JS log to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-i386-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-system-info", line 307, in testTimeServers
    b.wait_visible("#systime-ntp-servers")
  File "/build/cockpit/test/common/testlib.py", line 305, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 290, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 287, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_visible("#systime-ntp-servers")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":4,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1542874174263.89, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '1000036458.8'}
warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=i386 [Could not resolve host: mirrors.fedoraproject.org]

not ok 144 testTimeServers (check_system_info.TestSystemInfo) # duration: 91s
```
First occurrence: 2018-11-22T08:10:46.072916 | revision ec8571cff400415b8ceaa6df580debafaae9c289, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10589-20181122-075353-ec8571cf-verify-fedora-i386/log.html)
Times recorded: 1
Latest occurrences:

- 2018-11-22T08:10:46.072916 | revision ec8571cff400415b8ceaa6df580debafaae9c289, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-10589-20181122-075353-ec8571cf-verify-fedora-i386/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTimeServers (check_system_info.TestSystemInfo)
#
Removed /etc/systemd/system/dbus-org.freedesktop.timedate1.service.
Removed /etc/systemd/system/systemd-timedated.service.
[0204/073844.980027:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9331/devtools/browser/7fa9545d-200d-4665-b185-a1e00c1b1d24
[0204/073845.388435:ERROR:egl_util.cc(59)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0204/073845.447574:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 16519: Permission denied (13)
[0204/073845.541893:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[0204/073845.594322:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 16552: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Wrote screenshot to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testTimeServers-fedora-testing-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-system-info", line 313, in testTimeServers
    b.wait_visible("#systime-ntp-servers")
  File "/build/cockpit/test/common/testlib.py", line 336, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 321, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 318, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_visible("#systime-ntp-servers")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 199, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 198, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 210, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:211:24)', 'objectId': '{"injectedScriptId":4,"id":1}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1549265933955.39, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '1000016552.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Checking for available updates failed: Error: cannot update repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

not ok 258 testTimeServers (check_system_info.TestSystemInfo) # duration: 109s
```
First occurrence: 2019-02-04T07:40:07.380271 | revision e8004962d27666f326e2efc8dbdf898c61d902e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-11101-20190204-072828-e8004962-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2019-02-04T07:40:07.380271 | revision e8004962d27666f326e2efc8dbdf898c61d902e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-11101-20190204-072828-e8004962-verify-fedora-testing/log.html)
