### ISSUE TITLE
Firewalld and selinux on fedora-29 

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#9995]
https://bugzilla.redhat.com/show_bug.cgi?id=1608030 causes networking/firwalld tests to fail.

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdoMissingPackages (check_storage_vdo.TestStoragePackages)
#
which: no vdo in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
Unexpected journal messages:
audit: type=1400 audit(1536159535.057:90): avc:  denied  { create } for  pid=599 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0
Journal extracted to TestStoragePackages-testVdoMissingPackages-fedora-29-127.0.0.2-2801-FAIL.log
Journal extracted to TestStoragePackages-testVdoMissingPackages-fedora-29-127.0.0.2-2801-FAIL.log
ok 232 testVdoMissingPackages (check_storage_vdo.TestStoragePackages) # duration: 24s # SKIP No vdo available
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 854, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536159535.057:90): avc:  denied  { create } for  pid=599 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0

not ok 232 testVdoMissingPackages (check_storage_vdo.TestStoragePackages) # duration: 24s
```
First occurrence: 2018-09-05T14:59:05.591085 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T14:59:05.591085 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testHardwareInfo (check_system_info.TestSystemInfo)
#
[0905/145903.507421:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10044/devtools/browser/5f3ef452-df95-4fb1-8840-dfa7eab74328
[0905/145903.547855:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303606: Permission denied (13)
[0905/145903.738937:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303666: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
> debug: hardware info collection data: {"system":{"cpu_model":"Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz","nproc":1,"version":"pc-i440fx-2.10","name":"Standard PC (i440FX + PIIX, 1996)","type":"Other","bios_vendor":"SeaBIOS","bios_version":"1.10.2-2.fc27","bios_date":"04/01/2014"},"pci":[{"slot":"0000:00:00.0","cls":"Bridge","vendor":"Intel Corporation","model":"440FX - 82441FX PMC [Natoma] (Qemu virtual machine)"},{"slot":"0000:00:01.0","cls":"Bridge","vendor":"Intel Corporation","model":"82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.1","cls":"Mass storage controller","vendor":"Intel Corporation","model":"82371SB PIIX3 IDE [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.2","cls":"Serial bus controller","vendor":"Intel Corporation","model":"82371SB PIIX3 USB [Natoma/Triton II] (QEMU Virtual Machine)"},{"slot":"0000:00:01.3","cls":"Bridge","vendor":"Intel Corporation","model":"82371AB/EB/MB PIIX4 ACPI (Qemu virtual machine)"},{"slot":"0000:00:02.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio SCSI"},{"slot":"0000:00:03.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio block device"},{"slot":"0000:00:04.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio memory balloon"},{"slot":"0000:00:05.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio RNG"},{"slot":"0000:00:0e.0","cls":"Network controller","vendor":"Realtek Semiconductor Co., Ltd.","model":"RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (QEMU Virtual Machine)"},{"slot":"0000:00:0f.0","cls":"Network controller","vendor":"Realtek Semiconductor Co., Ltd.","model":"RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (QEMU Virtual Machine)"}]}
> warning: Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 04/01/2014, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:245:97)
    at yt (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:809:67)
    at Tt (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:858:112)
    at vt (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:853:151)
    at gt (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:846:34)
    at wt (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:866:32)
    at bt (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:869:24)
    at t (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:124:27)
    at Y (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:58:19)
    at y (http://127.0.0.2:9391/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/system/hwinfo.js:11605:72)
Unexpected journal messages:
audit: type=1400 audit(1536159535.327:90): avc:  denied  { create } for  pid=591 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0
Wrote JS log to TestSystemInfo-testHardwareInfo-fedora-29-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testHardwareInfo-fedora-29-127.0.0.2-2501-FAIL.log
Wrote screenshot to TestSystemInfo-testHardwareInfo-fedora-29-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestSystemInfo-testHardwareInfo-fedora-29-127.0.0.2-2501-FAIL.html
Wrote JS log to TestSystemInfo-testHardwareInfo-fedora-29-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testHardwareInfo-fedora-29-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 854, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536159535.327:90): avc:  denied  { create } for  pid=591 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0

not ok 235 testHardwareInfo (check_system_info.TestSystemInfo) # duration: 31s
```
First occurrence: 2018-09-05T14:59:10.883780 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T14:59:10.883780 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (check_storage_vdo.TestStorage)
#
[0905/145905.292384:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9724/devtools/browser/f8360935-201f-48ff-b0d2-7ee827a946cc
[0905/145905.336731:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303871: Permission denied (13)
[0905/145905.482286:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303896: Permission denied (13)
which: no vdo in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
Unexpected journal messages:
audit: type=1400 audit(1536159534.210:89): avc:  denied  { create } for  pid=597 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0
Wrote JS log to TestStorage-testVdo-fedora-29-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testVdo-fedora-29-127.0.0.2-2901-FAIL.log
> warning: Failed to query RHEL subscription status: 
Wrote screenshot to TestStorage-testVdo-fedora-29-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestStorage-testVdo-fedora-29-127.0.0.2-2901-FAIL.html
Wrote JS log to TestStorage-testVdo-fedora-29-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorage-testVdo-fedora-29-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 854, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536159534.210:89): avc:  denied  { create } for  pid=597 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0

not ok 231 testVdo (check_storage_vdo.TestStorage) # duration: 34s
```
First occurrence: 2018-09-05T14:59:14.295991 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T14:59:14.295991 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMotd (check_system_info.TestSystemInfo)
#
[0905/145905.755586:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9920/devtools/browser/e0858d76-4e6e-4c99-9558-35cf09737402
[0905/145905.807330:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303931: Permission denied (13)
[0905/145905.991645:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303960: Permission denied (13)
Unexpected journal messages:
audit: type=1400 audit(1536159534.924:86): avc:  denied  { create } for  pid=586 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0
Wrote JS log to TestSystemInfo-testMotd-fedora-29-127.0.0.2-2401-FAIL.js.log
> warning: Failed to query RHEL subscription status: 
Journal extracted to TestSystemInfo-testMotd-fedora-29-127.0.0.2-2401-FAIL.log
Wrote screenshot to TestSystemInfo-testMotd-fedora-29-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testMotd-fedora-29-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testMotd-fedora-29-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testMotd-fedora-29-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 854, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536159534.924:86): avc:  denied  { create } for  pid=586 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0

not ok 236 testMotd (check_system_info.TestSystemInfo) # duration: 34s
```
First occurrence: 2018-09-05T14:59:15.376997 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T14:59:15.376997 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_system_info.TestSystemInfo)
#
[0905/145903.477932:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10181/devtools/browser/3d876cc3-b47c-48df-98d6-051032c598b0
[0905/145903.523100:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303593: Permission denied (13)
[0905/145903.705102:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303646: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
> warning: # localhost:22 SSH-2.0-OpenSSH_7.8
# localhost:22 SSH-2.0-OpenSSH_7.8
# localhost:22 SSH-2.0-OpenSSH_7.8
# localhost:22 SSH-2.0-OpenSSH_7.8

> warning: # localhost:22 SSH-2.0-OpenSSH_7.8
# localhost:22 SSH-2.0-OpenSSH_7.8
# localhost:22 SSH-2.0-OpenSSH_7.8
# localhost:22 SSH-2.0-OpenSSH_7.8

CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1536159551119.92,"url":"http://127.0.0.2:9491/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/base1/cockpit.js","lineNumber":450,"stackTrace":{"callFrames":[{"functionName":"U","scriptId":"27","url":"http://127.0.0.2:9491/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/base1/cockpit.js","lineNumber":450,"columnNumber":14},{"functionName":"Je","scriptId":"27","url":"http://127.0.0.2:9491/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/base1/cockpit.js","lineNumber":761,"columnNumber":51},{"functionName":"l","scriptId":"30","url":"http://127.0.0.2:9491/cockpit/$a692b1a987a8c637bbb609d3a19fdb0b3fff833001ca0ac31a863d73a5953855/shell/index.js","lineNumber":3476,"columnNumber":56}]}}
Unexpected journal messages:
audit: type=1400 audit(1536159534.284:90): avc:  denied  { create } for  pid=592 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0
Wrote JS log to TestSystemInfo-testBasic-fedora-29-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSystemInfo-testBasic-fedora-29-127.0.0.2-2601-FAIL.log
> warning: Failed to query RHEL subscription status: 
Wrote screenshot to TestSystemInfo-testBasic-fedora-29-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestSystemInfo-testBasic-fedora-29-127.0.0.2-2601-FAIL.html
Wrote JS log to TestSystemInfo-testBasic-fedora-29-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSystemInfo-testBasic-fedora-29-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-system-info", line 192, in testBasic
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 854, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536159534.284:90): avc:  denied  { create } for  pid=592 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0

not ok 234 testBasic (check_system_info.TestSystemInfo) # duration: 37s
```
First occurrence: 2018-09-05T14:59:17.174298 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T14:59:17.174298 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEnablePcpLink (check_system_info.TestPcp)
#
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
10:59:09: posix_spawn avoided (fd close requested) 
10:59:09: posix_spawn avoided (fd close requested) 
10:59:09: posix_spawn avoided (fd close requested) 
[0905/145913.312846:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9545/devtools/browser/8050e731-2400-4729-ac69-0010a22a1d86
[0905/145913.363220:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 304188: Permission denied (13)
[0905/145913.663369:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 304217: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
Unexpected journal messages:
audit: type=1400 audit(1536159534.196:89): avc:  denied  { create } for  pid=589 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0
Wrote JS log to TestPcp-testEnablePcpLink-fedora-29-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestPcp-testEnablePcpLink-fedora-29-127.0.0.2-2701-FAIL.log
Wrote screenshot to TestPcp-testEnablePcpLink-fedora-29-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestPcp-testEnablePcpLink-fedora-29-127.0.0.2-2701-FAIL.html
Wrote JS log to TestPcp-testEnablePcpLink-fedora-29-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestPcp-testEnablePcpLink-fedora-29-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 854, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536159534.196:89): avc:  denied  { create } for  pid=589 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0

not ok 233 testEnablePcpLink (check_system_info.TestPcp) # duration: 45s
```
First occurrence: 2018-09-05T14:59:25.576710 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T14:59:25.576710 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by cockpituous** [comment]
verify/fedora-29
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTime (check_system_info.TestSystemInfo)
#
[0905/145904.220622:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10116/devtools/browser/1c934c87-ef80-4e12-b082-3225badc7c0d
[0905/145904.284610:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303770: Permission denied (13)
[0905/145904.406945:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 303804: Permission denied (13)
> warning: Failed to query RHEL subscription status: 
> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> log: systemd-timedated not in use, ntp server configuration not supported
> warning: Failed to query RHEL subscription status: 
Unexpected journal messages:
audit: type=1400 audit(1536159535.445:90): avc:  denied  { create } for  pid=613 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0
Wrote JS log to TestSystemInfo-testTime-fedora-29-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-29-127.0.0.2-2301-FAIL.log
Wrote screenshot to TestSystemInfo-testTime-fedora-29-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestSystemInfo-testTime-fedora-29-127.0.0.2-2301-FAIL.html
Wrote JS log to TestSystemInfo-testTime-fedora-29-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestSystemInfo-testTime-fedora-29-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 681, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 854, in check_journal_messages
    raise Error(first)
testlib.Error: audit: type=1400 audit(1536159535.445:90): avc:  denied  { create } for  pid=613 comm="ebtables" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=rawip_socket permissive=0

not ok 237 testTime (check_system_info.TestSystemInfo) # duration: 50s
```
First occurrence: 2018-09-05T14:59:29.949321 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)
Times recorded: 1
Latest occurrences:

- 2018-09-05T14:59:29.949321 | revision 8f22452a223623efa722ddffdf152fd1dc6bed46, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-9916-20180905-144949-8f22452a-verify-fedora-29/log.html)

**Comment by Gundersanne** [comment]
Closed because of noise, added exception in testlib
